force-app/main/default/objects/KDCE_TnCAccepted__c/KDCE_TnCAccepted__c.object-meta.xml
<CustomObject>
    <description>[KDCE]Terms and Conditions Accepted</description>
    <label>Terms and Conditions Accepted</label>
    <nameField>
        <displayFormat>TCA-{YY}{MM}{DD}{00000}</displayFormat>
        <label>RecordNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions Accepted</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_TnCAccepted__c/fields/Accepted__c.field-meta.xml
<CustomField>
    <fullName>Accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] Accepted</description>
    <label>Accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCVersion__c/KDCE_TnCVersion__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Terms and Conditions Version</description>
    <label>Terms and Conditions Version</label>
    <nameField>
        <label>Terms and Conditions Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms and Conditions Version</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_TnCVersionSet__c/KDCE_TnCVersionSet__c.object-meta.xml
<CustomObject>
    <description>[KDCE]Terms and Conditions Version Set</description>
    <label>Terms and Conditions Version Set</label>
    <nameField>
        <displayFormat>VS-{YY}{MM}{DD}{00000}</displayFormat>
        <label>T&amp;C VersionSet</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions Version Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TermsandConditions__c/TermsandConditions__c.object-meta.xml
<CustomObject>
    <description>[Korea DCE] As-Is reuse 
Terms and Conditions, that are related to the different markets. Actual Terms and Conditions need to be accepted during Self Registration or at login.</description>
    <label>Terms and Conditions</label>
    <nameField>
        <displayFormat>TaC-{YY}{MM}{DD}{00000}</displayFormat>
        <label>Terms and Conditions Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TermsandConditions__c/fields/KDCE_Active__c.field-meta.xml
<CustomField>
    <fullName>KDCE_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Active Status</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TermsandConditions__c/fields/KDCE_SubGroup__c.field-meta.xml
<CustomField>
    <fullName>KDCE_SubGroup__c</fullName>
    <description>[KDCE] Version 관리하기 위한 값</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>KDCE_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PMTC</fullName>
                <label>[PMTC]이용약관  (필수)</label>
            </value>
            <value>
                <fullName>PMPM</fullName>
                <label>[PMPM]개인정보 수집 및 이용 (필수)</label>
            </value>
            <value>
                <fullName>PMPO</fullName>
                <label>[PMPO]개인정보 수집 및 이용 (선택)</label>
            </value>
            <value>
                <fullName>PMPP</fullName>
                <label>[PMPP]개인정보 처리업무 위탁 동의 (2020년 9월 16일 18시25분 가입자까지 유효)</label>
            </value>
            <value>
                <fullName>PMPT</fullName>
                <label>[PMPT]개인정보 제3자 제공 (선택)</label>
            </value>
            <value>
                <fullName>PMTP</fullName>
                <label>[PMTP]개인정보 국외이전 (선택)</label>
            </value>
            <value>
                <fullName>PMCPE</fullName>
                <label>[PMCPE]휴면회원 전환기간 특례</label>
            </value>
            <value>
                <fullName>globaloptin</fullName>
                <label>[Common]광고성 정보 수신 (통합)</label>
            </value>
            <value>
                <fullName>PMPMG</fullName>
                <label>[Getinfo]개인정보 수집 및 이용 (필수)</label>
            </value>
            <value>
                <fullName>PMPOG</fullName>
                <label>[Getinfo]개인정보 수집 및 이용</label>
            </value>
            <value>
                <fullName>PMPPG</fullName>
                <label>[Getinfo]개인정보 처리 업무 위탁에 대한 동의</label>
            </value>
            <value>
                <fullName>PMPTG</fullName>
                <label>[Getinfo]개인정보 제3자 제공 (선택)</label>
            </value>
            <value>
                <fullName>PMDP</fullName>
                <label>[PMDP]개인정보 수집 및 이용 동의 (필수)</label>
            </value>
            <value>
                <fullName>PMNL</fullName>
                <label>[PMNL]개인정보 수집 및 이용 동의 (선택)</label>
            </value>
            <value>
                <fullName>PMDT</fullName>
                <label>[PMDT]개인정보 국외이전 동의</label>
            </value>
            <value>
                <fullName>PMTR</fullName>
                <label>[PMTR]Rental 이용약관 (필수)</label>
            </value>
            <value>
                <fullName>PMTI</fullName>
                <label>[PMTI]보상판매 이용 약관 (필수)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TermsandConditions__c/fields/KDCE_TnCVersionSet__c.field-meta.xml
<CustomField>
    <fullName>KDCE_TnCVersionSet__c</fullName>
    <description>[KDCE]Terms and Conditions Versions</description>
    <label>(X)Terms and Conditions Version Sets</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1.0</fullName>
            </value>
            <value>
                <fullName>2.0</fullName>
            </value>
            <value>
                <fullName>3.0</fullName>
            </value>
            <value>
                <fullName>4.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TermsandConditions__c/fields/KDCE_VersionName__c.field-meta.xml
<CustomField>
    <fullName>KDCE_VersionName__c</fullName>
    <description>[KDCE] Version Name 
고객에게 표시할 버젼이름</description>
    <label>Version Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TermsandConditions__c/fields/KDCE_VersionNumber__c.field-meta.xml
<CustomField>
    <fullName>KDCE_VersionNumber__c</fullName>
    <description>[KDCE]Version Number</description>
    <label>Version Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/KDCE_TnC_tr_ts.cls
/****************************************************************************************
  * @filename      : KDCE_TnC_tr_ts
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-15 오후 3:07
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-15 오후 3:07     i2max_Jihyun.Lee        Create
****************************************************************************************/

@IsTest
private class KDCE_TnC_tr_ts {
    static {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();
    }

    @IsTest
    private static void testBehavior() {

        // KDCE_TermsandConditions_tr를 위한
        TermsandConditions__c tnC = [
                SELECT Id, KDCE_VersionName__c, KDCE_VersionNumber__c, KDCE_SubGroup__c, KDCE_Active__c
                FROM TermsandConditions__c
                WHERE Id = :KDCE_TestBizUtil.tnC.Id
        ];

        TermsandConditions__c newTnC = tnC.clone(false, true);
//        newTnC.KDCE_SubGroup__c = 'PMPO';
        insert newTnC;
    }

    @IsTest
    private static void testBehaviorTnCVersion() {
        System.debug('@@ testBehaviorTnCVersion @@');

        List<KDCE_TnCVersion__c> tnCVersions = new List<KDCE_TnCVersion__c>();
        KDCE_TnCVersion__c tnCVersion = KDCE_TestBizUtil.tnCVersion;
        KDCE_TnCVersion__c tnCVersion2 = tnCVersion.clone(false, true);
        KDCE_TnCVersion__c tnCVersion3 = tnCVersion.clone(false, true);
        tnCVersions.add(tnCVersion2);
        tnCVersions.add(tnCVersion3);

        String errorMessage;
        Test.startTest();
        try {
            List<Database.SaveResult> result = Database.insert(tnCVersions, false);
        } catch (DmlException error) {
            errorMessage = error.getMessage();
        }
        Test.stopTest();
//        System.assertEquals(null, System.Label.KDCE_InvalidCreateMultipleRecord, errorMessage);

    }

    @IsTest
    private static void testBehaviorTnCVersionSet() {

        List<KDCE_TnCVersion__c> tnCVersions = new List<KDCE_TnCVersion__c>();
        KDCE_TnCVersion__c tnCVersion = KDCE_TestBizUtil.tnCVersion;

        KDCE_TnCVersionSet__c tnCVersionSet = KDCE_TestBizUtil.tnCVersionSet;

        KDCE_TnCVersionSet__c newTnCVersionSet = tnCVersionSet.clone(false, true);
        Database.insert(newTnCVersionSet, false);
        update tnCVersionSet;

    }

    @IsTest
    private static void testBehaviorTnCAccepted() {
        KDCE_TnCAccepted__c tnCAccepted = KDCE_TestBizUtil.tnCAccepted;
        tnCAccepted.Accepted__c = false;
        update tnCAccepted;
    }
}