force-app/main/default/objects/KDCE_OfflineProgram__c/KDCE_OfflineProgram__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Offline Progrma (Trade-in, Upgrade, Rental, Replacement..)</description>
    <label>Offline Program</label>
    <nameField>
        <displayFormat>OP{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offline Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/CancelDate__c.field-meta.xml
<CustomField>
    <fullName>CancelDate__c</fullName>
    <label>Cancel Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Offline Program</relationshipLabel>
    <relationshipName>OfflineProgram</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/NewCharger__c.field-meta.xml
<CustomField>
    <fullName>NewCharger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[KDCE] New Charger after the program change</description>
    <label>New Charger</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Offline Program (New Charger)</relationshipLabel>
    <relationshipName>OfflineProgramNC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/NewHolder__c.field-meta.xml
<CustomField>
    <fullName>NewHolder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[KDCE] New Holder after the program change</description>
    <label>New Holder</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Offline Program (New Holder)</relationshipLabel>
    <relationshipName>OfflineProgramNH</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/ProgramType__c.field-meta.xml
<CustomField>
    <fullName>ProgramType__c</fullName>
    <description>[KDCE] Program Type</description>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZTA</fullName>
                <label>Purchase</label>
            </value>
            <value>
                <fullName>ZTI</fullName>
                <label>Trade-in</label>
            </value>
            <value>
                <fullName>ZTU</fullName>
                <label>Upgrade</label>
            </value>
            <value>
                <fullName>ZRN</fullName>
                <label>Rental</label>
            </value>
            <value>
                <fullName>ZTAR</fullName>
                <label>Rental Purchase</label>
            </value>
            <value>
                <fullName>ZRT</fullName>
                <label>Kit to Kit</label>
            </value>
            <value>
                <fullName>ZRA</fullName>
                <isActive>false</isActive>
                <label>Replacement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Rental Process</fullName>
            </value>
            <value>
                <fullName>Rental Cancel</fullName>
            </value>
            <value>
                <fullName>Rental Closed</fullName>
            </value>
            <value>
                <fullName>Rental Purchase</fullName>
                <isActive>false</isActive>
                <label>Rental Purchase</label>
            </value>
            <value>
                <fullName>Rental Refund</fullName>
                <isActive>false</isActive>
                <label>Rental Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_OfflineProgram_tr_ts.cls
/****************************************************************************************
  * @filename      : KDCE_OfflineProgram_tr_ts
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-05-17 오전 9:38
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-05-17 오전 9:38     i2max_Jihyun.Lee        Create
****************************************************************************************/

@IsTest
private class KDCE_OfflineProgram_tr_ts {
    static {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();
    }

    @IsTest
    static void testBehavior01() {
        KDCE_OfflineProgram__c op = KDCE_TestBizUtil.offlineProgram;
        op.Status__c = 'Cancel';
        op.ProgramType__c = 'ZTI';
        op.CancelDate__c = System.today();
        update op;
    }

    @IsTest
    static void testBehavior02() {
        KDCE_OfflineProgram__c op = KDCE_TestBizUtil.offlineProgram;
        op.Status__c = 'Rental Process';
        op.CancelDate__c = System.today();
        update op;
    }

    @IsTest
    static void testBehavior03() {
        KDCE_OfflineProgram__c op = KDCE_TestBizUtil.offlineProgram;
        //op.Status__c = 'Rental Purchase';
        update op;
    }

    @IsTest
    static void testBehavior04() {
        KDCE_OfflineProgram__c op = new KDCE_OfflineProgram__c();
        op.Contact__c = KDCE_TestUtil.getContactMember().Id;
        op.ProgramType__c = 'ZRN';
        op.Status__c = 'Rental Process';
        op.NewHolder__c = KDCE_TestUtil.assetHolder.Id;
        op.NewCharger__c = KDCE_TestUtil.assetCharger.Id;
        insert op;

        op.CancelDate__c = System.today();
        op.Status__c = 'Rental Cancel';
        update op;
    }
}