force-app/main/default/objects/Case/fields/CCR_ContactType__c.field-meta.xml
<CustomField>
    <fullName>CCR_ContactType__c</fullName>
    <description>Created so the call center agent do not see the picklist of the queue from the other countries</description>
    <label>Case Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
                <default>true</default>
                <label>Phone</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Webpage</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Kakao Chat</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>In person - Direct Retail</fullName>
            </value>
            <value>
                <fullName>In person - Indirect Retail</fullName>
            </value>
            <value>
                <fullName>Self-Service - QURE</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Self Service - iREFER</fullName>
            </value>
            <value>
                <fullName>Consumer Engagement</fullName>
                <isActive>false</isActive>
                <label>Consumer Engagement</label>
            </value>
            <value>
                <fullName>Electronical Form</fullName>
                <isActive>false</isActive>
                <label>Electronical Form</label>
            </value>
            <value>
                <fullName>FC -1800 telephone number</fullName>
                <isActive>false</isActive>
                <label>FC -1800 telephone number</label>
            </value>
            <value>
                <fullName>FX -Facsimile</fullName>
                <isActive>false</isActive>
                <label>FX -Facsimile</label>
            </value>
            <value>
                <fullName>Face to Face</fullName>
                <isActive>false</isActive>
                <label>Face to Face</label>
            </value>
            <value>
                <fullName>Flagship Store</fullName>
                <isActive>false</isActive>
                <label>Flagship Store</label>
            </value>
            <value>
                <fullName>I -Inbound</fullName>
                <isActive>false</isActive>
                <label>I -Inbound</label>
            </value>
            <value>
                <fullName>In person</fullName>
                <isActive>false</isActive>
                <label>In person</label>
            </value>
            <value>
                <fullName>Letter</fullName>
                <isActive>false</isActive>
                <label>Letter</label>
            </value>
            <value>
                <fullName>O -Outbound</fullName>
                <isActive>false</isActive>
                <label>O -Outbound</label>
            </value>
            <value>
                <fullName>OB -Outbound Call</fullName>
                <isActive>false</isActive>
                <label>OB -Outbound Call</label>
            </value>
            <value>
                <fullName>Self-Service – QURE</fullName>
                <isActive>false</isActive>
                <label>Self-Service – QURE</label>
            </value>
            <value>
                <fullName>TS -TSM</fullName>
                <isActive>false</isActive>
                <label>TS -TSM</label>
            </value>
            <value>
                <fullName>Voicemail</fullName>
                <isActive>false</isActive>
                <label>Voicemail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/KDCE_SendNPS__c.field-meta.xml
<CustomField>
    <fullName>KDCE_SendNPS__c</fullName>
    <description>[KDCE] 케이스 종료 시 NPS 설문 발송여부 확인</description>
    <inlineHelpText>사례 종료 후 NPS 발송여부를 선택합니다. NPS 유형(Brand NPS/Channel NPS)은 선택한 서브젝트 코드에 따라 결정됩니다. 고객이 반드시 정보성 수신을 동의해야 정상 발송됩니다.</inlineHelpText>
    <label>Send NPS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CCR_ECommerceOrderOnBehalf.recordType-meta.xml
<RecordType>
    <fullName>CCR_ECommerceOrderOnBehalf</fullName>
    <active>true</active>
    <businessProcess>Case Status</businessProcess>
    <description>Questions related to online orders or if customer wants to place a new order</description>
    <label>2-Orders/Order On Behalf</label>
</RecordType>

force-app/main/default/objects/Contact/fields/KDCE_MarketingOptIn__c.field-meta.xml
<CustomField>
    <fullName>KDCE_MarketingOptIn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 마케팅 수신 동의여부 체크</description>
    <label>Marketing Opt-In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_Store__c.field-meta.xml
<CustomField>
    <fullName>KDCE_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[KDCE] 인입 채널</description>
    <label>Store</label>
    <referenceTo>KDCE_Store__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Anonymous</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Store__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Store External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestDataBaseFactory.cls
/****************************************************************************************
  * @filename      : TestDataBaseFactory
  * @author        : I2MAX
  * @date          : 2021-01-15 오후 1:18
  * @group         :
  * @group-content :
  * @description   : 
  * @reference     :
  * @release       : v1.0.0
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                     author            description
  * ===============================================================
    0.1     2021-01-15 오후 1:18      I2MAX               Create
****************************************************************************************/
@SuppressWarnings('PMD')
@IsTest
public class TestDataBaseFactory { 

    public static void init() {}

    /**
     * Account Test Data
     *
     * @param isInsert : Boolean
     *
     * @return Account
     */
    public static Account createAccount(final Boolean isInsert) {
        Account account = new Account();

        account.Name = 'businessOfficeAccount';

        if(isInsert)    insert account;

        return account;
    }

    public static Account baseAccount {get;set;}

    static {
        baseAccount = createAccount(true);
    }

    /**
     * Contact Test Data
     *
     * @param isInsert : Boolean
     *
     * @return Contact
     */
    public static Contact createContact(final Boolean isInsert) {
        Contact contact = new Contact();

        contact.LastName = 'testContact';
        contact.Email = 'test@test.com';
        contact.MobilePhone = '010-1234-1234';
        contact.KDCE_MarketingOptIn__c = true;

        if(isInsert)    insert contact;

        return contact;
    }

    public static Contact baseContact {get;set;}

    static {
        baseContact = createContact(true);
    }

    /**
    * Case Test Data
    *
    * @param isInsert : insert 여부.
    *
    * @return Case
    */
    public static Case createCase(final Boolean isInsert) {
        Case insertCase = new Case();

        insertCase.Subject = 'Test';
        insertCase.Description = 'Test';
        insertCase.SuppliedName = TestDataBaseFactory.baseContact.LastName;
        insertCase.Origin = 'Web';
        insertCase.CCR_ContactType__c = 'Webpage';
        insertCase.ContactId = TestDataBaseFactory.baseContact.Id;
        insertCase.Status = 'New';
        insertCase.KDCE_SendNPS__c = 'Yes';
        insertCase.SuppliedPhone = '010-0000-0135';
        //insertCase.RecordTypeId = TestDataUtilFactory.getRecordTypeId('Case','CCR_ECommerceOrderOnBehalf');

        if(isInsert) insert insertCase;

        return insertCase;
    }

    public static Case baseCase {get;set;}

    static {
        if(baseCase == null) {
            baseCase = createCase(true);
        }
    }

    /**
    * Store Test Data
    *
    * @param isInsert : insert 여부.
    *
    * @return Store
    */
    public static KDCE_Store__c createStore(final Boolean isInsert) {
        KDCE_Store__c store = new KDCE_Store__c();
        store.Name = 'Test';

        if(isInsert) insert store;

        return store;
    }

    public static KDCE_Store__c baseStore {get;set;}

    static {
        if(baseStore == null) {
            baseStore = createStore(true);
        }
    }

    /**
     * Campaign Test Data
     *
     * @param isInsert : Boolean
     *
     * @return Campaign
     */

    public static Campaign baseOutboundCampaign;
    public static Campaign createOutboundCampaign(Boolean isInsert){
        if(Util.isEmpty(baseOutboundCampaign)){
            baseOutboundCampaign = (Campaign)TestDataFactory.createSObject('Campaign', new Map<string, Object>{
                    'Name' => 'TEST OUTBOUND CAMPAIGN'
                    ,'Type' => 'Outbound Master'
                    ,'StartDate' => Date.newInstance(Date.today().year(), 1, 1)
                    ,'EndDate' => Date.newInstance(Date.today().year(), 12, 31)
                    , 'ExternalId__c' => '0909090'
                    ,'IsActive' =>true
            }, isInsert);
        }
        return baseOutboundCampaign;
    }
}