force-app/main/default/objects/KDCE_MCEmailLog__c/KDCE_MCEmailLog__c.object-meta.xml
<CustomObject>
    <label>Email Log</label>
    <nameField>
        <displayFormat>EM-{00000000}</displayFormat>
        <label>Email Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_MCEmailLog__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Email Logs</relationshipLabel>
    <relationshipName>EmailLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_MCEmailLog__c/fields/KDCE_EmailOptout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_EmailOptout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Opt-out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_MCEmailLog__c/fields/KDCE_SubscriberKey__c.field-meta.xml
<CustomField>
    <fullName>KDCE_SubscriberKey__c</fullName>
    <label>Subscriber Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCAccepted__c/KDCE_TnCAccepted__c.object-meta.xml
<CustomObject>
    <description>[KDCE]Terms and Conditions Accepted</description>
    <label>Terms and Conditions Accepted</label>
    <nameField>
        <displayFormat>TCA-{YY}{MM}{DD}{00000}</displayFormat>
        <label>RecordNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions Accepted</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_TnCAccepted__c/fields/Accepted__c.field-meta.xml
<CustomField>
    <fullName>Accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] Accepted</description>
    <label>Accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCAccepted__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Terms and Conditions Accepted</relationshipLabel>
    <relationshipName>TnCAccepted</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCAccepted__c/fields/TnC__c.field-meta.xml
<CustomField>
    <fullName>TnC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[KDCE] Terms and Conditions Lookup Id</description>
    <label>Terms and Conditions</label>
    <referenceTo>TermsandConditions__c</referenceTo>
    <relationshipName>TaCAcceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TermsandConditions__c/TermsandConditions__c.object-meta.xml
<CustomObject>
    <description>[Korea DCE] As-Is reuse 
Terms and Conditions, that are related to the different markets. Actual Terms and Conditions need to be accepted during Self Registration or at login.</description>
    <label>Terms and Conditions</label>
    <nameField>
        <displayFormat>TaC-{YY}{MM}{DD}{00000}</displayFormat>
        <label>Terms and Conditions Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TermsandConditions__c/fields/fm_TnCId__c.field-meta.xml
<CustomField>
    <fullName>fm_TnCId__c</fullName>
    <description>[KDCE] T&amp;C Id Key</description>
    <formula>TEXT(KDCE_SubGroup__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_MCEmailLog_tr.cls
/****************************************************************************************
  * @filename      : KDCE_MCEmailLog_tr
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-22 오후 3:10
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-22 오후 3:10     i2max_Jihyun.Lee        Create
****************************************************************************************/

public with sharing class KDCE_MCEmailLog_tr extends TriggerHandler {

    public override void beforeInsert() {
        updateField();  // EmailOptout 필드 업데이트시, 해당 TnC Acceopted를 False로 업데이트
    }

    public override void beforeUpdate() {
        updateField();  // EmailOptout 필드 업데이트시, 해당 TnC Acceopted를 False로 업데이트
    }

    private void updateField() {
        Set<Id> contactIds = new Set<Id>();
        Map<Id, KDCE_TnCAccepted__c> tnCAcceptedMap = new Map<Id, KDCE_TnCAccepted__c>();
        if (Trigger.isInsert) {
            for (KDCE_MCEmailLog__c mcLog : (List<KDCE_MCEmailLog__c>) Trigger.new) {
                if (mcLog.KDCE_EmailOptout__c == true) contactIds.add(mcLog.KDCE_SubscriberKey__c);
            }
        }
        else if (Trigger.isUpdate) {
            for (KDCE_MCEmailLog__c mcLog : (List<KDCE_MCEmailLog__c>) Trigger.new) {
                KDCE_MCEmailLog__c oldMCEmailLog = (KDCE_MCEmailLog__c) Trigger.oldMap.get(mcLog.Id);
                if (oldMCEmailLog.KDCE_EmailOptout__c == false && mcLog.KDCE_EmailOptout__c == true) contactIds.add(mcLog.KDCE_SubscriberKey__c);
            }

        }
        System.debug('=== contactIds : ' + contactIds);
        // TnCAccepted 중 global TnC와 연결되어 있는 6번만 것만 연결해제해야함.
        for (KDCE_TnCAccepted__c tnCAccepted : [
                SELECT Id, Accepted__c, TnC__r.fm_TnCId__c
                FROM KDCE_TnCAccepted__c
                WHERE Contact__c IN :contactIds
                AND TnC__r.fm_TnCId__c = 'globaloptin'
        ]) {
            tnCAccepted.Accepted__c = false;
            tnCAcceptedMap.put(tnCAccepted.Id, tnCAccepted);
        }
        System.debug('=== tnCAcceptedMap : ' + tnCAcceptedMap);
        if (!tnCAcceptedMap.isEmpty()) update tnCAcceptedMap.values();
    }
}