force-app/main/default/objects/KDCE_MCEmailLog__c/KDCE_MCEmailLog__c.object-meta.xml
<CustomObject>
    <label>Email Log</label>
    <nameField>
        <displayFormat>EM-{00000000}</displayFormat>
        <label>Email Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_MCEmailLog__c/fields/KDCE_EmailOptout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_EmailOptout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Opt-out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_MCEmailLog__c/fields/KDCE_External_ID__c.field-meta.xml
<CustomField>
    <fullName>KDCE_External_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>외부 Key</description>
    <externalId>true</externalId>
    <inlineHelpText>Job ID + ContactID (SubscriptionKey)</inlineHelpText>
    <label>External ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_MCEmailLog__c/fields/KDCE_SubscriberKey__c.field-meta.xml
<CustomField>
    <fullName>KDCE_SubscriberKey__c</fullName>
    <label>Subscriber Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_MCEmailLog_tr_ts.cls
/****************************************************************************************
  * @filename      : KDCE_MCEmailLog_tr_ts
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-22 오후 4:28
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-22 오후 4:28     i2max_Jihyun.Lee        Create
****************************************************************************************/

@IsTest
private class KDCE_MCEmailLog_tr_ts {
    static {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();
    }

    @IsTest
    static void testBehavior() {
        KDCE_MCEmailLog__c mcLog = new KDCE_MCEmailLog__c();
        mcLog.KDCE_SubscriberKey__c = KDCE_TestUtil.contactMember.Id;
        mcLog.KDCE_EmailOptout__c = true;
        mcLog.KDCE_External_ID__c = 'TestMCEmailLog';
        insert mcLog;
        update mcLog;
    }
}