force-app/main/default/objects/CCR_DeviceDiagnostic__c/CCR_DeviceDiagnostic__c.object-meta.xml
<CustomObject>
    <description>Used by: CCR. Description: It&apos;s to store information that will be show to the consumer to get diagnostic result.</description>
    <label>Device Diagnostic</label>
    <nameField>
        <label>Device Diagnostic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Device Diagnostics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/fields/CCR_Active__c.field-meta.xml
<CustomField>
    <fullName>CCR_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used By:CCR
Description: Is this step active for the Diagnostic process?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/fields/CCR_DefaultMessage__c.field-meta.xml
<CustomField>
    <fullName>CCR_DefaultMessage__c</fullName>
    <description>Used by: CCR 
Description: field used to store default message of the issue</description>
    <label>Default Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/fields/CCR_DiagnosticDescription__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticDescription__c</fullName>
    <description>Used by: CCR. 
Description: It&apos;s to store Qure diagnostic issue description.</description>
    <label>Diagnostic Description</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticDescription</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/fields/CCR_DiagnosticResult__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticResult__c</fullName>
    <description>Used by: CCR
Description: It&apos;s to store information about the diagnostic result code as configured also in QURE configuration.</description>
    <label>Diagnostic Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticResult</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/fields/CCR_EndMessageType__c.field-meta.xml
<CustomField>
    <fullName>CCR_EndMessageType__c</fullName>
    <description>Used by: CCR 
Description: field used to store type of end message</description>
    <label>End Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Message</fullName>
                <default>true</default>
                <label>Standard Message</label>
            </value>
            <value>
                <fullName>Input Message</fullName>
            </value>
            <value>
                <fullName>Select Message</fullName>
            </value>
            <value>
                <fullName>Critical Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/fields/CCR_MessageName__c.field-meta.xml
<CustomField>
    <fullName>CCR_MessageName__c</fullName>
    <description>Used by: CCR. 
Description: It&apos;s for end messages, to store information which end message needs to be displayed (e.g. code not covered)</description>
    <label>Message Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accessory Issue</fullName>
            </value>
            <value>
                <fullName>Accessory Issue Agents</fullName>
            </value>
            <value>
                <fullName>Address1 Title</fullName>
            </value>
            <value>
                <fullName>Address2 Title</fullName>
            </value>
            <value>
                <fullName>Address3</fullName>
                <label>Address 3</label>
            </value>
            <value>
                <fullName>Address4</fullName>
                <label>Address 4</label>
            </value>
            <value>
                <fullName>Address5</fullName>
                <label>Address 5</label>
            </value>
            <value>
                <fullName>Address Lookup</fullName>
            </value>
            <value>
                <fullName>Asset Blocked</fullName>
            </value>
            <value>
                <fullName>Blinking Bottom Red Light</fullName>
            </value>
            <value>
                <fullName>Blinking Charger Red Light</fullName>
            </value>
            <value>
                <fullName>Blinking Holder Red Light</fullName>
            </value>
            <value>
                <fullName>Blinking Red Light</fullName>
            </value>
            <value>
                <fullName>Bluetooth malfunction</fullName>
            </value>
            <value>
                <fullName>Broken Heating Blade</fullName>
            </value>
            <value>
                <fullName>Call Center Agent SWAP</fullName>
            </value>
            <value>
                <fullName>Cancel Button</fullName>
            </value>
            <value>
                <fullName>CarePlus Invite Agent</fullName>
                <label>Care+ Invite Agent</label>
            </value>
            <value>
                <fullName>CarePlus Invite Consumer</fullName>
                <label>Care+ Invite Consumer</label>
            </value>
            <value>
                <fullName>Channel Selected</fullName>
            </value>
            <value>
                <fullName>City Title</fullName>
            </value>
            <value>
                <fullName>Code Not Covered</fullName>
            </value>
            <value>
                <fullName>Color Swap Title</fullName>
            </value>
            <value>
                <fullName>Confirm Button</fullName>
            </value>
            <value>
                <fullName>CourierDelivery</fullName>
                <label>Courier Delivery</label>
            </value>
            <value>
                <fullName>Courier Delivery Subtitle</fullName>
            </value>
            <value>
                <fullName>Cracks and Dirty Contacts</fullName>
            </value>
            <value>
                <fullName>Cracks and Other Damages</fullName>
            </value>
            <value>
                <fullName>CVS Mobile Number Confirm</fullName>
            </value>
            <value>
                <fullName>CVS Selected</fullName>
            </value>
            <value>
                <fullName>Generic Error</fullName>
            </value>
            <value>
                <fullName>Thanks For Phone</fullName>
            </value>
            <value>
                <fullName>UnReplaceable EndMessage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/recordTypes/CCR_EndMessage.recordType-meta.xml
<RecordType>
    <fullName>CCR_EndMessage</fullName>
    <active>true</active>
    <description>It&apos;s for information which need to be displayed for consumer as end messages at the end of Qure process.</description>
    <label>End Message</label>
</RecordType>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/recordTypes/CCR_OtherMessage.recordType-meta.xml
<RecordType>
    <fullName>CCR_OtherMessage</fullName>
    <active>true</active>
    <description>It&apos;s for all labels and messages that need to be displayed as info</description>
    <label>Other Message</label>
</RecordType>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/CCR_DeviceDiagnosticLocalization__c.object-meta.xml
<CustomObject>
    <description>Used By: CCR
Description: Object used to store localized translations of the QURE process</description>
    <label>Device Diagnostic Localization</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Device Diagnostic Localization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Device Diagnostics Localizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/fields/CCR_Active__c.field-meta.xml
<CustomField>
    <fullName>CCR_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used By: CCR 
Description: Status of the issue</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/fields/CCR_Country__c.field-meta.xml
<CustomField>
    <fullName>CCR_Country__c</fullName>
    <description>Used By CCR: Description: Country of the diagnostic image or text</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DTE_CountryISOs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/fields/CCR_DeviceDiagnostic__c.field-meta.xml
<CustomField>
    <fullName>CCR_DeviceDiagnostic__c</fullName>
    <description>Used By: CCR 
Description: To relate the Localization of the diagnostic with the diagnostic flow</description>
    <label>Device Diagnostic</label>
    <referenceTo>CCR_DeviceDiagnostic__c</referenceTo>
    <relationshipLabel>Devices Diagnostics Localizations</relationshipLabel>
    <relationshipName>Devices_Diagnostics_Localizations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/fields/CCR_Language__c.field-meta.xml
<CustomField>
    <fullName>CCR_Language__c</fullName>
    <description>Used By: CCR
Description: Language of the diagnostic image or text</description>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CTI_Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/fields/CCR_Message__c.field-meta.xml
<CustomField>
    <fullName>CCR_Message__c</fullName>
    <description>Used By: CCR
Description: to hold the country and language specific message</description>
    <label>Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/fields/CCR_Status__c.field-meta.xml
<CustomField>
    <fullName>CCR_Status__c</fullName>
    <description>Used By: CCR
Description: Status of the record</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Ready for Deployment</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_Material__c/CCR_Material__c.object-meta.xml
<CustomObject>
    <description>Created to store information regarding the Device Master Data (catalogue).</description>
    <label>Material</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_Material__c/fields/CCR_Material__c.field-meta.xml
<CustomField>
    <fullName>CCR_Material__c</fullName>
    <description>Contains the same value than the name field. The field is used to set the Material/Name as external id</description>
    <externalId>true</externalId>
    <label>Material</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/CCR_QureHistory__c.object-meta.xml
<CustomObject>
    <description>Used by: CCR
Description: It&apos;s to store information collected during Qure process for that device.</description>
    <label>Qure History</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>QURE History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qure History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_Device__c.field-meta.xml
<CustomField>
    <fullName>CCR_Device__c</fullName>
    <description>Used by: CCR. 
Description: Lookup field to Asset.</description>
    <label>Device</label>
    <referenceTo>Asset</referenceTo>
    <relationshipName>QURE_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_DiagnosticResult__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticResult__c</fullName>
    <description>Used by: CCR 
Description: It stores the unique code list for the diagnostic result used in QURE configuration and Device configuration</description>
    <label>Diagnostic Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticResult</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_QureChannel__c.field-meta.xml
<CustomField>
    <fullName>CCR_QureChannel__c</fullName>
    <description>Used by: CCR. 
Description: It&apos;s to store information using which channel Qure process has been performed (ecommerce, service center, call center).</description>
    <label>Qure Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Service Center</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Flagship Store</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
            <value>
                <fullName>Retailer Light</fullName>
            </value>
            <value>
                <fullName>Shift</fullName>
            </value>
            <value>
                <fullName>Shift Light</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_Status__c.field-meta.xml
<CustomField>
    <fullName>CCR_Status__c</fullName>
    <description>this field is used in qure process that indicates record is active or not.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/CCR_UserType__c.field-meta.xml
<CustomField>
    <fullName>CCR_UserType__c</fullName>
    <description>Used by: CCR Description: Used to monitor which SFDC licence has been assigned to the user. Introduced by QURE</description>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_UserType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CCR_QureMainController_ts.cls
/**
 * Created by I2MAX on 2021-07-14.
 */

@istest(seeAllData = false)
public class CCR_QureMainController_ts {
    /**
    * Method Name :  testdata
    * Arguments: null
    * Return : void
    * Description: This method is used to create test data
    **/
    @testSetup static void testdata() {
        User admuserKR = CCR_TestUtility.createAdminUserforCountry('Korea, Republic of','KR');
        System.runAs(admuserKR) {
            List<CCR_Material__c> mats= CCR_TestUtility.createMaterials(1,'D0201','2.2','JP04');
            List<Contact> con = CCR_TestUtility.createContacts(1);
            user usr = CCR_TestUtility.createCallCntAgentForCountry('Korea, Republic of');
            update usr;

            con[0].OwnerId = usr.Id;
            TriggerHandler.bypass('DTE_ContactTriggerHandler');
            TriggerHandler.bypass('CAA_ContactTriggerHandler');
            update con;

            Asset ast = CCR_TestUtility.createassets(mats[0].id, null, CCR_Constants.ASSETPRODUCED, 'TESTCODENTIFY', 'TESTPARENTCODENTIFY', 'TESTINTERNALID');
            ast.Status = 'Active';
            ast.ContactId = con[0].Id;
            ast.OwnerId = usr.id;
            TriggerHandler.bypass('CCR_AssetTriggerHandler');
            update ast;

            CCR_QureHistory__c qureHis = new CCR_QureHistory__c();
            qureHis.CCR_Status__c = 'Active';
            qureHis.CCR_Device__c = ast.Id;
            qureHis.CCR_QureChannel__c = 'E-Commerce';
            qureHis.CCR_DiagnosticResult__c = 'HB1' ;
            qureHis.CCR_DiagnosticDescription__c = 'Blinking Red Light';
            insert qureHis;

            System.debug(qureHis);

            Id endMessageType, otherMessageType;
            for(RecordType rec : [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'CCR_DeviceDiagnostic__c' AND DeveloperName IN ('CCR_EndMessage', 'CCR_OtherMessage')]){
                if(rec.DeveloperName == 'CCR_EndMessage') endMessageType = rec.Id;
                else otherMessageType = rec.Id;
            }

            CCR_DeviceDiagnostic__c endMessage = new CCR_DeviceDiagnostic__c();
            endMessage.RecordTypeId = endMessageType;
            endMessage.Name = 'Test End Message';
            endMessage.CCR_MessageName__c = 'Thanks For Phone';
            endMessage.CCR_EndMessageType__c = 'Standard Message';
            endMessage.CCR_Active__c = true;
            endMessage.CCR_DefaultMessage__c = 'test message';

            CCR_DeviceDiagnostic__c endMessage2 = new CCR_DeviceDiagnostic__c();
            endMessage2.RecordTypeId = endMessageType;
            endMessage2.Name = 'Test End Message';
            endMessage2.CCR_MessageName__c = 'UnReplaceable EndMessage';
            endMessage2.CCR_EndMessageType__c = 'Standard Message';
            endMessage2.CCR_Active__c = true;
            endMessage2.CCR_DefaultMessage__c = 'test message';

            CCR_DeviceDiagnostic__c otherMessage = new CCR_DeviceDiagnostic__c();
            otherMessage.RecordTypeId = otherMessageType;
            otherMessage.Name = 'Test Other Message';
            otherMessage.CCR_MessageName__c = 'Generic Error';
            otherMessage.CCR_Active__c = true;
            otherMessage.CCR_DefaultMessage__c = 'test message';

            List<CCR_DeviceDiagnostic__c> diagnosticsToInsert = new List<CCR_DeviceDiagnostic__c>();
            diagnosticsToInsert.add(endMessage);
            diagnosticsToInsert.add(otherMessage);
            diagnosticsToInsert.add(endMessage2);
            insert diagnosticsToInsert;

            CCR_DeviceDiagnosticLocalization__c endMessageLocalization = new CCR_DeviceDiagnosticLocalization__c();
            endMessageLocalization.CCR_Active__c = true;
            endMessageLocalization.CCR_Country__c = 'KR';
            endMessageLocalization.CCR_DeviceDiagnostic__c = endMessage.Id;
            endMessageLocalization.CCR_Language__c = 'ko';
            endMessageLocalization.CCR_Message__c = 'test message';

            CCR_DeviceDiagnosticLocalization__c otherMessageLocalization = new CCR_DeviceDiagnosticLocalization__c();
            otherMessageLocalization.CCR_Active__c = true;
            otherMessageLocalization.CCR_Country__c = 'KR';
            otherMessageLocalization.CCR_DeviceDiagnostic__c = otherMessage.Id;
            otherMessageLocalization.CCR_Language__c = 'ko';
            otherMessageLocalization.CCR_Message__c = 'test message';

            CCR_DeviceDiagnosticLocalization__c otherMessageLocalization2 = new CCR_DeviceDiagnosticLocalization__c();
            otherMessageLocalization2.CCR_Active__c = true;
            otherMessageLocalization2.CCR_Country__c = 'KR';
            otherMessageLocalization2.CCR_DeviceDiagnostic__c = endMessage2.Id;
            otherMessageLocalization2.CCR_Language__c = 'ko';
            otherMessageLocalization2.CCR_Message__c = 'test message';

            List<CCR_DeviceDiagnosticLocalization__c> localizationsToInsert = new List<CCR_DeviceDiagnosticLocalization__c>();
            localizationsToInsert.add(endMessageLocalization);
            localizationsToInsert.add(otherMessageLocalization);
            localizationsToInsert.add(otherMessageLocalization2);
            insert localizationsToInsert;

        }
    }

    /**
    * Method Name :  positivePreEligibility
    * Arguments: null
    * Return : void
    * Description: This method is used to test the QURE Main functionality
    **/
    static testMethod void positivePreEligibility() {
        user usr = [SELECT Id, Name, Profile.Name FROM User WHERE CCR_UserType__c = 'Call Center Agent' ORDER BY CreatedDate DESC LIMIT 1];
        System.runAs(usr) {
            CCR_QureMsg qMsg = new CCR_QureMsg();
            qMsg.Codentify = 'TESTCODENTIFY';
            qMsg.IsLimitedEdition = false;
            qMsg.Language = 'EN';
            qMsg.Market = 'KR';
            String qMsgString = Json.serialize(qMsg);
            CCR_QureMainController.returnWrapper retWrap = CCR_QureMainController.callPreEligibility(qMsgString);

        }
    }

    /**
* Method Name :  negativePreEligibility
* Arguments: null
* Return : void
* Description: This method is used to test the QURE Main functionality
**/
    static testMethod void negativePreEligibility() {
        user usr = [SELECT Id, Name, Profile.Name FROM User WHERE CCR_UserType__c = 'Call Center Agent' ORDER BY CreatedDate DESC LIMIT 1];
        System.runAs(usr) {
            CCR_QureMainController.returnWrapper retWrap = CCR_QureMainController.callPreEligibility('Exception');
        }
    }

    /**
* Method Name :  positiveEligibility
* Arguments: null
* Return : void
* Description: This method is used to test the QURE Main functionality
**/
    static testMethod void testEligibility() {
        CCR_QureMsg qMsg = new CCR_QureMsg();
        qMsg.Codentify = 'TESTCODENTIFY';
        qMsg.IsLimitedEdition = false;
        qMsg.Language = 'EN';
        qMsg.Market = 'KR';
        qMsg.ResultCode = 'HB1';
        qMsg.UserType = 'Call Center Agent';
        qMsg.ErrorMsgId = 'Thanks For Phone';
        String qMsgString = Json.serialize(qMsg);
        CCR_QureMainController.returnWrapper retWrap = CCR_QureMainController.callEligibility(qMsgString);

        qMsg.ErrorMsgId = null;
        qMsg.Results = CCR_QureMsg.ESCALATETOCSC;
        qMsgString = Json.serialize(qMsg);
        retWrap = CCR_QureMainController.callEligibility(qMsgString);


        retWrap = CCR_QureMainController.callEligibility('Exception');
    }

    /**
* Method Name :  getMessage
* Arguments: null
* Return : void
* Description: This method is used to test the QURE Main functionality
**/
    static testMethod void getMessage() {
        CCR_QureMsg qMsg = new CCR_QureMsg();
        qMsg.Codentify = 'TESTCODENTIFY';
        qMsg.IsLimitedEdition = false;
        qMsg.Language = 'EN';
        qMsg.Market = 'KR';
        qMsg.ErrorMsgId = 'Thanks For Phone';
        String qMsgString = Json.serialize(qMsg);
        String message = CCR_QureMainController.getStandardEndMessage(qMsgString);

    }

    /**
* Method Name :  positiveEscalation
* Arguments: null
* Return : void
* Description: This method is used to test the QURE Main functionality
**/
    static testMethod void positiveEscalation() {
        user usr = [SELECT Id, Name, Profile.Name FROM User WHERE CCR_UserType__c = 'Call Center Agent' ORDER BY CreatedDate DESC LIMIT 1];
        System.runAs(usr) {
            CCR_QureMsg qMsg = new CCR_QureMsg();
            qMsg.Codentify = 'TESTCODENTIFY';
            qMsg.IsLimitedEdition = false;
            qMsg.Language = 'EN';
            qMsg.Market = 'KR';
            qMsg.ResultCode = 'HB1';
            qMsg.UserType = 'Call Center Agent';

            List<CCR_Material__c> mats= [select id from CCR_Material__c];
            List<Contact> con = CCR_TestUtility.createContacts(1);

            Asset ast = CCR_TestUtility.createassets(mats[0].id, null, CCR_Constants.ASSETPRODUCED, 'TESTCODENTIFY2', 'TESTPARENTCODENTIFY2', 'TESTINTERNALID2');
            ast.Status = 'Active';
            ast.ContactId = con[0].Id;
            ast.OwnerId = usr.id;
            TriggerHandler.bypass('CCR_AssetTriggerHandler');
            update ast;

            CCR_QureHistory__c qureHis = new CCR_QureHistory__c();
            qureHis.CCR_Status__c = 'Active';
            qureHis.CCR_Device__c = ast.Id;
            qureHis.CCR_QureChannel__c = 'E-Commerce';
            qureHis.CCR_DiagnosticResult__c = 'HB1' ;
            qureHis.CCR_DiagnosticDescription__c = 'Blinking Red Light';
            insert qureHis;

//            qMsg.QureHistryId = [SELECT Id FROM CCR_QureHistory__c LIMIT 1].Id;
            qMsg.QureHistryId = qureHis.Id;
            qMsg.MaterialGroup = CCR_Constants.HOLDER;
            String qMsgString = Json.serialize(qMsg);
            CCR_QureMainController.returnWrapper retWrap = CCR_QureMainController.escalateToCSC('0123456789', null, qMsgString);

        }
    }

}