force-app/main/default/objects/KDCE_DormantCase__c/KDCE_DormantCase__c.object-meta.xml
<CustomObject>
    <description>휴면 전환된 고객의 Case 정보 분리 보관</description>
    <label>Dormant Case</label>
    <nameField>
        <displayFormat>DormantCase{YY}{MM}{DD}{000000}</displayFormat>
        <label>Dormant Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dormant Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DormantCase__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <externalId>true</externalId>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantCase__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <description>Date/Time Opened</description>
    <label>Date/Time Opened</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOfflineProgram__c/KDCE_DormantOfflineProgram__c.object-meta.xml
<CustomObject>
    <label>Dormant OfflineProgram</label>
    <nameField>
        <label>Dormant OfflineProgram Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dormant OfflineProgram</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DormantOfflineProgram__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <externalId>true</externalId>
    <label>Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/KDCE_DormantOrder__c.object-meta.xml
<CustomObject>
    <description>휴면 전환된 고객의 Order 정보 분리 보관</description>
    <label>Dormant Order</label>
    <nameField>
        <displayFormat>DormantOrder{YY}{MM}{DD}{000000}</displayFormat>
        <label>Dormant Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dormant Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <externalId>true</externalId>
    <label>Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>CreatedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrderLineItem__c/KDCE_DormantOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Dormant OrderLineItem</label>
    <nameField>
        <displayFormat>Dormant OLI{YY}{MM}{DD}{000000}</displayFormat>
        <label>Dormant OrderLineItem Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dormant OrderLineItem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DropOutCase__c/KDCE_DropOutCase__c.object-meta.xml
<CustomObject>
    <description>탈퇴한 고객의 Case 정보 분리 보관</description>
    <label>DropOut Case</label>
    <nameField>
        <displayFormat>DropOutCase{YY}{MM}{DD}{000000}</displayFormat>
        <label>DropOut Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DropOut Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DropOutCase__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <externalId>true</externalId>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutCase__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <externalId>true</externalId>
    <label>ContactId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutCase__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <description>Date/Time Opened</description>
    <label>Date/Time Opened</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutContact__c/KDCE_DropOutContact__c.object-meta.xml
<CustomObject>
    <description>탈퇴 고객 정보를 저장하기 위한 오브젝트</description>
    <label>DropOut Contact</label>
    <nameField>
        <label>DropOut Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DropOut Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DropOutContact__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>DropOut_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutContact__c/fields/KDCE_DeleteCheckTarget__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DeleteCheckTarget__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete Check Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOfflineProgram__c/KDCE_DropOutOfflineProgram__c.object-meta.xml
<CustomObject>
    <label>DropOut OfflineProgram</label>
    <nameField>
        <label>DropOut OfflineProgram Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DropOut OfflineProgram</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DropOutOrder__c/KDCE_DropOutOrder__c.object-meta.xml
<CustomObject>
    <description>탈퇴 고객 중 Order에 대한 정보 분리 보관</description>
    <label>DropOut Order</label>
    <nameField>
        <displayFormat>DropOutOrder{YY}{MM}{DD}{000000}</displayFormat>
        <label>DropOutOrder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DropOutOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <externalId>true</externalId>
    <label>Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>CreatedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrderLineItem__c/KDCE_DropOutOrderLineItem__c.object-meta.xml
<CustomObject>
    <description>탈퇴 고객 중 OrderLineItem에 대한 정보 분리 보관</description>
    <label>DropOut OrderLineItem</label>
    <nameField>
        <label>DropOut Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DropOut OrderLineItem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/KDCE_Order__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Order</description>
    <label>Order</label>
    <nameField>
        <displayFormat>KO{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/KDCE_DormantDropoutDailyDelOLI_ba_ts.cls
/****************************************************************************************
  * @filename      : KDCE_DormantDropoutDailyDelOLI_ba_ts
  * @projectname   : PMK qa - KR
  * @author        : Park HE
  * @date          : 2021-06-21
  * @group         :
  * @group-content :
  * @description   :
  * @tester        :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                    author          description
  * ===============================================================
    0.1     2021-06-21             Park HE         Create
****************************************************************************************/

@IsTest
private class KDCE_DormantDropoutDailyDelOLI_ba_ts {
    @IsTest
    static void testBehavior() {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();

        KDCE_Order__c order = KDCE_TestBizUtil.order.clone(true);
        Contact cont = KDCE_TestUtil.contactMember.clone(true);
        KDCE_DormantOrderLineItem__c dorOli = new KDCE_DormantOrderLineItem__c( CreatedDate__c = System.now().addYears(-6));
        KDCE_DropOutOrderLineItem__c dropOli = new KDCE_DropOutOrderLineItem__c(CreatedDate__c = System.now().addYears(-6), Order__c = order.Id);

        // Order, Offline, Case 데이터 만들기.
        KDCE_DormantOrder__c dorOrder = new KDCE_DormantOrder__c(CreatedDate__c = System.now().addYears(-6), Contact__c = cont.Id);
        KDCE_DropOutOrder__c dropOrder = new KDCE_DropOutOrder__c(CreatedDate__c = System.now().addYears(-6), Contact__c = cont.Id);

        KDCE_DormantOfflineProgram__c dorOff = new KDCE_DormantOfflineProgram__c(CreatedDate__c = System.now().addYears(-6), Contact__c = cont.Id);
        KDCE_DropOutOfflineProgram__c dropOff = new KDCE_DropOutOfflineProgram__c(CreatedDate__c = System.now().addYears(-6), Contact__c = cont.Id);

        KDCE_DormantCase__c dorCase = new KDCE_DormantCase__c(CreatedDate__c = System.now().addYears(-6), ContactId__c = cont.Id);
        KDCE_DropOutCase__c dropCase = new KDCE_DropOutCase__c(CreatedDate__c = System.now().addYears(-6), ContactId__c = cont.Id);

        KDCE_DropOutContact__c dropCont = new KDCE_DropOutContact__c(ContactId__c = cont.Id, KDCE_DeleteCheckTarget__c = true);
        List<SObject> sObjects = new List<SObject>{dorOli, dropOli, dorOrder, dropOrder, dorOff, dropOff, dorCase, dropCase, dropCont  };
        insert sObjects;

        Database.executeBatch(new KDCE_DormantDropoutDailyDelOLI_ba(KDCE_DormantDropoutDailyDelOLI_ba.getDeleteSObject()), 200);
    }
}