force-app/main/default/objects/KDCE_DormantCase__c/KDCE_DormantCase__c.object-meta.xml
<CustomObject>
    <description>휴면 전환된 고객의 Case 정보 분리 보관</description>
    <label>Dormant Case</label>
    <nameField>
        <displayFormat>DormantCase{YY}{MM}{DD}{000000}</displayFormat>
        <label>Dormant Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dormant Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DormantCase__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <description>Date/Time Opened</description>
    <label>Date/Time Opened</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/KDCE_DormantOrder__c.object-meta.xml
<CustomObject>
    <description>휴면 전환된 고객의 Order 정보 분리 보관</description>
    <label>Dormant Order</label>
    <nameField>
        <displayFormat>DormantOrder{YY}{MM}{DD}{000000}</displayFormat>
        <label>Dormant Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dormant Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>CreatedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutCase__c/KDCE_DropOutCase__c.object-meta.xml
<CustomObject>
    <description>탈퇴한 고객의 Case 정보 분리 보관</description>
    <label>DropOut Case</label>
    <nameField>
        <displayFormat>DropOutCase{YY}{MM}{DD}{000000}</displayFormat>
        <label>DropOut Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DropOut Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DropOutCase__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <description>Date/Time Opened</description>
    <label>Date/Time Opened</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrder__c/KDCE_DropOutOrder__c.object-meta.xml
<CustomObject>
    <description>탈퇴 고객 중 Order에 대한 정보 분리 보관</description>
    <label>DropOut Order</label>
    <nameField>
        <displayFormat>DropOutOrder{YY}{MM}{DD}{000000}</displayFormat>
        <label>DropOutOrder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DropOutOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>CreatedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/KDCE_RecordBulkDelete_sc.cls
/****************************************************************************************
 * @filename      : KDCE_RecordBulkDelete_sc
 * @projectname   : 
 * @author        : i2max_SeokHo
 * @date          : 2021-03-23 오후 4:25
 * @group         :
 * @group-content :
 * @description   :
 * @tester        :
 * @reference     :
 * @copyright     : Copyright © I2max. All Rights Reserved.
 * @modification Log
 * ===============================================================
 * ver     date                     author              description
 * ===============================================================
 0.1     2021-03-23 오후 4:25      i2max_SeokHo         Create
 ****************************************************************************************/

global without sharing class  KDCE_RecordBulkDelete_sc implements Schedulable  {

    // Schedule 등록 배치명
    private static String batchName = '[Case] 3달이 지난 RecordType : 6-Adverse Event 삭제';

    // TODO 배치 주기는 추후 정의
    // Schedule Cron Expression
    private static String batchCron = '0 15 * * * ? ';

    // Batch 수행 Size
    private static Integer batchSize = 200;

    global void execute(SchedulableContext SC) {
        KDCE_RecordBulkDelete_sc.executeBatch();
    }

    /**
     * 배치 Schedule 등록
     */
    public static void runSchedule() {
        System.schedule(batchName, batchCron, new KDCE_RecordBulkDelete_sc());
    }

    /**
     *  배치 Schedule 삭제
     */
    public static void abortSchedule() {
        for (CronTrigger t : [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = :batchName]) {
            if(!Test.isRunningTest())   System.abortJob(t.Id);
        }
    }

    /**
     * 배치 실행(외부 바로 호출) 
     */
    public static void executeBatch() {
        KDCE_RecordBulkDelete_ba nextBa = new KDCE_RecordBulkDelete_ba();
        nextBa.query = 'SELECT Id From Case Where CreatedDate < Last_N_Years:3';
//        nextBa.query = 'SELECT Id From KDCE_DropOutCase__c Where CreatedDate__c < Last_N_Years:3';
//        nextBa.query = 'SELECT Id From KDCE_DormantCase__c Where CreatedDate__c < Last_N_Years:3';

        // order는 delete 아님님
//       nextBa.query = 'SELECT Id From KDCE_DormantOrder__c Where CreatedDate__c < Last_N_Years:5';
//        nextBa.query = 'SELECT Id From KDCE_DropOutOrder__c Where CreatedDate__c < Last_N_Years:5';


        Database.executeBatch(nextBa, batchSize);
    }
}