force-app/main/default/objects/ModelProductMapping__c/ModelProductMapping__c.object-meta.xml
<CustomObject>
    <label>Model Product Mapping</label>
    <nameField>
        <displayFormat>MPM-{00000000}</displayFormat>
        <label>Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Model Product Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ModelProductMapping__c/fields/ModelNumber__c.field-meta.xml
<CustomField>
    <fullName>ModelNumber__c</fullName>
    <label>Model Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ModelProductMapping__c/fields/RecordKey__c.field-meta.xml
<CustomField>
    <fullName>RecordKey__c</fullName>
    <externalId>true</externalId>
    <label>Record Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_ModelProductMapping_tr.cls
/****************************************************************************************
  * @filename      : 
  * @projectname   : 
  * @author        : i2max_Junseok.Kwon
  * @date          : 2021-06-14 오전 9:21
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-14 오전 9:21     i2max_Junseok.Kwon        Create
****************************************************************************************/

public without sharing class KDCE_ModelProductMapping_tr extends TriggerHandler{

    public override void beforeInsert() {
        setDefault();
    }

    public override void beforeUpdate() {
        setDefault();
    }

    private void setDefault(){

        for(ModelProductMapping__c row : (List<ModelProductMapping__c>)Trigger.new){
            row.RecordKey__c = row.ModelNumber__c + '_' + row.Color__c;
        }
    }
}