force-app/main/default/objects/ModelProductMapping__c/ModelProductMapping__c.object-meta.xml
<CustomObject>
    <label>Model Product Mapping</label>
    <nameField>
        <displayFormat>MPM-{00000000}</displayFormat>
        <label>Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Model Product Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ModelProductMapping__c/fields/ModelNumber__c.field-meta.xml
<CustomField>
    <fullName>ModelNumber__c</fullName>
    <label>Model Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_ModelProductMapping_tr_ts.cls
/****************************************************************************************
  * @filename      : KDCE_ModelProductMapping_tr_ts
  * @projectname   : PMK qa - KR
  * @author        : Park HE
  * @date          : 2021-07-09
  * @group         :
  * @group-content :
  * @description   :
  * @tester        :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                    author          description
  * ===============================================================
    0.1     2021-07-09             Park HE         Create
****************************************************************************************/

@IsTest
private class KDCE_ModelProductMapping_tr_ts {
    @IsTest
    static void testBehavior() {
        ModelProductMapping__c item = new ModelProductMapping__c(
                ModelNumber__c  = '00000',
                Color__c        = 'GOLD'
        );
        insert item;
        update item;
    }
}