force-app/main/default/objects/KDCE_DropOutOrderLineItem__c/KDCE_DropOutOrderLineItem__c.object-meta.xml
<CustomObject>
    <description>탈퇴 고객 중 OrderLineItem에 대한 정보 분리 보관</description>
    <label>DropOut OrderLineItem</label>
    <nameField>
        <label>DropOut Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DropOut OrderLineItem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/KDCE_Order__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Order</description>
    <label>Order</label>
    <nameField>
        <displayFormat>KO{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_OrderLineItem__c/KDCE_OrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_OrderLineItem__c/fields/KDCE_fm_OrderContactId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_fm_OrderContactId__c</fullName>
    <formula>CASESAFEID(Order__r.Contact__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_OrderLineItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>KDCE_Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/KDCE_DropOutOrderLineItemSoftDeletion_ba.cls
/****************************************************************************************
  * @filename      : KDCE_DropOutOrderLineItemSoftDeletion_ba
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-11 오전 10:29
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : KDCE_DropOutContactSoftDeletion_ba_ts
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-11 오전 10:29     i2max_Jihyun.Lee        Create
****************************************************************************************/

public with sharing class KDCE_DropOutOrderLineItemSoftDeletion_ba implements Database.Batchable<sObject>, Database.Stateful {
    //public Set<Id> batchContactIds;

    String objectName = 'KDCE_OrderLineItem__c';
    String query = 'SELECT ';
    Map<String, Schema.SObjectField> orderFieldMap = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap();


    public Database.QueryLocator start(Database.BatchableContext BC) {

        for (String fieldName : orderFieldMap.keySet()) {
            if (query != 'SELECT ') query += ' ,';      // 첫번째 필드가 아닐 경우 , 붙이기
            query += fieldName;
        }
        query += ' FROM ';
        query += objectName;
        if (!Test.isRunningTest()) query += ' WHERE Order__r.Contact__r.KDCE_IsDropOut__c = true AND Order__r.Contact__r.KDCE_DropOutDate__c = TODAY ';
        //query += ' WHERE KDCE_fm_OrderContactId__c IN :batchContactIds';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {

        Map<String, Schema.SObjectField> objectSchema = Schema.SObjectType.KDCE_OrderLineItem__c.fields.getMap();
        Set<String> notNullField = new Set<String>{
                'id', 'ownerid'
        };
        KDCE_ContactSeparateService.separateObject('DropOut', 'KDCE_OrderLineItem__c', 'KDCE_DropOutOrderLineItem__c', scope);

    }

    public void finish(Database.BatchableContext BC) {

        KDCE_DropOutOrderSoftDeletion_ba nextBatch = new KDCE_DropOutOrderSoftDeletion_ba();
        Database.executeBatch(nextBatch, 200);

        /*
        if(!batchContactIds.isEmpty()) {
            KDCE_DropOutOrderSoftDeletion_ba nextBatch = new KDCE_DropOutOrderSoftDeletion_ba();
            nextBatch.batchContactIds = batchContactIds;
            Database.executeBatch(nextBatch, 2000);
        }
        */
    }
}