force-app/main/default/objects/CCR_CarePlusConfiguration__c/CCR_CarePlusConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to store Care+ configuration per market</description>
    <label>CCR Care+ Configuration</label>
</CustomObject>

force-app/main/default/objects/CCR_CarePlusConfiguration__c/fields/CCR_AccidentalDamageLimit__c.field-meta.xml
<CustomField>
    <fullName>CCR_AccidentalDamageLimit__c</fullName>
    <description>Field to store information how many times device has been replaced due to Accidental Damage.</description>
    <label>Accidental Damage Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCR_CarePlusConfiguration__c/fields/CCR_CarePlusActivated__c.field-meta.xml
<CustomField>
    <fullName>CCR_CarePlusActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to store information if Care+ program is active for country.</description>
    <label>Care+ Activated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCR_CarePlusConfiguration__c/fields/CCR_Country__c.field-meta.xml
<CustomField>
    <fullName>CCR_Country__c</fullName>
    <description>Field to store information about country</description>
    <label>Country</label>
    <length>254</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR_CarePlusConfiguration__c/fields/CCR_L0codes__c.field-meta.xml
<CustomField>
    <fullName>CCR_L0codes__c</fullName>
    <description>Field to store all issue codes which are covered by Care+ program</description>
    <label>L0 codes</label>
    <length>254</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/CCR_DeviceDiagnostic__c.object-meta.xml
<CustomObject>
    <description>Used by: CCR. Description: It&apos;s to store information that will be show to the consumer to get diagnostic result.</description>
    <label>Device Diagnostic</label>
    <nameField>
        <label>Device Diagnostic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Device Diagnostics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/fields/CCR_Active__c.field-meta.xml
<CustomField>
    <fullName>CCR_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used By:CCR
Description: Is this step active for the Diagnostic process?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/fields/CCR_DiagnosticDescription__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticDescription__c</fullName>
    <description>Used by: CCR. 
Description: It&apos;s to store Qure diagnostic issue description.</description>
    <label>Diagnostic Description</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticDescription</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/fields/CCR_DiagnosticResult__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticResult__c</fullName>
    <description>Used by: CCR
Description: It&apos;s to store information about the diagnostic result code as configured also in QURE configuration.</description>
    <label>Diagnostic Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticResult</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/fields/CCR_Model__c.field-meta.xml
<CustomField>
    <fullName>CCR_Model__c</fullName>
    <description>Used By:CCR
Description:It&apos;s to store information about device model.</description>
    <label>Model</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnostic__c/recordTypes/CCR_DeviceIssue.recordType-meta.xml
<RecordType>
    <fullName>CCR_DeviceIssue</fullName>
    <active>true</active>
    <description>It&apos;s for information which need to be displayed for consumer during the diagnostic process</description>
    <label>Device Issue</label>
</RecordType>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/CCR_DeviceDiagnosticLocalization__c.object-meta.xml
<CustomObject>
    <description>Used By: CCR
Description: Object used to store localized translations of the QURE process</description>
    <label>Device Diagnostic Localization</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Device Diagnostic Localization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Device Diagnostics Localizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/fields/CCR_Active__c.field-meta.xml
<CustomField>
    <fullName>CCR_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used By: CCR 
Description: Status of the issue</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/fields/CCR_Country__c.field-meta.xml
<CustomField>
    <fullName>CCR_Country__c</fullName>
    <description>Used By CCR: Description: Country of the diagnostic image or text</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DTE_CountryISOs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/fields/CCR_DeviceDiagnostic__c.field-meta.xml
<CustomField>
    <fullName>CCR_DeviceDiagnostic__c</fullName>
    <description>Used By: CCR 
Description: To relate the Localization of the diagnostic with the diagnostic flow</description>
    <label>Device Diagnostic</label>
    <referenceTo>CCR_DeviceDiagnostic__c</referenceTo>
    <relationshipLabel>Devices Diagnostics Localizations</relationshipLabel>
    <relationshipName>Devices_Diagnostics_Localizations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/fields/CCR_Language__c.field-meta.xml
<CustomField>
    <fullName>CCR_Language__c</fullName>
    <description>Used By: CCR
Description: Language of the diagnostic image or text</description>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CTI_Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_DeviceDiagnosticLocalization__c/fields/CCR_Message__c.field-meta.xml
<CustomField>
    <fullName>CCR_Message__c</fullName>
    <description>Used By: CCR
Description: to hold the country and language specific message</description>
    <label>Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CCR_Material__c/CCR_Material__c.object-meta.xml
<CustomObject>
    <description>Created to store information regarding the Device Master Data (catalogue).</description>
    <label>Material</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_Material__c/fields/CCR_Color__c.field-meta.xml
<CustomField>
    <fullName>CCR_Color__c</fullName>
    <description>Device Color</description>
    <label>Color</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR_Material__c/fields/CCR_Material__c.field-meta.xml
<CustomField>
    <fullName>CCR_Material__c</fullName>
    <description>Contains the same value than the name field. The field is used to set the Material/Name as external id</description>
    <externalId>true</externalId>
    <label>Material</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/CCR_QureConfiguration__c.object-meta.xml
<CustomObject>
    <description>Used by: CCR
Description: It&apos;s to store information that will be used in back-end to execute pre-eligibility and eligibility checks during the Qure process.</description>
    <label>Qure Configuration</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Qure Configuration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qure Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_Color__c.field-meta.xml
<CustomField>
    <fullName>CCR_Color__c</fullName>
    <description>Used by: CCR
Description: It&apos;s to store information about the device color.</description>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AQE</fullName>
            </value>
            <value>
                <fullName>BCO</fullName>
            </value>
            <value>
                <fullName>BGD</fullName>
            </value>
            <value>
                <fullName>BLA</fullName>
            </value>
            <value>
                <fullName>BLU</fullName>
            </value>
            <value>
                <fullName>BRG</fullName>
            </value>
            <value>
                <fullName>CAM</fullName>
            </value>
            <value>
                <fullName>CHG</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>COR</fullName>
            </value>
            <value>
                <fullName>DDM</fullName>
            </value>
            <value>
                <fullName>DLV</fullName>
            </value>
            <value>
                <fullName>DPT</fullName>
            </value>
            <value>
                <fullName>EMP</fullName>
            </value>
            <value>
                <fullName>FGR</fullName>
            </value>
            <value>
                <fullName>FRY</fullName>
            </value>
            <value>
                <fullName>GOL</fullName>
            </value>
            <value>
                <fullName>GRA</fullName>
            </value>
            <value>
                <fullName>GRN</fullName>
            </value>
            <value>
                <fullName>GRY</fullName>
            </value>
            <value>
                <fullName>HOP</fullName>
            </value>
            <value>
                <fullName>HRP</fullName>
            </value>
            <value>
                <fullName>IPL</fullName>
            </value>
            <value>
                <fullName>IRO</fullName>
            </value>
            <value>
                <fullName>JBL</fullName>
            </value>
            <value>
                <fullName>LBE</fullName>
            </value>
            <value>
                <fullName>LBL</fullName>
            </value>
            <value>
                <fullName>LUT</fullName>
            </value>
            <value>
                <fullName>MAB</fullName>
            </value>
            <value>
                <fullName>MAR</fullName>
            </value>
            <value>
                <fullName>SLV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_Country__c.field-meta.xml
<CustomField>
    <fullName>CCR_Country__c</fullName>
    <description>Used by: CCR
Description: It&apos;s to store information about the country.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CTI_CountryISOs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_DiagnosticResult__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticResult__c</fullName>
    <description>Used by: CCR
Description: It&apos;s to store information about diagnostic result code as also used in Device diagnostic.</description>
    <label>Diagnostic Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticResult</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_Model__c.field-meta.xml
<CustomField>
    <fullName>CCR_Model__c</fullName>
    <description>Used by: CCR
Description: It&apos;s to store information about the device model.</description>
    <label>Model</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/recordTypes/CCR_LimitedEdition.recordType-meta.xml
<RecordType>
    <fullName>CCR_LimitedEdition</fullName>
    <active>true</active>
    <description>Used by: CCR  Description:It&apos;s to store information about limited edition devices for country</description>
    <label>Limited Edition</label>
</RecordType>

force-app/main/default/objects/CCR_QureHistory__c/CCR_QureHistory__c.object-meta.xml
<CustomObject>
    <description>Used by: CCR
Description: It&apos;s to store information collected during Qure process for that device.</description>
    <label>Qure History</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>QURE History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qure History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_Device__c.field-meta.xml
<CustomField>
    <fullName>CCR_Device__c</fullName>
    <description>Used by: CCR. 
Description: Lookup field to Asset.</description>
    <label>Device</label>
    <referenceTo>Asset</referenceTo>
    <relationshipName>QURE_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_DiagnosticResult__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticResult__c</fullName>
    <description>Used by: CCR 
Description: It stores the unique code list for the diagnostic result used in QURE configuration and Device configuration</description>
    <label>Diagnostic Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticResult</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_QureChannel__c.field-meta.xml
<CustomField>
    <fullName>CCR_QureChannel__c</fullName>
    <description>Used by: CCR. 
Description: It&apos;s to store information using which channel Qure process has been performed (ecommerce, service center, call center).</description>
    <label>Qure Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Service Center</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Flagship Store</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
            <value>
                <fullName>Retailer Light</fullName>
            </value>
            <value>
                <fullName>Shift</fullName>
            </value>
            <value>
                <fullName>Shift Light</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CCR_QurePreEligibility_ts.cls
/**
 * Created by I2MAX on 2021-07-17.
 */

@IsTest(seealldata=false)
public class CCR_QurePreEligibility_ts {
    static final string TESTDEVICE = 'Test Device';
    static final string TESTCODENTIFY = 'xyz353';
    static final string TESTINTERNALID = 'cdf678';
    static final string TESTPARENTCODENTIFY = 'abc123';
    static final string TESTCONLNAME = 'John';
    static final string TESTCONFNAME = 'King';
    static final String DEVICEISSUE = SObjectType.CCR_DeviceDiagnostic__c.getRecordTypeInfosByDeveloperName().get('CCR_DeviceIssue').getRecordTypeId();
    /**
* Method Name :  testdata
* Arguments:
@ String -
@ String -
@ String -
* Return : None
* Description: Test data method.
**/
    @testSetup static void testdata(){
        //List<CCR_DeviceDiagnostic__c> DeviceDiagnosticdata= Test.loadData(CCR_DeviceDiagnostic__c.sObjectType, 'CCR_DeviceDiagnosticCS');
        CCR_CarePlusConfiguration__c testCSData = new CCR_CarePlusConfiguration__c(Name='KR', CCR_Country__c='Korea', CCR_CarePlusActivated__c=true, CCR_L0codes__c='C101', CCR_AccidentalDamageLimit__c=2);//Amrit Das added CCR_BrandFamiliesCovered__c as a part of CCR-174919
        insert testCSData;
        user admuser=CCR_TestUtility.createAdminUserforCountry('Korea, Republic of','KR');
        System.runAs(admuser) {
            List<Contact> con = CCR_TestUtility.createContacts(1);
            //List<CCR_DeviceDiagnostic__c> deviceDiagnostics = Test.loadData(CCR_DeviceDiagnostic__c.sObjectType, 'CCR_DeviceDiagnostics');
            list<CCR_Material__c> mats= CCR_TestUtility.createMaterials(1,'D0201','2.4','JP04');
            mats[0].CCR_Color__c = 'SLV';
            update mats;
            CCR_DeviceDiagnostic__c devicediagnostic = new CCR_DeviceDiagnostic__c(CCR_Model__c = 'A1403', CCR_Active__c = true, RecordTypeId = DEVICEISSUE);
            insert devicediagnostic;
            CCR_DeviceDiagnosticLocalization__c qureMessage = new CCR_DeviceDiagnosticLocalization__c(CCR_DeviceDiagnostic__c =devicediagnostic.Id, CCR_Country__c = 'KR', CCR_Language__c ='en', CCR_Message__c = 'test message');
            insert qureMessage;
            List<RecordType> limitedEditionType = [SELECT Id
            FROM RecordType
            WHERE SObjectType = 'CCR_QureConfiguration__c'
            AND DeveloperName = 'CCR_LimitedEdition'];
            Asset ast = CCR_TestUtility.createassets(mats[0].id,con[0].id, CCR_Constants.ASSETACTIVE, TESTCODENTIFY, TESTPARENTCODENTIFY, TESTINTERNALID);
            CCR_QureHistory__c qureHis = new CCR_QureHistory__c(CCR_Device__c = ast.Id, CCR_QureChannel__c = 'E-Commerce', CCR_DiagnosticResult__c = 'HC1', CCR_DiagnosticDescription__c='Paint Peeling',
                    CCR_EndDiagnostic__c = datetime.now(), CCR_EligibilityResult__c = CCR_Constants.NOTELIGIBLE);
            insert qureHis;
            CCR_QureConfiguration__c qureConfig = new CCR_QureConfiguration__c( CCR_Model__c = 'A1403',CCR_Color__c='SLV',
                    recordtypeid = limitedEditionType[0].Id, CCR_Country__c ='KR');
            insert qureConfig;
            user u = CCR_TestUtility.createCallCntAgentForCountry('Korea, Republic of');
            ast.OwnerId = u.Id;
            update ast;
            con[0].OwnerId = u.Id;
            update con;
        }
    }
    /*
* Method Name: positiveTestAsset;
* Arguments :
* Return : Pagereference
* Description :test
*/
    static testMethod void positiveTestAsset() {
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c ='Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        usrqure.CCR_UserType__c = 'Call Center Agent';
        update usrqure;
        system.debug('&&&&'+usrqure);
        DateTime startTime = DateTime.now();
        Boolean limitedDevice = false;
        String qurhstrChannel ='Call Center Agent';
        System.runAs(usrqure) {
            asset astRec =[SELECT Id, Status, CCR_CodentifyId__c,
                    Contact.CCR_CountryID__c,
                    CCR_DeviceProductCode__r.CCR_ModelNumber__c,
                    CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            astRec.Status = 'active';
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            system.debug('astRec.CCR_EligibilityDueDate__c'+astRec.CCR_EligibilityDueDate__c);
            update astRec;
            system.debug('astRec  '+astRec);
            system.Debug('quey res '+[SELECT Id FROM CCR_DeviceDiagnostic__c
            WHERE CCR_Active__c = true AND
            CCR_Model__c=:astRec.CCR_DeviceProductCode__r.CCR_ModelNumber__c]);
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];
            qureHistory[0].CCR_QureReplacementChannel__c = CCR_Constants.PICKUPATCVSSTORE;
            update qureHistory;
            system.debug('qureHistory'+qureHistory);
            System.assert(qureHistory[0].CCR_QureReplacementChannel__c  != null);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            quremsg.UserType = 'Call Center Agent';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            qureHistory[0].CCR_QureReplacementChannel__c = CCR_Constants.COURIERDELIVERY;
            update qureHistory;
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            qureHistory[0].CCR_QureReplacementChannel__c = CCR_Constants.FACETOFACE;
            update qureHistory;
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            CCR_QurePreEligibility.updateQurechannel(usrqure.CCR_UserType__c);
            CCR_QurePreEligibility.createQurehistory(astRec, startTime, limitedDevice, qurhstrChannel);
            CCR_QurePreEligibility.updateQureHistory(qureHistory[0]);
            test.stopTest();

        }
    }

    /*
* Method Name: positiveTestAsset;
* Arguments :
* Return : Pagereference
* Description :test
*/
    static testMethod void testNodeviceDiagnostic() {
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c ='Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        usrqure.CCR_UserType__c = 'Call Center Agent';
        update usrqure;
        system.debug('&&&&'+usrqure);
        DateTime startTime = DateTime.now();
        Boolean limitedDevice = false;
        String qurhstrChannel ='Call Center Agent';
        System.runAs(usrqure) {
            asset astRec =[SELECT Id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c,
                    CCR_DeviceProductCode__r.CCR_ModelNumber__c,CCR_EligibilityDueDate__c
            FROM asset limit 1];
            astRec.Status = 'active';
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            update astRec;
            system.Debug('quey res '+[SELECT Id FROM CCR_DeviceDiagnostic__c
            WHERE CCR_Active__c = true AND
            CCR_Model__c=:astRec.CCR_DeviceProductCode__r.CCR_ModelNumber__c]);
            CCR_DeviceDiagnostic__c devicediagnostic = [SELECT Id,CCR_Model__c
            FROM CCR_DeviceDiagnostic__c
            WHERE CCR_Model__c ='A1403'];
            devicediagnostic.CCR_Active__c = false;
            update devicediagnostic;
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];
            qureHistory[0].CCR_QureReplacementChannel__c = CCR_Constants.PICKUPATCVSSTORE;
            update qureHistory;
            system.debug('qureHistory'+qureHistory);
            System.assert(qureHistory[0].CCR_QureReplacementChannel__c  != null);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            CCR_QurePreEligibility.updateQurechannel(usrqure.CCR_UserType__c);
            CCR_QurePreEligibility.createQurehistory(astRec, startTime, limitedDevice, qurhstrChannel);
            CCR_QurePreEligibility.updateQureHistory(qureHistory[0]);
            test.stopTest();

        }
    }
    /**
* Method Name :  testdata
* Arguments: positiveTestAsset1
* Return : None
* Description: Test data method.
**/
    static testMethod void positiveTestAsset1() {
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c ='Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        usrqure.CCR_UserType__c = 'Consumer';
        update usrqure;
        DateTime startTime = DateTime.now();
        Boolean limitedDevice = false;
        String qurhstrChannel ='Consumer';
        System.runAs(usrqure) {
            //List<Contact> con = CCR_TestUtility.createContacts(1);
            asset astRec =[SELECT Id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c,CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            astRec.Status = 'active';
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            system.debug('astRec.CCR_EligibilityDueDate__c'+astRec.CCR_EligibilityDueDate__c);
            update astRec;
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];
            CCR_DeviceDiagnostic__c devicediagnostic = [SELECT Id,CCR_Model__c
            FROM CCR_DeviceDiagnostic__c
            WHERE CCR_Model__c ='A1403'];
            devicediagnostic.CCR_Active__c = true ;
            update devicediagnostic;
            qureHistory[0].CCR_QureReplacementChannel__c = CCR_Constants.COURIERDELIVERY;
            update qureHistory;
            system.debug('qureHistory'+qureHistory);
            System.assert(qureHistory[0].CCR_QureReplacementChannel__c  != null);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            CCR_QurePreEligibility.updateQurechannel(usrqure.CCR_UserType__c);
            CCR_QurePreEligibility.createQurehistory(astRec, startTime, limitedDevice, qurhstrChannel);
            CCR_QurePreEligibility.updateQureHistory(qureHistory[0]);
            test.stopTest();

        }
    }
    /**
* Method Name :  positiveTestAsset2
* Arguments:
* Return : None
* Description: Test data method.
**/
    static testMethod void positiveTestAsset2() {
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c ='Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        usrqure.CCR_UserType__c = 'Flagship Store Agent';
        update usrqure;
        DateTime startTime = DateTime.now();
        Boolean limitedDevice = false;
        String qurhstrChannel ='SYSADm';
        System.runAs(usrqure) {
            asset astRec =[SELECT Id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c, CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            astRec.Status = 'active';
            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            system.debug('astRec.CCR_EligibilityDueDate__c'+astRec.CCR_EligibilityDueDate__c);
            update astRec;
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];
            qureHistory[0].CCR_QureReplacementChannel__c = CCR_Constants.COURIERDELIVERY;
            update qureHistory;
            system.debug('qureHistory'+qureHistory);
            System.assert(qureHistory[0].CCR_QureReplacementChannel__c  != null);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            CCR_QurePreEligibility.updateQurechannel(usrqure.CCR_UserType__c);
            CCR_QurePreEligibility.createQurehistory(astRec, startTime, limitedDevice, qurhstrChannel);
            CCR_QurePreEligibility.updateQurechannel(CCR_Constants.SERVICECENTERS);
            CCR_QurePreEligibility.updateQurechannel(CCR_Constants.FLAGSHIPSTORE);
            test.stopTest();

        }
    }
    /**
* Method Name :  positiveTestAsset2
* Arguments:
* Return : None
* Description: Test data method.
**/
    static testMethod void positiveTestAsset3(){
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c = 'Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        usrqure.CCR_UserType__c = 'Flagship Store Agent';
        update usrqure;
        system.debug('####'+usrqure);
        DateTime startTime = DateTime.now();
        Boolean limitedDevice = false;
        String qurhstrChannel = CCR_Constants.SERVICECENTERS;
        System.runAs(usrqure) {
            asset astRec =[SELECT Id, Status, CCR_CodentifyId__c,
                    Contact.CCR_CountryID__c,
                    CCR_EligibilityDueDate__c
            FROM asset  LIMIT 1];
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            astRec.Status = 'active';
            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            system.debug('astRec.CCR_EligibilityDueDate__c'+astRec.CCR_EligibilityDueDate__c);
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];

            qureHistory[0].CCR_QureReplacementChannel__c = CCR_Constants.PICKUPATCVSSTORE;
            update qureHistory;
            system.debug('qureHistory'+qureHistory);
            System.assert(qureHistory[0].CCR_QureReplacementChannel__c  != null);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            CCR_QurePreEligibility.updateQurechannel(usrqure.CCR_UserType__c);
            CCR_QurePreEligibility.createQurehistory(astRec, startTime, limitedDevice, qurhstrChannel);
            CCR_QurePreEligibility.updateQurechannel(CCR_Constants.SERVICECENTERS);
            CCR_QurePreEligibility.updateQurechannel(CCR_Constants.FLAGSHIPSTORE);
            CCR_QurePreEligibility.updateQureHistory(qureHistory[0]);
            test.stopTest();


        }

    }
    /**
* Method Name :
* Arguments:
* Return : None
* Description: Test data method.
**/
    static testMethod void negiviteTest(){
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c = 'Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        System.runAs(usrqure) {
            asset astRec =[SELECT Id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c, CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            astRec.Status = 'Produced';
            Update astRec;
            System.assert(astRec.Status != null);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            test.stopTest();
        }
    }
    /**
* Method Name :  positiveTestAsset4
* Arguments:
* Return : None
* Description: Test data method.
**/
    static testMethod void positiveTestAsset4(){
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c = 'Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        System.runAs(usrqure) {
            asset astRec =[SELECT id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c, CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            //astRec.Status = 'active';
            system.debug('status'+astRec.Status);
            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            update astRec;
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];

            qureHistory[0].CCR_QureReplacementChannel__c = CCR_Constants.FACETOFACE;
            update qureHistory;
            System.assert(qureHistory[0].CCR_QureReplacementChannel__c != null);
            system.debug('qureHistoryF2F'+qureHistory);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            test.stopTest();

        }

    }

    static testMethod void positiveTestAsset6(){
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c = 'Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        System.runAs(usrqure) {
            asset astRec =[SELECT id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c, CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            //astRec.Status = 'active';
            system.debug('status'+astRec.Status);
            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            update astRec;
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];

            qureHistory[0].CCR_QureReplacementChannel__c = null;
            update qureHistory;
//            System.assert(qureHistory[0].CCR_QureReplacementChannel__c != null);
            system.debug('qureHistoryF2F'+qureHistory);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            test.stopTest();

        }

    }

    /**
* Method Name :  positiveTestAsset5
* Arguments:
* Return : None
* Description: Test data method.
**/
    static testMethod void positiveTestAsset5(){
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c = 'Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        System.runAs(usrqure) {
            asset astRec =[SELECT id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c, CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            astRec.Status = 'active';
            system.debug('status'+astRec.Status);
            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            update astRec;
            qureHistory[0].CCR_QureReplacementChannel__c = CCR_Constants.PICKUPATCVSSTORE;
            update qureHistory;
            System.assert(qureHistory[0].CCR_QureReplacementChannel__c != null);
            system.debug('qureHistoryCVS'+qureHistory);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            test.stopTest();
        }
    }
    /**
* Method Name :  negiviteTest2
* Arguments:
* Return : None
* Description: Test data method.
**/
    static testMethod void negiviteTest2(){
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c = 'Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        system.debug('usrqure'+usrqure);
        System.runAs(usrqure) {
            asset astRec =[SELECT id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c, CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            update astRec;
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];

            qureHistory[0].CCR_QureReplacementChannel__c = CCR_Constants.COURIERDELIVERY;
            update qureHistory;
            System.assert(qureHistory[0].CCR_QureReplacementChannel__c != null);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            test.stopTest();

        }

    }
    /**
* Method Name :  negiviteTest3
* Arguments:
* Return : None
* Description: Test data method.
**/
    static testMethod void negiviteTest3(){
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c = 'Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        usrqure.CCR_UserType__c = 'Consumer';
        update usrqure;
        system.debug('usrqure@@'+usrqure);
        System.runAs(usrqure) {
            asset astRec =[SELECT id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c, CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            update astRec;
            system.assert(astRec.CCR_EligibilityDueDate__c !=null);
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];

            qureHistory[0].CCR_QureReplacementChannel__c = null;
            update qureHistory;
            system.debug('QureReplacementChannel'+qureHistory);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            test.stopTest();

        }

    }
    /**
* Method Name :  negiviteTest3
* Arguments:
* Return : None
* Description: Test data method.
**/
    static testMethod void negiviteTest4(){
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c = 'Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        usrqure.CCR_UserType__c = 'Flagship Store Agent';
        update usrqure;
        system.debug('servicecenter'+usrqure);
        System.runAs(usrqure) {
            asset astRec =[SELECT id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c, CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            update astRec;
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];

            qureHistory[0].CCR_QureReplacementChannel__c = CCR_Constants.FACETOFACE;
            update qureHistory;
            System.assert(qureHistory[0].CCR_QureReplacementChannel__c != null);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            test.stopTest();

        }
    }
    /**
* Method Name :  negiviteTest3
* Arguments:
* Return : None
* Description: Test data method.
**/
    static testMethod void negiviteTest5(){
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c = 'Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        usrqure.CCR_UserType__c = 'Corner Shop Agent';
        update usrqure;
        system.debug('servicecenter2'+usrqure);
        System.runAs(usrqure) {
            asset astRec =[SELECT id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c, CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            update astRec;
            system.assert(astRec.CCR_EligibilityDueDate__c != null);
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];

            qureHistory[0].CCR_QureReplacementChannel__c = null;
            update qureHistory;
            system.debug('QureReplacementChannel'+qureHistory);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            test.stopTest();

        }

    }

    static testMethod void negiviteTest6(){
        user usrqure =[SELECT Id,CCR_UserType__c
        FROM user
        WHERE  CCR_UserType__c = 'Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        usrqure.CCR_UserType__c = 'Consumer';
        update usrqure;
        system.debug('servicecenter2'+usrqure);
        System.runAs(usrqure) {
            asset astRec =[SELECT id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c, CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            System.currentPageReference().getParameters().put('asset',astRec.Id);
//            astRec.CCR_EligibilityDueDate__c = system.today().addDays(1) ;
            astRec.CCR_CarePlusStatus__c = 'Disenrolled';
            update astRec;
//            system.assert(astRec.CCR_EligibilityDueDate__c != null);
            List<CCR_QureHistory__c> qureHistory = [SELECT Id,CCR_QureChannel__c,CCR_Device__c,CCR_EndDiagnostic__c,
                    CCR_QureReplacementChannel__c,
                    CCR_EligibilityResult__c,CCR_CodeToBeEscalated__c FROM CCR_QureHistory__c
            WHERE CCR_Device__c =:astRec.id
            ORDER BY createddate DESC LIMIT 1];

            qureHistory[0].CCR_QureReplacementChannel__c = null;
            update qureHistory;
            system.debug('QureReplacementChannel'+qureHistory);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            test.stopTest();

        }

    }

    /**
* Method Name :  qureNotActive
* Arguments:
* Return : None
* Description: Test data method.
**/
    static testMethod void qureNotActive(){
        user usrqure =[SELECT Id,CCR_UserType__c,country
        FROM user WHERE  CCR_UserType__c = 'Call Center Agent'
        ORDER BY CreatedDate DESC LIMIT 1];
        system.debug('user'+usrqure);
        System.runAs(usrqure) {
            asset astRec =[SELECT Id, Status, CCR_CodentifyId__c,Contact.CCR_CountryID__c,contactid, CCR_EligibilityDueDate__c
            FROM asset LIMIT 1];
            System.currentPageReference().getParameters().put('asset',astRec.Id);
            contact con = [SELECT Id,CCR_CountryID__c
            FROM contact
            WHERE id =: astRec.contactid];
            con.CCR_CountryID__c = 'FR';
            update con;
            system.debug('@@astRec'+astRec);
            system.assert(con.CCR_CountryID__c != null);
            test.startTest();
            CCR_QureMsg quremsg = new CCR_QureMsg();
            quremsg.Codentify = astRec.CCR_CodentifyId__c;
            quremsg.Market = 'KR';
            CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
            test.stopTest();
        }
    }

    /**
   * Method Name :  qureNotActive
   * Description: Test data method.
   **/
    static testMethod void subscriptionsDeviceQureBlock(){
        asset astRec =[SELECT Id, CCR_SubscribedDevice__c, CCR_SubscriptionID__c,
                Status, CCR_CodentifyId__c, Contact.CCR_CountryID__c,
                CCR_DeviceProductCode__r.CCR_ModelNumber__c, CCR_EligibilityDueDate__c
        FROM asset limit 1];
        astRec.CCR_SubscribedDevice__c = true;
        astRec.CCR_SubscriptionID__c = '12345SubscriptionDevice';
        update astRec;
        test.startTest();
        CCR_QureMsg quremsg = new CCR_QureMsg();
        quremsg.Codentify = astRec.CCR_CodentifyId__c;
        quremsg.Market = 'KR';
        quremsg.UserType = 'Call Center Agent';
        CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg);
        //system.assert(quremsg.ErrorMsgId == CCR_Constants.SUBSCRIPTIONUNPAIDAGENT);
        CCR_QureMsg quremsg1 = new CCR_QureMsg();
        quremsg1.Codentify = astRec.CCR_CodentifyId__c;
        quremsg1.Market = 'KR';
        quremsg1.UserType = 'Consumer';
        CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg1);
//        system.assert(quremsg1.ErrorMsgId == CCR_Constants.SUBSCRIPTIONUNPAIDCONSUMER);
        CCR_QureMsg quremsg2 = new CCR_QureMsg();
        quremsg2.Codentify = astRec.CCR_CodentifyId__c;
        quremsg2.Market = 'KR';
        quremsg2.UserType = 'Call Center Agent';
        CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg2);
//        system.assert(quremsg2.ErrorMsgId == CCR_Constants.SUBSQUREDISABLEAGENT);
        CCR_QureMsg quremsg3 = new CCR_QureMsg();
        quremsg3.Codentify = astRec.CCR_CodentifyId__c;
        quremsg3.Market = 'KR';
        quremsg3.UserType = 'Consumer';
        CCR_QurePreEligibility.runPreeligibilitychecksqure(quremsg3);
//        system.assert(quremsg3.ErrorMsgId == CCR_Constants.SUBSQUREDISABLECONSUMER);
        CCR_QurePreEligibility.forTest();
        CCR_Constants c = new CCR_Constants();
        test.stopTest();
    }
}