force-app/main/default/objects/Asset/fields/CCR_CodentifyId__c.field-meta.xml
<CustomField>
    <fullName>CCR_CodentifyId__c</fullName>
    <description>Unique identifier of the device to be used as external key.</description>
    <externalId>true</externalId>
    <label>Codentify ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IF_MG_SFDC_Dummy__c/IF_MG_SFDC_Dummy__c.object-meta.xml
<CustomObject>
    <label>IF_MG_SFDC_Dummy</label>
    <nameField>
        <displayFormat>MG_SFDC-{0000000000}</displayFormat>
        <label>IF_MG_SFDC_Dummy 이름</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IF_MG_SFDC_Dummy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_MG_SFDC_Dummy__c/fields/Parentcodentify__c.field-meta.xml
<CustomField>
    <fullName>Parentcodentify__c</fullName>
    <label>Parentcodentify</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_MG_SFDC_Dummy__c/fields/ToReplaceCodentify__c.field-meta.xml
<CustomField>
    <fullName>ToReplaceCodentify__c</fullName>
    <label>ToReplaceCodentify</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IF_MG_SFDC_Dummy_tr_ts.cls
/****************************************************************************************
  * @filename      : IF_MG_SFDC_Dummy_tr_ts
  * @projectname   : PMK qa - KR
  * @author        : Park HE
  * @date          : 2021-05-24
  * @group         :
  * @group-content :
  * @description   :
  * @tester        :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                    author          description
  * ===============================================================
    0.1     2021-05-24             Park HE         Create
****************************************************************************************/

@IsTest
private class IF_MG_SFDC_Dummy_tr_ts {
    @IsTest
    static void testBehavior() {

        Asset oldAsset = KDCE_TestUtil.assetCharger.clone(true);
        oldAsset.ContactId = KDCE_TestUtil.contactMember.Id;
        update oldAsset;

        IF_MG_SFDC_Dummy__c dummy = new IF_MG_SFDC_Dummy__c(
                Parentcodentify__c = KDCE_TestUtil.assetHolder.SerialNumber,
                ToReplaceCodentify__c = oldAsset.CCR_CodentifyId__c
        );
        insert dummy;

        IF_MG_SFDC_Dummy__c dummy2 = new IF_MG_SFDC_Dummy__c(
                Parentcodentify__c = 'testCodentify',
                ToReplaceCodentify__c = oldAsset.CCR_CodentifyId__c
        );
        insert dummy2;
    }
}