force-app/main/default/objects/Asset/fields/CCR_CarePlusDueDate__c.field-meta.xml
<CustomField>
    <fullName>CCR_CarePlusDueDate__c</fullName>
    <label>Care+ Due Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_Override__c.field-meta.xml
<CustomField>
    <fullName>CCR_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by: CCR
Description: To store information if eligibility result has been overwritten by the agent.</description>
    <label>Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/KDCE_ReplacementSource__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ReplacementSource__c</fullName>
    <description>[KDCE] Replacement Source</description>
    <label>Replacement Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>QURE</fullName>
            </value>
            <value>
                <fullName>KIT TO KIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_CarePlusStatus_ba_ts.cls
/****************************************************************************************
  * @filename      : KDCE_CarePlusStatus_ba_ts
  * @projectname   : PMK qa - KR
  * @author        : Park HE
  * @date          : 2021-05-28
  * @group         :
  * @group-content :
  * @description   :
  * @tester        :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                    author          description
  * ===============================================================
    0.1     2021-05-28             Park HE         Create
****************************************************************************************/

@IsTest
private class KDCE_CarePlusStatus_ba_ts {
    static {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();
    }

    @IsTest
    static void testBehavior1() {
        Test.startTest();

        Asset asset = KDCE_TestUtil.assetCharger.clone(true);
        asset.CCR_CarePlusDueDate__c = System.Today().addDays(-1);
        asset.KDCE_ReplacementSource__c = 'Qure';
        update asset;

        KDCE_CarePlusStatus_ba ba = new KDCE_CarePlusStatus_ba();
        Id batchId = Database.executeBatch(ba);
        Test.stopTest();

    }

    @IsTest
    static void testBehavior2() {
        Test.startTest();

        Asset asset = KDCE_TestUtil.assetCharger.clone(true);
        asset.CCR_CarePlusDueDate__c = System.Today().addDays(-1);
        asset.CCR_Override__c = true;
        update asset;

        KDCE_CarePlusStatus_ba ba = new KDCE_CarePlusStatus_ba();
        Id batchId = Database.executeBatch(ba);
        Test.stopTest();

    }

    @IsTest
    static void testBehavior3() {
        Test.startTest();

        Asset asset = KDCE_TestUtil.assetCharger.clone(true);
        asset.CCR_CarePlusDueDate__c = System.Today().addDays(-1);
        asset.KDCE_ReplacementSource__c = null;
        update asset;

        KDCE_CarePlusStatus_ba ba = new KDCE_CarePlusStatus_ba();
        Id batchId = Database.executeBatch(ba);
        Test.stopTest();

    }


}