force-app/main/default/objects/Asset/fields/CCR_CarePlusDueDate__c.field-meta.xml
<CustomField>
    <fullName>CCR_CarePlusDueDate__c</fullName>
    <label>Care+ Due Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_CarePlusStatus__c.field-meta.xml
<CustomField>
    <fullName>CCR_CarePlusStatus__c</fullName>
    <label>Care+ Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CCR_Inbound_Outbound__c.field-meta.xml
<CustomField>
    <fullName>CCR_Inbound_Outbound__c</fullName>
    <label>Inbound/Outbound</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCR_SubjectCodeNew__c.field-meta.xml
<CustomField>
    <fullName>CCR_SubjectCodeNew__c</fullName>
    <description>Used by: CCR
Description: subject code is the dependent picklist of sub type.</description>
    <inlineHelpText>Subject Code</inlineHelpText>
    <label>Subject Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CCR_SubType__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CCR_SubjectCode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/KDCE_IsOnlineCase__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsOnlineCase__c</fullName>
    <defaultValue>false</defaultValue>
    <description>케이스 소유자의 division과 일치하는 store정보가 없으면 온라인, 아닐 경우 오프라인</description>
    <label>Online Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CCR_AdverseEvent.recordType-meta.xml
<RecordType>
    <fullName>CCR_AdverseEvent</fullName>
    <active>true</active>
    <businessProcess>Case Status</businessProcess>
    <description>When customer reports that an Adverse Event was experienced</description>
    <label>6-Adverse Event</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/CCR_ECommerceOrderOnBehalf.recordType-meta.xml
<RecordType>
    <fullName>CCR_ECommerceOrderOnBehalf</fullName>
    <active>true</active>
    <businessProcess>Case Status</businessProcess>
    <description>Questions related to online orders or if customer wants to place a new order</description>
    <label>2-Orders/Order On Behalf</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/CCR_HolderChargerAccessory.recordType-meta.xml
<RecordType>
    <fullName>CCR_HolderChargerAccessory</fullName>
    <active>true</active>
    <businessProcess>Case Status</businessProcess>
    <description>Case related to devices or accessories, only used when Asset codentify is unavailable (if codentify is available, start &quot;New asset case&quot; directly from the Asset detail screen</description>
    <label>3-Holder/Charger/Accessory</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/CCR_NewHeatStick.recordType-meta.xml
<RecordType>
    <fullName>CCR_NewHeatStick</fullName>
    <active>true</active>
    <businessProcess>Case Status</businessProcess>
    <description>New case for Heatstick</description>
    <label>7-HeatStick</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/CCR_QoachProgram.recordType-meta.xml
<RecordType>
    <fullName>CCR_QoachProgram</fullName>
    <active>false</active>
    <businessProcess>Case Status</businessProcess>
    <description>For Qoach Programs</description>
    <label>Qoach Program</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CCR_CarePlusDueDate__c.field-meta.xml
<CustomField>
    <fullName>CCR_CarePlusDueDate__c</fullName>
    <description>Field on Contact to store information about Care+ due date (Validity date): is the max(Validity Date, Due Dates) of all linked devices.</description>
    <label>Care+ Due Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CCR_CarePlusStatus__c.field-meta.xml
<CustomField>
    <fullName>CCR_CarePlusStatus__c</fullName>
    <description>Field on Contact level to show Care+ current status.
Person is Enrolled if at least one device is Care+ enrolled.</description>
    <label>Care+ Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Enrolled</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsDormant__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDormant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 배치로 인해 휴면 처리가 된 고객</description>
    <label>Dormant Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsMGMIssue__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsMGMIssue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 개발용</description>
    <label>MGM Coupon Issue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LASLAU__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LASLAU__c</fullName>
    <description>[KDCE] LAS / LAU</description>
    <label>LAS/LAU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LAS</fullName>
                <default>true</default>
                <label>LAS</label>
            </value>
            <value>
                <fullName>LAU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_MGMCode__c.field-meta.xml
<CustomField>
    <fullName>KDCE_MGMCode__c</fullName>
    <description>MGM Coupon Code</description>
    <externalId>true</externalId>
    <inlineHelpText>[KDCE] MGM 친구 추천인 코드</inlineHelpText>
    <label>MGM Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/CouponCode__c.field-meta.xml
<CustomField>
    <fullName>CouponCode__c</fullName>
    <description>[KDCE] Coupon Code</description>
    <externalId>true</externalId>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_MGM.recordType-meta.xml
<RecordType>
    <fullName>Coupon_MGM</fullName>
    <active>true</active>
    <description>[KDCE] MGM</description>
    <label>MGM</label>
</RecordType>

force-app/main/default/objects/KDCE_SurvyPerSubjectCode__c/KDCE_SurvyPerSubjectCode__c.object-meta.xml
<CustomObject>
    <label>Survey Per Subject Code</label>
    <nameField>
        <displayFormat>SSC-{0000}</displayFormat>
        <label>Survey Per Subject Code	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Per Subject Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_SurvyPerSubjectCode__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>카테고리</description>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>[i2sema] Notification Sending Infomations
알림 메세지 발송정보</description>
    <label>Notifications</label>
    <nameField>
        <displayFormat>N{yyMMdd}{0000000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Channel</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/NotificationGroup__c.field-meta.xml
<CustomField>
    <fullName>NotificationGroup__c</fullName>
    <label>Notification Group</label>
    <referenceTo>NotificationGroup__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/NotificationTemplate__c.field-meta.xml
<CustomField>
    <fullName>NotificationTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Notification Template</description>
    <label>Notification Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>NotificationTemplate__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NotificationTemplate__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NotificationGroup__c/NotificationGroup__c.object-meta.xml
<CustomObject>
    <description>[2020.02.10] Notification 발송요청 묶음</description>
    <label>Notification Group</label>
    <nameField>
        <displayFormat>NG{yyMMdd}{0000000000}</displayFormat>
        <label>Notification Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/NotificationTemplate__c.object-meta.xml
<CustomObject>
    <description>[i2sema] Notification Message Templates
Channel 별 알림 메세지 템플릿 제공</description>
    <label>Notification Template</label>
    <nameField>
        <label>Notification Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Notification 발송 채널</description>
    <label>Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>[20.01.06] 템플릿 내용</description>
    <label>Content</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>(x)External Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_Contact_tr_Test.cls
/****************************************************************************************
  * @filename      : KDCE_Contact_tr_Test
  * @projectname   : PMK LocalDCE QA
  * @author        : i2max_JE Yoon
  * @date          : 2021-03-30
  * @group         :
  * @description   : Contact 및 Case를 위한 Test Class
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                author              description
  * ===============================================================
    0.1  2021-03-30          i2max_JE Yoon             Create
    0.2  2021-03-31          i2max_JE Yoon             Update
****************************************************************************************/

@IsTest
private class KDCE_Contact_tr_Test {

    static List<Contact> contacts;
    static List<KDCE_Coupon__c> coupons;
    static Contact contact_with_Coupon;
    static Contact contact_without_Coupon;
    static String developerName_Coupon_MGM = 'Coupon_MGM';
    static String couponStatus_Produce = 'Produce';
    static String couponStatus_Issue = 'Issue';
    static String KDCE_LAU = 'LAU';

    // Case
    static Map<String, Id> caseRecordTypeMap = KDCE_Util.getRecordTypeBySObject('Case');
    private final static Id qoachProgramRTId    = caseRecordTypeMap.get('CCR_QoachProgram');
    private final static Id adverseEventRTId    = caseRecordTypeMap.get('CCR_AdverseEvent');
    private final static Id heatStickRTId       = caseRecordTypeMap.get('CCR_NewHeatStick');
    private final static Id ecommerceOrder      = caseRecordTypeMap.get('CCR_ECommerceOrderOnBehalf');


    static void getData() {

        contacts = [SELECT KDCE_IsMGMIssue__c, KDCE_LASLAU__c, KDCE_MGMCode__c FROM Contact LIMIT 2];

        for (Contact contact : contacts) {
            contact.KDCE_LASLAU__c = KDCE_LAU;
        }

        update contacts;

        contacts = [SELECT KDCE_IsMGMIssue__c, KDCE_LASLAU__c, KDCE_MGMCode__c FROM Contact LIMIT 2];
        coupons = [SELECT Status__c, Contact__c, CouponCode__c FROM KDCE_Coupon__c LIMIT 1];

        for (Contact contact : contacts) {
            if (contact.KDCE_IsMGMIssue__c == true) contact_with_Coupon = contact;
            else if (contact.KDCE_IsMGMIssue__c == false) contact_without_Coupon = contact;
        }

    }

    /**
     * @description Contact의 subType이 LAU로 변경되는 케이스 및 KDCE_IsMGMIssue__c = true 되는 시나리오에서
     *             컨택에게 발급할 쿠폰이 있는 케이스 테스트
     * @author JE Yoon (2021.03.30)
     **/
    @IsTest
    static void testCase01 () {

        Test.startTest();

        CouponTestDataUtil.getCoupon(developerName_Coupon_MGM, couponStatus_Produce);
        if (contact_with_Coupon == null) getData();

//        System.assertEquals(KDCE_LAU, contact_with_Coupon.KDCE_LASLAU__c);
//        System.assertEquals(true, contact_with_Coupon.KDCE_IsMGMIssue__c);
//        System.assertEquals(coupons[0].Contact__c, contact_with_Coupon.Id);
//        System.assertEquals(coupons[0].CouponCode__c, contact_with_Coupon.KDCE_MGMCode__c);
//        System.assertEquals(couponStatus_Issue, coupons[0].Status__c);
//        System.assertEquals(false, contact_without_Coupon.KDCE_IsMGMIssue__c);
        Test.stopTest();
    }

    /**
     * @description Contact의 subType이 LAU로 변경되는 케이스 및 KDCE_IsMGMIssue__c = true 되는 시나리오에서
     *             컨택에게 발급할 쿠폰이 없는 케이스 테스트
     * @author JE Yoon (2021.03.30)
     **/
    @IsTest
    static void testCase02 () {

        Test.startTest();

        CouponTestDataUtil.getContacts(developerName_Coupon_MGM);
        if (contact_without_Coupon == null) getData();

        System.assertEquals(KDCE_LAU, contact_without_Coupon.KDCE_LASLAU__c);
        System.assertEquals(false, contact_without_Coupon.KDCE_IsMGMIssue__c);
        System.assertEquals(0, coupons.size());
        System.assertEquals(null, contact_with_Coupon);
        
        Test.stopTest();
    }

    @IsTest
    static void testRestore() {
        Contact contact = KDCE_TestUtil.contactMember;
        contact.KDCE_IsDormant__c = true;
        contact.KDCE_LASLAU__c = 'LAU';
        update contact;
    }

    @IsTest
    static void testreCalculateAssetCarePlusStatus() {
        Test.startTest();
        Contact contact = KDCE_TestUtil.contactMember;
        contact.CCR_CarePlusStatus__c = 'Not Enrolled';
        contact.CCR_CarePlusDueDate__c = null;
        update contact;

        Asset asset = KDCE_TestUtil.assetHolder.clone(true);
        asset.CCR_CarePlusStatus__c = 'Not Enrolled';
        asset.CCR_CarePlusDueDate__c = null;
        asset.ContactId = contact.Id;
        update asset;

        contact.CCR_CarePlusStatus__c = 'Enrolled';
        update contact;

        Test.stopTest();
    }

    /**
     * Case_tr Testcode
     *
     */
    @IsTest
    static void sendNPSSurveySMS() {
        Test.startTest();
        Case caseItem = KDCE_TestUtil.caseItem.clone(false);
        caseItem.Status = 'New';
        caseItem.RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CCR_HolderChargerAccessory').getRecordTypeId();
        insert caseItem;

        KDCE_SurvyPerSubjectCode__c subCode = new KDCE_SurvyPerSubjectCode__c(
                Category__c = '3-홀더/충전기/액세서리 이슈'
        );
        insert subCode;

        caseItem.Status = 'Closed';
        update caseItem;
        Test.stopTest();
    }

    @IsTest
    static void testCaseBehavior01() {

        List<Case> insertCases = new List<Case>();

        Case webToCase = new Case(
                SuppliedEmail = 'test@email.com', SuppliedName = 'Nme', SuppliedPhone = '0102838291727', Origin = 'Web',
                ContactId = KDCE_TestUtil.getContactMember().Id
        );
        insertCases.add(webToCase);

        Case emailToCase = webToCase.clone(false, true);
        emailToCase.Origin = 'Email';
        insertCases.add(emailToCase);

        Case chatToCase = webToCase.clone(false, true);
        chatToCase.Origin = 'Chat';
        insertCases.add(chatToCase);

        Case webToCase2 = webToCase.clone(false, true);
        webToCase2.ContactId = KDCE_TestUtil.getContactMember().Id;
        webToCase2.CCR_Inbound_Outbound__c = 'Inbound';
        webToCase2.KDCE_IsOnlineCase__c = true;
        insertCases.add(webToCase2);

        insert insertCases;

        webToCase2.RecordTypeId = KDCE_Util.getRecordTypeBySObject('Case').get('CCR_QoachProgram');
//        webToCase2.CCR_SubjectCodeNew__c = 'Remote Coach';

        update webToCase2;
    }

    @IsTest
    static void testCaseBehavior02() {

        NotificationTemplate__c notificationTemplate = new NotificationTemplate__c();
        notificationTemplate.Content__c = '';
        notificationTemplate.Channel__c = '0';
        notificationTemplate.ExternalId__c = 'Survey';
        insert notificationTemplate;
        System.debug('=== notificationTemplate : ' + notificationTemplate);

        NotificationGroup__c notificationGroup = new NotificationGroup__c();
        insert notificationGroup;
        System.debug('=== notificationGroup : ' + notificationGroup);

        Notification__c notification = new Notification__c();
        notification.Channel__c = '0';
        notification.NotificationTemplate__c = notificationTemplate.Id;
        notification.NotificationGroup__c = notificationGroup.Id;
        notification.Contact__c = KDCE_TestUtil.contactMember.Id;
        notification.Channel__c = '0';
        insert notification;
    }

    @IsTest
    static void testCaseBehavior03() {

        Case caseItem = KDCE_TestUtil.caseItem;
        caseItem.Status = 'Closed';
        caseItem.RecordTypeId = qoachProgramRTId;
        update caseItem;

        caseItem.RecordTypeId = adverseEventRTId;
        update caseItem;

        caseItem.RecordTypeId = heatStickRTId;
        update caseItem;
    }

    @IsTest
    static void testCaseBehavior04() {

        List<Case> insertCases = new List<Case>();
        Case webCase = new Case();
        webCase.Origin = 'Web';
        webCase.SuppliedPhone = '01029382949';
        webCase.SuppliedEmail = 'test321@naver.com';
        webCase.SuppliedName = 'testtest';
        webCase.ContactId = KDCE_TestUtil.contactMember.Id;

        Case emailCase = webCase.clone(false);
        emailCase.Origin = 'Email';
//        emailCase.RecordTypeId = qoachProgramRTId;

        Case chatCase = webCase.clone(false);
        webCase.SuppliedEmail = 'test32221@naver.com';
        webCase.SuppliedName = 'testtest22';
        chatCase.SuppliedPhone = '0102039299';
        chatCase.Origin = 'Chat';

        Case chatCase2 = new Case();
        chatCase2.Origin = 'Chat';
        chatCase2.SuppliedName = KDCE_TestUtil.contactMember.LastName;
        chatCase2.SuppliedEmail = KDCE_TestUtil.contactMember.Email;
        chatCase2.SuppliedPhone = KDCE_TestUtil.contactMember.Phone;

        insertCases.add(webCase);
        insertCases.add(emailCase);
        insertCases.add(chatCase);
        insertCases.add(chatCase2);

        insert insertCases;
    }

    @IsTest
    static void testCaseBehavior05() {
        List<Case> insertCases = new List<Case>();
        List<Case> updateCases = new List<Case>();
        Case webCase = new Case();
        webCase.Origin = 'Web';
        webCase.SuppliedPhone = '01029382949';
        webCase.SuppliedEmail = 'test321@naver.com';
        webCase.SuppliedName = 'testtest';

        Case newCase = new Case();
        newCase.ContactId = KDCE_TestUtil.contactMember.Id;
        newCase.RecordTypeId = heatStickRTId;
        newCase.Status = 'New';
        newCase.CCR_Inbound_Outbound__c = 'Inbound';
        newCase.KDCE_IsOnlineCase__c = true;

        insertCases.add(webCase);
        insertCases.add(newCase);
        insert insertCases;

        newCase.Status = 'Closed';
        newCase.RecordTypeId = ecommerceOrder;
        updateCases.add(webCase);
        updateCases.add(newCase);

        update updateCases;
    }

    @IsTest
    static void testCaseBehavior06() {
        List<Case> insertCases = new List<Case>();
        List<Case> updateCases = new List<Case>();
        Case emailCase = new Case();
        emailCase.Origin = 'Email';
        emailCase.SuppliedEmail = KDCE_TestUtil.contactMember.Email;

        Case emailCase2 = new Case();
        emailCase2.Origin = 'Email';
        emailCase2.SuppliedEmail = 'kdescemail@test.com';

        Case chatCase = new Case();
        chatCase.Origin = 'Chat';
        chatCase.SuppliedPhone = '01029382942319';
        chatCase.SuppliedEmail = 'test322131@naver.com';
        chatCase.SuppliedName = 'testtest232';

        insertCases.add(emailCase);
        insertCases.add(emailCase2);
        insertCases.add(chatCase);
        System.debug('=== insertCases : ' + insertCases);
        insert insertCases;

    }

}