force-app/main/default/objects/Asset/fields/CCR_EligibleForReplacement__c.field-meta.xml
<CustomField>
    <fullName>CCR_EligibleForReplacement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used By: CCR
Description: This field is for the Device the Eligible for replacement.</description>
    <label>(QURE) Eligible For Replacement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_MaterialGroupDescription__c.field-meta.xml
<CustomField>
    <fullName>CCR_MaterialGroupDescription__c</fullName>
    <description>Group Material description</description>
    <formula>CCR_DeviceProductCode__r.CCR_GroupDescription__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Group Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CCR_Country__c.field-meta.xml
<CustomField>
    <fullName>CCR_Country__c</fullName>
    <description>used for routing the web to case to the right queue of the respective country -not visible on page layout.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CTI_CountryISOs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCR_DiagnosticDescription__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticDescription__c</fullName>
    <description>Used By: CCR
Description: This field stores the diagnostic descriptive information and is populated during Qure process</description>
    <label>Diagnostic Description</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticDescription</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCR_DiagnosticResult__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticResult__c</fullName>
    <description>Used by: CCR Description: It&apos;s to store information about diagnostic result.</description>
    <label>Diagnostic Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticResult</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_CarePlusConfiguration__c/CCR_CarePlusConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to store Care+ configuration per market</description>
    <label>CCR Care+ Configuration</label>
</CustomObject>

force-app/main/default/objects/CCR_CarePlusConfiguration__c/fields/CCR_AccidentalDamageLimit__c.field-meta.xml
<CustomField>
    <fullName>CCR_AccidentalDamageLimit__c</fullName>
    <description>Field to store information how many times device has been replaced due to Accidental Damage.</description>
    <label>Accidental Damage Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCR_CarePlusConfiguration__c/fields/CCR_CarePlusActivated__c.field-meta.xml
<CustomField>
    <fullName>CCR_CarePlusActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to store information if Care+ program is active for country.</description>
    <label>Care+ Activated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCR_CarePlusConfiguration__c/fields/CCR_Country__c.field-meta.xml
<CustomField>
    <fullName>CCR_Country__c</fullName>
    <description>Field to store information about country</description>
    <label>Country</label>
    <length>254</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR_CarePlusConfiguration__c/fields/CCR_L0codes__c.field-meta.xml
<CustomField>
    <fullName>CCR_L0codes__c</fullName>
    <description>Field to store all issue codes which are covered by Care+ program</description>
    <label>L0 codes</label>
    <length>254</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR_Material__c/CCR_Material__c.object-meta.xml
<CustomObject>
    <description>Created to store information regarding the Device Master Data (catalogue).</description>
    <label>Material</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_Material__c/fields/CCR_Material__c.field-meta.xml
<CustomField>
    <fullName>CCR_Material__c</fullName>
    <description>Contains the same value than the name field. The field is used to set the Material/Name as external id</description>
    <externalId>true</externalId>
    <label>Material</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/CCR_QureConfiguration__c.object-meta.xml
<CustomObject>
    <description>Used by: CCR
Description: It&apos;s to store information that will be used in back-end to execute pre-eligibility and eligibility checks during the Qure process.</description>
    <label>Qure Configuration</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Qure Configuration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qure Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_CodeToBeEscalated__c.field-meta.xml
<CustomField>
    <fullName>CCR_CodeToBeEscalated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by: CCR. 
Description: It&apos;s to store information if diagnostic result code should be escalated.</description>
    <label>Code to be Escalated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_Country__c.field-meta.xml
<CustomField>
    <fullName>CCR_Country__c</fullName>
    <description>Used by: CCR
Description: It&apos;s to store information about the country.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CTI_CountryISOs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_CoveredInWarranty__c.field-meta.xml
<CustomField>
    <fullName>CCR_CoveredInWarranty__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by: CCR. 
Description: It&apos;s to store information if diagnostic result code is covered by warranty.</description>
    <label>Covered in Warranty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_DiagnosticDescription__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticDescription__c</fullName>
    <description>Used By: CCR 
Description: It&apos;s to store Qure diagnostic issue description.</description>
    <label>Diagnostic Description</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticDescription</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_DiagnosticResult__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticResult__c</fullName>
    <description>Used by: CCR
Description: It&apos;s to store information about diagnostic result code as also used in Device diagnostic.</description>
    <label>Diagnostic Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticResult</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_EligibleForReplacement__c.field-meta.xml
<CustomField>
    <fullName>CCR_EligibleForReplacement__c</fullName>
    <description>Used by: CCR
Description: It&apos;s to store information for how many days from Diagnostic process consumer is able to replace the device.</description>
    <label>Eligibile for Replacement (days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_L0code__c.field-meta.xml
<CustomField>
    <fullName>CCR_L0code__c</fullName>
    <description>Used by: CCR. 
Description: It&apos;s to store information about L0 code (ex. A1, B1)</description>
    <label>L0 code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A01</fullName>
            </value>
            <value>
                <fullName>A411</fullName>
            </value>
            <value>
                <fullName>A412</fullName>
            </value>
            <value>
                <fullName>A413</fullName>
            </value>
            <value>
                <fullName>A414</fullName>
            </value>
            <value>
                <fullName>B02</fullName>
            </value>
            <value>
                <fullName>B03</fullName>
            </value>
            <value>
                <fullName>B01</fullName>
            </value>
            <value>
                <fullName>C01</fullName>
            </value>
            <value>
                <fullName>C02</fullName>
            </value>
            <value>
                <fullName>B04</fullName>
            </value>
            <value>
                <fullName>B05</fullName>
            </value>
            <value>
                <fullName>B07</fullName>
            </value>
            <value>
                <fullName>B06</fullName>
            </value>
            <value>
                <fullName>B08</fullName>
            </value>
            <value>
                <fullName>B09</fullName>
            </value>
            <value>
                <fullName>A101</fullName>
            </value>
            <value>
                <fullName>B102</fullName>
            </value>
            <value>
                <fullName>C002</fullName>
            </value>
            <value>
                <fullName>B037</fullName>
            </value>
            <value>
                <fullName>B104</fullName>
            </value>
            <value>
                <fullName>B038</fullName>
            </value>
            <value>
                <fullName>B045</fullName>
            </value>
            <value>
                <fullName>B006</fullName>
            </value>
            <value>
                <fullName>B105</fullName>
            </value>
            <value>
                <fullName>B101</fullName>
            </value>
            <value>
                <fullName>C101</fullName>
            </value>
            <value>
                <fullName>B103</fullName>
            </value>
            <value>
                <fullName>B033</fullName>
            </value>
            <value>
                <fullName>B050</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_MaterialGroupDescription__c.field-meta.xml
<CustomField>
    <fullName>CCR_MaterialGroupDescription__c</fullName>
    <description>Used By: CCR 
Description: It&apos;s to store information about material group description.</description>
    <label>Material Group Description</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_MaterialGroupDescription</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_MaxNumberOfReplacementsPerDevice__c.field-meta.xml
<CustomField>
    <fullName>CCR_MaxNumberOfReplacementsPerDevice__c</fullName>
    <description>Used by: CCR
Description: It&apos;s to store information how many times consumer is able to replace the same device.</description>
    <label>Max number of replacements per device</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_Model__c.field-meta.xml
<CustomField>
    <fullName>CCR_Model__c</fullName>
    <description>Used by: CCR
Description: It&apos;s to store information about the device model.</description>
    <label>Model</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/fields/CCR_SubjectCode__c.field-meta.xml
<CustomField>
    <fullName>CCR_SubjectCode__c</fullName>
    <description>Used by: CCR. 
Description: It&apos;s to store information about the subject code.</description>
    <label>Subject Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_SubjectCode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureConfiguration__c/recordTypes/CCR_MarketConfiguration.recordType-meta.xml
<RecordType>
    <fullName>CCR_MarketConfiguration</fullName>
    <active>true</active>
    <description>Used by: CCR  Description:It&apos;s to store information about market configuration per diagnostic result.</description>
    <label>Market Configuration</label>
</RecordType>

force-app/main/default/objects/CCR_QureConfiguration__c/recordTypes/CCR_MarketReplacement.recordType-meta.xml
<RecordType>
    <fullName>CCR_MarketReplacement</fullName>
    <active>true</active>
    <description>Used by: CCR  Description:It&apos;s to store information about limits for replacement specific for market.</description>
    <label>Market Replacement</label>
</RecordType>

force-app/main/default/objects/CCR_QureConfiguration__c/recordTypes/CCR_SubscriptionReplacement.recordType-meta.xml
<RecordType>
    <fullName>CCR_SubscriptionReplacement</fullName>
    <active>true</active>
    <description>This Record Type is for the Subscription Replacement</description>
    <label>Subscription Replacement</label>
</RecordType>

force-app/main/default/objects/CCR_QureHistory__c/CCR_QureHistory__c.object-meta.xml
<CustomObject>
    <description>Used by: CCR
Description: It&apos;s to store information collected during Qure process for that device.</description>
    <label>Qure History</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>QURE History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qure History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_CodeToBeEscalated__c.field-meta.xml
<CustomField>
    <fullName>CCR_CodeToBeEscalated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by: CCR. 
Description: It&apos;s to store information if code got as diagnostic result should be escalated or not.</description>
    <inlineHelpText>If it is Checked, Qure Escalated to Call Center Agent.</inlineHelpText>
    <label>Code To Be Escalated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_Device__c.field-meta.xml
<CustomField>
    <fullName>CCR_Device__c</fullName>
    <description>Used by: CCR. 
Description: Lookup field to Asset.</description>
    <label>Device</label>
    <referenceTo>Asset</referenceTo>
    <relationshipName>QURE_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_DiagnosticResult__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticResult__c</fullName>
    <description>Used by: CCR 
Description: It stores the unique code list for the diagnostic result used in QURE configuration and Device configuration</description>
    <label>Diagnostic Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticResult</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_SubjectCode__c.field-meta.xml
<CustomField>
    <fullName>CCR_SubjectCode__c</fullName>
    <description>Used by: CCR. 
Description: It&apos;s to store information about subject code.</description>
    <inlineHelpText>Replacement reason</inlineHelpText>
    <label>Subject Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_SubjectCode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CCR_QureUtility_ts.cls
/**
 * Created by I2MAX on 2021-07-20.
 */

@IsTest(seealldata = false)
private class CCR_QureUtility_ts {
    @testSetup static void testdata() {

        user admuserKR = CCR_TestUtility.createAdminUserforCountry('Korea, Republic of','KR');
        CCR_CarePlusConfiguration__c testCSData = new CCR_CarePlusConfiguration__c(Name='KR', CCR_Country__c='Korea', CCR_CarePlusActivated__c=true, CCR_L0codes__c='C101', CCR_AccidentalDamageLimit__c=2);//Amrit Das added CCR_BrandFamiliesCovered__c as a part of CCR-174919
        insert testCSData;
        System.runAs(admuserKR) {
            list<CCR_Material__c> mats= CCR_TestUtility.createMaterials(1,'D0201','2.4','JP04');
            Asset ast = CCR_TestUtility.createassets(mats[0].id, null, CCR_Constants.ASSETPRODUCED, 'TESTCODENTIFY', 'TESTPARENTCODENTIFY', 'TESTINTERNALID');
            Asset ast1 = CCR_TestUtility.createassets(mats[0].id, null, CCR_Constants.ASSETPRODUCED, 'TESTCODENTIFY1', 'TESTPARENTCODENTIFY1', 'TESTINTERNALID1');
            Asset ast2 = CCR_TestUtility.createassets(mats[0].id, null, CCR_Constants.ASSETPRODUCED, 'CODENTIFYSUBS1', 'SERIALCODENTIFYSUBS1', 'TESTSUBSCRIPTI1');
            CCR_TestUtility.createassets(mats[0].id, null, CCR_Constants.ASSETREPLACED, 'TESTCODENTIFY2', 'TESTPARENTCODENTIFY2', 'TESTINTERNALID3');
            CCR_TestUtility.createassets(mats[0].id, null, CCR_Constants.ASSETREPLACED, 'CODENTIFYSUBS3', 'SERIALCODENTIFYSUBS3', 'TESTSUBSCRIPTI3');
            String marketConfigrecordtypeId = SObjectType.CCR_QureConfiguration__c.getRecordTypeInfosByDeveloperName().get('CCR_MarketConfiguration').getRecordTypeId();
            String marketRplacementrecordtypeId = SObjectType.CCR_QureConfiguration__c.getRecordTypeInfosByDeveloperName().get('CCR_MarketReplacement').getRecordTypeId();
            String subsRplacementrecordtypeId = SObjectType.CCR_QureConfiguration__c.getRecordTypeInfosByDeveloperName().get('CCR_SubscriptionReplacement').getRecordTypeId();
            List<CCR_QureConfiguration__c> configList = new List<CCR_QureConfiguration__c>();
            CCR_QureConfiguration__c qureConfig = new CCR_QureConfiguration__c(CCR_DiagnosticResult__c = 'HC1', CCR_DiagnosticDescription__c='Paint Peeling',CCR_SubjectCode__c='C101', recordtypeid = marketConfigrecordtypeId, CCR_Country__c ='KR', CCR_CoveredInWarranty__c =true, CCR_CodeToBeEscalated__c = true, CCR_MaterialGroupDescription__c ='Holder /S',CCR_Model__c='A1403', CCR_L0code__c='C101');
            configList.add(qureConfig);
            CCR_QureConfiguration__c marketQureConfig = new CCR_QureConfiguration__c(CCR_EligibleForReplacement__c = 14, recordtypeid = marketRplacementrecordtypeId, CCR_MaxNumberOfReplacementsPerDevice__c =1, CCR_Country__c ='KR',CCR_Model__c='A1403');
            configList.add(marketQureConfig);
            CCR_QureConfiguration__c qureConfigTwo = new CCR_QureConfiguration__c(recordtypeid = subsRplacementrecordtypeId, CCR_Country__c ='KR', CCR_MaxNumberOfReplacementsPerDevice__c = 1);
            configList.add(qureConfigTwo);
            CCR_QureConfiguration__c qureConfigThree = new CCR_QureConfiguration__c(CCR_DiagnosticResult__c = 'HC3', CCR_DiagnosticDescription__c='Paint Peeling',CCR_SubjectCode__c='C101', recordtypeid = marketConfigrecordtypeId, CCR_Country__c ='KR', CCR_CoveredInWarranty__c =false, CCR_CodeToBeEscalated__c = false, CCR_MaterialGroupDescription__c ='Holder /S',CCR_Model__c='A1403', CCR_L0code__c='C101');
            configList.add(qureConfigThree);
            insert configList;
            CCR_QureHistory__c qureHis = new CCR_QureHistory__c(CCR_Device__c = ast.Id, CCR_QureChannel__c = 'E-Commerce', CCR_DiagnosticResult__c = 'HC1', CCR_DiagnosticDescription__c='Paint Peeling', CCR_Status__c= 'Active');
            insert qureHis;
            user u = CCR_TestUtility.createCallCntAgentForCountry('Korea, Republic of');
            ast.OwnerId = u.id;
            update ast;
            ast1.OwnerId = u.id;
            update ast1;
            CCR_CarePlusConfiguration__c cpc = new CCR_CarePlusConfiguration__c();
            cpc.Name = 'testCPC';
            cpc.CCR_AccidentalDamageLimit__c = 1;
            cpc.CCR_CarePlusActivated__c = true;
            cpc.CCR_Country__c = 'kr';
            cpc.CCR_L0codes__c = 'C101';
            insert cpc;
        }
    }

    /**
* Method Name:  positiveTest
* Arguments: NA
* Return: NA.
* Description: This method is to test positive scenariao.
**/

    static testMethod void positiveTest() {
        Asset astUpdate = [SELECT id, KDCE_OriginalWarrantyDate__c FROM asset LIMIT 1];
        astUpdate.KDCE_OriginalWarrantyDate__c = system.today().addDays(100);
        update astUpdate;
        user userAgent =[SELECT id, name from user WHERE CCR_UserType__c = 'Call Center Agent' ORDER BY CreatedDate DESC LIMIT 1];
        System.runAs(userAgent) {
            Account acc = new Account(Name='testAccount');
            insert acc;
            Contact ct = new Contact(LastName='testContact',Phone='01012341234');
            insert ct;
            Asset ast = new Asset(Name='testAsset',AccountId=acc.Id,ContactId=ct.Id);
            insert ast;
            Map<String, Map<String, String>> codentifyConsumerMap = new Map<String, Map<String, String>>();
            Map<String, String> map2 = new Map<String, String>();
            map2.put('SpiceId',ct.id);
            map2.put('ActionDate',String.valueOf(System.now()));
            codentifyConsumerMap.put(ast.CCR_CodentifyId__c, map2);
            test.startTest();

            CCR_QureHistory__c qureHisZero = new CCR_QureHistory__c(CCR_Device__c = ast.Id, CCR_Consumer__c = ct.id, CCR_QureChannel__c = 'E-Commerce', CCR_DiagnosticResult__c = 'HC3', CCR_DiagnosticDescription__c='Paint Peeling', CCR_Status__c= 'Active');
            insert qureHisZero;
            CCR_QureMsg qurmsgZero = new CCR_QureMsg();
            qurmsgZero.Codentify = ast.CCR_CodentifyId__c;
            qurmsgZero.QureHistryId = qureHisZero.Id;
            qurmsgZero.Market = 'KR';
            qurmsgZero.UserType = 'Consumer';
            CCR_QureUtility.deviceQureEligibility(qurmsgZero);

            CCR_QureHistory__c qureHis = new CCR_QureHistory__c(CCR_Device__c = ast.Id, CCR_Consumer__c = ct.id, CCR_QureChannel__c = 'Call Center', CCR_DiagnosticResult__c = 'HC1', CCR_DiagnosticDescription__c='Paint Peeling', CCR_Status__c= 'Active');
            insert qureHis;
            CCR_QureMsg qurmsg = new CCR_QureMsg();
            qurmsg.Codentify = ast.CCR_CodentifyId__c;
            qurmsg.QureHistryId = qureHis.Id;
            qurmsg.Market = 'KR';
            Asset astUpdateTemp = [SELECT id, KDCE_OriginalWarrantyDate__c FROM asset WHERE Id =: ast.Id];
            astUpdateTemp.KDCE_OriginalWarrantyDate__c = system.today().addDays(100);
            update astUpdateTemp;
            CCR_QureUtility.deviceQureEligibility(qurmsg);
            String quremes = JSON.serialize(qurmsg);
            CCR_QureHistory__c qureHisOne = new CCR_QureHistory__c(CCR_Device__c = ast.Id, CCR_Consumer__c = ct.id, CCR_QureChannel__c = 'Call Center', CCR_DiagnosticResult__c = 'HC3', CCR_DiagnosticDescription__c='Paint Peeling', CCR_Status__c= 'Active');
            insert qureHisOne;
            CCR_QureMsg qurmsgOne = new CCR_QureMsg();
            qurmsgOne.Codentify = ast.CCR_CodentifyId__c;
            qurmsgOne.QureHistryId = qureHisOne.Id;
            qurmsgOne.Market = 'KR';
            CCR_QureUtility.deviceQureEligibility(qurmsgOne);
            system.assert(quremes != null);
            CCR_QureUtility.prepareOverrideData(quremes,'Case', 'Status');
            CCR_QureUtility.deviceQureOverRide(quremes, false, null);
            CCR_QureUtility.getCaseSubtype('Pocket');
            CCR_QureUtility.getAssetDetails(ast.CCR_CodentifyId__c);
            CCR_QureUtility.updateUserLanguage('ko');
            CCR_QureUtility.deviceQureOverRide(quremes, true, 'Unsatisfied customer');
            test.stopTest();
        }
    }

    /**
* Method Name:  positiveTestTwo
* Arguments: NA
* Return: NA.
* Description: This method is to test positive scenariao.
**/
    static testMethod void positiveTestTwo() {
        user u =[SELECT id, name from user WHERE CCR_UserType__c = 'Call Center Agent' ORDER BY CreatedDate DESC LIMIT 1];
        System.runAs(u) {
            Account acc = new Account(Name='testAccount');
            insert acc;
            Contact ct = new Contact(LastName='testContact',Phone='01012341234');
            insert ct;
            Asset ast = new Asset(Name='testAsset',AccountId=acc.Id,ContactId=ct.Id);
            insert ast;
            CCR_QureHistory__c qureHis = new CCR_QureHistory__c(CCR_Device__c = ast.Id, CCR_QureChannel__c = 'E-Commerce', CCR_DiagnosticResult__c = 'HC1', CCR_DiagnosticDescription__c='Paint Peeling', CCR_Status__c= 'Active');
            insert qureHis;
            qureHis.CCR_Consumer__c = ct.id;
            update qureHis;
            Map<String, Map<String, String>> codentifyConsumerMap = new Map<String, Map<String, String>>();
            Map<String, String> map2 = new Map<String, String>();
            map2.put('SpiceId',ct.id);
            map2.put('ActionDate',String.valueOf(System.now()));
            codentifyConsumerMap.put(ast.CCR_CodentifyId__c, map2);
            test.startTest();
            CCR_QureMsg qurmsg = new CCR_QureMsg();
            qurmsg.Codentify = ast.CCR_CodentifyId__c;
            qurmsg.QureHistryId = qureHis.Id;
            qurmsg.Market = 'KR';
            CCR_QureUtility.deviceQureEligibility(qurmsg);
            System.assert(qurmsg != null);
            test.stopTest();
        }
    }

    /**
* Method Name:  escaltedCaseTest
* Arguments: NA
* Return: NA.
* Description: This method is to test Escalated to CSC.
**/

    static testMethod void escaltedCaseTest() {
        user u =[SELECT id, name from user WHERE CCR_UserType__c = 'Call Center Agent' ORDER BY CreatedDate DESC LIMIT 1];
        CCR_QureConfiguration__c qureconfig = [SELECT ID, CCR_CodeToBeEscalated__c from CCR_QureConfiguration__c WHERE CCR_DiagnosticResult__c ='HC1' ];
        qureconfig.CCR_CodeToBeEscalated__c = true;
        update qureconfig;
        System.runAs(u) {
            Account acc = new Account(Name='testAccount');
            insert acc;
            Contact ct = new Contact(LastName='testContact',Phone='01012341234');
            insert ct;
            Asset ast = new Asset(Name='testAsset',AccountId=acc.Id,ContactId=ct.Id);
            insert ast;
            ast.KDCE_OriginalWarrantyDate__c = null;
            update ast;
            list<contact> con = CCR_TestUtility.createContacts(1);
            CCR_QureHistory__c qureHis = new CCR_QureHistory__c(CCR_Device__c = ast.Id, CCR_QureChannel__c = 'E-Commerce', CCR_DiagnosticResult__c = 'HC1', CCR_DiagnosticDescription__c='Paint Peeling', CCR_Status__c= 'Active');
            insert qureHis;
            system.assert(qureHis != null);
            qureHis.CCR_Consumer__c = con[0].id;
            update qureHis;
            test.startTest();
            CCR_QureMsg qurmsg = new CCR_QureMsg();
            qurmsg.Codentify = ast.CCR_CodentifyId__c;
            qurmsg.QureHistryId = qureHis.Id;
            qurmsg.Market = 'KR';
            CCR_QureUtility.deviceQureEligibility(qurmsg);
            test.stopTest();
        }
    }


    /**
* Method Name:  codeNotCoveredTest
* Arguments: NA
* Return: NA.
* Description: This method is to test Code Not covered in Qure.
**/

    static testMethod void codeNotCoveredTest() {
        user u =[SELECT id, name from user WHERE CCR_UserType__c = 'Call Center Agent' ORDER BY CreatedDate DESC LIMIT 1];
        CCR_QureConfiguration__c qureconfig = [SELECT ID, CCR_CoveredInWarranty__c from CCR_QureConfiguration__c WHERE CCR_DiagnosticResult__c ='HC1' ];
        qureconfig.CCR_CoveredInWarranty__c = false;
        update qureconfig;
        System.runAs(u) {
            Account ass = new Account(Name='testAccount');
            insert ass;
            Contact ct = new Contact(LastName='testContact',Phone='01012331234');
            Asset ast = new Asset(Name='testAsset', ContactId=ct.Id, AccountId=ass.Id);
            insert ast;
            CCR_QureHistory__c qureHis = new CCR_QureHistory__c(CCR_Device__c = ast.Id, CCR_QureChannel__c = 'E-Commerce', CCR_DiagnosticResult__c = 'HC1', CCR_DiagnosticDescription__c='Paint Peeling', CCR_Status__c= 'Active');
            insert qureHis;
            system.assert(qureHis != null);
            qureHis.CCR_Consumer__c = ct.id;
            update qureHis;
            Map<String, Map<String, String>> codentifyConsumerMap = new Map<String, Map<String, String>>();
            Map<String, String> map2 = new Map<String, String>();
            map2.put('SpiceId',ct.id);
            map2.put('ActionDate',String.valueOf(System.now()));
            codentifyConsumerMap.put(ast.CCR_CodentifyId__c, map2);
            test.startTest();
            CCR_QureMsg qurmsg = new CCR_QureMsg();
            qurmsg.Codentify = ast.CCR_CodentifyId__c;
            qurmsg.QureHistryId = qureHis.Id;
            qurmsg.Market = 'KR';
            CCR_QureUtility.deviceQureEligibility(qurmsg);
            test.stopTest();
        }
    }

    /**
* Method Name:  outoffWarrantyTest
* Arguments: NA
* Return: NA.
* Description: This method is to test out off warranty in Qure.
**/

    static testMethod void outoffWarrantyTest() {
        user u =[SELECT id, name from user WHERE CCR_UserType__c = 'Call Center Agent' ORDER BY CreatedDate DESC LIMIT 1];
        CCR_QureConfiguration__c qureconfig = [SELECT ID, CCR_CoveredInWarranty__c from CCR_QureConfiguration__c WHERE CCR_DiagnosticResult__c ='HC1' ];
        qureconfig.CCR_CoveredInWarranty__c = true;
        update qureconfig;
        System.runAs(u) {
            list<contact> con = CCR_TestUtility.createContacts(1);
            Account ass = new Account(Name='testAccount');
            insert ass;
            Contact ct = new Contact(LastName='testContact',Phone='01012331234');
            Asset ast = new Asset(Name='testAsset', ContactId=ct.Id, AccountId=ass.Id);
            insert ast;
            ast.KDCE_OriginalWarrantyDate__c = date.today().addDays(-10);
            ast.ContactId =con[0].Id;
            update ast;

            CCR_QureHistory__c qureHis = new CCR_QureHistory__c(CCR_Device__c = ast.Id, CCR_QureChannel__c = 'E-Commerce', CCR_DiagnosticResult__c = 'HC1', CCR_DiagnosticDescription__c='Paint Peeling', CCR_Status__c= 'Active');
            insert qureHis;
            qureHis.CCR_Consumer__c = con[0].id;
            update qureHis;
            CCR_QureMsg qurmsg = new CCR_QureMsg();
            qurmsg.Codentify = ast.CCR_CodentifyId__c;
            qurmsg.QureHistryId = qureHis.Id;
            qurmsg.Market = 'KR';
            test.startTest();
            CCR_QureUtility.deviceQureEligibility(qurmsg);
            test.stopTest();
        }
    }

    /**
* Method Name:  overRIdeTest
* Arguments: NA
* Return: NA.
* Description: This method is to test over RIde in Qure.
**/

    static testMethod void overRIdeTest() {
        user u =[SELECT id, name from user WHERE CCR_UserType__c = 'Call Center Agent' ORDER BY CreatedDate DESC LIMIT 1];
        CCR_QureConfiguration__c qureconfig = [SELECT ID, CCR_CoveredInWarranty__c from CCR_QureConfiguration__c WHERE CCR_DiagnosticResult__c ='HC1' ];
        qureconfig.CCR_CoveredInWarranty__c = false;
        update qureconfig;
        System.runAs(u) {
            Account ass = new Account(Name='testAccount');
            insert ass;
            Contact ct = new Contact(LastName='testContact',Phone='01012331234');
            Asset ast = new Asset(Name='testAsset', ContactId=ct.Id, AccountId=ass.Id);
            insert ast;
            CCR_QureHistory__c qureHis = new CCR_QureHistory__c(CCR_Device__c = ast.Id, CCR_QureChannel__c = 'E-Commerce', CCR_DiagnosticResult__c = 'HC1', CCR_DiagnosticDescription__c='Paint Peeling', CCR_Status__c= 'Active');
            insert qureHis;
            system.assert(qureHis != null);
            qureHis.CCR_Consumer__c = ct.id;
            update qureHis;
            Map<String, Map<String, String>> codentifyConsumerMap = new Map<String, Map<String, String>>();
            Map<String, String> map2 = new Map<String, String>();
            map2.put('SpiceId',ct.id);
            map2.put('ActionDate',String.valueOf(System.now()));
            codentifyConsumerMap.put(ast.CCR_CodentifyId__c, map2);
            test.startTest();
            CCR_QureMsg qurmsg = new CCR_QureMsg();
            qurmsg.Codentify = ast.CCR_CodentifyId__c;
            qurmsg.QureHistryId = qureHis.Id;
            qurmsg.Market = 'KR';
            CCR_QureUtility.deviceQureEligibility(qurmsg);
            test.stopTest();
        }
    }

    /**
    * Method Name:  defectiveDeviceTest
    * Description: This method is to test over RIde in Qure.
    **/
    static testMethod void defectiveDeviceTest() {
        user admuserKR = CCR_TestUtility.createAdminUserforCountry('Korea, Republic of','KR');
        System.runAs(admuserKR) {
            Asset ast = [SELECT id, Status, CCR_CodentifyId__c, SerialNumber, ContactId, CCR_DefectiveDevice__c, KDCE_OriginalWarrantyDate__c FROM asset LIMIT 1];
            ast.CCR_DefectiveDevice__c = true;
            ast.KDCE_OriginalWarrantyDate__c = system.today().addDays(100);
            update ast;
            String marketConfigrecordtypeId = SObjectType.CCR_QureConfiguration__c.getRecordTypeInfosByDeveloperName().get('CCR_MarketConfiguration').getRecordTypeId();
            CCR_QureConfiguration__c marketQureConfig = new CCR_QureConfiguration__c(CCR_EligibleForReplacement__c = 14, recordtypeid = marketConfigrecordtypeId, CCR_MaxNumberOfReplacementsPerDevice__c =1, CCR_Country__c ='KR',CCR_Model__c='A1403', CCR_SubjectCode__c = 'C002', CCR_DiagnosticResult__c = 'HC2');
            insert marketQureConfig;
            CCR_QureHistory__c qureHis = new CCR_QureHistory__c(CCR_Device__c = ast.Id, CCR_QureChannel__c = 'E-Commerce', CCR_DiagnosticResult__c = 'HC2', CCR_DiagnosticDescription__c='Broken Heating Blade', CCR_Status__c= 'Active');
            insert qureHis;
        }
        user testUser =[SELECT id, name from user WHERE CCR_UserType__c = 'Call Center Agent' ORDER BY CreatedDate DESC LIMIT 1];
        System.runAs(testUser) {
            Asset ast = [SELECT id, Status, CCR_CodentifyId__c, SerialNumber, Contactid FROM asset LIMIT 1];
            list<contact> con = CCR_TestUtility.createContacts(1);
            CCR_QureHistory__c qureHis = [SELECT ID, CCR_Consumer__c FROM CCR_QureHistory__c where  CCR_QureChannel__c = 'E-Commerce' AND CCR_DiagnosticResult__c = 'HC2' LIMIT 1];
            system.assert(qureHis != null);
            qureHis.CCR_Consumer__c = con[0].id;
            update qureHis;
            CCR_QureMsg qurmsg = new CCR_QureMsg();
            qurmsg.Codentify = ast.CCR_CodentifyId__c;
            qurmsg.QureHistryId = qureHis.Id;
            qurmsg.Market = 'KR';
            test.startTest();
//            CCR_QureUtility.deviceQureEligibility(qurmsg);
            test.stopTest();
        }
    }

    static testMethod void test001(){
        Account ass = new Account(Name='testAccount');
        insert ass;
        Contact ct = new Contact(LastName='testContact',Phone='01012331234');
        Asset ast = new Asset(Name='testAsset', ContactId=ct.Id, AccountId=ass.Id);
        insert ast;
        CCR_QureHistory__c qureHis = new CCR_QureHistory__c(CCR_Device__c = ast.Id, CCR_QureChannel__c = 'E-Commerce', CCR_DiagnosticResult__c = 'HC2', CCR_DiagnosticDescription__c='Broken Heating Blade', CCR_Status__c= 'Active');
        insert qureHis;
        Case c = new Case();
        insert c;
        List<Asset> astList = new List<Asset>();
        astList.add(ast);
        test.startTest();
        CCR_QureUtility.updateQureHistory(qureHis, true,true,true,c.Id,true,'broken','C002','Not Eligible',true,system.now(),true);
        CCR_QureUtility.updateQureDeviceReplacementChannel(ast,'LSP');
        CCR_QureUtility.updateQureDeviceEligibleDays(ast);
        CCR_QureUtility.getReplacementDate(astList);
        CCR_QureUtility.runTest();
        test.stopTest();
    }
}