force-app/main/default/objects/Asset/fields/CCR_CodentifyId__c.field-meta.xml
<CustomField>
    <fullName>CCR_CodentifyId__c</fullName>
    <description>Unique identifier of the device to be used as external key.</description>
    <externalId>true</externalId>
    <label>Codentify ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/KDCE_Order__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Order</description>
    <label>Order</label>
    <nameField>
        <displayFormat>KO{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderReason__c.field-meta.xml
<CustomField>
    <fullName>OrderReason__c</fullName>
    <description>주문 사유
forward: 주문
return: 반품
collect: 반납
rental forward: 렌탈 후 구매주문
rental return: 렌탈 후 구매주문 반품</description>
    <inlineHelpText>주문 사유</inlineHelpText>
    <label>Order Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>forward</fullName>
            </value>
            <value>
                <fullName>return</fullName>
            </value>
            <value>
                <fullName>collect</fullName>
                <label>Collect</label>
            </value>
            <value>
                <fullName>rental forward</fullName>
            </value>
            <value>
                <fullName>rental return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>[KDCE] 주문 상태
Mapping Column : order_status</description>
    <inlineHelpText>주문 상태</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>processing</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>ready_for_delivery</fullName>
            </value>
            <value>
                <fullName>picking</fullName>
            </value>
            <value>
                <fullName>delivery_collection</fullName>
            </value>
            <value>
                <fullName>complete_delivery</fullName>
            </value>
            <value>
                <fullName>closed</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>cancel</fullName>
            </value>
            <value>
                <fullName>cancel_order</fullName>
            </value>
            <value>
                <fullName>return_received</fullName>
            </value>
            <value>
                <fullName>reject</fullName>
            </value>
            <value>
                <fullName>authorized</fullName>
            </value>
            <value>
                <fullName>approved</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>renting</fullName>
            </value>
            <value>
                <fullName>complete</fullName>
                <label>Complete</label>
            </value>
            <value>
                <fullName>paid</fullName>
            </value>
            <value>
                <fullName>received</fullName>
            </value>
            <value>
                <fullName>processed_closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <description>[KDCE] 주문타입
ZTA(일반주문)
ZTI(보상판매)
ZRN(렌탈 중고)
ZRNNEW(렌탈 신규)
ZRA(QURE)</description>
    <inlineHelpText>주문타입</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZTA</fullName>
            </value>
            <value>
                <fullName>ZTI</fullName>
            </value>
            <value>
                <fullName>ZRN</fullName>
            </value>
            <value>
                <fullName>ZRNNEW</fullName>
            </value>
            <value>
                <fullName>ZRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OriginOrder__c.field-meta.xml
<CustomField>
    <fullName>OriginOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original Order (반품/취소의 경우)</description>
    <inlineHelpText>Original Order (반품/취소의 경우)</inlineHelpText>
    <label>Original Order</label>
    <referenceTo>KDCE_Order__c</referenceTo>
    <relationshipLabel>Sub Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_OrderLineItem__c/KDCE_OrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_OrderLineItem__c/fields/Codentify__c.field-meta.xml
<CustomField>
    <fullName>Codentify__c</fullName>
    <description>[KDCE] 시리얼 (Parent Codentify Id OR Codentify Id)
Mapping Column : codentify</description>
    <inlineHelpText>시리얼 (Parent Codentify Id OR Codentify Id)</inlineHelpText>
    <label>Codentify</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_OrderLineItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>KDCE_Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KDCE_OrderLineItem__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>[KDCE] 주문 상태
Mapping Column : order_status</description>
    <inlineHelpText>주문 상태</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>processing</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>ready_for_delivery</fullName>
            </value>
            <value>
                <fullName>picking</fullName>
            </value>
            <value>
                <fullName>delivery_collection</fullName>
            </value>
            <value>
                <fullName>complete_delivery</fullName>
            </value>
            <value>
                <fullName>closed</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>cancel</fullName>
            </value>
            <value>
                <fullName>cancel_order</fullName>
            </value>
            <value>
                <fullName>return_received</fullName>
            </value>
            <value>
                <fullName>reject</fullName>
            </value>
            <value>
                <fullName>authorized</fullName>
            </value>
            <value>
                <fullName>approved</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>renting</fullName>
            </value>
            <value>
                <fullName>complete</fullName>
                <label>Complete</label>
            </value>
            <value>
                <fullName>paid</fullName>
            </value>
            <value>
                <fullName>received</fullName>
            </value>
            <value>
                <fullName>processed_closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_OrderLineItem__c/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <description>[KDCE] 주문타입
ZTA(일반주문)
ZTI(보상판매)
ZRN(렌탈 중고)
ZRNNEW(렌탈 신규)
ZRA(QURE)</description>
    <inlineHelpText>주문타입</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZTA</fullName>
            </value>
            <value>
                <fullName>ZTI</fullName>
            </value>
            <value>
                <fullName>ZRN</fullName>
            </value>
            <value>
                <fullName>ZRNNEW</fullName>
            </value>
            <value>
                <fullName>ZRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_OrderLineItem_tr_ts.cls
/****************************************************************************************
  * @filename      : KDCE_OrderLineItem_tr_ts
  * @projectname   : PMK qa - KR
  * @author        : Park HE
  * @date          : 2021-06-18
  * @group         :
  * @group-content :
  * @description   :
  * @tester        :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                    author          description
  * ===============================================================
    0.1     2021-06-18             Park HE         Create
****************************************************************************************/

@IsTest
private class KDCE_OrderLineItem_tr_ts {


    static KDCE_Order__c tempOrder;
    static  KDCE_OrderLineItem__c tempOli ;
    static  Asset tempAsset ;
    static  KDCE_Order__c collectOrder ;
    static  KDCE_OrderLineItem__c collectOli ;
    static  Asset collectAsset ;
    static Id orderId;
    static private void createOrderSet(String orderStatus, String orderReason, String orderType){
        if(orderReason != KDCE_GlobalValue.ORDER_REASON_COLLECT) {
            System.debug('if 안쪽');
            if(tempOrder == null) tempOrder = KDCE_TestBizUtil.getOrder();
            if(tempOli == null) tempOli = KDCE_TestBizUtil.getOrderLineItem(tempOrder.Id);
            //tempOli = KDCE_TestBizUtil.getOrder();

            String tempCodentify = String.valueOf(Integer.valueOf((Math.random() * 1000000)));
            tempOli.OrderStatus__c = orderStatus;
            tempOli.OrderReason__c = orderReason;
            tempOli.OrderType__c = orderType;
            orderId = tempOrder.Id;

            // Asset 생성
            tempAsset = KDCE_TestUtil.assetHolder.clone(false);
            tempAsset.CCR_CodentifyId__c = tempCodentify;
            tempAsset.SerialNumber = tempCodentify;
            tempAsset.ContactId = KDCE_TestUtil.contactMember.Id;


            tempOli.Codentify__c = tempCodentify;
            insert tempAsset;

            tempOrder.Contact__c =  KDCE_TestUtil.contactMember.Id;
            List<SObject> sObjects = new List<SObject>{tempOli, tempOrder};
            update sObjects;

            System.debug('tempAsset :: ' + tempAsset);
            System.debug('tempOli :: ' + tempOli);

        }
        if(orderReason == KDCE_GlobalValue.ORDER_REASON_COLLECT) {
            if(collectOrder == null)    collectOrder = KDCE_TestBizUtil.getOrder();
            if(collectOli == null)      collectOli = KDCE_TestBizUtil.getOrderLineItem(collectOrder.Id);
            //tempOli = KDCE_TestBizUtil.getOrder();


            String tempCodentify = String.valueOf(Integer.valueOf((Math.random() * 1000000)));
            collectOli.OrderStatus__c = orderStatus;
            collectOli.OrderReason__c = orderReason;
            collectOli.OrderType__c = orderType;
            collectOrder.OriginOrder__c = orderId;
            //orderId = collectOrder.Id;

            // Asset 생성
            collectAsset = KDCE_TestUtil.assetHolder.clone(false);
            collectAsset.CCR_CodentifyId__c = tempCodentify;
            collectAsset.ContactId = KDCE_TestUtil.contactMember.Id;

            collectOli.Codentify__c = tempCodentify;
            insert collectAsset;

            List<SObject> sObjects = new List<SObject>{collectOli, collectOrder};
            update sObjects;

            System.debug('collectOli :: ' + collectOli);
            System.debug('tempAsset :: ' + collectAsset);
        }
    }

    static private void updateOrderSet(String orderStatus, String orderReason, String orderType) {
        System.debug('updateOrderSet');
        if(tempOli == null)     createOrderSet('process','forward', orderType);
        if(collectOli == null)  createOrderSet('process','collect', orderType);

        System.debug(tempOli);
        System.debug(collectOli);

        if(orderReason == 'forward') {
            tempOli.OrderStatus__c = orderStatus;
            System.debug(tempOli.Order__c);
        }
        else if(orderReason == 'collect') {
            collectOli.OrderStatus__c = orderStatus;
        }
        collectOrder.OriginOrder__c = orderId;

        List<SObject> sObjects = new List<SObject>{tempOli, collectOli, collectOrder};
        System.debug('tempOrder : ' + tempOrder);
        System.debug('collectOrder : ' + collectOrder);
        System.debug('sObjects :: ' + sObjects);
        update sObjects;

    }
    @IsTest
    static void testWhenPickingZTA1() {
        Test.startTest();
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_COMPLETE_DELIVERY, KDCE_GlobalValue.ORDER_REASON_FORWARD, KDCE_GlobalValue.ORDER_TYPE_NORMAL);
        Test.stopTest();
    }
    @IsTest
    static void testWhenPickingZTA2() {
        Test.startTest();
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_COMPLETE_DELIVERY, KDCE_GlobalValue.ORDER_REASON_FORWARD, KDCE_GlobalValue.ORDER_TYPE_NORMAL);
        Test.stopTest();
    }
   /* @IsTest
    static void testWhenPickingZRN1() {
        Test.startTest();
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_COMPLETE, KDCE_GlobalValue.ORDER_REASON_FORWARD, KDCE_GlobalValue.ORDER_TYPE_RENTAL);
        String changeTest = KDCE_TestUtil.assetHolder.CCR_CodentifyId__c;
        tempOli.OrderType__c =KDCE_GlobalValue.ORDER_TYPE_RENTAL;
        tempOli.Codentify__c = changeTest;
        update tempOli;

        Test.stopTest();
    }*/

    @IsTest
    static void testWhenPickingZRNNEW1() {
        Test.startTest();
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_COMPLETE, KDCE_GlobalValue.ORDER_REASON_FORWARD, KDCE_GlobalValue.ORDER_TYPE_RENTALNEW);

        Test.stopTest();
    }

    @IsTest
    static void testWhenPickingRTLBUY() {
        Test.startTest();
        System.debug('tempOli :: ' + tempOli);
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_COMPLETE, KDCE_GlobalValue.ORDER_REASON_RTLFORWARD, KDCE_GlobalValue.ORDER_TYPE_RTLBUY);
        System.debug('tempOli :: ' + tempOli);
        Test.stopTest();
    }

    @IsTest
    static void testWhenPickingZRNPaid() {
        Test.startTest();
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_PAID, KDCE_GlobalValue.ORDER_REASON_FORWARD, KDCE_GlobalValue.ORDER_TYPE_RENTAL);
        Test.stopTest();
    }

    @IsTest
    static void testWhenPickingTradeIn1() {
        tempOli = null;
        Test.startTest();
        updateOrderSet(KDCE_GlobalValue.ORDER_STATUS_COMPLETE, KDCE_GlobalValue.ORDER_REASON_FORWARD, KDCE_GlobalValue.ORDER_TYPE_TRADEIN);


        Test.stopTest();
    }

    @IsTest
    static void testWhenPickingTradeIn2() {
        tempOli = null;
        Test.startTest();
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_PENDING, KDCE_GlobalValue.ORDER_REASON_COLLECT, KDCE_GlobalValue.ORDER_TYPE_TRADEIN);
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_PROCESSED_CLOSED, KDCE_GlobalValue.ORDER_REASON_COLLECT, KDCE_GlobalValue.ORDER_TYPE_TRADEIN);
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_CLOSE, KDCE_GlobalValue.ORDER_REASON_COLLECT, KDCE_GlobalValue.ORDER_TYPE_TRADEIN);
        Test.stopTest();
    }

    @IsTest
    static void testWhenPickingQure() {
        tempOli = null;
        Test.startTest();
        updateOrderSet(KDCE_GlobalValue.ORDER_STATUS_COMPLETE, KDCE_GlobalValue.ORDER_REASON_FORWARD, KDCE_GlobalValue.ORDER_TYPE_QURE);


        Test.stopTest();
    }

    @IsTest
    static void testWhenPickingQure2() {
        tempOli = null;
        Test.startTest();
//        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_PENDING, KDCE_GlobalValue.ORDER_REASON_COLLECT, KDCE_GlobalValue.ORDER_TYPE_QURE);
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_PROCESSED_CLOSED, KDCE_GlobalValue.ORDER_REASON_COLLECT, KDCE_GlobalValue.ORDER_TYPE_QURE);
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_CLOSE, KDCE_GlobalValue.ORDER_REASON_COLLECT, KDCE_GlobalValue.ORDER_TYPE_QURE);
        Test.stopTest();
    }

    @IsTest
    static void testwhenRentalForwardComplete() {
        Test.startTest();
        tempOli = null;
        returnOLIValue(KDCE_GlobalValue.ORDER_STATUS_COMPLETE, KDCE_GlobalValue.ORDER_REASON_RTLFORWARD, KDCE_GlobalValue.ORDER_TYPE_RTLBUY);
        Test.stopTest();
    }



    @IsTest
    static void testWhenReturnReject() {
        tempOli = null;
        Test.startTest();
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_CLOSE, KDCE_GlobalValue.ORDER_REASON_COLLECT, KDCE_GlobalValue.ORDER_TYPE_QURE);

        Test.stopTest();
    }


    @IsTest
    static void testWhenReturnRefund1() {
        tempOli = null;
        Test.startTest();
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_PROCESSED_CLOSED, KDCE_GlobalValue.ORDER_REASON_RETURN, KDCE_GlobalValue.ORDER_TYPE_NORMAL);

        Test.stopTest();
    }
    static private void returnOLIValue(String status, String reason, String type){
        String tempCodentify = String.valueOf(Integer.valueOf((Math.random() * 1000000)));
        tempAsset = new Asset(
                CCR_CodentifyId__c = tempCodentify,
                AccountId = KDCE_TestUtil.account.Id,
                Name = tempCodentify);
        tempOrder=KDCE_TestBizUtil.order;
        tempOrder.Contact__c = KDCE_TestUtil.contactMember.Id;
        update tempOrder;

        KDCE_OrderLineItem__c tempItem = new KDCE_OrderLineItem__c(
                Order__c = tempOrder.Id,
                OrderStatus__c = status,
                OrderReason__c = reason,
                OrderType__c = type,
                Codentify__c = tempCodentify
        );

        List<SObject> sObjects = new List<SObject>{tempAsset, tempItem};
        insert sObjects;
    }
}