force-app/main/default/objects/Asset/fields/CCR_CarePlusDueDate__c.field-meta.xml
<CustomField>
    <fullName>CCR_CarePlusDueDate__c</fullName>
    <label>Care+ Due Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_CarePlusStatus__c.field-meta.xml
<CustomField>
    <fullName>CCR_CarePlusStatus__c</fullName>
    <label>Care+ Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_CodentifyId__c.field-meta.xml
<CustomField>
    <fullName>CCR_CodentifyId__c</fullName>
    <description>Unique identifier of the device to be used as external key.</description>
    <externalId>true</externalId>
    <label>Codentify ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_MaterialGroupDescription__c.field-meta.xml
<CustomField>
    <fullName>CCR_MaterialGroupDescription__c</fullName>
    <description>Group Material description</description>
    <formula>CCR_DeviceProductCode__r.CCR_GroupDescription__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Group Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_OriginalAsset__c.field-meta.xml
<CustomField>
    <fullName>CCR_OriginalAsset__c</fullName>
    <description>Codentify of the original asset (before replacement)</description>
    <label>Original Asset Codentify</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_OriginalBox__c.field-meta.xml
<CustomField>
    <fullName>CCR_OriginalBox__c</fullName>
    <description>Codentify of the original box (before replacement)</description>
    <externalId>true</externalId>
    <label>Original Box Codentify</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_Override__c.field-meta.xml
<CustomField>
    <fullName>CCR_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by: CCR
Description: To store information if eligibility result has been overwritten by the agent.</description>
    <label>Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_OverrideReason__c.field-meta.xml
<CustomField>
    <fullName>CCR_OverrideReason__c</fullName>
    <description>Used by: CCR
Description: To store information why eligibility result was overwritten by the agent,</description>
    <label>Override Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unsatisfied customer</fullName>
            </value>
            <value>
                <fullName>Warranty Expiration</fullName>
            </value>
            <value>
                <fullName>Product issue not covered by fault tree</fullName>
            </value>
            <value>
                <fullName>적절한 고장코드 없음</fullName>
            </value>
            <value>
                <fullName>강성클레임 예외승인</fullName>
            </value>
            <value>
                <fullName>보증기간 예외승인</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_ReplacedBy__c.field-meta.xml
<CustomField>
    <fullName>CCR_ReplacedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference of the replacement device to be populated by VF page or API only</description>
    <label>Replaced By</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Assets (Replaced by)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_ReplacementChannelNew__c.field-meta.xml
<CustomField>
    <fullName>CCR_ReplacementChannelNew__c</fullName>
    <description>Used By: CCR
Description: This value is updated depending on the type of user.</description>
    <label>Replacement Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Retail</fullName>
            </value>
            <value>
                <fullName>Indirect Retail</fullName>
            </value>
            <value>
                <fullName>Field Sales Force</fullName>
            </value>
            <value>
                <fullName>Service Point</fullName>
            </value>
            <value>
                <fullName>Pickup Point</fullName>
            </value>
            <value>
                <fullName>LSP</fullName>
            </value>
            <value>
                <fullName>LSP SHIFT-X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_ReplacementDate__c.field-meta.xml
<CustomField>
    <fullName>CCR_ReplacementDate__c</fullName>
    <description>Date/Time of replacement.</description>
    <label>Replacement Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_ReplacementReason__c.field-meta.xml
<CustomField>
    <fullName>CCR_ReplacementReason__c</fullName>
    <description>Reason of replacement</description>
    <label>Replacement Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_ReplacementSponsored_By__c.field-meta.xml
<CustomField>
    <fullName>CCR_ReplacementSponsored_By__c</fullName>
    <label>Replacement Sponsored By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Goodwill</fullName>
            </value>
            <value>
                <fullName>Care+</fullName>
                <label>IQOS CARE PLUS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_Replaces__c.field-meta.xml
<CustomField>
    <fullName>CCR_Replaces__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference of the replaced device to be populated by VF page or API only</description>
    <label>Replaces</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/KDCE_DeviceType__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DeviceType__c</fullName>
    <description>[KDCE] Device Type</description>
    <label>Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeviceType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/KDCE_fm_WarrantyDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_fm_WarrantyDate__c</fullName>
    <description>[KDCE] Warranty Date</description>
    <formula>IF(Not(ISNULL(KDCE_OriginalWarrantyDate__c)), KDCE_OriginalWarrantyDate__c,
IF(AND(ISNULL(KDCE_ShipmentDate__c), ISNULL(PurchaseDate)), ADDMONTHS( DATEVALUE(CCR_ParentProductionDateTime__c), 15),
IF(AND(NOT(ISNULL(KDCE_ShipmentDate__c)),NOT(ISNULL(PurchaseDate)), PurchaseDate &lt; KDCE_ShipmentDate__c) , ADDMONTHS(KDCE_ShipmentDate__c,12),
IF(AND(NOT(ISNULL(KDCE_ShipmentDate__c)),NOT(ISNULL(PurchaseDate)), PurchaseDate &gt;= KDCE_ShipmentDate__c), ADDMONTHS(PurchaseDate,12),
IF(AND(NOT(ISNULL(KDCE_ShipmentDate__c)),ISNULL(PurchaseDate)), ADDMONTHS(KDCE_ShipmentDate__c,12),
IF(AND(NOT(ISNULL(PurchaseDate)),ISNULL(KDCE_ShipmentDate__c)), ADDMONTHS(PurchaseDate,12), ADDMONTHS( DATEVALUE(CCR_ParentProductionDateTime__c), 15)
)
)
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>보증일. 구매일이 있으면 구매일+12개월, 구매일이 없으면 생산일+15개월</inlineHelpText>
    <label>Warranty Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/KDCE_IsCarePlusHistory__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsCarePlusHistory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCarePlusHistory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/KDCE_OriginalWarrantyDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_OriginalWarrantyDate__c</fullName>
    <label>Original Warranty Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/KDCE_ReplacementCount__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ReplacementCount__c</fullName>
    <label>Replacement Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/KDCE_ReplacementSource__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ReplacementSource__c</fullName>
    <description>[KDCE] Replacement Source</description>
    <label>Replacement Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>QURE</fullName>
            </value>
            <value>
                <fullName>KIT TO KIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CCR_DiagnosticDescription__c.field-meta.xml
<CustomField>
    <fullName>CCR_DiagnosticDescription__c</fullName>
    <description>Used By: CCR
Description: This field stores the diagnostic descriptive information and is populated during Qure process</description>
    <label>Diagnostic Description</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_DiagnosticDescription</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/KDCE_OtherReason__c.field-meta.xml
<CustomField>
    <fullName>KDCE_OtherReason__c</fullName>
    <label>KDCE_OtherReason</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/CCR_QureHistory__c.object-meta.xml
<CustomObject>
    <description>Used by: CCR
Description: It&apos;s to store information collected during Qure process for that device.</description>
    <label>Qure History</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>QURE History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qure History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_Case__c.field-meta.xml
<CustomField>
    <fullName>CCR_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used by: CCR. 
Description: Lookup field to Case.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>QURE_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_Override__c.field-meta.xml
<CustomField>
    <fullName>CCR_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It&apos;s to store information if Qure process has been overwritten.</description>
    <label>Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_OverrideReason__c.field-meta.xml
<CustomField>
    <fullName>CCR_OverrideReason__c</fullName>
    <description>It&apos;s to store information about the reason of overwriting.</description>
    <label>Override Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unsatisfied customer</fullName>
            </value>
            <value>
                <fullName>Warranty Expiration</fullName>
            </value>
            <value>
                <fullName>Product issue not covered by fault tree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_QureReplacementChannel__c.field-meta.xml
<CustomField>
    <fullName>CCR_QureReplacementChannel__c</fullName>
    <description>It&apos;s to store Qure replacement channels.</description>
    <label>Qure Replacement Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_QureReplacementChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/CCR_ReplacementChannelSelectedBy__c.field-meta.xml
<CustomField>
    <fullName>CCR_ReplacementChannelSelectedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used By: CCR 
Description: Replacement Channel Selected user in QURE</description>
    <label>Replacement Channel Selected By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Qure_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCR_QureHistory__c/fields/KDCE_OtherReason__c.field-meta.xml
<CustomField>
    <fullName>KDCE_OtherReason__c</fullName>
    <label>KDCE_OtherReason</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_MG_SFDC_Dummy__c/IF_MG_SFDC_Dummy__c.object-meta.xml
<CustomObject>
    <label>IF_MG_SFDC_Dummy</label>
    <nameField>
        <displayFormat>MG_SFDC-{0000000000}</displayFormat>
        <label>IF_MG_SFDC_Dummy 이름</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IF_MG_SFDC_Dummy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_MG_SFDC_Dummy__c/fields/Channel_v2__c.field-meta.xml
<CustomField>
    <fullName>Channel_v2__c</fullName>
    <label>Channel_v2</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_MG_SFDC_Dummy__c/fields/ErrorContent__c.field-meta.xml
<CustomField>
    <fullName>ErrorContent__c</fullName>
    <label>Error Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IF_MG_SFDC_Dummy__c/fields/IsProcess__c.field-meta.xml
<CustomField>
    <fullName>IsProcess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsProcess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IF_MG_SFDC_Dummy__c/fields/Parentcodentify__c.field-meta.xml
<CustomField>
    <fullName>Parentcodentify__c</fullName>
    <label>Parentcodentify</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_MG_SFDC_Dummy__c/fields/ReplacementDate__c.field-meta.xml
<CustomField>
    <fullName>ReplacementDate__c</fullName>
    <label>ReplacementDate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_MG_SFDC_Dummy__c/fields/requestId__c.field-meta.xml
<CustomField>
    <fullName>requestId__c</fullName>
    <label>requestId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_MG_SFDC_Dummy__c/fields/ToReplaceCodentify__c.field-meta.xml
<CustomField>
    <fullName>ToReplaceCodentify__c</fullName>
    <label>ToReplaceCodentify</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IF_MG_SFDC_Dummy_tr.cls
/****************************************************************************************
  * @filename      : IF_MG_SFDC_Dummy_tr
  * @projectname   : PMK qa - KR
  * @author        : Park HE
  * @date          : 2021-05-20
  * @group         :
  * @group-content :
  * @description   : Qure 더미
  * @tester        :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                    author          description
  * ===============================================================
    0.1     2021-05-20             Park HE         Create
****************************************************************************************/
public with sharing class IF_MG_SFDC_Dummy_tr extends TriggerHandler{
    public override void beforeInsert() {
        connectAsset();
    }
     
    private void connectAsset(){

        List<IF_MG_SFDC_Dummy__c> dummyList = (List<IF_MG_SFDC_Dummy__c>)Trigger.new;
        Set<String> newAssetCodentify = new Set<String>();
        Set<String> oldAssetCodentify = new Set<String>();
        Set<String> caseNo = new Set<String>();
        for(IF_MG_SFDC_Dummy__c dummy : dummyList) {
            newAssetCodentify.add(dummy.Parentcodentify__c);
            oldAssetCodentify.add(dummy.ToReplaceCodentify__c);
            // requestId__c = CaseNumber로 예상(Case Id 아님)
            caseNo.add(dummy.requestId__c);
        }
        // IF_MG_SFDC_Dummy__c.requestId__c에 해당하는 Case Id 가져오기
        Map<String, Id> caseNoById = new Map<String, Id>();
        for(Case item : [
                SELECT Id, CaseNumber FROM Case WHERE CaseNumber IN :caseNo
        ]){
            caseNoById.put(item.CaseNumber, item.Id);
        }

        // CaseId를 키값으로 Qure History 저장
        Map<Id, CCR_QureHistory__c> qureHistoryByCaseIds = new Map<Id, CCR_QureHistory__c>();
        for(CCR_QureHistory__c qureHistory : [
                SELECT  Id, KDCE_OtherReason__c, CCR_ReplacementChannelSelectedBy__c, CCR_QureReplacementChannel__c,
                        CCR_Override__c, CCR_OverrideReason__c, CCR_Case__c, CCR_DiagnosticDescription__c
                FROM CCR_QureHistory__c
                WHERE CCR_Case__c IN : caseNoById.values()
        ]){
            qureHistoryByCaseIds.put(qureHistory.CCR_Case__c, qureHistory);
        }
        System.debug(qureHistoryByCaseIds.size());

        List<Asset> assetList = [
                SELECT Id, SerialNumber, CCR_CodentifyId__c,CCR_MaterialGroupDescription__c,
                        CCR_ReplacedBy__c,CCR_ReplacementChannelNew__c,CCR_ReplacementDate__c, Status, CCR_CarePlusDueDate__c, CCR_CarePlusStatus__c,
                        KDCE_DeviceType__c, ContactId, AccountId, CCR_Replaces__c, CCR_OriginalBox__c, CCR_OriginalAsset__c, KDCE_OriginalWarrantyDate__c,
                        KDCE_ReplacementCount__c, KDCE_ReplacementSource__c, KDCE_fm_WarrantyDate__c, CCR_ReplacementSponsored_By__c, CCR_Override__c,
                        CCR_OverrideReason__c, CCR_ReplacementReason__c, KDCE_IsCarePlusHistory__c
                FROM Asset
                WHERE SerialNumber IN : newAssetCodentify OR CCR_CodentifyId__c IN : oldAssetCodentify
        ];

        Map<String, Asset> tempOldAssetMap = new Map<String, Asset>();
        Map<String, Asset> tempNewAssetMap = new Map<String, Asset>();
        String contents;
        for(Asset asset : assetList){
            if(oldAssetCodentify.contains(asset.CCR_CodentifyId__c)){
                //contents = asset.CCR_MaterialGroupDescription__c.contains('holder')? 'holder' : 'charger' ;
                tempOldAssetMap.put(asset.CCR_CodentifyId__c, asset);
            }
            if(newAssetCodentify.contains(asset.SerialNumber)){
                tempNewAssetMap.put(asset.SerialNumber, asset);
            }
        }

        Asset tempOldAsset;
        Asset tempNewAsset;
        contents = null;
        Date criteria;
        Date originalDate;
        final String replacementReasonKr  = '히터 블레이드 파손';
        final String replacementReasonEn  = 'Broken Heating Blade';
        final String careplus             = 'Care+';
        String sponsoredBy ='';


        List<Asset> updateAssets = new List<Asset>();
        List<Asset> updateAssetsOld = new List<Asset>();
        List<Asset> updateAssetsNew = new List<Asset>();
        CCR_QureHistory__c tempQureHistory;


        for(IF_MG_SFDC_Dummy__c dummy : dummyList) {
            dummy.IsProcess__c = true;

            if(tempOldAssetMap.containsKey(dummy.ToReplaceCodentify__c) && tempNewAssetMap.containsKey(dummy.Parentcodentify__c)){
                tempNewAsset = tempNewAssetMap.get(dummy.Parentcodentify__c);
                tempOldAsset = tempOldAssetMap.get(dummy.ToReplaceCodentify__c);
            }else {
                dummy.IsError__c = true;
                dummy.ErrorContent__c  = '새 기기(Parentcodentify__c) 혹은 반납 기기(ToReplaceCodentify__c)의 Codentify가 Asset에 없습니다.';
                continue;
            }

            // 이전 기기 Asset 정보 업데이트
            tempOldAsset.CCR_ReplacedBy__c              = tempNewAsset.Id;
            tempOldAsset.CCR_ReplacementChannelNew__c   = dummy.Channel_v2__c; //KDCE_GlobalValue.ASSET_REPLACEMENT_CHANNEL_PICKUP;
            tempOldAsset.CCR_ReplacementDate__c         = dummy.ReplacementDate__c == null ? System.now() : Datetime.valueOf(dummy.ReplacementDate__c);
//            tempOldAsset.CCR_ReplacementDate__c = dummy.ReplacementDate__c == null ? System.now() :(DateTime)JSON.deserialize('"' + dummy.ReplacementDate__c + '"', DateTime.class);
//            tempOldAsset.CCR_ReplacementDate__c = dummy.ReplacementDate__c == null ? System.now() : Datetime.parse(dummy.ReplacementDate__c);
            tempOldAsset.Status                         = KDCE_GlobalValue.ASSET_STATUS_REPLACED;
            tempOldAsset.CCR_CarePlusDueDate__c         = tempOldAsset.CCR_ReplacementDate__c;

            // qure history 찾아서 매핑
            String caseId = caseNoById?.get(dummy.requestId__c);
            if(qureHistoryByCaseIds.containsKey(caseId) && caseId <> null){
                tempQureHistory = qureHistoryByCaseIds.get(caseId);
                //tempOldAsset.CCR_ReplacementDoneBy__c = tempQureHistory.CCR_ReplacementChannelSelectedBy__c;
                tempOldAsset.CCR_Override__c = tempQureHistory.CCR_Override__c;
                tempOldAsset.CCR_OverrideReason__c = tempQureHistory.CCR_OverrideReason__c;
                tempOldAsset.CCR_ReplacementReason__c = tempQureHistory.CCR_DiagnosticDescription__c;

                if(tempOldAsset.CCR_Override__c)
                    sponsoredBy = KDCE_GlobalValue.ASSET_REPLACE_SPONSOREDBY_GOODWILL;
                else if(tempOldAsset.CCR_ReplacementReason__c == replacementReasonEn)
                    sponsoredBy = KDCE_GlobalValue.ASSET_REPLACE_SPONSOREDBY_IQOSCARE;
                else
                    sponsoredBy = KDCE_GlobalValue.ASSET_REPLACE_SPONSOREDBY_WARRANTY;

                tempOldAsset.CCR_ReplacementSponsored_By__c = sponsoredBy;
            }

            // 4. 스폰서바이가 Iqos Care Plus 이거나 Override+히터블레이드 파손인 경우에는 Disenrolled 처리.
            if(tempOldAsset.CCR_ReplacementSponsored_By__c == careplus
                    || (tempOldAsset.CCR_Override__c && (tempOldAsset.CCR_ReplacementReason__c == replacementReasonKr || tempOldAsset.CCR_ReplacementReason__c == replacementReasonEn))
                ){
                tempOldAsset.CCR_CarePlusStatus__c = KDCE_GlobalValue.ASSET_CAREPLUSSTATUS_DISENROLLED;
                tempOldAsset.KDCE_IsCarePlusHistory__c = true;
            }

            // Override 교환이 아닌 경우에만 오늘 날짜로부터 3개월 추가하기
            if(!tempOldAsset.CCR_Override__c) {
                criteria = tempOldAsset.KDCE_fm_WarrantyDate__c <> null ? tempOldAsset.KDCE_fm_WarrantyDate__c.addMonths(-3) : null;
                if (criteria <> null)
                    originalDate = criteria <= System.today() ? System.today().addMonths(+3) : tempOldAsset.KDCE_fm_WarrantyDate__c;
            }
            else{ // Override 교환인 경우 이전 기기의 Original Warrnaty Date 그대로 사용하기
                originalDate = tempOldAsset.KDCE_fm_WarrantyDate__c;
            }

            // 새 기기 Asset 정보 업데이트
//            tempNewAsset.KDCE_DeviceType__c             = 'Standard'; // Device Type 삭제 예정
            tempNewAsset.Status                         = KDCE_GlobalValue.ASSET_STATUS_ACTIVE;
            tempNewAsset.ContactId                      = tempOldAsset.ContactId;
            tempNewAsset.AccountId                      = null;

            tempNewAsset.CCR_Replaces__c                = tempOldAsset.Id;
            tempNewAsset.CCR_OriginalAsset__c           = tempOldAsset.CCR_OriginalAsset__c;
            tempNewAsset.CCR_OriginalBox__c             = tempOldAsset.CCR_OriginalBox__c;
            tempNewAsset.KDCE_OriginalWarrantyDate__c   = tempOldAsset.KDCE_OriginalWarrantyDate__c <> null? tempOldAsset.KDCE_OriginalWarrantyDate__c : tempOldAsset.KDCE_fm_WarrantyDate__c;
            tempNewAsset.KDCE_ReplacementCount__c       = tempOldAsset.KDCE_ReplacementCount__c == null ? 1 : (tempOldAsset.KDCE_ReplacementCount__c + 1);
            tempNewAsset.KDCE_ReplacementSource__c      = 'Qure';
            tempNewAsset.KDCE_IsCarePlusHistory__c = tempOldAsset.KDCE_IsCarePlusHistory__c;

            updateAssets.add(tempOldAsset);
            updateAssets.add(tempNewAsset);
            updateAssetsOld.add(tempOldAsset);
            updateAssetsNew.add(tempNewAsset);
            System.debug('tempNewAsset : ' + tempNewAsset);
            System.debug('tempOldAsset : ' + tempOldAsset);
        }

//        if(!updateAssets.isEmpty()) update updateAssets;
        if(!updateAssetsOld.isEmpty() && !Test.isRunningTest()) {
            update updateAssetsOld;
            KDCE_Asset_tr.isAlreadyExecuted = false;
        }
        if(!updateAssetsNew.isEmpty() && !Test.isRunningTest()) {
            update updateAssetsNew;
            KDCE_Asset_tr.isAlreadyExecuted = false;
        }

    }

}