force-app/main/default/objects/Asset/fields/CCR_CodentifyId__c.field-meta.xml
<CustomField>
    <fullName>CCR_CodentifyId__c</fullName>
    <description>Unique identifier of the device to be used as external key.</description>
    <externalId>true</externalId>
    <label>Codentify ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_DeviceProductCode__c.field-meta.xml
<CustomField>
    <fullName>CCR_DeviceProductCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the related Material on the Material Object</description>
    <label>Device  Product Code</label>
    <referenceTo>CCR_Material__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_MaterialGroupDescription__c.field-meta.xml
<CustomField>
    <fullName>CCR_MaterialGroupDescription__c</fullName>
    <description>Group Material description</description>
    <formula>CCR_DeviceProductCode__r.CCR_GroupDescription__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Group Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_OriginalAsset__c.field-meta.xml
<CustomField>
    <fullName>CCR_OriginalAsset__c</fullName>
    <description>Codentify of the original asset (before replacement)</description>
    <label>Original Asset Codentify</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_ReplacedBy__c.field-meta.xml
<CustomField>
    <fullName>CCR_ReplacedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference of the replacement device to be populated by VF page or API only</description>
    <label>Replaced By</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Assets (Replaced by)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_Version__c.field-meta.xml
<CustomField>
    <fullName>CCR_Version__c</fullName>
    <description>Device Product Code Version</description>
    <formula>CCR_DeviceProductCode__r.CCR_Version__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Version</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/KDCE_DeviceLabelling__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DeviceLabelling__c</fullName>
    <description>[KDCE] Status가 변경됨에 따라 Device Label도 변경된다</description>
    <label>Device Labelling</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Online Trade-in Return</fullName>
            </value>
            <value>
                <fullName>Online Trade-in</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Rental Purchased</fullName>
            </value>
            <value>
                <fullName>To be disposed</fullName>
            </value>
            <value>
                <fullName>Return Fail</fullName>
            </value>
            <value>
                <fullName>Offline Trade-in</fullName>
            </value>
            <value>
                <fullName>Offline Trade-in Return</fullName>
            </value>
            <value>
                <fullName>E-commerce Rental</fullName>
            </value>
            <value>
                <fullName>Offline Rental</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Rental Returned</fullName>
                <isActive>false</isActive>
                <label>Rental Returned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/KDCE_RentalCount__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RentalCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>고객이 렌탈 할때마다 1번씩 증가함.</description>
    <label>Rental Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCR_Material__c/CCR_Material__c.object-meta.xml
<CustomObject>
    <description>Created to store information regarding the Device Master Data (catalogue).</description>
    <label>Material</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_Material__c/fields/CCR_Group__c.field-meta.xml
<CustomField>
    <fullName>CCR_Group__c</fullName>
    <description>Identification code of the group the device belongs to.</description>
    <label>Group</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR_Material__c/fields/CCR_Material__c.field-meta.xml
<CustomField>
    <fullName>CCR_Material__c</fullName>
    <description>Contains the same value than the name field. The field is used to set the Material/Name as external id</description>
    <externalId>true</externalId>
    <label>Material</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CCR_Material__c/fields/CCR_MaterialType__c.field-meta.xml
<CustomField>
    <fullName>CCR_MaterialType__c</fullName>
    <description>Use to filter by the type of records and allow in the case object to view, when searching on the look up of the field Material Group Description, only one record of each  Material Group description</description>
    <label>Type of Record</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>--None--</fullName>
                <default>true</default>
                <label>--None--</label>
            </value>
            <value>
                <fullName>Material Group Description</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_Material__c/fields/CCR_Version__c.field-meta.xml
<CustomField>
    <fullName>CCR_Version__c</fullName>
    <description>Device Version</description>
    <label>Version</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_Store__c.field-meta.xml
<CustomField>
    <fullName>KDCE_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[KDCE] 인입 채널</description>
    <label>Store</label>
    <referenceTo>KDCE_Store__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Anonymous</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/UsedDate__c.field-meta.xml
<CustomField>
    <fullName>UsedDate__c</fullName>
    <label>CVS Used Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/KDCE_OfflineProgram__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Offline Progrma (Trade-in, Upgrade, Rental, Replacement..)</description>
    <label>Offline Program</label>
    <nameField>
        <displayFormat>OP{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offline Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Offline Program</relationshipLabel>
    <relationshipName>OfflineProgram</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Rental Process</fullName>
            </value>
            <value>
                <fullName>Rental Cancel</fullName>
            </value>
            <value>
                <fullName>Rental Closed</fullName>
            </value>
            <value>
                <fullName>Rental Purchase</fullName>
                <isActive>false</isActive>
                <label>Rental Purchase</label>
            </value>
            <value>
                <fullName>Rental Refund</fullName>
                <isActive>false</isActive>
                <label>Rental Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/recordTypes/OfflineProgram_ZRN.recordType-meta.xml
<RecordType>
    <fullName>OfflineProgram_ZRN</fullName>
    <active>true</active>
    <description>[KDCE] Rental Record Type</description>
    <label>Rental</label>
</RecordType>

force-app/main/default/classes/KDCE_OfflineProgramController_ts.cls
/****************************************************************************************
  * @filename      : KDCE_OfflineProgramController_ts
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-05-26 오후 3:28
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-05-26 오후 3:28     i2max_Jihyun.Lee        Create
****************************************************************************************/

@IsTest
private class KDCE_OfflineProgramController_ts {

    static Contact contact = KDCE_TestUtil.contactMember;
    static KDCE_Coupon__c coupon = KDCE_TestBizUtil.coupon;
    static KDCE_Coupon__c selectCoupon = [SELECT Id, Status__c, Contact__c, UsedDate__c FROM KDCE_Coupon__c WHERE Id = :coupon.Id];
    static KDCE_Store__c store = KDCE_TestBizUtil.store;
    static Asset holder = KDCE_TestUtil.assetHolder;
    static Asset charger = KDCE_TestUtil.assetCharger;
    static String assetVersion = holder.CCR_Version__c == null ? '3.0' : holder.CCR_Version__c;


    static {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();
    }

    private static Map<String, List<Asset>> createRecordForTest() {
        Map<String, List<Asset>> assetMap = new Map<String, List<Asset>>();

        // Asset Select List
        Asset selectHolder = [SELECT Id, CCR_ReplacedBy__c, AccountId, ContactId, Status, CCR_OriginalAsset__c, CCR_CodentifyId__c, SerialNumber, CCR_DeviceProductCode__c, CCR_MaterialGroupDescription__c, CCR_Version__c, PurchaseDate, KDCE_DeviceLabelling__c, KDCE_RentalCount__c FROM Asset WHERE Id = :holder.Id];
        Asset selectCharger = [SELECT Id, CCR_ReplacedBy__c, AccountId, ContactId, Status, CCR_OriginalAsset__c, CCR_CodentifyId__c, SerialNumber, CCR_DeviceProductCode__c, CCR_MaterialGroupDescription__c, CCR_Version__c, PurchaseDate, KDCE_DeviceLabelling__c, KDCE_RentalCount__c FROM Asset WHERE Id = :charger.Id];
        List<Asset> selectList = new List<Asset>();
        selectList.add(selectHolder);
        selectList.add(selectCharger);

        // Contact Asset 연결 생성
        List<Asset> insertAssetList = new List<Asset>();
        Asset conHolder = selectHolder.clone(false, true);
        conHolder.Name = 'AssetHolder2';
        conHolder.CCR_CodentifyId__c = 'ContactHolder';
        conHolder.ContactId = contact.Id;
        Asset conCharger = selectCharger.clone(false, true);
        conCharger.Name = 'AssetCharger2';
        conCharger.CCR_CodentifyId__c = 'ContactCharger';
        conCharger.ContactId = contact.Id;
        insertAssetList.add(conHolder);
        insertAssetList.add(conCharger);
        insert insertAssetList;

        assetMap.put('selectList', selectList);
        assetMap.put('insertAssetList', insertAssetList);

        return assetMap;
    }

    @IsTest
    static void testBehavior01() {
        Test.startTest();
        KDCE_OfflineProgramController.getInvalidContact(contact.Id);
        KDCE_OfflineProgramController.getTypeList();
        KDCE_OfflineProgramController.getDefaultStore();
        Test.stopTest();
    }

    @IsTest
    static void testBehavior02() {
        Test.startTest();
        Asset asset = [SELECT Id, ContactId, Status, CCR_Version__c FROM Asset WHERE Id = :holder.Id];
        asset.Status = 'Active';
        asset.ContactId = contact.Id;
        KDCE_OfflineProgramController.checkValidKitToKiT(asset.Id);
        Test.stopTest();
    }

//    @IsTest
//    static void testBehavior03() {
//    }

    @IsTest
    static void testBehavior04() {
        Test.startTest();
        KDCE_OfflineProgramController.getDataTableHeader(contact.Id, 'ZTA');
        Test.stopTest();
    }

    @IsTest
    static void testBehavior05() {
        Test.startTest();
        KDCE_OfflineProgramController.getAssetList(holder.Id, 'ZTA', store.Id);
        Test.stopTest();
    }

    @IsTest
    static void testBehavior06() {
        Test.startTest();
        KDCE_OfflineProgramController.checkCouponCount(coupon.Id);
        Test.stopTest();
    }

    @IsTest
    static void testBehavior07() {
        Test.startTest();
        Map<String, List<Asset>> assetMap = createRecordForTest();
        List<Asset> selectList = assetMap.get('selectList');
        List<Asset> insertAssetList = assetMap.get('insertAssetList');
        KDCE_OfflineProgramController.swapAsset(contact.Id, System.today(), System.today(), 'ZTAR', null, selectList, selectList, store.Id, store.Id, selectCoupon.Id, 'Starbucks', assetVersion, 'Reason1','Reason2', 'Sponsor', 'Sponsor', System.now(), 'Reference', 'Channel');
        Test.stopTest();
    }

    @IsTest
    static void testBehavior08() {
        Test.startTest();
        Map<String, List<Asset>> assetMap = createRecordForTest();
        List<Asset> selectList = assetMap.get('selectList');
        List<Asset> insertAssetList = assetMap.get('insertAssetList');
        KDCE_OfflineProgramController.swapAsset(contact.Id, System.today(), System.today(), 'ZTI', insertAssetList, selectList, selectList, store.Id, store.Id, null, 'Starbucks', assetVersion, '', 'Reason', 'Sponsor', 'Sponsor',  System.now(), 'Reference', 'Channel');
//        KDCE_OfflineProgramController.swapAsset(contact.Id, System.today(), System.today(), 'ZTU', insertAssetList, selectList, selectList, store.Id, store.Id, null, 'Starbucks', assetVersion, '', 'Reason', 'Sponsor', System.now(), 'Reference', 'Channel');
        Test.stopTest();
    }

    @IsTest
    static void testBehavior09() {
        Test.startTest();
        Map<String, List<Asset>> assetMap = createRecordForTest();
        List<Asset> selectList = assetMap.get('selectList');
        List<Asset> insertAssetList = assetMap.get('insertAssetList');
        KDCE_OfflineProgramController.swapAsset(contact.Id, System.today(), System.today(), 'ZTA', null, selectList, selectList, store.Id, store.Id, selectCoupon.Id, 'Starbucks', assetVersion, '', 'Reason', 'Sponsor', 'Sponsor', System.now(), 'Reference', 'Channel');
        Test.stopTest();
    }

    @IsTest
    static void testBehavior10() {
        Test.startTest();
        Map<String, List<Asset>> assetMap = createRecordForTest();
        List<Asset> selectList = assetMap.get('selectList');
        List<Asset> insertAssetList = assetMap.get('insertAssetList');
        KDCE_OfflineProgramController.swapAsset(contact.Id, System.today(), System.today(), 'ZTA', null, selectList, selectList, store.Id, store.Id, null, 'Starbucks', assetVersion, '', 'Reason', 'Sponsor', 'Sponsor', System.now(), 'Reference', 'Channel');
        Test.stopTest();
    }

    @IsTest
    static void testBehavior11() {
        Test.startTest();
        Map<String, List<Asset>> assetMap = createRecordForTest();
        List<Asset> selectList = assetMap.get('selectList');
        List<Asset> insertAssetList = assetMap.get('insertAssetList');
        KDCE_OfflineProgramController.swapAsset(contact.Id, System.today(), System.today(), 'ZTA', null, selectList, selectList, store.Id, store.Id, null, 'Starbucks', assetVersion, '', 'Reason', 'Sponsor', 'Sponsor', System.now(), 'Reference', 'Channel');
        Test.stopTest();
    }

    @IsTest
    static void testBehavior12() {
        Test.startTest();
        Map<String, List<Asset>> assetMap = createRecordForTest();
        List<Asset> selectList = assetMap.get('selectList');
        List<Asset> insertAssetList = assetMap.get('insertAssetList');
        KDCE_OfflineProgramController.swapAsset(contact.Id, System.today(), System.today(), 'ZRN', null, selectList, selectList, store.Id, store.Id, null, null, null, null, null, null, null, System.now(), null, null);
        Test.stopTest();
    }

    @IsTest
    static void testBehavior13() {
        Test.startTest();
        Id rt_Rental = Schema.SObjectType.KDCE_OfflineProgram__c.getRecordTypeInfosByDeveloperName().get('OfflineProgram_ZRN').getRecordTypeId();
        Map<String, List<Asset>> assetMap = createRecordForTest();
        List<Asset> selectList = assetMap.get('selectList');
        List<Asset> insertAssetList = assetMap.get('insertAssetList');
        // 고객이 렌탈중인 기기가 있을때
        KDCE_OfflineProgram__c newOp = new KDCE_OfflineProgram__c(
                Contact__c = contact.Id,
                Status__c = 'Rental Process',
                RecordTypeId = rt_Rental
        );
        insert newOp;
        KDCE_OfflineProgramController.swapAsset(contact.Id, System.today(), System.today(), 'ZRN', null, selectList, selectList, store.Id, store.Id, null, null, null, null, null, null, null, System.now(), null, null);
        Test.stopTest();
    }

    @IsTest
    static void testBehavior14() {
        Test.startTest();
        Map<String, List<Asset>> assetMap = createRecordForTest();
        List<Asset> selectList = assetMap.get('selectList');
        List<Asset> insertAssetList = assetMap.get('insertAssetList');
        Asset asset = [SELECT Id, ContactId, CCR_Version__c FROM Asset WHERE Id = :holder.Id];
        asset.ContactId = contact.Id;
        update asset;
        System.debug('=== asset.CCR_Version__c : ' + asset.CCR_Version__c);

        KDCE_OfflineProgramController.swapAsset(asset.Id, System.today(), System.today(), 'ZRT', insertAssetList, selectList, selectList, store.Id, store.Id, coupon.Id, 'Starbucks', assetVersion, 'Other Software Malfunction', 'Other Software Malfunction', 'Sponsor', 'Sponsor', System.now(), 'Reference', 'Channel');
        Test.stopTest();
    }

    @IsTest
    static void testBehavior15() {
        Test.startTest();

        Map<String, List<Asset>> assetMap = createRecordForTest();
        List<Asset> selectList = assetMap.get('selectList');
        List<Asset> insertAssetList = assetMap.get('insertAssetList');

        // Material M으로 업데이트
        CCR_Material__c material = KDCE_TestUtil.materialHolder;
        material = [SELECT Id, Name, CCR_Group__c, CCR_Material__c, CCR_MaterialType__c, CCR_Version__c FROM CCR_Material__c WHERE Id = :material.Id];
        material.CCR_Version__c = '3.0M';
        update material;

        Asset asset = [SELECT Id, ContactId, CCR_Version__c FROM Asset WHERE Id = :holder.Id];
        asset.ContactId = contact.Id;
        update asset;
        System.debug('=== asset.CCR_Version__c : ' + asset.CCR_Version__c);

        KDCE_OfflineProgramController.swapAsset(asset.Id, System.today(), System.today(), 'ZRT', insertAssetList, selectList, selectList, store.Id, store.Id, coupon.Id, 'Starbucks', assetVersion, 'Other Software Malfunction', 'Other Software Malfunction', 'Sponsor', 'Sponsor', System.now(), 'Reference', null);
        Test.stopTest();
    }



}