force-app/main/default/objects/Asset/fields/CCR_CodentifyId__c.field-meta.xml
<CustomField>
    <fullName>CCR_CodentifyId__c</fullName>
    <description>Unique identifier of the device to be used as external key.</description>
    <externalId>true</externalId>
    <label>Codentify ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CCR_ISOBARGetVoucherApiDetails__c/CCR_ISOBARGetVoucherApiDetails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used by: CCR 
Description : To store details regarding ISOBAR API to get and resend voucher.</description>
    <label>CCR ISOBARGetVoucherApiDetails</label>
</CustomObject>

force-app/main/default/objects/CCR_ISOBARGetVoucherApiDetails__c/fields/CCR_Active__c.field-meta.xml
<CustomField>
    <fullName>CCR_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used By: CCR
Description: This field is for the active flag for the record</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCR_ISOBARGetVoucherApiDetails__c/fields/CCR_PrivateKey__c.field-meta.xml
<CustomField>
    <fullName>CCR_PrivateKey__c</fullName>
    <description>Used by: CCR Description : to store private key to encrypt phone number.</description>
    <label>Private Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR_ISOBARGetVoucherApiDetails__c/fields/CCR_SaltKey__c.field-meta.xml
<CustomField>
    <fullName>CCR_SaltKey__c</fullName>
    <description>Used by: CCR Description : to store salt key to encrypt phone number.</description>
    <label>Salt Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IF_KDCE_CalloutController_ts.cls
/****************************************************************************************
  * @filename      : IF_KDCE_CalloutController_ts
  * @projectname   : PMK qa - KR
  * @author        : Park HE
  * @date          : 2021-06-28
  * @group         :
  * @group-content :
  * @description   :
  * @tester        :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                    author          description
  * ===============================================================
    0.1     2021-06-28             Park HE         Create
****************************************************************************************/

@IsTest
private class IF_KDCE_CalloutController_ts {
    @IsTest
    static void testBehavior() {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();
        Asset tempAsset = KDCE_TestUtil.assetHolder.clone();
        CCR_ISOBARGetVoucherApiDetails__c tempISOBAR = new CCR_ISOBARGetVoucherApiDetails__c(
                CCR_Active__c = true,
                Name ='test',
                CCR_SaltKey__c = 'Ame7kBGjV7mDoQUw',
                CCR_PrivateKey__c = 'XT3LEBuUuE81Z0qW');
        insert tempISOBAR;

        CCR_QureMsg qureMsg = new CCR_QureMsg();
        qureMsg.Codentify       = tempAsset.CCR_CodentifyId__c;
        qureMsg.ConsumerPhone   = '01012345678';
        System.debug(qureMsg);


        IF_KDCE_CallOutController.getGlobalDeviceInfo('test');
        IF_KDCE_CallOutController.getHeetsInfo('test');
        //IF_KDCE_CallOutController.getShortURL('tryiqos.kr');
        IF_KDCE_CallOutController.callIssueGS25VoucherAPI(qureMsg);
        IF_KDCE_CallOutController.callMagentoOrderAPI(qureMsg);

//        IF_KDCE_CallOutController.runTest();
        IF_KDCE_CalloutService.runTest();
    }
}