force-app/main/default/objects/Asset/fields/CCR_CodentifyId__c.field-meta.xml
<CustomField>
    <fullName>CCR_CodentifyId__c</fullName>
    <description>Unique identifier of the device to be used as external key.</description>
    <externalId>true</externalId>
    <label>Codentify ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_DeviceProductCode__c.field-meta.xml
<CustomField>
    <fullName>CCR_DeviceProductCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the related Material on the Material Object</description>
    <label>Device  Product Code</label>
    <referenceTo>CCR_Material__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_MaterialDescription__c.field-meta.xml
<CustomField>
    <fullName>CCR_MaterialDescription__c</fullName>
    <description>Material Description</description>
    <formula>CCR_DeviceProductCode__r.CCR_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_MaterialGroupDescription__c.field-meta.xml
<CustomField>
    <fullName>CCR_MaterialGroupDescription__c</fullName>
    <description>Group Material description</description>
    <formula>CCR_DeviceProductCode__r.CCR_GroupDescription__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Group Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_OriginaDesignMarket__c.field-meta.xml
<CustomField>
    <fullName>CCR_OriginaDesignMarket__c</fullName>
    <description>Market where the box will be commercialized</description>
    <formula>Product2.CCR_OriginalDesignMarket__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Original Design Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/KDCE_fm_ProductEAN__c.field-meta.xml
<CustomField>
    <fullName>KDCE_fm_ProductEAN__c</fullName>
    <description>[KDCE] Product Barcode</description>
    <formula>Product2.KDCE_EANCode__c</formula>
    <label>Product EAN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR_Material__c/CCR_Material__c.object-meta.xml
<CustomObject>
    <description>Created to store information regarding the Device Master Data (catalogue).</description>
    <label>Material</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_Material__c/fields/CCR_Color__c.field-meta.xml
<CustomField>
    <fullName>CCR_Color__c</fullName>
    <description>Device Color</description>
    <label>Color</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_INFO__c/IF_INFO__c.object-meta.xml
<CustomObject>
    <description>I/F구현관련 개발단위 세부정보 (Master, Detail 분리 구성 정보 등)</description>
    <label>IF INFOs</label>
    <nameField>
        <displayFormat>IF-{YYYY}{MM}{DD}{0000000000}</displayFormat>
        <label>Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IF INFOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_INFO__c/fields/TO__c.field-meta.xml
<CustomField>
    <fullName>TO__c</fullName>
    <description>false</description>
    <label>TO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IfStaticValue__c/IfStaticValue__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>인터페이스 상수 정의</label>
</CustomObject>

force-app/main/default/objects/IfStaticValue__c/fields/hub_aes_init_vector__c.field-meta.xml
<CustomField>
    <fullName>hub_aes_init_vector__c</fullName>
    <label>HUB VECTOR KEY</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IfStaticValue__c/fields/hub_aes_private_key__c.field-meta.xml
<CustomField>
    <fullName>hub_aes_private_key__c</fullName>
    <label>HUB PRIVATE KEY</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IfStaticValue__c/fields/hub_auth_name__c.field-meta.xml
<CustomField>
    <fullName>hub_auth_name__c</fullName>
    <label>HUB 계정</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IfStaticValue__c/fields/hub_auth_password__c.field-meta.xml
<CustomField>
    <fullName>hub_auth_password__c</fullName>
    <label>HUB 비밀번호</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IfStaticValue__c/fields/hub_url__c.field-meta.xml
<CustomField>
    <fullName>hub_url__c</fullName>
    <label>HUB URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/IfStaticValue__c/fields/sfdc_aes_algorithm__c.field-meta.xml
<CustomField>
    <fullName>sfdc_aes_algorithm__c</fullName>
    <label>SFDC ENCRYPT ALGORITHM</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IfStaticValue__c/fields/sfdc_oauth_client_id__c.field-meta.xml
<CustomField>
    <fullName>sfdc_oauth_client_id__c</fullName>
    <label>SFDC CLIENT ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IfStaticValue__c/fields/sfdc_oauth_client_secret__c.field-meta.xml
<CustomField>
    <fullName>sfdc_oauth_client_secret__c</fullName>
    <label>SFDC CLIENT SECRET</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IfStaticValue__c/fields/sfdc_oauth_password__c.field-meta.xml
<CustomField>
    <fullName>sfdc_oauth_password__c</fullName>
    <label>SFDC PASSWORD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IfStaticValue__c/fields/sfdc_oauth_username__c.field-meta.xml
<CustomField>
    <fullName>sfdc_oauth_username__c</fullName>
    <label>SFDC USER NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IfStaticValue__c/fields/sfdc_org_url__c.field-meta.xml
<CustomField>
    <fullName>sfdc_org_url__c</fullName>
    <label>SFDC ORG URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CCR_ProductName__c.field-meta.xml
<CustomField>
    <fullName>CCR_ProductName__c</fullName>
    <description>To make the standar field unique</description>
    <externalId>true</externalId>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL_TEST.cls
/****************************************************************************************
  * @filename      : IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL_TEST
  * @projectname   : PMK LocalDCE QA
  * @author        : i2max_shlee 
  * @date          : 2021/02/18 3:38 오후
  * @group         : e.g)tab name
  * @group-content : e.g)view file  
  * @description   : 
  * @tester        : IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL_TEST_ts.cls
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                author              description
  * ===============================================================
    0.1     2021/02/18 3:38 오후     i2max_shlee       Create
****************************************************************************************/
@IsTest
public with sharing class IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL_TEST {
    private static void testStaticValue() {
        IfStaticValue__c staticValue = new IfStaticValue__c();

        staticValue.sfdc_org_url__c              = 'https://salesforce.com';
        staticValue.sfdc_oauth_client_id__c      = 'client_id';
        staticValue.sfdc_oauth_client_secret__c  = 'client_secret';
        staticValue.sfdc_oauth_username__c       = 'salesforce@salesforce.com';
        staticValue.sfdc_oauth_password__c       = 'salesforce';
        staticValue.sfdc_aes_algorithm__c        = 'AES258';
        staticValue.hub_auth_name__c             = 'dih';
        staticValue.hub_auth_password__c         = 'dih_password';
        staticValue.hub_aes_private_key__c       = 'aes_key';
        staticValue.hub_aes_init_vector__c       = 'aes_vector';

        staticValue.hub_url__c       = 'Test_Setup_Value';

        IF_Base.IfStaticValue(staticValue);
    }

    // 입력 객체 생성
    private static IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL.InputDIH newInputParameter() {

        String req = '{"request":{"payload":{"t_data":[{"DYNAMIC_SOQL":"SELECT ContactId,CCR_CodentifyId__c, SerialNumber, CCR_MaterialGroupDescription__c, CCR_MaterialDescription__c, CCR_OriginaDesignMarket__c, CCR_DeviceProductCode__r.CCR_Color__c, Product2.CCR_ProductName__c,KDCE_fm_ProductEAN__c, CreatedDate, LastModifiedDate FROM Asset WHERE CCR_CodentifyId__c \\u003d\\u0027TGC2X7HQ6GPQGR\\u0027","UN_ENCRYPT":"Y"}]},"header":{"ifSender":"POS","ifReceiverGp":"SC","ifSenderGp":"POS","ifReceiver":"SC","ifId":"IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL"}}}';
        IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL.InputDIH input = new IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL.InputDIH();
        input = (IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL.InputDIH)JSON.deserialize(req, IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL.InputDIH.class);

        return input;
    }

    // HTTPResponse 객체 생성
    private static HTTPResponse newResponse(Integer statusCode) {
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setStatusCode(statusCode);
        res.setBody('{"header":{"ifTrackingId":null,"ifSenderGp":"SFSC","ifSender":"SFSC","ifResult":"S","ifReceiverGp":"Magento","ifReceiver":"Magento","ifId":"IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL","ifFailMsg":"","ifFailCode":"","ifDateTime":"20210224030047"},"payload":{"t_data":[{"productIds":["01t1m000000uBBaAAM","01t1m000000u8RRAAY","01t1m000000uA5tAAE","01t1m000000uA1jAAE"]}],"ifSplitCnt":"1","ifRcvCnt":"1","ifAggregation":"0002e2d0-cec3-6e84-5761-ae68b3bf20a3"}}');
        IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL.OutputDIH temp = (IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL.OutputDIH)JSON.deserialize(res.getBody(), IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL.OutputDIH.class);
        return res;
    }

    // StatusCode=200 Mock
    private class HttpCalloutSuccessMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = newResponse(200);
            return res;
        }
    }

    // 공통 테스트 진행
    private static Boolean testServiceExecute() {
        String jsonMsg = JSON.serialize(newInputParameter());

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = '/services/apexrest/IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL';  //Request URL
        req.httpMethod = 'POST';  //HTTP Request Type
        req.requestBody = Blob.valueof(jsonMsg);
        RestContext.request = req;
        RestContext.response = res;

        // 서비스 실행
        IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL.OutputDIH result = IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL.doPost();
        System.debug('result : '+result);
        //System.assertEquals(result.Response.Header.ResultCode, 'S', 'IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL 실패!!!');

        // crashTest
        IF_Base.crashTest = true;
        result = IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL.doPost();

        //System.assertEquals(result.Response.Header.ResultCode, 'E', 'IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL 실패!!!');
        return true;
    }

    // 성공 테스트
    @isTest public static void testServiceSuccess() {
        testStaticValue();
        IF_INFO__c ifInfo = new IF_INFO__c(
                IF_ID__c = 'IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL',
                URL__c = '/IF_DCE_Korea_SFDC_REST_DYNAMIC_SOQL',
                CYCLE__c ='realtime',
                FROM__c ='Ecommerce',
                TO__c ='SFDC',
                TITLE__c ='Ecommerce에서 SFDC로 \'SOQL\' 을(를) 조회한다.',
                FORCE_LOGGING__c = true
        );
        insert ifInfo;

        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());

        System.assertEquals(testServiceExecute(), true);
    }
}