force-app/main/default/objects/Asset/fields/CCR_CodentifyId__c.field-meta.xml
<CustomField>
    <fullName>CCR_CodentifyId__c</fullName>
    <description>Unique identifier of the device to be used as external key.</description>
    <externalId>true</externalId>
    <label>Codentify ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_DeviceProductCode__c.field-meta.xml
<CustomField>
    <fullName>CCR_DeviceProductCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the related Material on the Material Object</description>
    <label>Device  Product Code</label>
    <referenceTo>CCR_Material__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CCR_Version__c.field-meta.xml
<CustomField>
    <fullName>CCR_Version__c</fullName>
    <description>Device Product Code Version</description>
    <formula>CCR_DeviceProductCode__r.CCR_Version__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Version</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/KDCE_ShipmentDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ShipmentDate__c</fullName>
    <label>Shipment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CCR_Material__c/CCR_Material__c.object-meta.xml
<CustomObject>
    <description>Created to store information regarding the Device Master Data (catalogue).</description>
    <label>Material</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_Material__c/fields/CCR_GroupDescription__c.field-meta.xml
<CustomField>
    <fullName>CCR_GroupDescription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identification code of the group the device belongs to.</description>
    <label>Group Description</label>
    <referenceTo>CCR_Material__c</referenceTo>
    <relationshipLabel>Materials (Material)</relationshipLabel>
    <relationshipName>Material</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCR_Material__c/fields/CCR_Version__c.field-meta.xml
<CustomField>
    <fullName>CCR_Version__c</fullName>
    <description>Device Version</description>
    <label>Version</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_AssetHistory__c/KDCE_AssetHistory__c.object-meta.xml
<CustomObject>
    <label>Asset History</label>
    <nameField>
        <displayFormat>AH-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/CCR_Version__c.field-meta.xml
<CustomField>
    <fullName>CCR_Version__c</fullName>
    <description>Device Version</description>
    <label>Version</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_Asset_tr_ts.cls
/****************************************************************************************
  * @filename      : KDCE_Asset_tr_ts
  * @projectname   : PMK qa - KR
  * @author        : Park HE
  * @date          : 2021-04-19
  * @group         :
  * @group-content :
  * @description   :
  * @tester        :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                    author          description
  * ===============================================================
    0.1     2021-04-19             Park HE         Create
****************************************************************************************/

@IsTest
private class KDCE_Asset_tr_ts {
    static {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();
    }

    @IsTest
    static void testAssetLifeCycle() {
        Test.startTest();
        System.debug('aaa + ' + KDCE_TestUtil.contactMember);
        KDCE_TestUtil.assetCharger.AccountId = null;
        KDCE_TestUtil.assetCharger.ContactId = KDCE_TestUtil.contactMember.Id;
        KDCE_TestUtil.assetCharger.KDCE_ShipmentDate__c = System.today();
        KDCE_TestUtil.assetCharger.Status = KDCE_GlobalValue.ASSET_STATUS_ACTIVE;

        update KDCE_TestUtil.assetCharger;

        System.debug('KDCE_TestUtil.assetCharger' + KDCE_TestUtil.assetCharger);
        System.debug('KDCE_TestUtil.assetCharger' + KDCE_TestUtil.assetCharger.Product2.CCR_Version__c);
        System.debug('KDCE_TestUtil.assetCharger' + KDCE_TestUtil.assetCharger.Product2Id);
        System.debug('KDCE_TestUtil.assetCharger' + KDCE_TestUtil.assetCharger.Product2);
        System.debug('KDCE_TestUtil.assetCharger' + KDCE_TestUtil.assetCharger.CCR_DeviceProductCode__r.CCR_GroupDescription__r.Name);
        System.debug('KDCE_TestUtil.assetCharger' + KDCE_TestUtil.assetCharger.CCR_DeviceProductCode__c);
        System.debug('KDCE_TestUtil.assetCharger' + KDCE_TestUtil.assetCharger.CCR_DeviceProductCode__r.CCR_GroupDescription__c);

        KDCE_AssetHistory__c assetHistory = new KDCE_AssetHistory__c();

        System.assertNotEquals(assetHistory, null);

        System.assertEquals(KDCE_TestUtil.assetCharger.Status, KDCE_GlobalValue.ASSET_STATUS_ACTIVE);

        KDCE_TestUtil.assetCharger.Status = KDCE_GlobalValue.ASSET_STATUS_PRODUCED;
        update KDCE_TestUtil.assetCharger;
        System.assertEquals(KDCE_TestUtil.assetCharger.Status, KDCE_GlobalValue.ASSET_STATUS_PRODUCED);
        Test.stopTest();

    }

    @IsTest
    static void testRestoreAsset() {
        Test.startTest();
        KDCE_TestUtil.assetCharger.Status = KDCE_GlobalValue.ASSET_STATUS_PRODUCED;
        update KDCE_TestUtil.assetCharger;
        System.assertEquals(KDCE_TestUtil.assetCharger.Status, KDCE_GlobalValue.ASSET_STATUS_PRODUCED);
        Test.stopTest();

    }

    @IsTest
    static void testDeleteRelatedAsset() {
        Test.startTest();
        Asset asset = KDCE_TestUtil.assetCharger.clone(false);
        asset.Status = KDCE_GlobalValue.ASSET_STATUS_ACTIVE;
        asset.CCR_CodentifyId__c = String.valueOf(Integer.valueOf((Math.random() * 1000000)));
        insert asset;

        asset.Status = KDCE_GlobalValue.ASSET_STATUS_PRODUCED;
        update asset;
//        System.assertEquals(KDCE_TestUtil.assetCharger.Status, KDCE_GlobalValue.ASSET_STATUS_PRODUCED);
//        System.debug('aa : ' + KDCE_TestUtil.assetCharger.Status);
        Test.stopTest();

    }

}