force-app/main/default/objects/Asset/fields/KDCE_DeviceType__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DeviceType__c</fullName>
    <description>[KDCE] Device Type</description>
    <label>Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeviceType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_AssetLifeCycle__c/CCR_AssetLifeCycle__c.object-meta.xml
<CustomObject>
    <description>Created to store information on the linking and unlinking of the Device.</description>
    <label>Asset Life Cycle</label>
    <nameField>
        <displayFormat>LC-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Life Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR_AssetLifeCycle__c/fields/CCR_Action__c.field-meta.xml
<CustomField>
    <fullName>CCR_Action__c</fullName>
    <description>Possible action performed on a device.</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Unlink</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR_AssetLifeCycle__c/fields/CCR_ActionDate__c.field-meta.xml
<CustomField>
    <fullName>CCR_ActionDate__c</fullName>
    <description>Date and time when the link / unlink action is performed.</description>
    <inlineHelpText>This field indicates the date and time when linking/unlinking the contact.</inlineHelpText>
    <label>Action Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CCR_AssetLifeCycle__c/fields/CCR_Asset__c.field-meta.xml
<CustomField>
    <fullName>CCR_Asset__c</fullName>
    <description>Reference to the asset for which the life cycle information belongs to.</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Life Cycles</relationshipLabel>
    <relationshipName>AssetLifeCycles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CCR_AssetLifeCycle__c/fields/CCR_Consumer__c.field-meta.xml
<CustomField>
    <fullName>CCR_Consumer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Relationship to the contact with action associated to the device.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asset Life Cycles</relationshipLabel>
    <relationshipName>AssetLifeCycles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCR_AssetLifeCycle__c/fields/KDCE_DeviceType__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DeviceType__c</fullName>
    <description>[KDCE] Device Type</description>
    <label>Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeviceType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_AssetHistory__c/KDCE_AssetHistory__c.object-meta.xml
<CustomObject>
    <label>Asset History</label>
    <nameField>
        <displayFormat>AH-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_AssetHistory__c/fields/ActionDate__c.field-meta.xml
<CustomField>
    <fullName>ActionDate__c</fullName>
    <label>Action Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_AssetHistory__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Status Change</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Replaced By</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_AssetHistory__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Histories</relationshipLabel>
    <relationshipName>AssetHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KDCE_AssetHistory__c/fields/OrderLineItem__c.field-meta.xml
<CustomField>
    <fullName>OrderLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line Item</label>
    <referenceTo>KDCE_OrderLineItem__c</referenceTo>
    <relationshipName>AssetOrderHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/KDCE_Order__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Order</description>
    <label>Order</label>
    <nameField>
        <displayFormat>KO{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <description>Order Action Type</description>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDate__c</fullName>
    <description>[KDCE] 주문 생성 년월일시분초
Mapping Column : order_date</description>
    <inlineHelpText>주문 생성 년월일시분초</inlineHelpText>
    <label>Order Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderReason__c.field-meta.xml
<CustomField>
    <fullName>OrderReason__c</fullName>
    <description>주문 사유
forward: 주문
return: 반품
collect: 반납
rental forward: 렌탈 후 구매주문
rental return: 렌탈 후 구매주문 반품</description>
    <inlineHelpText>주문 사유</inlineHelpText>
    <label>Order Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>forward</fullName>
            </value>
            <value>
                <fullName>return</fullName>
            </value>
            <value>
                <fullName>collect</fullName>
                <label>Collect</label>
            </value>
            <value>
                <fullName>rental forward</fullName>
            </value>
            <value>
                <fullName>rental return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>[KDCE] 주문 상태
Mapping Column : order_status</description>
    <inlineHelpText>주문 상태</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>processing</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>ready_for_delivery</fullName>
            </value>
            <value>
                <fullName>picking</fullName>
            </value>
            <value>
                <fullName>delivery_collection</fullName>
            </value>
            <value>
                <fullName>complete_delivery</fullName>
            </value>
            <value>
                <fullName>closed</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>cancel</fullName>
            </value>
            <value>
                <fullName>cancel_order</fullName>
            </value>
            <value>
                <fullName>return_received</fullName>
            </value>
            <value>
                <fullName>reject</fullName>
            </value>
            <value>
                <fullName>authorized</fullName>
            </value>
            <value>
                <fullName>approved</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>renting</fullName>
            </value>
            <value>
                <fullName>complete</fullName>
                <label>Complete</label>
            </value>
            <value>
                <fullName>paid</fullName>
            </value>
            <value>
                <fullName>received</fullName>
            </value>
            <value>
                <fullName>processed_closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <description>[KDCE] 주문타입
ZTA(일반주문)
ZTI(보상판매)
ZRN(렌탈 중고)
ZRNNEW(렌탈 신규)
ZRA(QURE)</description>
    <inlineHelpText>주문타입</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZTA</fullName>
            </value>
            <value>
                <fullName>ZTI</fullName>
            </value>
            <value>
                <fullName>ZRN</fullName>
            </value>
            <value>
                <fullName>ZRNNEW</fullName>
            </value>
            <value>
                <fullName>ZRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_OrderLineItem__c/KDCE_OrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_OrderLineItem__c/fields/Codentify__c.field-meta.xml
<CustomField>
    <fullName>Codentify__c</fullName>
    <description>[KDCE] 시리얼 (Parent Codentify Id OR Codentify Id)
Mapping Column : codentify</description>
    <inlineHelpText>시리얼 (Parent Codentify Id OR Codentify Id)</inlineHelpText>
    <label>Codentify</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_OrderLineItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>KDCE_Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KDCE_OrderLineItem__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>[KDCE] 주문 상태
Mapping Column : order_status</description>
    <inlineHelpText>주문 상태</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>processing</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>ready_for_delivery</fullName>
            </value>
            <value>
                <fullName>picking</fullName>
            </value>
            <value>
                <fullName>delivery_collection</fullName>
            </value>
            <value>
                <fullName>complete_delivery</fullName>
            </value>
            <value>
                <fullName>closed</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>cancel</fullName>
            </value>
            <value>
                <fullName>cancel_order</fullName>
            </value>
            <value>
                <fullName>return_received</fullName>
            </value>
            <value>
                <fullName>reject</fullName>
            </value>
            <value>
                <fullName>authorized</fullName>
            </value>
            <value>
                <fullName>approved</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>renting</fullName>
            </value>
            <value>
                <fullName>complete</fullName>
                <label>Complete</label>
            </value>
            <value>
                <fullName>paid</fullName>
            </value>
            <value>
                <fullName>received</fullName>
            </value>
            <value>
                <fullName>processed_closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_OrderLineItem__c/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <description>[KDCE] 주문타입
ZTA(일반주문)
ZTI(보상판매)
ZRN(렌탈 중고)
ZRNNEW(렌탈 신규)
ZRA(QURE)</description>
    <inlineHelpText>주문타입</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZTA</fullName>
            </value>
            <value>
                <fullName>ZTI</fullName>
            </value>
            <value>
                <fullName>ZRN</fullName>
            </value>
            <value>
                <fullName>ZRNNEW</fullName>
            </value>
            <value>
                <fullName>ZRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_AssetService.cls
/****************************************************************************************
  * @filename      : 
  * @projectname   : 
  * @author        : i2max_Junseok.Kwon
  * @date          : 2021-03-05 오후 5:21
  * @group         : 
  * @group-content : 
  * @description   : Asset 관련 비지니스 로직 정리
  * @tester        : KDCE_AssetService_ts.cls
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-03-05 오후 5:21     i2max_Junseok.Kwon        Create
****************************************************************************************/

public without sharing class KDCE_AssetService {

   /* public static KDCE_AssetHistory__c createAssetHistory(Asset device, String actionType, Contact ct){
        return createAssetHistory(device, actionType, ct, null, null);
    }

    public static KDCE_AssetHistory__c createAssetHistory(Asset device, String actionType, Contact ct, String status, String labelling){

        KDCE_AssetHistory__c ah = new KDCE_AssetHistory__c();
        ah.ActionType__c        = actionType;
        ah.ActionDate__c        = System.now();
        ah.Contact__c           = ct.Id;
        ah.StatusValue__c       = status;
        ah.LabellingValue__c    = labelling;

        return ah;
    }*/

    public static KDCE_AssetHistory__c createAssetHistory(Asset device, KDCE_OrderLineItem__c oli, String actionType){

        KDCE_AssetHistory__c ah = new KDCE_AssetHistory__c();
        ah.ActionType__c        = actionType;
        ah.ActionDate__c        = System.now();
        ah.Asset__c             = device.Id;
        ah.OrderLineItem__c     = oli == null? null : oli.Id;

        return ah;
    }


    /**
     * @author Park HE
     * @description  CCR_AssetLifeCycle__c 레코드 생성
     * @param assetId
     * @param contactId
     * @param action (Link or Unlink)
     *
     * @return CCR_AssetLifeCycle__c 단일 레코드
     */
    public static CCR_AssetLifeCycle__c returnAssetLifeCycleValue(Asset asset, String action, Id contactId) {

        CCR_AssetLifeCycle__c alc = new CCR_AssetLifeCycle__c(
                CCR_Asset__c = asset.Id,
                CCR_Action__c = KDCE_Util.getPicklistValue('CCR_AssetLifeCycle__c', 'CCR_Action__c').get(action),
                CCR_ActionDate__c = System.now(),
                CCR_Consumer__c = contactId,
                KDCE_DeviceType__c = asset.KDCE_DeviceType__c
        );
        return alc;
    }

    public static List<KDCE_OrderLineItem__c> getOrderLineItems(Set<Id> orderIds){
        List<KDCE_OrderLineItem__c> oliList = new List<KDCE_OrderLineItem__c>([
                SELECT  Id, Codentify__c, Order__c, Order__r.Contact__c, Order__r.OrderDate__c, Order__r.OrderType__c,
                        Order__r.Name, Order__r.OrderStatus__c, Order__r.OrderReason__c, Order__r.OriginOrder__c
                FROM    KDCE_OrderLineItem__c WHERE Order__c IN :orderIds
        ]);

        System.debug('================================================= getOrderLineItems (Start) ================================================= ');
        System.debug(oliList);
        System.debug('================================================= getOrderLineItems (End) =================================================== ');

        return oliList;
    }

    public static List<Asset> getAssets(Set<String> codentifySet){
        List<Asset> assets = new List<Asset>([
                SELECT  Id, CCR_CodentifyId__c, SerialNumber, ContactId, Product2Id, ProductCode, PurchaseDate, Status, KDCE_DeviceType__c, KDCE_DeviceLabelling__c,
                        AccountId, CCR_PurchaseChannel__c, KDCE_ShipmentDate__c, CCR_CarePlusDueDate__c, KDCE_fm_WarrantyDate__c, KDCE_RentalCount__c, CCR_ReplacedBy__c
                FROM    Asset
                WHERE   CCR_CodentifyId__c IN :codentifySet OR SerialNumber IN : codentifySet
        ]);

        System.debug('==================================================== getAssets (Start) ===================================================== ');
        System.debug(assets);
        System.debug('==================================================== getAssets (End) ======================================================= ');

        return assets;
    }

    public static Set<String> getCodentifySet(List<KDCE_OrderLineItem__c> oliList){
        Set<String> codentifySet = new Set<String>();
        String tempCodentify;
        for (KDCE_OrderLineItem__c oli : oliList) {
            if (oli.Codentify__c <> null) {
                tempCodentify = oli.Codentify__c;

                for(String str : tempCodentify.split(',')){
                    codentifySet.add(str.trim());
                }
            }
        }

        System.debug('==================================================== getCodentifySet (Start) ===================================================== ');
        System.debug(codentifySet);
        System.debug('==================================================== getCodentifySet (End) ======================================================== ');

        return codentifySet;
    }

    public static Map<String, List<Asset>> getCodentifyAssetMap(List<Asset> assetList, Set<String> codentifySet){
        Map<String, List<Asset>> codentifyAssetMap = new Map<String, List<Asset>>();
        //(OLI의) Codentify별로 Asset 저장하기
        for (Asset asset : assetList) {
            for (String codentify : codentifySet) {
                if (codentify == asset.CCR_CodentifyId__c || codentify == asset.SerialNumber) {
                    if (codentifyAssetMap.containsKey(codentify)) {
                        codentifyAssetMap.get(codentify).add(asset);
                    } else {
                        codentifyAssetMap.put(codentify, new List<Asset>{asset});
                    }
                }
            }
        }

        System.debug('==================================================== getCodentifyAssetMap (Start) ===================================================== ');
        System.debug(codentifyAssetMap);
        System.debug('==================================================== getCodentifyAssetMap (End) ======================================================== ');

        return codentifyAssetMap;
    }

    public static Set<String> splitCodentify(KDCE_OrderLineItem__c oli){
        Map<Id, List<String>> codentifyByOli = new Map<Id, List<String>>();
        Set<String> tempCodentifyList = new Set<String>();
        String tempCodentify;
        if(oli.Codentify__c != null) {
            tempCodentify = oli.Codentify__c;
            for (String str : tempCodentify.split(',')) {
                tempCodentifyList.add(str.trim());
            }
        }
            System.debug('================================================= splitCodentify (Start) ================================================= ');
            System.debug(tempCodentifyList);
            System.debug('================================================= splitCodentify (End) =================================================== ');
        return tempCodentifyList;
    }

    public static void checkFirstLinkDate(List<Asset> newList) {
        System.debug('@@@@@@ checkFirstLinkDate @@@@@@');

        Set<Id> assetIds = new Set<Id>();
        for (Asset item : newList) {
            assetIds.add(item.Id);
        }
        System.debug('assetIds ======= :: ' + assetIds);

        Map<String, AggregateResult> arLifeCycleMap = new Map<String, AggregateResult>();


        List<AggregateResult> arLifeCycleList = [
                SELECT MIN(CCR_ActionDate__c) actiondate, CCR_Asset__c asset
                FROM CCR_AssetLifeCycle__c
                WHERE CCR_Asset__c IN :assetIds AND CCR_ActionDate__c <> NULL AND CCR_Consumer__c <> NULL
                GROUP BY CCR_Asset__c
        ];
        String arKey;
        for (AggregateResult lifeCycle : arLifeCycleList) {
            arKey = (String) lifeCycle.get('asset');
            arLifeCycleMap.put(arKey, lifeCycle);
        }

        System.debug('====== arLifeCycleList ========' + arLifeCycleList);
        System.debug('====== arLifeCycleMap ========' + arLifeCycleMap);

        arKey = null;
        AggregateResult ar;

        List<Asset> updateAsset = new List<Asset>();

        for (Asset item : newList) {
            arKey = item.Id;
            if (arLifeCycleMap.containsKey(arKey)) {
                ar = arLifeCycleMap.get(arKey);

                updateAsset.add(new Asset(Id = item.Id,
                        CCR_FirstLinkDatetoCurrentContact__c = ((Datetime) (ar.get('actiondate'))).date()));
            }
        }
        update updateAsset;
    }
}