force-app/main/default/objects/Product2/fields/CCR_Category__c.field-meta.xml
<CustomField>
    <fullName>CCR_Category__c</fullName>
    <description>product category</description>
    <label>Product Category</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CCR_OriginalDesignMarket__c.field-meta.xml
<CustomField>
    <fullName>CCR_OriginalDesignMarket__c</fullName>
    <description>Market where the box will be commercialized</description>
    <label>Original Design Market</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/KDCE_MG_SendTarget__c.field-meta.xml
<CustomField>
    <fullName>KDCE_MG_SendTarget__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] MG로 전송 되어야 하는 제품</description>
    <label>MG Send Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/KDCE_ProductCategoryDescription__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ProductCategoryDescription__c</fullName>
    <description>커머스 사용자가 수정가능한 Product Category 필드. 초기에 들어올땐 기존에 있던 Product Category값과 같은 값으로 매핑되어서 들어옴.</description>
    <label>Product Category Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M0101</fullName>
                <label>(M0101) RRP HTP Sticks</label>
            </value>
            <value>
                <fullName>M0301</fullName>
                <label>(M0301) Reduced Risk Products HTP Holder</label>
            </value>
            <value>
                <fullName>M0302</fullName>
                <label>(M0302) Reduced Risk Products HTP Pocket Charger</label>
            </value>
            <value>
                <fullName>M0303</fullName>
                <label>(M0303) Accessory Organize</label>
            </value>
            <value>
                <fullName>M0304</fullName>
                <label>(M0304) Accessory Customize</label>
            </value>
            <value>
                <fullName>M0306</fullName>
                <label>(M0306) Reduced Risk Products HTP USB Power Adapter</label>
            </value>
            <value>
                <fullName>M0307</fullName>
                <label>(M0307) Reduced Risk Products HTP Car Charger</label>
            </value>
            <value>
                <fullName>M0308</fullName>
                <label>(M0308) Reduced Risk Products HTP USB Cable</label>
            </value>
            <value>
                <fullName>M0309</fullName>
                <label>(M0309) Accessory Charge</label>
            </value>
            <value>
                <fullName>M0320</fullName>
                <label>(M0320) RRP HTP Cleaning Tool</label>
            </value>
            <value>
                <fullName>M0321</fullName>
                <label>(M0321) RRP HTP Cleaning Sticks</label>
            </value>
            <value>
                <fullName>M0322</fullName>
                <label>(M0322) Accessory Dispose</label>
            </value>
            <value>
                <fullName>M0323</fullName>
                <label>(M0323) RRP HTP Sleeve</label>
            </value>
            <value>
                <fullName>M0390</fullName>
                <label>(M0390) RRP HTP Other Accessory</label>
            </value>
            <value>
                <fullName>M0401</fullName>
                <label>(M0401) RRP HTP Kit with holder</label>
            </value>
            <value>
                <fullName>M0405</fullName>
                <label>(M0405) NCP Closed System Sys Kit</label>
            </value>
            <value>
                <fullName>M0412</fullName>
                <label>(M0412) RRP HTP Combo Box</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_Product_tr.cls
/****************************************************************************************
  * @filename      : 
  * @projectname   : 
  * @author        : i2max_Junseok.Kwon
  * @date          : 2021-05-10 오후 2:12
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-05-10 오후 2:12     i2max_Junseok.Kwon        Create
****************************************************************************************/

public with sharing class KDCE_Product_tr extends TriggerHandler {
    public static Map<String, String> productCategoryPickVal = KDCE_Util.getPicklistValue('Product2', 'KDCE_ProductCategoryDescription__c');

    public override void beforeInsert() {
        setDefault();
    }
    public override void beforeUpdate() {
        setDefault();
    }

    private void setDefault() {

        Set<String> targetSet = new Set<String>();
        targetSet.add('KR04');
        targetSet.add('KR05');

        for(Product2 pd : (List<Product2>)Trigger.new){

            // CCR_OriginalDesignMarket__c 의 값이 KR04, KR05인 경우에 마젠토로 해당 제품 정보가 전송될 수 있도록 설정함
            if(targetSet.contains(pd.CCR_OriginalDesignMarket__c)) pd.KDCE_MG_SendTarget__c = true;

            // KDCE_ProductCategoryDescription에 대한 초기값 설정 (처음 생성될때는, Product Category와 같은 값으로 생성)
            if (Trigger.isInsert) {
                if (pd.CCR_Category__c != null && productCategoryPickVal.containsKey(pd.CCR_Category__c)) {
                    pd.KDCE_ProductCategoryDescription__c = pd.CCR_Category__c;
                }
            }
        }


    }
}