force-app/main/default/objects/Account/fields/CCR_ConsumerUID__c.field-meta.xml
<CustomField>
    <fullName>CCR_ConsumerUID__c</fullName>
    <description>SPICE internal ID</description>
    <label>Consumer UID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <description>Contact External Id (Auto). Process Builder로 생성</description>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CCR_ConsumerUID__c.field-meta.xml
<CustomField>
    <fullName>CCR_ConsumerUID__c</fullName>
    <description>SPICE internal ID</description>
    <externalId>true</externalId>
    <label>Consumer DB ID (AsIs Key)</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>[KDCE] Contact Key SpiceID 대체</description>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MIG_Contact_tr.cls
/****************************************************************************************
  * @filename      : 
  * @projectname   : 
  * @author        : i2max_Junseok.Kwon
  * @date          : 2021-07-30 오후 9:18
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-07-30 오후 9:18     i2max_Junseok.Kwon        Create
****************************************************************************************/

//public with sharing class MIG_Contact_tr {

//}

public without sharing class MIG_Contact_tr extends TriggerHandler {


    public override void beforeInsert() {

        runTest();
        createAccountRecord();              // Account 생성
    }

    /*
    * Contact 생성 시, Account 자동 생성
    **/
    private void createAccountRecord() {
        System.debug('@@@@@@ createAccountRecord @@@@@@');

        List<Account> accountList = new List<Account>();
        Account tempAccount;
        Map<String, String> accountIdMap = new Map<String, String>();
        for (Contact contact : (List<Contact>) Trigger.new) {
            String accName = contact.LastName == null ? 'Null LastName Account' : contact.LastName;
            accName += ' ';
            accName += contact.FirstName == null ? '' : contact.FirstName;
            tempAccount = new Account(
                    Name = accName,
                    KDCE_ExternalId__c = contact.KDCE_ExternalId__c,
                    CCR_ConsumerUID__c = contact.CCR_ConsumerUID__c
            );
            accountList.add(tempAccount);
        }

        insert accountList;

        for (Account acc : accountList) {
            accountIdMap.put(acc.KDCE_ExternalId__c, acc.Id);
        }

        System.debug(accountList);
        for (Contact contact : (List<Contact>) Trigger.new) {
            String accName = contact.LastName == null ? '' : contact.LastName;
            accName += ' ';
            accName += contact.FirstName == null ? '' : contact.FirstName;
            contact.AccountId = accountIdMap.get(contact.KDCE_ExternalId__c);
        }
    }

    private void runTest(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}