force-app/main/default/objects/Account/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <description>Contact External Id (Auto). Process Builder로 생성</description>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>[KDCE] Contact Key SpiceID 대체</description>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_PNKey__c.field-meta.xml
<CustomField>
    <fullName>KDCE_PNKey__c</fullName>
    <description>[KDCE] Record Key 전화번호</description>
    <externalId>true</externalId>
    <label>Contact Key (Phone Number)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>[i2sema] Notification Sending Infomations
알림 메세지 발송정보</description>
    <label>Notifications</label>
    <nameField>
        <displayFormat>N{yyMMdd}{0000000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/BTNURL1_1__c.field-meta.xml
<CustomField>
    <fullName>BTNURL1_1__c</fullName>
    <label>BTNURL1_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/BTNURL1_2__c.field-meta.xml
<CustomField>
    <fullName>BTNURL1_2__c</fullName>
    <label>BTNURL1_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/BTNURL2_1__c.field-meta.xml
<CustomField>
    <fullName>BTNURL2_1__c</fullName>
    <label>BTNURL2_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/BTNURL2_2__c.field-meta.xml
<CustomField>
    <fullName>BTNURL2_2__c</fullName>
    <label>BTNURL2_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/BTNURL3_1__c.field-meta.xml
<CustomField>
    <fullName>BTNURL3_1__c</fullName>
    <label>BTNURL3_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/BTNURL3_2__c.field-meta.xml
<CustomField>
    <fullName>BTNURL3_2__c</fullName>
    <label>BTNURL3_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/BTNURL4_1__c.field-meta.xml
<CustomField>
    <fullName>BTNURL4_1__c</fullName>
    <label>BTNURL4_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/BTNURL4_2__c.field-meta.xml
<CustomField>
    <fullName>BTNURL4_2__c</fullName>
    <label>BTNURL4_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/BTNURL5_1__c.field-meta.xml
<CustomField>
    <fullName>BTNURL5_1__c</fullName>
    <label>BTNURL5_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/BTNURL5_2__c.field-meta.xml
<CustomField>
    <fullName>BTNURL5_2__c</fullName>
    <label>BTNURL5_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Channel</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/IsForcedSend__c.field-meta.xml
<CustomField>
    <fullName>IsForcedSend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsForcedSend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL1__c.field-meta.xml
<CustomField>
    <fullName>LABEL1__c</fullName>
    <label>LABEL1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL2__c.field-meta.xml
<CustomField>
    <fullName>LABEL2__c</fullName>
    <label>LABEL2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL3__c.field-meta.xml
<CustomField>
    <fullName>LABEL3__c</fullName>
    <label>LABEL3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL4__c.field-meta.xml
<CustomField>
    <fullName>LABEL4__c</fullName>
    <label>LABEL4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL5__c.field-meta.xml
<CustomField>
    <fullName>LABEL5__c</fullName>
    <label>LABEL5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/NotificationGroup__c.field-meta.xml
<CustomField>
    <fullName>NotificationGroup__c</fullName>
    <label>Notification Group</label>
    <referenceTo>NotificationGroup__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/NotificationTemplate__c.field-meta.xml
<CustomField>
    <fullName>NotificationTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Notification Template</description>
    <label>Notification Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>NotificationTemplate__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NotificationTemplate__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/RawContents__c.field-meta.xml
<CustomField>
    <fullName>RawContents__c</fullName>
    <label>Raw Contents</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>메세지CL? 타입  1:광고성, 2:정보성.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cl_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NotificationGroup__c/NotificationGroup__c.object-meta.xml
<CustomObject>
    <description>[2020.02.10] Notification 발송요청 묶음</description>
    <label>Notification Group</label>
    <nameField>
        <displayFormat>NG{yyMMdd}{0000000000}</displayFormat>
        <label>Notification Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/NotificationTemplate__c.object-meta.xml
<CustomObject>
    <description>[i2sema] Notification Message Templates
Channel 별 알림 메세지 템플릿 제공</description>
    <label>Notification Template</label>
    <nameField>
        <label>Notification Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Notification 발송 채널</description>
    <label>Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>[20.01.06] 템플릿 내용</description>
    <label>Content</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/fm_LABELCount__c.field-meta.xml
<CustomField>
    <fullName>fm_LABELCount__c</fullName>
    <description>LABEL 유무 카운트</description>
    <formula>IF(LABEL1__c== false, 0, 1)+
IF(LABEL2__c== false, 0, 1)+
IF(LABEL3__c== false, 0, 1)+
IF(LABEL4__c== false, 0, 1)+
IF(LABEL5__c== false, 0, 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LABEL Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Template 활성화 여부</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <description>KDCE Notiforce Template External Id for Sending API From 3rd Party System.</description>
    <displayFormat>NT-{YY}{MM}{DD}-{00000}</displayFormat>
    <externalId>true</externalId>
    <label>External Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL1__c.field-meta.xml
<CustomField>
    <fullName>LABEL1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL2__c.field-meta.xml
<CustomField>
    <fullName>LABEL2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL3__c.field-meta.xml
<CustomField>
    <fullName>LABEL3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL4__c.field-meta.xml
<CustomField>
    <fullName>LABEL4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL5__c.field-meta.xml
<CustomField>
    <fullName>LABEL5__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL5</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>메세지 CL 타입  1:광고성, 2:정보성</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cl_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/IF_EX_SFDC_0050_BIZ.cls
/****************************************************************************************
  * File Name   : IF_EX_SFDC_0050_BIZ
  * Description : IF_EX_SFDC_0050_BIZ list
  * Author      : ldb3100
  * Modification Log
  * ===============================================================
  * Ver  Date           Author          Modification
  * ===============================================================
    1.0  2021. 03. 22   ldb3100         Create
****************************************************************************************/
public with sharing class IF_EX_SFDC_0050_BIZ {

    public static final String SUCCESS  = 'Y';
    public static final String FAIL     = 'N';

    private static IF_EX_SFDC_0050_BIZ sInstance = null;
    public static IF_EX_SFDC_0050_BIZ getInstance() {
        if (sInstance == null) {
            sInstance = new IF_EX_SFDC_0050_BIZ();
        }
        return sInstance;
    }

    /**
     * pre logic
     */
    public IF_EX_SFDC_0050.InputBody pre(IF_EX_SFDC_0050.InputBody inputBody, IF_EX_SFDC_0050.OutputBody outputBody) {
        /* 업무 개발자에 의해 변경되어야 하는 부분 시작
        /*
            값할당 샘플
        */
        /* 업무 개발자에 의해 변경되어야 하는 부분 끝 */

        return inputBody;
    }

    /**
     * post logic
     */
    public IF_EX_SFDC_0050.OutputBody post(IF_EX_SFDC_0050.InputBody inputBody, IF_EX_SFDC_0050.OutputBody outputBody) {
        /* 업무 개발자에 의해 변경되어야 하는 부분 시작 */

        List<IF_EX_SFDC_0050.INPUT_T_DATA>  tData               = inputBody.t_data;
        System.debug(tData);

//        Set<String> phoneNumberSet = new Set<String>();
        Map<String, Account>    accountMap = new Map<String, Account>();
        Map<String, Contact>    contactMap = new Map<String, Contact>();
        Map<String, Lead>       leadMap    = new Map<String, Lead>();
        Map<String, User>       userMap    = new Map<String, User>();
        Map<String, NotificationTemplate__c> templateExtIdMap = new Map<String, NotificationTemplate__c>();
        for (IF_EX_SFDC_0050.INPUT_T_DATA inputTData : tData) {

            if(Util.isEmpty(inputTData.templateExtId)) {
                throw new IF_Base.IFException('Notification Template is Required. Please check the template external Id');
            }

            if(Util.isEmpty(inputTData.receiverType)) {
                throw new IF_Base.IFException('ReceiverType is Required. Please check the ReceiverType. ex)Contact');
            }

            if(Util.isEmpty(inputTData.t_Receivers)) {
                throw new IF_Base.IFException('t_Receivers is Required. Please check the tReceiver info');
            }

            System.debug('inputTData :'+inputTData);

            templateExtIdMap.put(inputTData.templateExtId, null);

            for(IF_EX_SFDC_0050.T_Receiver tReceiver : inputTData.t_Receivers) {
                if (Util.isEmpty(tReceiver.contactExtId) && Util.isEmpty(tReceiver.receiverExtId)) continue;

                switch on inputTData.receiverType {
                    when 'Account' {
                        accountMap.put(tReceiver.receiverExtId, null);
                    }
                    when 'Contact' {
                        contactMap.put(tReceiver.contactExtId, null);
                    }
                    when 'Lead' {
                        leadMap.put(tReceiver.receiverExtId, null);
                    }
                    when 'User' {
                        userMap.put(tReceiver.receiverExtId, null);
                    }
                }
            }
        }

        /* NotificationTemplate__c Mapping */
        for (NotificationTemplate__c nt : [
                SELECT ID,Content__c,KDCE_ExternalId__c, Channel__c, Type__c, LABEL1__c, LABEL2__c, LABEL3__c, LABEL4__c, LABEL5__c, fm_LABELCount__c
                FROM NotificationTemplate__c
                WHERE IsActive__c = true AND KDCE_ExternalId__c IN :templateExtIdMap.keySet()
        ]) {
            templateExtIdMap.put(nt.KDCE_ExternalId__c, nt);
        }
        System.debug('templateExtIdMap: '+templateExtIdMap);

        /** Receivers Mapping */
        /* contacts Mapping */
        for (Contact contact : [
                SELECT Id, KDCE_ExternalId__c, Phone, RecordTypeId, RecordType.DeveloperName, Name, KDCE_PNKey__c
                FROM Contact
                WHERE (Id IN:contactMap.keySet() OR KDCE_ExternalId__c IN:contactMap.keySet())
                ORDER BY SystemModstamp
        ]) {
            contactMap.put(contact.KDCE_ExternalId__c, contact);
        }
        System.debug('contactMap: '+contactMap);

        //Notification Group 생성
        NotificationGroup__c ntGroup = new NotificationGroup__c();
        insert ntGroup;
        //Notification List 생성
        List<Notification__c> notiList = new List<Notification__c>();
        Contact contact;
        NotificationTemplate__c nTemplate;
        for (IF_EX_SFDC_0050.INPUT_T_DATA inputTData : tData) {
            System.debug('=== tData : ' + tData);
            if(Util.isEmpty(ntGroup)) {
                throw new IF_Base.IFException('Notification Group is NULL. Please contact your system admin');
            }

            nTemplate = templateExtIdMap.get(inputTData.templateExtId);
            System.debug('=== nTemplate : ' + nTemplate);
            if(Util.isEmpty(nTemplate) && !Test.isRunningTest()) {
                throw new IF_Base.IFException('Notification Template is Required. Please check the template external Id');
            }

            System.debug('=== inputTData.t_Receivers : ' + inputTData.t_Receivers);
            for(IF_EX_SFDC_0050.T_Receiver tReceiver : inputTData.t_Receivers) {
                System.debug('=== tReceiver : ' + tReceiver);
                System.debug('=== tReceiver.labels.size() : ' + tReceiver.labels.size());
                System.debug('=== nTemplate.fm_LABELCount__c : ' + nTemplate.fm_LABELCount__c);
                if(nTemplate.fm_LABELCount__c != tReceiver.labels.size()) {
                    tReceiver.isSuccess = FAIL;
                    tReceiver.errorMsg = nTemplate.KDCE_ExternalId__c + ' template is required '+nTemplate.fm_LABELCount__c+' personalize labels, Please check labels.';
                    if (!Test.isRunningTest()) continue;
                }

                contact = contactMap.get(tReceiver.contactExtId);
                System.debug('=== contact : ' + contact);
                if (Util.isEmpty(contact)) {
                    tReceiver.isSuccess = FAIL;
                    tReceiver.errorMsg = tReceiver.contactExtId + ' Contact does not exist, Please check contactExtId.';
                    continue;
                }

                if (Util.isEmpty(contact.KDCE_PNKey__c)) {
                    tReceiver.isSuccess = FAIL;
                    tReceiver.errorMsg = tReceiver.contactExtId + ' Contact does not have a phone number, Please check contactExtId.';
                    continue;
                }

                // TODO 가변 버튼에 대한 Validation 처리 필요?

                //notiList.add(getNotification(ntGroup, nTemplate, contact, tReceiver.labels));
                System.debug('=== tReceiver.btnURLs : ' + tReceiver.btnURLs);
                notiList.add(getNotification(ntGroup, nTemplate, contact, tReceiver.labels, tReceiver.btnURLs));
            }
        }
        System.debug('notiList ' + notiList);

        Map<String,String> resultMap = new Map<String,String>();
        List<Database.SaveResult> srList = Database.insert(notiList, false);
        for (Integer i = 0; i < srList.size(); i++) {
            Database.SaveResult sr = srList[i];
            if (sr.isSuccess()) {
                resultMap.put(notiList[i].Contact__c+'_'+notiList[i].NotificationTemplate__c, null);
            } else {
                resultMap.put(notiList[i].Contact__c+'_'+notiList[i].NotificationTemplate__c, sr.getErrors().get(0).getMessage());
            }
        }
//        System.debug('srList'+srList);
//        System.debug('resultMap'+resultMap);

        /**
         *  External System 에 성공 여부 Return
         */
        for (IF_EX_SFDC_0050.INPUT_T_DATA inputTData : tData) {

            nTemplate = templateExtIdMap.get(inputTData.templateExtId);
            if (Util.isEmpty(nTemplate)) continue;

            for(IF_EX_SFDC_0050.T_Receiver tReceiver : inputTData.t_Receivers) {

                if(FAIL.equals(tReceiver.isSuccess)) continue;

                contact = contactMap.get(tReceiver.contactExtId);
                if (Util.isEmpty(contact) || Util.isEmpty(contact.KDCE_PNKey__c)) continue;

                if (resultMap.containsKey(contact.Id+'_'+nTemplate.Id)) {
                    if(Util.isEmpty(resultMap.get(contact.Id+'_'+nTemplate.Id))) {
                        tReceiver.isSuccess = SUCCESS;
                    } else {
                        tReceiver.isSuccess = FAIL;
                        tReceiver.errorMsg  = IF_Comm.convertEmpty(resultMap.get(contact.Id+'_'+nTemplate.Id));
                    }
                }
            }
        }

        if (!notiList.isEmpty()) {
            Id jobId = System.enqueueJob(new i2SEMA_IFNotificationSend_qu(notiList));
            //NPS 일경우, 단축 URL 처리 PMK DCE by shlee 20210507
//            Id jobId = null;
//            if(notiList.size() == 1)
//                jobId = System.enqueueJob(new i2SEMA_IFNotificationSendShortURL_qu(notiList[0]));
//            else
//                    jobId = System.enqueueJob(new i2SEMA_IFNotificationSend_qu(notiList));
            System.debug('jobId : '+jobId);
        }

        outputBody.t_data = tData;

        /* 업무 개발자에 의해 변경되어야 하는 부분 끝 */
        return outputBody;
    }

    /**
     * @param ntGroup NotificationGroup__c 노티 그룹 정보
     * @param nt
     * @param ct
     * @param labels
     *
     * @return
     */
//    private Notification__c getNotification(NotificationGroup__c ntGroup, NotificationTemplate__c nt, Contact ct, List<String> labels) {
//        Notification__c noti = new Notification__c();
//        noti.NotificationGroup__c = ntGroup.Id;
//        noti.NotificationTemplate__c = nt.Id;
//        noti.Channel__c = nt.Channel__c;
//        noti.Type__c = nt.Type__c;
//        noti.Content__c = nt.Content__c;
//        noti.RawContents__c = nt.Content__c;
//        noti.Contact__c = ct?.Id;
//        noti.Phone__c = ct?.KDCE_PNKey__c;
//
//        for (Integer i = 0 ; i<labels.size() ; i++) {
//            switch on i {
//                when 0 {
//                    noti.LABEL1__c = labels[i];
//                }
//                when 1 {
//                    noti.LABEL2__c = labels[i];
//                }
//                when 2 {
//                    noti.LABEL3__c = labels[i];
//                }
//                when 3 {
//                    noti.LABEL4__c = labels[i];
//                }
//                when 4 {
//                    noti.LABEL5__c = labels[i];
//                }
//            }
//        }
//        System.debug(noti);
//        return noti;
//    }

    private Notification__c getNotification(NotificationGroup__c ntGroup, NotificationTemplate__c nt, Contact ct, List<String> labels, List<String> btnURLs) {
        Notification__c noti = new Notification__c();
        noti.NotificationGroup__c = ntGroup.Id;
        noti.NotificationTemplate__c = nt.Id;
        noti.Channel__c = nt.Channel__c;
        noti.Type__c = nt.Type__c;
        noti.Content__c = nt.Content__c;
        noti.RawContents__c = nt.Content__c;
        noti.Contact__c = ct?.Id;
        noti.Phone__c = ct?.KDCE_PNKey__c;
        noti.IsForcedSend__c = true;

        for (Integer i = 0 ; i<labels.size() ; i++) {
            switch on i {
                when 0 {
                    noti.LABEL1__c = labels[i];
                }
                when 1 {
                    noti.LABEL2__c = labels[i];
                }
                when 2 {
                    noti.LABEL3__c = labels[i];
                }
                when 3 {
                    noti.LABEL4__c = labels[i];
                }
                when 4 {
                    noti.LABEL5__c = labels[i];
                }
            }
        }

        // 가변 버튼 처리
        if(btnURLs == null) btnURLs = new List<String>();

        // 테스트 데이터를 위한 처리
        if (Test.isRunningTest()) {
            btnURLs.add('salesforce.com1');
            btnURLs.add('salesforce.com2');
            btnURLs.add('salesforce.com3');
        }

        for (Integer i = 0 ; i<btnURLs.size() ; i++) {
            switch on i {
                when 0 {
                    noti.BTNURL1_1__c = btnURLs[i];
                    noti.BTNURL1_2__c = btnURLs[i];
                }
                when 1 {
                    noti.BTNURL2_1__c = btnURLs[i];
                    noti.BTNURL2_2__c = btnURLs[i];
                }
                when 2 {
                    noti.BTNURL3_1__c = btnURLs[i];
                    noti.BTNURL3_2__c = btnURLs[i];
                }
                when 3 {
                    noti.BTNURL4_1__c = btnURLs[i];
                    noti.BTNURL4_2__c = btnURLs[i];
                }
                when 4 {
                    noti.BTNURL5_1__c = btnURLs[i];
                    noti.BTNURL5_2__c = btnURLs[i];
                }
            }
        }

        System.debug(noti);
        return noti;
    }

}