force-app/main/default/objects/TermsandConditions__c/TermsandConditions__c.object-meta.xml
<CustomObject>
    <description>[Korea DCE] As-Is reuse 
Terms and Conditions, that are related to the different markets. Actual Terms and Conditions need to be accepted during Self Registration or at login.</description>
    <label>Terms and Conditions</label>
    <nameField>
        <displayFormat>TaC-{YY}{MM}{DD}{00000}</displayFormat>
        <label>Terms and Conditions Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TermsandConditions__c/fields/KDCE_Active__c.field-meta.xml
<CustomField>
    <fullName>KDCE_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Active Status</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TermsandConditions__c/fields/KDCE_SubGroup__c.field-meta.xml
<CustomField>
    <fullName>KDCE_SubGroup__c</fullName>
    <description>[KDCE] Version 관리하기 위한 값</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>KDCE_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PMTC</fullName>
                <label>[PMTC]이용약관  (필수)</label>
            </value>
            <value>
                <fullName>PMPM</fullName>
                <label>[PMPM]개인정보 수집 및 이용 (필수)</label>
            </value>
            <value>
                <fullName>PMPO</fullName>
                <label>[PMPO]개인정보 수집 및 이용 (선택)</label>
            </value>
            <value>
                <fullName>PMPP</fullName>
                <label>[PMPP]개인정보 처리업무 위탁 동의 (2020년 9월 16일 18시25분 가입자까지 유효)</label>
            </value>
            <value>
                <fullName>PMPT</fullName>
                <label>[PMPT]개인정보 제3자 제공 (선택)</label>
            </value>
            <value>
                <fullName>PMTP</fullName>
                <label>[PMTP]개인정보 국외이전 (선택)</label>
            </value>
            <value>
                <fullName>PMCPE</fullName>
                <label>[PMCPE]휴면회원 전환기간 특례</label>
            </value>
            <value>
                <fullName>globaloptin</fullName>
                <label>[Common]광고성 정보 수신 (통합)</label>
            </value>
            <value>
                <fullName>PMPMG</fullName>
                <label>[Getinfo]개인정보 수집 및 이용 (필수)</label>
            </value>
            <value>
                <fullName>PMPOG</fullName>
                <label>[Getinfo]개인정보 수집 및 이용</label>
            </value>
            <value>
                <fullName>PMPPG</fullName>
                <label>[Getinfo]개인정보 처리 업무 위탁에 대한 동의</label>
            </value>
            <value>
                <fullName>PMPTG</fullName>
                <label>[Getinfo]개인정보 제3자 제공 (선택)</label>
            </value>
            <value>
                <fullName>PMDP</fullName>
                <label>[PMDP]개인정보 수집 및 이용 동의 (필수)</label>
            </value>
            <value>
                <fullName>PMNL</fullName>
                <label>[PMNL]개인정보 수집 및 이용 동의 (선택)</label>
            </value>
            <value>
                <fullName>PMDT</fullName>
                <label>[PMDT]개인정보 국외이전 동의</label>
            </value>
            <value>
                <fullName>PMTR</fullName>
                <label>[PMTR]Rental 이용약관 (필수)</label>
            </value>
            <value>
                <fullName>PMTI</fullName>
                <label>[PMTI]보상판매 이용 약관 (필수)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TermsandConditions__c/fields/KDCE_VersionName__c.field-meta.xml
<CustomField>
    <fullName>KDCE_VersionName__c</fullName>
    <description>[KDCE] Version Name 
고객에게 표시할 버젼이름</description>
    <label>Version Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TermsandConditions__c/fields/KDCE_VersionNumber__c.field-meta.xml
<CustomField>
    <fullName>KDCE_VersionNumber__c</fullName>
    <description>[KDCE]Version Number</description>
    <label>Version Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/KDCE_TermsandConditions_tr.cls
/***********************로*****************************************************************
 * @filename      : KDCE_TermsandConditions_tr
 * @projectname   : PMK Local DCE
 * @author        : i2max_Sukun
 * @date          : 4/5/21 1:05 PM
 * @group         : Service
 * @group-content :
 * @description   : Terms and Conditions Trigger Business Logic Class
 * @tester        :
 * @reference     :
 * @copyright     : Copyright © I2max. All Rights Reserved.
 * @modification Log
 * ===============================================================
 * ver     date                     author              description
 * ===============================================================
 0.1     4/5/21 1:05 PM            i2max_Sukun           Create
 ****************************************************************************************/
public with sharing class KDCE_TermsandConditions_tr extends TriggerHandler {

    public override void beforeInsert() {
        forceSetToNextVersionNumber();
    }

    public override void beforeUpdate() {
//        Make sure there's no newer version of the TNC Master();
    }

    private void forceSetToNextVersionNumber() {
        Map<String, Decimal> versionMap = new Map<String, Decimal>();

        for (TermsandConditions__c tnc : (List<TermsandConditions__c>) Trigger.new) {
            System.debug('=== tnc : ' + tnc);
            versionMap.put(tnc.KDCE_SubGroup__c, tnc.KDCE_VersionNumber__c);
        }

        List<TermsandConditions__c> termsandConditions = [
                SELECT KDCE_VersionName__c, KDCE_VersionNumber__c, KDCE_SubGroup__c FROM TermsandConditions__c
                WHERE KDCE_SubGroup__c IN :versionMap.keyset()
                AND KDCE_Active__c = TRUE
                ORDER BY KDCE_VersionNumber__c DESC
        ];

        if(termsandConditions.size() > 0) {
            for (TermsandConditions__c retrievedTnc : termsandConditions) {
                versionMap.put(retrievedTnc.KDCE_SubGroup__c, retrievedTnc.KDCE_VersionNumber__c + 1);  // SubGroup마다 가장 높은 버전이 최종적으로 Key에 대한 Value 값으 들어갈 것
            }
        }

        String tempType;
        for (TermsandConditions__c tncNewSetting : (List<TermsandConditions__c>) Trigger.new) {
            System.debug('=== tempType : ' + tempType);
            System.debug('=== tncNewSetting : ' + tncNewSetting);
            if(tempType != tncNewSetting.KDCE_SubGroup__c) {
                tempType = tncNewSetting.KDCE_SubGroup__c;
            } else {
                System.debug('=== 여기탄다 ');
                // custom validation error - trigger new에 같은 타입에 대한 여러개 레코드가 존재할 경우
                // 해당 레코드들에 대하여는 에러처리
                tncNewSetting.addError(System.Label.KDCE_InvalidCreateMultipleRecordSameType);
            }
            tncNewSetting.KDCE_VersionNumber__c = versionMap.get(tempType);
            tncNewSetting.KDCE_VersionName__c = String.valueOf(versionMap.get(tempType));
        }
    }
}