force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/ChannelDetails__c.field-meta.xml
<CustomField>
    <fullName>ChannelDetails__c</fullName>
    <description>[KDCE] CVS Channel</description>
    <label>CVS Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CU</fullName>
                <label>CU 편의점</label>
            </value>
            <value>
                <fullName>GS</fullName>
                <label>GS25 편의점</label>
            </value>
            <value>
                <fullName>MS</fullName>
                <label>미니스톱 편의점</label>
            </value>
            <value>
                <fullName>K7</fullName>
                <label>세븐일레븐 편의점</label>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>씨스페이스 편의점</label>
            </value>
            <value>
                <fullName>EM</fullName>
                <label>이마트24(위드미) 편의점</label>
            </value>
            <value>
                <fullName>SS</fullName>
                <label>일반 소매점</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <description>[KDCE] Coupon Expiry Date</description>
    <label>Coupon Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/IssuableDate__c.field-meta.xml
<CustomField>
    <fullName>IssuableDate__c</fullName>
    <label>Coupon Issuable Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>[KDCE] Coupon Type</description>
    <label>Coupon Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MGM</fullName>
            </value>
            <value>
                <fullName>CVS</fullName>
                <label>Special Purchase Code</label>
            </value>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Tradein</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_CVS.recordType-meta.xml
<RecordType>
    <fullName>Coupon_CVS</fullName>
    <active>true</active>
    <description>[KDCE] KA, GT</description>
    <label>Special Purchase Code</label>
</RecordType>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_GetInfo.recordType-meta.xml
<RecordType>
    <fullName>Coupon_GetInfo</fullName>
    <active>true</active>
    <description>[KDCE] GetInfo</description>
    <label>GetInfo</label>
</RecordType>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_MGM.recordType-meta.xml
<RecordType>
    <fullName>Coupon_MGM</fullName>
    <active>true</active>
    <description>[KDCE] MGM</description>
    <label>MGM</label>
</RecordType>

force-app/main/default/objects/KDCE_CouponHistory__c/KDCE_CouponHistory__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Coupon Journey</description>
    <label>Coupon Journey</label>
    <nameField>
        <displayFormat>CH-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Journeys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupon Journeys</relationshipLabel>
    <relationshipName>CouponHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/KDCE_Coupon_tr_Test.cls
/****************************************************************************************
  * @filename      : KDCE_Coupon_tr_Test
  * @projectname   : PMK LocalDCE QA
  * @author        : i2max_JE Yoon
  * @date          : 2021-04-01
  * @group         :
  * @description   :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                author              description
  * ===============================================================
    0.1  2021-04-01          i2max_JE Yoon             Create
****************************************************************************************/
@IsTest
private class KDCE_Coupon_tr_Test {

    static KDCE_Coupon__c coupon;
    static KDCE_CouponHistory__c couponHistory;
    static Contact contact;
    static String developerName_Coupon_MGM = 'Coupon_MGM';
    static String developerName_Coupon_CVS = 'Coupon_CVS';
    static String developerName_Coupon_GetInfo = 'Coupon_GetInfo';
    static String couponStatus_Produce = 'Produce';
    static String couponStatus_Issue = 'Issue';
    static Decimal amount_Coupon_MGM = 25000;
    static Decimal amount_Coupon_CVS = 31000;
    static Decimal amount_Coupon_GetInfo = 10000;
    static Map<String, Id> rtMap_Coupon = KDCE_Util.getRecordTypeBySObject('KDCE_Coupon__c');


    @IsTest
    static void testCase01() {
        Contact contact = KDCE_TestUtil.contactMember;
        String recordTypeId_Coupon_CVS = rtMap_Coupon.get('Coupon_CVS');

        // Coupon 생성
        KDCE_Coupon__c newCoupon = new KDCE_Coupon__c(
                Name = 'coupon Name',
                Contact__c = contact.Id,
                Status__c = 'Issue',
                Type__c = 'CVS',
                RecordTypeId = recordTypeId_Coupon_CVS,
                ChannelDetails__c = 'CU',
                ExpiryDate__c = Date.today().addMonths(6),
                IssuableDate__c = Date.today().addMonths(5)
        );
        insert newCoupon;
        System.debug('=== 1 newCoupon : ' + newCoupon);

        newCoupon.Status__c = 'Use';
        update newCoupon;
        System.debug('=== 2 newCoupon : ' + newCoupon);

        newCoupon.Status__c = 'Issue';
        System.debug('=== 3 newCoupon : ' + newCoupon);
        update newCoupon;
    }

    @IsTest
    static void testCase02() {
        KDCE_Coupon__c newCoupon = new KDCE_Coupon__c(
                Name = 'coupon Name',
                Contact__c = null,
                Status__c = 'Produce',
                Type__c = 'CVS',
                ChannelDetails__c = 'CU',
                ExpiryDate__c = Date.today().addMonths(6),
                IssuableDate__c = Date.today().addMonths(5)
        );
        insert newCoupon;

        newCoupon.Contact__c = KDCE_TestUtil.contactMember.Id;
        newCoupon.Status__c = 'Issue';
        update newCoupon;
    }


}