force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>[KDCE] Coupon Type</description>
    <label>Coupon Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MGM</fullName>
            </value>
            <value>
                <fullName>CVS</fullName>
                <label>Special Purchase Code</label>
            </value>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Tradein</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/KDCE_CouponHistory__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Coupon Journey</description>
    <label>Coupon Journey</label>
    <nameField>
        <displayFormat>CH-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Journeys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/ActionChannel__c.field-meta.xml
<CustomField>
    <fullName>ActionChannel__c</fullName>
    <description>[KDCE] History Action Channel : Online / Offline / Call Center</description>
    <label>Action Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <description>[KDCE] Coupon Action Type</description>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupon Journeys</relationshipLabel>
    <relationshipName>CouponHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <label>Coupon</label>
    <referenceTo>KDCE_Coupon__c</referenceTo>
    <relationshipLabel>Coupon Journeys</relationshipLabel>
    <relationshipName>CouponHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>KDCE_Order__c</referenceTo>
    <relationshipName>CouponHistory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/KDCE_Order__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Order</description>
    <label>Order</label>
    <nameField>
        <displayFormat>KO{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/fields/ActionChannel__c.field-meta.xml
<CustomField>
    <fullName>ActionChannel__c</fullName>
    <description>Order Action Channel</description>
    <label>Action Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>iqos.com</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <description>Order Action Type</description>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applied Coupon</description>
    <inlineHelpText>Applied Coupon</inlineHelpText>
    <label>Coupon</label>
    <referenceTo>KDCE_Coupon__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/isTargetPurchaseDateUpdate__c.field-meta.xml
<CustomField>
    <fullName>isTargetPurchaseDateUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Order Insert 시, Purchase Date 업데이트를 하기 위한 필드</description>
    <label>isTargetPurchaseDateUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderReason__c.field-meta.xml
<CustomField>
    <fullName>OrderReason__c</fullName>
    <description>주문 사유
forward: 주문
return: 반품
collect: 반납
rental forward: 렌탈 후 구매주문
rental return: 렌탈 후 구매주문 반품</description>
    <inlineHelpText>주문 사유</inlineHelpText>
    <label>Order Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>forward</fullName>
            </value>
            <value>
                <fullName>return</fullName>
            </value>
            <value>
                <fullName>collect</fullName>
                <label>Collect</label>
            </value>
            <value>
                <fullName>rental forward</fullName>
            </value>
            <value>
                <fullName>rental return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>[KDCE] 주문 상태
Mapping Column : order_status</description>
    <inlineHelpText>주문 상태</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>processing</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>ready_for_delivery</fullName>
            </value>
            <value>
                <fullName>picking</fullName>
            </value>
            <value>
                <fullName>delivery_collection</fullName>
            </value>
            <value>
                <fullName>complete_delivery</fullName>
            </value>
            <value>
                <fullName>closed</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>cancel</fullName>
            </value>
            <value>
                <fullName>cancel_order</fullName>
            </value>
            <value>
                <fullName>return_received</fullName>
            </value>
            <value>
                <fullName>reject</fullName>
            </value>
            <value>
                <fullName>authorized</fullName>
            </value>
            <value>
                <fullName>approved</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>renting</fullName>
            </value>
            <value>
                <fullName>complete</fullName>
                <label>Complete</label>
            </value>
            <value>
                <fullName>paid</fullName>
            </value>
            <value>
                <fullName>received</fullName>
            </value>
            <value>
                <fullName>processed_closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <description>[KDCE] 주문타입
ZTA(일반주문)
ZTI(보상판매)
ZRN(렌탈 중고)
ZRNNEW(렌탈 신규)
ZRA(QURE)</description>
    <inlineHelpText>주문타입</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZTA</fullName>
            </value>
            <value>
                <fullName>ZTI</fullName>
            </value>
            <value>
                <fullName>ZRN</fullName>
            </value>
            <value>
                <fullName>ZRNNEW</fullName>
            </value>
            <value>
                <fullName>ZRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OriginOrder__c.field-meta.xml
<CustomField>
    <fullName>OriginOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original Order (반품/취소의 경우)</description>
    <inlineHelpText>Original Order (반품/취소의 경우)</inlineHelpText>
    <label>Original Order</label>
    <referenceTo>KDCE_Order__c</referenceTo>
    <relationshipLabel>Sub Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/KDCE_Order_tr_Test.cls
/****************************************************************************************
  * @filename      : KDCE_Order_tr_Test
  * @projectname   : PMK LocalDCE QA
  * @author        : i2max_JE Yoon
  * @date          : 2021-04-01
  * @group         :
  * @description   :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                author              description
  * ===============================================================
    0.1  2021-04-01          i2max_JE Yoon             Create
****************************************************************************************/
@IsTest
private class KDCE_Order_tr_Test {

    //final static String CANCEL_STATUS = '주문취소'; //todo OrderStatus__c 주문 취소 값 정해지면 수정 필요
    final static String CANCEL_STATUS = KDCE_GlobalValue.ORDER_STATUS_CLOSE; //todo OrderStatus__c 주문 취소 값 정해지면 수정 필요
    static KDCE_Order__c order;
    static List<KDCE_CouponHistory__c> couponHistories;
    static KDCE_CouponHistory__c couponHistory;
    static List<Task> tasks;
    static String actionType_Cancel = 'Cancel';

    static void getData(String coupon_DeveloperName, Boolean couponExists) {
        CouponTestDataUtil.getOrder(coupon_DeveloperName, couponExists);
        KDCE_Coupon__c coupon = CouponTestDataUtil.coupon.clone(true);
        order = [SELECT OrderStatus__c FROM KDCE_Order__c LIMIT 1];
        order.OrderStatus__c = CANCEL_STATUS;
        order.Coupon__c = coupon.Id;

        update order;
        System.debug('Order : ' + order);

        order = [SELECT OrderStatus__c, Coupon__c FROM KDCE_Order__c LIMIT 1];
        couponHistories = [SELECT ActionType__c, Order__c FROM KDCE_CouponHistory__c WHERE Coupon__c = :order.Coupon__c AND ActionType__c = :actionType_Cancel LIMIT 1];
//        if (couponExists == true) couponHistory = couponHistories[0];
        tasks = [SELECT Id FROM Task];

    }


    static private void createOrderSet(String orderStatus, String orderReason, String orderType, String couponType) {
        KDCE_Order__c tempOrder = new KDCE_Order__c(
                OrderStatus__c = KDCE_GlobalValue.ORDER_STATUS_COMPLETE_DELIVERY,
                Contact__c = KDCE_TestUtil.contactMember.Id
        );
        KDCE_Coupon__c coupon = new KDCE_Coupon__c( Type__c = couponType);
        List<SObject> sObjects = new List<SObject>{coupon, tempOrder};
        insert sObjects;

        tempOrder.OrderStatus__c = orderStatus;
        tempOrder.OrderReason__c = orderReason;
        tempOrder.OrderType__c = orderType;
        tempOrder.Coupon__c = coupon.Id;
        tempOrder.ActionChannel__c = 'POS';
        tempOrder.isTargetPurchaseDateUpdate__c = true;
        update tempOrder;
    }

    static private void createOrderSet1(String orderStatus, String orderReason, String orderType, String couponType) {
        KDCE_Order__c tempOrder = new KDCE_Order__c(
                OrderStatus__c = KDCE_GlobalValue.ORDER_STATUS_CLOSE,
                Contact__c = KDCE_TestUtil.contactMember.Id
        );
        insert tempOrder;

        tempOrder.OrderStatus__c = 'complete';
        tempOrder.OrderReason__c = 'forward';
        tempOrder.OrderType__c = 'ZTA';
        tempOrder.ActionChannel__c = 'iqos.com';
        tempOrder.isTargetPurchaseDateUpdate__c = true;
        update tempOrder;
    }

    @IsTest
    static void testCase07() {
        Test.startTest();
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_CLOSE, KDCE_GlobalValue.ORDER_REASON_FORWARD, KDCE_GlobalValue.ORDER_TYPE_NORMAL, KDCE_GlobalValue.COUPON_TYPE_MGM);
        Test.stopTest();
    }

    @IsTest
    static void testCase08() {
        Test.startTest();
        createOrderSet(KDCE_GlobalValue.ORDER_STATUS_CLOSE, KDCE_GlobalValue.ORDER_REASON_FORWARD, KDCE_GlobalValue.ORDER_TYPE_NORMAL, KDCE_GlobalValue.COUPON_TYPE_GETINFO);
        createOrderSet1(KDCE_GlobalValue.ORDER_STATUS_COMPLETE_DELIVERY, KDCE_GlobalValue.ORDER_REASON_FORWARD, KDCE_GlobalValue.ORDER_TYPE_NORMAL, KDCE_GlobalValue.COUPON_TYPE_GETINFO);

        Test.stopTest();
    }

    @IsTest
    static void testUpdateToRefundOrder() {
        KDCE_Order__c order = KDCE_TestBizUtil.order;
        KDCE_Order__c order2 = KDCE_TestBizUtil.order.clone(false);
        order2.OrderReason__c = 'return';
        order2.OriginOrder__c = order.Id;
        insert order2;

        Test.startTest();


        Test.stopTest();
    }
}