force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>[KDCE] Coupon Type</description>
    <label>Coupon Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MGM</fullName>
            </value>
            <value>
                <fullName>CVS</fullName>
                <label>Special Purchase Code</label>
            </value>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Tradein</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_CVS.recordType-meta.xml
<RecordType>
    <fullName>Coupon_CVS</fullName>
    <active>true</active>
    <description>[KDCE] KA, GT</description>
    <label>Special Purchase Code</label>
</RecordType>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_GetInfo.recordType-meta.xml
<RecordType>
    <fullName>Coupon_GetInfo</fullName>
    <active>true</active>
    <description>[KDCE] GetInfo</description>
    <label>GetInfo</label>
</RecordType>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_MGM.recordType-meta.xml
<RecordType>
    <fullName>Coupon_MGM</fullName>
    <active>true</active>
    <description>[KDCE] MGM</description>
    <label>MGM</label>
</RecordType>

force-app/main/default/objects/KDCE_CouponHistory__c/KDCE_CouponHistory__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Coupon Journey</description>
    <label>Coupon Journey</label>
    <nameField>
        <displayFormat>CH-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Journeys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <label>Coupon</label>
    <referenceTo>KDCE_Coupon__c</referenceTo>
    <relationshipLabel>Coupon Journeys</relationshipLabel>
    <relationshipName>CouponHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/KDCE_CouponHistory_tr.cls
/****************************************************************************************
  * @filename      : KDCE_CouponHistory_tr
  * @projectname   : PMK LocalDCE QA
  * @author        : i2max_JE Yoon
  * @date          : 2021-03-05
  * @group         :
  * @description   :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                author              description
  * ===============================================================
    0.1  2021-03-05          i2max_JE Yoon             Create
****************************************************************************************/
public without sharing class KDCE_CouponHistory_tr extends TriggerHandler {

    private final static Id RT_Coupon_CVSId             = Schema.SObjectType.KDCE_Coupon__c.getRecordTypeInfosByDeveloperName().get('Coupon_CVS').getRecordTypeId();    // 쿠폰 : 편의점
    private final static Id RT_Coupon_GetInfo           = Schema.SObjectType.KDCE_Coupon__c.getRecordTypeInfosByDeveloperName().get('Coupon_GetInfo').getRecordTypeId();// 쿠폰 : Getinfo
    private final static Id RT_Coupon_MGM               = Schema.SObjectType.KDCE_Coupon__c.getRecordTypeInfosByDeveloperName().get('Coupon_MGM').getRecordTypeId();    // 쿠폰 : MGM

    public override void afterInsert() {
        this.updateContactMGMUseCount();
    }

    public override void afterUpdate(){
    }


    /**
     * @description MGM 쿠폰 사용/사용취소 히스토리 생성 시 MGM 쿠폰이 발급된 Contact의 KDCE_MGMUseCount__c 값 업데이트
     * @author JE Yoon
     **/
    private void updateContactMGMUseCount() {
        System.debug('@@@@@@ updateContactMGMUseCount @@@@@@');
        List<KDCE_CouponHistory__c> couponHistories = new List<KDCE_CouponHistory__c>();
        Map<KDCE_CouponHistory__c, Id> historyByCouponMap = new Map<KDCE_CouponHistory__c, Id>();
        for (KDCE_CouponHistory__c history : (List<KDCE_CouponHistory__c>) Trigger.new) {
            historyByCouponMap.put(history, history.Coupon__c);
        }
        Set<Id> mgmCoupons = new Set<Id>();
        for (KDCE_Coupon__c coupon : [SELECT Id FROM KDCE_Coupon__c WHERE Id IN :historyByCouponMap.values() AND Type__c = 'MGM']) {
            mgmCoupons.add(coupon.Id);
        }
        for (KDCE_CouponHistory__c history : (List<KDCE_CouponHistory__c>) Trigger.new) {
            if (mgmCoupons.contains(history.Coupon__c)) couponHistories.add(history);
        }
        KDCE_CouponService.updateContactMGMUseCount(couponHistories);
    }

}