force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/CouponCode__c.field-meta.xml
<CustomField>
    <fullName>CouponCode__c</fullName>
    <description>[KDCE] Coupon Code</description>
    <externalId>true</externalId>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/ExternalType__c.field-meta.xml
<CustomField>
    <fullName>ExternalType__c</fullName>
    <description>데이터가 너무 많아 쿼리를 하기 위한 External Field (MGM 발급에서 사용)</description>
    <externalId>true</externalId>
    <label>ExternalType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>[KDCE] Coupon Type</description>
    <label>Coupon Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MGM</fullName>
            </value>
            <value>
                <fullName>CVS</fullName>
                <label>Special Purchase Code</label>
            </value>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Tradein</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_IssuableCouponCount_ba_ts.cls
/****************************************************************************************
  * @filename      : 
  * @projectname   : 
  * @author        : i2max_Junseok.Kwon
  * @date          : 2021-08-12 오후 7:17
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-08-12 오후 7:17     i2max_Junseok.Kwon        Create
****************************************************************************************/

@IsTest
private class KDCE_IssuableCouponCount_ba_ts {

    @TestSetup
    static void setDate(){

        List<KDCE_Coupon__c> couponList = new List<KDCE_Coupon__c>();

        KDCE_Coupon__c issuable = new KDCE_Coupon__c();
        issuable.CouponCode__c = 'Issuable_Coupon';
        issuable.Type__c = 'MGM';
        issuable.ExternalType__c = 'MGM';
        issuable.Status__c = 'Produce';
        couponList.add(issuable);

        KDCE_Coupon__c pending = new KDCE_Coupon__c();
        pending.CouponCode__c = 'Pending_Coupon';
        pending.Type__c = 'MGM';
        pending.Status__c = 'Produce';
        couponList.add(pending);

        insert couponList;
    }

    @IsTest
    static void testBehavior() {
        KDCE_IssuableCouponCount_ba batch = new KDCE_IssuableCouponCount_ba();
        batch.couponType = 'MGM';
        Database.executeBatch(batch, 2000);
    }

}