force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/ChannelDetails__c.field-meta.xml
<CustomField>
    <fullName>ChannelDetails__c</fullName>
    <description>[KDCE] CVS Channel</description>
    <label>CVS Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CU</fullName>
                <label>CU 편의점</label>
            </value>
            <value>
                <fullName>GS</fullName>
                <label>GS25 편의점</label>
            </value>
            <value>
                <fullName>MS</fullName>
                <label>미니스톱 편의점</label>
            </value>
            <value>
                <fullName>K7</fullName>
                <label>세븐일레븐 편의점</label>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>씨스페이스 편의점</label>
            </value>
            <value>
                <fullName>EM</fullName>
                <label>이마트24(위드미) 편의점</label>
            </value>
            <value>
                <fullName>SS</fullName>
                <label>일반 소매점</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/CouponCode__c.field-meta.xml
<CustomField>
    <fullName>CouponCode__c</fullName>
    <description>[KDCE] Coupon Code</description>
    <externalId>true</externalId>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <description>[KDCE] Coupon Expiry Date</description>
    <label>Coupon Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>[KDCE] Coupon Type</description>
    <label>Coupon Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MGM</fullName>
            </value>
            <value>
                <fullName>CVS</fullName>
                <label>Special Purchase Code</label>
            </value>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Tradein</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_MGM.recordType-meta.xml
<RecordType>
    <fullName>Coupon_MGM</fullName>
    <active>true</active>
    <description>[KDCE] MGM</description>
    <label>MGM</label>
</RecordType>

force-app/main/default/objects/NotificationTemplate__c/NotificationTemplate__c.object-meta.xml
<CustomObject>
    <description>[i2sema] Notification Message Templates
Channel 별 알림 메세지 템플릿 제공</description>
    <label>Notification Template</label>
    <nameField>
        <label>Notification Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>[20.01.06] 템플릿 내용</description>
    <label>Content</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL2__c.field-meta.xml
<CustomField>
    <fullName>LABEL2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL3__c.field-meta.xml
<CustomField>
    <fullName>LABEL3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL4__c.field-meta.xml
<CustomField>
    <fullName>LABEL4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Template 타이틀</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>메세지 CL 타입  1:광고성, 2:정보성</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cl_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_CouponResendQa_ts.cls
/****************************************************************************************
 * @filename      : KDCE_CouponResendQa_ts
 * @projectname   : PMK Local DCE
 * @author        : i2max_ehlee 
 * @date          : 2021-05-03 오후 1:01
 * @group         : Service 
 * @group-content :
 * @description   : 
 * @tester        :
 * @reference     :
 * @copyright     : Copyright © I2max. All Rights Reserved.
 * @modification Log
 * ===============================================================
 * ver     date                     author              description
 * ===============================================================
 0.1     2021-05-03 오후 1:01      i2max_ehlee          Create
 ****************************************************************************************/

@IsTest
public with sharing class KDCE_CouponResendQa_ts {
    @TestSetup
    static void setData(){
        NotificationTemplate__c notificationTemplate = i2SEMA_TestDataUtil.getMMSTemplate();
        notificationTemplate.Title__c = '1.GetInfo Test';
        update notificationTemplate;

        NotificationTemplate__c n1 =notificationTemplate.clone(false);
        n1.LABEL2__c = false;
        n1.LABEL3__c = false;
        n1.Title__c = '2.MGM Test';

        NotificationTemplate__c n2 =notificationTemplate.clone(false);
        n2.LABEL2__c = true;
        n2.LABEL3__c = true;
        n2.LABEL4__c = true;
        n2.Title__c = '3.CVS Test';
        n2.Content__c = '%%LABEL1%% %%LABEL2%% %%LABEL3%% %%LABEL4%%';

        List<NotificationTemplate__c> notificationTemplates = new List<NotificationTemplate__c>();
        notificationTemplates.add(n1);
        notificationTemplates.add(n2);
        insert notificationTemplates;

        System.debug('notification template: '+notificationTemplate);
    }
    static {
    }

    static testMethod void couponResendTest(){
        Test.startTest();

//        KDCE_Coupon__c resendingCoupon = [SELECT Id FROM KDCE_Coupon__c WHERE RecordTypeId =: KDCE_TestUtil.getRecordTypeId('KDCE_Coupon__c', 'Coupon_MGM') LIMIT 1];
        KDCE_Coupon__c resendingCoupon = KDCE_TestBizUtil.coupon.clone(true);
        resendingCoupon.Type__c = 'GetInfo';
        resendingCoupon.Contact__c = KDCE_TestUtil.contactMember.Id;
        resendingCoupon.CouponCode__c = 'GetInfo_couponCodeTest00';
        update resendingCoupon;

        KDCE_TestUtil.contactMember.KDCE_MarketingOptInDate__c = System.today();
        update KDCE_TestUtil.contactMember;

        KDCE_Coupon__c resendingCoupon2 = resendingCoupon.clone(false);
        resendingCoupon2.Type__c = 'MGM';
        resendingCoupon2.CouponCode__c = 'MGM_couponCodeTest01';
        insert resendingCoupon2;

        KDCE_Coupon__c resendingCoupon3 = resendingCoupon.clone(false);
        resendingCoupon3.Type__c = 'CVS';
        resendingCoupon3.CouponCode__c = 'CVS_couponCodeTest01';
        resendingCoupon3.ChannelDetails__c = 'CU';
        resendingCoupon3.ExpiryDate__c = System.today();
        insert resendingCoupon3;

        System.debug(resendingCoupon);
        System.debug(resendingCoupon2);
        System.debug(resendingCoupon3);

        List<NotificationTemplate__c> notificationTemplate = [SELECT Id FROM NotificationTemplate__c ORDER BY Title__c];
        system.debug('=== notificationTemplate : ' + notificationTemplate);

        KDCE_CouponResendQa.RequestData testClass = new KDCE_CouponResendQa.RequestData();
//        KDCE_CouponResendQa.testNotificationTemplateId = notificationTemplate.Id;
        testClass.templateId = notificationTemplate[0].Id;
        KDCE_CouponResendQa.init(resendingCoupon.Id);
        KDCE_CouponResendQa.save(resendingCoupon.Id, testClass);

        testClass.templateId = notificationTemplate[1].Id;
        KDCE_CouponResendQa.init(resendingCoupon2.Id);
        KDCE_CouponResendQa.save(resendingCoupon2.Id, testClass);

        testClass.templateId = notificationTemplate[2].Id;
        KDCE_CouponResendQa.init(resendingCoupon3.Id);
        KDCE_CouponResendQa.save(resendingCoupon3.Id, testClass);

        Test.stopTest();
    }

//    public static boolean updateCustomLabel(string csname,string description,string language,string value, boolean isProtected){
//        List<Metadata> allMetadataList = new List<Metadata>();
//        Metadata.CustomMetadataValue
//        MetadataService.MetadataPort service = createService();
//        MetadataService.CustomLabel csLabel = new MetadataService.CustomLabel();
//        csLabel.fullName = csname;
//        csLabel.language = language;
//        csLabel.protected_x  = isProtected;
//        csLabel.shortDescription  = description;
//        csLabel.value=value;
//        allMetadataList.add(csLabel);
//        List<MetadataService.SaveResult> results = service.updateMetadata(allMetadataList);
//        for(MetadataService.SaveResult result: results){
//            system.debug('update custom label results success='+result.success);
//        }
//        return results[0].success;
//    }
}