force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/ChannelDetails__c.field-meta.xml
<CustomField>
    <fullName>ChannelDetails__c</fullName>
    <description>[KDCE] CVS Channel</description>
    <label>CVS Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CU</fullName>
                <label>CU 편의점</label>
            </value>
            <value>
                <fullName>GS</fullName>
                <label>GS25 편의점</label>
            </value>
            <value>
                <fullName>MS</fullName>
                <label>미니스톱 편의점</label>
            </value>
            <value>
                <fullName>K7</fullName>
                <label>세븐일레븐 편의점</label>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>씨스페이스 편의점</label>
            </value>
            <value>
                <fullName>EM</fullName>
                <label>이마트24(위드미) 편의점</label>
            </value>
            <value>
                <fullName>SS</fullName>
                <label>일반 소매점</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/ExternalType__c.field-meta.xml
<CustomField>
    <fullName>ExternalType__c</fullName>
    <description>데이터가 너무 많아 쿼리를 하기 위한 External Field (MGM 발급에서 사용)</description>
    <externalId>true</externalId>
    <label>ExternalType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/IssuableDate__c.field-meta.xml
<CustomField>
    <fullName>IssuableDate__c</fullName>
    <label>Coupon Issuable Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>[KDCE] Coupon Type</description>
    <label>Coupon Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MGM</fullName>
            </value>
            <value>
                <fullName>CVS</fullName>
                <label>Special Purchase Code</label>
            </value>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Tradein</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_IssuableCouponSet_ba.cls
/****************************************************************************************
  * @filename      : 
  * @projectname   : 
  * @author        : i2max_Junseok.Kwon
  * @date          : 2021-08-10 오후 10:24
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-08-10 오후 10:24     i2max_Junseok.Kwon        Create
****************************************************************************************/

global without sharing class KDCE_IssuableCouponSet_ba implements Database.Batchable<SObject>, Database.Stateful {

    global Integer changeCount;
    global String couponType;
    global String cvsChannel;

    public Database.QueryLocator start(Database.BatchableContext BC) {

        System.debug('=== KDCE_IssuableCouponSet_ba start ===');

        String query = '';
        query += ' SELECT Id FROM KDCE_Coupon__c ';
        query += ' WHERE Status__c = \'Produce\' ';
        query += ' AND Type__c = :couponType ';
        query += ' AND ExternalType__c != :couponType ';
        // CVS 쿠폰은 채널별로 처리
        if(cvsChannel != null && cvsChannel != ''){
            query += ' AND ChannelDetails__c = :cvsChannel ';
            query += ' AND IssuableDate__c > TODAY ORDER BY IssuableDate__c DESC ';
        }
        if(!Test.isRunningTest()) query += ' LIMIT :changeCount ';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<KDCE_Coupon__c> scope) {

        System.debug('=== KDCE_IssuableCouponSet_ba execute ===');

        for(KDCE_Coupon__c row : scope){
            row.ExternalType__c = couponType;
        }
        update scope;
    }

    public void finish(Database.BatchableContext BC) {

        System.debug('=== KDCE_IssuableCouponSet_ba finish ===');

    }

}