force-app/main/default/objects/Kakao_Consult_Chat__c/Kakao_Consult_Chat__c.object-meta.xml
<CustomObject>
    <label>Kakao Consult Chat</label>
    <nameField>
        <displayFormat>KCC-{0000000000}</displayFormat>
        <label>Kakao Consult Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Consult Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Kakao Consult Chat</relationshipLabel>
    <relationshipName>Kakao_Consult_Chat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <externalId>true</externalId>
    <label>User Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KakaoConsultCustomerIdentify_Test.cls
/**
 * @description       : Test class for customer identify logic
 * @author            : Obidjon
 * @group             : Kakao Consult Chat
 * @last modified on  : 04-23-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   04-23-2021   Obidjon   Initial Version
 **/
@isTest
private class KakaoConsultCustomerIdentify_Test {
    @testSetup
    private static void testSetup() {
        Case kakaoCase = new Case();
        kakaoCase.Subject = 'Test Case';
        insert kakaoCase;

        Kakao_Consult_Chat__c consultChat = new Kakao_Consult_Chat__c();
        consultChat.Case__c = kakaoCase.Id;
        consultChat.User_Key__c = 'testuserkey';
        insert consultChat;
    }

    @isTest
    private static void testDoPostCustomerInformation() {
        Case kakaoCase = [SELECT Id FROM Case LIMIT 1];
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        String bodyString = '{';
        bodyString += '"cid":"' + kakaoCase.Id + '",';
        bodyString += '"firstName":"First",';
        bodyString += '"lastName":"Last",';
        bodyString += '"phone":"01012341234",';
        bodyString += '"email":"email@mail.com",';
        bodyString += '"payload":"payload"';
        bodyString += '}';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(bodyString);
        Test.startTest();
        RestContext.request = request;
        RestContext.response = response;
        KakaoConsultCustomerIdentify.doPostCustomerInformation();
        System.assertEquals(200, response.statusCode, 'Failed status from doPostCustomerInformation');
        Test.stopTest();
    }
}