force-app/main/default/objects/Kakao_Consult_Chat__c/Kakao_Consult_Chat__c.object-meta.xml
<CustomObject>
    <label>Kakao Consult Chat</label>
    <nameField>
        <displayFormat>KCC-{0000000000}</displayFormat>
        <label>Kakao Consult Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Consult Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Kakao Consult Chat</relationshipLabel>
    <relationshipName>Kakao_Consult_Chat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Session_Live__c.field-meta.xml
<CustomField>
    <fullName>Session_Live__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Session Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <externalId>true</externalId>
    <label>User Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/KakaoConsultDealerCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Kakao Consult Dealer Credentials</label>
</CustomObject>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Channel_Secret__c.field-meta.xml
<CustomField>
    <fullName>Channel_Secret__c</fullName>
    <label>Channel Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Customer_Identify_Url__c.field-meta.xml
<CustomField>
    <fullName>Customer_Identify_Url__c</fullName>
    <label>Customer Identify Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/JWT_Token__c.field-meta.xml
<CustomField>
    <fullName>JWT_Token__c</fullName>
    <label>JWT Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Sender_Key__c.field-meta.xml
<CustomField>
    <fullName>Sender_Key__c</fullName>
    <label>Sender Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/InboundExpiredSessionRestService_Test.cls
/**
 * @description       :
 * @author            : Obidjon
 * @group             :
 * @last modified on  : 06-13-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   04-23-2021   Obidjon   Initial Version
 **/
@isTest
private class InboundExpiredSessionRestService_Test {
    @testSetup
    private static void testSetup() {
        User standardUser = KakaoTestUtils.createUser('Standard User');
        KakaoTestUtils.assignPermissionSet('KakaoConsult_User', standardUser.Id);

        System.runAs(standardUser) {
            KakaoConsultDealerCredentials__c dealerCredentials = new KakaoConsultDealerCredentials__c();
            dealerCredentials.Channel_Secret__c = 'channelsecret';
            dealerCredentials.Sender_Key__c = 'senderkey';
            dealerCredentials.JWT_Token__c = 'jwtToken';
            dealerCredentials.Customer_Identify_Url__c = 'https://test.ap24.force.com';
            insert dealerCredentials;

            Case kakaoCase = new Case();
            kakaoCase.Subject = 'Test Case';
            insert kakaoCase;

            Kakao_Consult_Chat__c consultChat = new Kakao_Consult_Chat__c();
            consultChat.Case__c = kakaoCase.Id;
            consultChat.User_Key__c = 'testuserkey';
            consultChat.Session_Live__c = true;
            insert consultChat;
        }
    }

    @isTest
    private static void testDoPostExpireSession() {
        User standardUser = [SELECT Id FROM User WHERE Alias = 'standt' LIMIT 1];

        System.runAs(standardUser) {
            RestRequest request = new RestRequest();
            RestResponse response = new RestResponse();
            request.requestURI = '/services/apexrest/expired_session';
            request.httpMethod = 'POST';
            String body = '{';
            body += '"user_key": "testuserkey",';
            body += '"sender_key": "senderkey",';
            body += '"session_id": "sessionid",';
            body += '"payload": "payload"';
            body += '}';
            request.requestBody = Blob.valueOf(body);
            Test.startTest();
            RestContext.request = request;
            RestContext.response = response;
            InboundExpiredSessionRestService.doPostExpireSession();
            System.assertEquals(200, response.statusCode, 'Failed status of doPostExpireSession');
            Test.stopTest();
        }
    }
}