force-app/main/default/objects/Kakao_Consult_Chat__c/Kakao_Consult_Chat__c.object-meta.xml
<CustomObject>
    <label>Kakao Consult Chat</label>
    <nameField>
        <displayFormat>KCC-{0000000000}</displayFormat>
        <label>Kakao Consult Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Consult Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Session_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Time__c</fullName>
    <label>Session End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Session_Id__c.field-meta.xml
<CustomField>
    <fullName>Session_Id__c</fullName>
    <externalId>true</externalId>
    <label>Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Session_Live__c.field-meta.xml
<CustomField>
    <fullName>Session_Live__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Session Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <externalId>true</externalId>
    <label>User Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/KakaoConsultDealerCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Kakao Consult Dealer Credentials</label>
</CustomObject>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Channel_Secret__c.field-meta.xml
<CustomField>
    <fullName>Channel_Secret__c</fullName>
    <label>Channel Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/JWT_Token__c.field-meta.xml
<CustomField>
    <fullName>JWT_Token__c</fullName>
    <label>JWT Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/InboundExpiredSessionRestService.cls
/**
 * @description       : Expired session's inbound callout service
 * @author            : Obidjon
 * @group             : Kakao Consult Chat
 * @last modified on  : 06-12-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   04-07-2021   Obidjon   Initial Version
 **/
@RestResource(urlMapping='/expired_session')
global without sharing class InboundExpiredSessionRestService {
    @SuppressWarnings('PMD.ApexCRUDViolation')
    @HttpPost
    global static void doPostExpireSession() {
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response;
        String requestBody = request.requestBody.toString();
        InboundExpiredSession expiredSession = InboundExpiredSession.parse(requestBody);

        KakaoConsultDealerCredentials__c dealerCredentials = KakaoConsultDealerCredentials__c.getOrgDefaults();
        String jwtToken = dealerCredentials.JWT_Token__c;
        String secret = dealerCredentials.Channel_Secret__c;
        String headerSignature = request.headers.get('X-Signature');

        KakaoConsult_JWT jwt = new KakaoConsult_JWT('HS256', 'JWT', jwtToken, secret);
        if (!Test.isRunningTest() && !jwt.verify(headerSignature)) {
            response.statusCode = 401;
            return;
        }

        try {
            Kakao_Consult_Chat__c konsultChat = [
                SELECT Id
                FROM Kakao_Consult_Chat__c
                WHERE Session_Live__c = TRUE AND Session_Id__c = NULL AND User_Key__c = :expiredSession.user_key
            ];
            konsultChat.Session_Id__c = expiredSession.session_id;
            konsultChat.Session_Live__c = false;
            konsultChat.Session_End_Time__c = System.now();
            update konsultChat;
        } catch (Exception e) {
            response.responseBody = Blob.valueOf(e.getMessage());
        }

        response.statusCode = 200;
    }
}