force-app/main/default/objects/Contact/fields/CCR_AgeVerificationStatus__c.field-meta.xml
<CustomField>
    <fullName>CCR_AgeVerificationStatus__c</fullName>
    <description>derived: blank, failed, pending, recognized, verified</description>
    <inlineHelpText>연령 확인 여부에 따른 컨택트의 상황정보 제공</inlineHelpText>
    <label>Age Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
            <value>
                <fullName>INVALID</fullName>
                <isActive>false</isActive>
                <label>INVALID</label>
            </value>
            <value>
                <fullName>NONVERIFIED</fullName>
                <isActive>false</isActive>
                <label>NONVERIFIED</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Recognized</fullName>
                <isActive>false</isActive>
                <label>Recognized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CCR_CarePlusStatus__c.field-meta.xml
<CustomField>
    <fullName>CCR_CarePlusStatus__c</fullName>
    <description>Field on Contact level to show Care+ current status.
Person is Enrolled if at least one device is Care+ enrolled.</description>
    <label>Care+ Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Enrolled</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CCR_ConsumerUID__c.field-meta.xml
<CustomField>
    <fullName>CCR_ConsumerUID__c</fullName>
    <description>SPICE internal ID</description>
    <externalId>true</externalId>
    <label>Consumer DB ID (AsIs Key)</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/CCR_SmokerNew__c.field-meta.xml
<CustomField>
    <fullName>CCR_SmokerNew__c</fullName>
    <description>Used by: CCR Description: New field that will substitute CCR_Smoker. This was requested in order to be able to handle 3x values to sent to SPICE instead of just TRUE or FALSE</description>
    <label>Smoker Declaration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_Declaration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CCR_SoftAgeVerifiedNew__c.field-meta.xml
<CustomField>
    <fullName>CCR_SoftAgeVerifiedNew__c</fullName>
    <complianceGroup>PII;HIPAA;GDPR;PCI;COPPA;CCPA</complianceGroup>
    <description>Used by: CCR Description: New field that will substitute CCR_SoftAgeVerified. This was requested in order to be able to handle 3x values to sent to SPICE instead of just TRUE or FALSE</description>
    <label>Soft Age Verified</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCR_Declaration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>[KDCE] Contact Key SpiceID 대체</description>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_fm_ConsumerType__c.field-meta.xml
<CustomField>
    <fullName>KDCE_fm_ConsumerType__c</fullName>
    <formula>RecordType.Name</formula>
    <label>Consumer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_fm_POS_BirthdateMask__c.field-meta.xml
<CustomField>
    <fullName>KDCE_fm_POS_BirthdateMask__c</fullName>
    <description>POS Birthdate Masking</description>
    <formula>SUBSTITUTE( TEXT( Birthdate ), MID( TEXT( Birthdate ), 6, 5 ), &quot;**-**&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Birthdate(Mask) for POS</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IqosON__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IqosON__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] ON 프로그램 가입 여부</description>
    <label>IQOS ON</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IqosUP__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IqosUP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] UP 프로그램 가입여부</description>
    <label>IQOS UP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_KakaoId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_KakaoId__c</fullName>
    <description>[KDCE] KAKAO Account ID</description>
    <inlineHelpText>KAKAO Account ID</inlineHelpText>
    <label>KAKAO Account ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LASLAU__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LASLAU__c</fullName>
    <description>[KDCE] LAS / LAU</description>
    <label>LAS/LAU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LAS</fullName>
                <default>true</default>
                <label>LAS</label>
            </value>
            <value>
                <fullName>LAU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_MarketingOptIn__c.field-meta.xml
<CustomField>
    <fullName>KDCE_MarketingOptIn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 마케팅 수신 동의여부 체크</description>
    <label>Marketing Opt-In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_MGMCode__c.field-meta.xml
<CustomField>
    <fullName>KDCE_MGMCode__c</fullName>
    <description>MGM Coupon Code</description>
    <externalId>true</externalId>
    <inlineHelpText>[KDCE] MGM 친구 추천인 코드</inlineHelpText>
    <label>MGM Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_RentalConsumer__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RentalConsumer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] Rental 진행 중 여부 체크</description>
    <label>Rental Consumer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/KDCE_OfflineProgram__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Offline Progrma (Trade-in, Upgrade, Rental, Replacement..)</description>
    <label>Offline Program</label>
    <nameField>
        <displayFormat>OP{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offline Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Offline Program</relationshipLabel>
    <relationshipName>OfflineProgram</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/RentalEndDate__c.field-meta.xml
<CustomField>
    <fullName>RentalEndDate__c</fullName>
    <description>[KDCE] Rental End Date</description>
    <label>Rental End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/RentalStartDate__c.field-meta.xml
<CustomField>
    <fullName>RentalStartDate__c</fullName>
    <description>[KDCE] Rental Start Date</description>
    <label>Rental Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Rental Process</fullName>
            </value>
            <value>
                <fullName>Rental Cancel</fullName>
            </value>
            <value>
                <fullName>Rental Closed</fullName>
            </value>
            <value>
                <fullName>Rental Purchase</fullName>
                <isActive>false</isActive>
                <label>Rental Purchase</label>
            </value>
            <value>
                <fullName>Rental Refund</fullName>
                <isActive>false</isActive>
                <label>Rental Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/KDCE_Order__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Order</description>
    <label>Order</label>
    <nameField>
        <displayFormat>KO{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <description>[KDCE] 주문타입
ZTA(일반주문)
ZTI(보상판매)
ZRN(렌탈 중고)
ZRNNEW(렌탈 신규)
ZRA(QURE)</description>
    <inlineHelpText>주문타입</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZTA</fullName>
            </value>
            <value>
                <fullName>ZTI</fullName>
            </value>
            <value>
                <fullName>ZRN</fullName>
            </value>
            <value>
                <fullName>ZRNNEW</fullName>
            </value>
            <value>
                <fullName>ZRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/RentalEndDate__c.field-meta.xml
<CustomField>
    <fullName>RentalEndDate__c</fullName>
    <description>[KDCE] 렌탈 종료일 (주문유형 렌탈일 경우만 존재)</description>
    <label>Rental End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/RentalStartDate__c.field-meta.xml
<CustomField>
    <fullName>RentalStartDate__c</fullName>
    <description>[KDCE] 렌탈 시작일 (주문유형 렌탈일 경우만 존재)</description>
    <label>Rental Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/RentalStatus__c.field-meta.xml
<CustomField>
    <fullName>RentalStatus__c</fullName>
    <description>[KDCE] 렌탈 상태 (주문유형이 렌탈일 경우만 존재)</description>
    <label>Rental Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_C360Controller.cls
/****************************************************************************************
 * @filename      : KDCE_C360Controller
 * @projectname   : 
 * @author        : Donghu
 * @date          : 2021-04-28
 * @group         :
 * @group-content :
 * @description   :
 * @tester        : KDCE_C360Controller_ts
 * @reference     :
 * @copyright     : Copyright © I2max. All Rights Reserved.
 * @modification Log
 * ===============================================================
 * ver     date                     author              description
 * ===============================================================
 0.1      2021-04-28                  Donghu          Create
 ****************************************************************************************/
public with sharing class KDCE_C360Controller {
    /**
        * @description C360 View
        * @param recordId (String)
        * @return response (KDCE_ComponentResponse)
        **/
    @AuraEnabled
    public static KDCE_ComponentResponse getContact(String recordId) {
        KDCE_ComponentResponse response = new KDCE_ComponentResponse();

        Contact contact;
        List<Contact> contactList = [
                SELECT Name,Phone,KDCE_fm_ConsumerType__c,KDCE_LASLAU__c,KDCE_ExternalId__c,Birthdate,Email,CCR_CarePlusStatus__c,KDCE_RentalConsumer__c,KDCE_MarketingOptIn__c,KDCE_KakaoId__c,KDCE_IqosON__c,KDCE_IqosUP__c,KDCE_MGMCode__c,CCR_ConsumerUID__c,CCR_AgeVerificationStatus__c,CCR_SmokerNew__c,CCR_SoftAgeVerifiedNew__c, KDCE_fm_POS_BirthdateMask__c
                FROM Contact
                WHERE Id = :recordId
                LIMIT 1
        ];
        contact = contactList[0];
        response.setData('contact', contact);

        if (contact.KDCE_RentalConsumer__c) {
            KDCE_OfflineProgram__c[] offlineRental = [
                    SELECT RentalStartDate__c, RentalEndDate__c
                    FROM KDCE_OfflineProgram__c
                    WHERE Contact__c = :recordId
                    AND Status__c =: KDCE_GlobalValue.OFF_PG_STATUS_RTNPROCESS
                    //ORDER BY CreatedDate DESC
                    LIMIT 1
            ];

            KDCE_Order__c[] onlineRental = [
                    SELECT RentalStartDate__c, RentalEndDate__c
                    FROM KDCE_Order__c
                    WHERE Contact__c = :recordId
                    AND OrderType__c = :KDCE_GlobalValue.ORDER_TYPE_RENTAL
                    AND RentalStatus__c = :KDCE_GlobalValue.ORDER_RNTSTATUS_RENTAL
                    LIMIT 1
            ];

            if(!offlineRental.isEmpty())    response.setData('offlineRental', offlineRental[0]);
            if(!onlineRental.isEmpty())     response.setData('onlineRental', onlineRental[0]);
        }

        System.debug('response :: ' + response);
        return response;
    }
}