force-app/main/default/objects/Contact/fields/CCR_DatabaseOptin__c.field-meta.xml
<CustomField>
    <fullName>CCR_DatabaseOptin__c</fullName>
    <defaultValue>true</defaultValue>
    <description>I want to be part of the DB / I want to be deleted</description>
    <label>Database Opt-in</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ConvertDormantDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ConvertDormantDate__c</fullName>
    <description>[KDCE] 휴면고객으로 전환된 일</description>
    <label>Dormant Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_DropoutDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DropoutDate__c</fullName>
    <description>[KDCE] 탈퇴고객으로 전환된 일자</description>
    <label>DropOut Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_DropoutRequestDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DropoutRequestDate__c</fullName>
    <description>[KDCE] 탈퇴 요청을 한 일자</description>
    <label>DropOut Request Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>[KDCE] Contact Key SpiceID 대체</description>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_fm_IsTargetDormant__c.field-meta.xml
<CustomField>
    <fullName>KDCE_fm_IsTargetDormant__c</fullName>
    <description>[KDCE] 일정 기간 동안 활동내역이 없어서 휴면으로 전환될 고객</description>
    <formula>if (AND(ADDMONTHS(KDCE_fm_LastActivityDate__c,12)&lt;=now(),  ISPICKVAL(KDCE_PersonalInfoValidityPeriod__c, &apos;1y&apos;)),true, 
				if (AND(ADDMONTHS(KDCE_fm_LastActivityDate__c,36)&lt;=now(),  ISPICKVAL(KDCE_PersonalInfoValidityPeriod__c, &apos;3y&apos;) ), true, false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dormant Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsDormant__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDormant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 배치로 인해 휴면 처리가 된 고객</description>
    <label>Dormant Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsDropout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDropout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 탈퇴고객으로 전환된 고객</description>
    <label>DropOut Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsRequestDropout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsRequestDropout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 탈퇴 요청을 한 고객</description>
    <label>DropOut Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ReactivateDormantDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ReactivateDormantDate__c</fullName>
    <description>[KDCE] Reactivate Dormant Date</description>
    <label>Reactivate Dormant Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_RegistrationChannel__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationChannel__c</fullName>
    <description>[KDCE] Registration Channel</description>
    <inlineHelpText>Registration Channel</inlineHelpText>
    <label>Registration Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>EasyIqos</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
                <default>true</default>
                <label>SC</label>
            </value>
            <value>
                <fullName>iqos.com</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_RegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationDate__c</fullName>
    <description>[KDCE] 고객 등록 시간</description>
    <label>Registration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_RegistrationObject__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationObject__c</fullName>
    <description>Contact 별 중복규칙을 다르게 하기 위해 사용되는 필드 (Apex)</description>
    <label>Registration Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact_Anonymous.recordType-meta.xml
<RecordType>
    <fullName>Contact_Anonymous</fullName>
    <active>true</active>
    <description>[KDCE]</description>
    <label>Anonymous</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact_Member.recordType-meta.xml
<RecordType>
    <fullName>Contact_Member</fullName>
    <active>true</active>
    <description>[KDCE]</description>
    <label>Member</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact_Prospect.recordType-meta.xml
<RecordType>
    <fullName>Contact_Prospect</fullName>
    <active>true</active>
    <description>[KDCE]</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/KDCE_DormantContact__c/KDCE_DormantContact__c.object-meta.xml
<CustomObject>
    <description>고객 중 휴면으로 전환된 고객 정보를 저장하기 위한 오브젝트</description>
    <label>Dormant Contact</label>
    <nameField>
        <label>Dormant Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dormant Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_ConvertDormantDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ConvertDormantDate__c</fullName>
    <label>Dormant Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_DropoutDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DropoutDate__c</fullName>
    <label>DropOut Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_IsDormant__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDormant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dormant Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_IsDropout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDropout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DropOut Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_IsRequestDropout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsRequestDropout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DropOut Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_ReactivateDormantDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ReactivateDormantDate__c</fullName>
    <label>Reactivate Dormant Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_RegistrationChannel__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationChannel__c</fullName>
    <label>Registration Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IQOS</fullName>
            </value>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>EasyIqos</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_RegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationDate__c</fullName>
    <label>Registration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_RegistrationObject__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationObject__c</fullName>
    <description>Contact 별 중복규칙을 다르게 하기 위해 사용되는 필드 (Apex)</description>
    <label>Registration Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_DormantContact_ba.cls
/****************************************************************************************
  * @filename      : KDCE_DormantContact_ba
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-04 오후 1:15
  * @group         : 
  * @group-content : 
  * @description   : Contact이 휴면 Contact으로 전환될경우, Dormant Contact 생성 후 해당 Contact 필드 null 처리하는 배치
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-04 오후 1:15     i2max_Jihyun.Lee        Create
****************************************************************************************/
/*******************************************************************************************
 * Serial Batch Order
 * 1. KDCE_DormantContact_ba:        Contact 휴면 처리 (Contact 정보 Null처리). Member일 경우는 분리보관 및 개인정보 Null처리
 * 2. KDCE_DormantCase_ba:           Contact 휴면 전환시, Contact과 관련된 Case 분리보관 및 개인정보 Null처리
 * 3. KDCE_DormantOrderLineItem_ba:  Contact 휴면 전환시, Contact과 관련된 Order Line Item 분리보관 및 개인정보 Null처리
 * 4. KDCE_DormantOrder_ba:          Contact 휴면 전환시, Contact과 관련된 Order 분리보관 및 개인정보 Null처리
 * 5. KDCE_DormantOfflineProgram_ba: Contact 휴면 전환시, Contact과 관련된 Offline Program 분리보관 및 개인정보 Null처리
 *******************************************************************************************/


public with sharing class KDCE_DormantContact_ba implements Database.Batchable<sObject>, Database.Stateful {

    private final static Id RT_Contact_AnonymousId      = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact_Anonymous').getRecordTypeId();    // 고객 : Anonymous
    private final static Id RT_Contact_ProspectId       = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact_Prospect').getRecordTypeId();     // 고객 : Prospect
    private final static Id RT_Contact_MemberId         = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact_Member').getRecordTypeId();       // 고객 : iqos.com 회원 멤버

    String objectName = 'CONTACT';
    String query = 'SELECT ';
    Map<String, Schema.SObjectField> conFieldMap = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap();

    //Set<Id> batchContactIds = new Set<Id>();

    public Database.QueryLocator start(Database.BatchableContext BC) {

        // 오브젝트에 해당하는 전체 필드 가져오기
        for (String fieldName : conFieldMap.keySet()) {
            if (query != 'SELECT ') query += ' , ';     // 첫번째 필드가 아닐 경우 , 붙이기
            query += fieldName;
        }
        query += ' FROM ';
        query += objectName;
        if (!Test.isRunningTest()) query += ' WHERE KDCE_fm_IsTargetDormant__c = TRUE ';
        if (!Test.isRunningTest()) query += ' AND (RecordType.DeveloperName = \'Contact_Member\' ) ';
        if (!Test.isRunningTest()) query += ' AND CCR_DatabaseOptin__c = TRUE AND KDCE_IsDormant__c = FALSE ';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {

        Map<String, Schema.SObjectField> objectSchema = Schema.SObjectType.Contact.fields.getMap();

        // Null처리하면 안되는 필드 저장
        Set<String> notNullField = new Set<String>{
                'id', 'ownerid', 'accountid', 'kdce_externalid__c', 'kdce_registrationchannel__c', 'kdce_registrationdate__c', 'kdce_registrationobject__c',
                'kdce_isdropout__c', 'kdce_dropoutdate__c', 'kdce_isrequestdropout__c', 'kdce_dropoutrequestdate__c',
                'kdce_isdormant__c', 'kdce_convertdormantdate__c', 'kdce_reactivatedormantdate__c'
        };


        /*
        for (Contact con : (List<Contact>) scope) {
            batchContactIds.add(con.Id);    // 다음 배치에서 Order, Case NULL처리할 배치
        }
        System.debug('=== batchContactIds : ' + batchContactIds);
        */

        // Member인 경우만 분리보관
        // Contact 휴면처리인 경우 null처리
        KDCE_ContactSeparateService.separateObject('Dormant', 'Contact', 'KDCE_DormantContact__c', scope);
        KDCE_ContactSeparateService.setNullField('Dormant','Contact', scope, objectSchema, notNullField, null);

    }

    public void finish(Database.BatchableContext BC) {
        /*
        if(!batchContactIds.isEmpty()) {
            KDCE_DormantCase_ba nextBatch = new KDCE_DormantCase_ba();
            nextBatch.batchContactIds = batchContactIds;
            Database.executeBatch(nextBatch, 2000);
        }
        */
        KDCE_DormantCase_ba nextBatch = new KDCE_DormantCase_ba();
        Database.executeBatch(nextBatch, 200);
    }

}