force-app/main/default/objects/Contact/fields/CCR_AgeVerificationStatus__c.field-meta.xml
<CustomField>
    <fullName>CCR_AgeVerificationStatus__c</fullName>
    <description>derived: blank, failed, pending, recognized, verified</description>
    <inlineHelpText>연령 확인 여부에 따른 컨택트의 상황정보 제공</inlineHelpText>
    <label>Age Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
            <value>
                <fullName>INVALID</fullName>
                <isActive>false</isActive>
                <label>INVALID</label>
            </value>
            <value>
                <fullName>NONVERIFIED</fullName>
                <isActive>false</isActive>
                <label>NONVERIFIED</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Recognized</fullName>
                <isActive>false</isActive>
                <label>Recognized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CCR_AVStatusDateChange__c.field-meta.xml
<CustomField>
    <fullName>CCR_AVStatusDateChange__c</fullName>
    <description>derived datetime</description>
    <label>AV Status Date Change</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_fm_AgeVerificationExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_fm_AgeVerificationExpiryDate__c</fullName>
    <description>[KDCE] 본인인증일 + 1년</description>
    <formula>ADDMONTHS(CCR_AVStatusDateChange__c,12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age Verification Expiry Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_fm_IsAgeReVerification__c.field-meta.xml
<CustomField>
    <fullName>KDCE_fm_IsAgeReVerification__c</fullName>
    <description>[KDCE] HAV 재인증 대상. .HAV 인증 만료일에 따라 체크.</description>
    <formula>IF(
    or (KDCE_fm_AgeVerificationExpiryDate__c = null, KDCE_fm_AgeVerificationExpiryDate__c &gt;=  NOW()),
				FALSE,
				KDCE_fm_AgeVerificationExpiryDate__c &lt;  NOW()
)</formula>
    <label>Age ReVerification Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact_Member.recordType-meta.xml
<RecordType>
    <fullName>Contact_Member</fullName>
    <active>true</active>
    <description>[KDCE]</description>
    <label>Member</label>
</RecordType>

force-app/main/default/classes/KDCE_ContactHAVStatus_ba.cls
/****************************************************************************************
  * @filename      : KDCE_ContactHAVStatus_ba
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-04-22 오후 2:18
  * @group         : 
  * @group-content : 
  * @description   : HAV 재인증 대상별, Age Verification (CCR_AgeVerificationStatus__c) 업데이트
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-04-22 오후 2:18     i2max_Jihyun.Lee        Create
****************************************************************************************/

public with sharing class KDCE_ContactHAVStatus_ba implements Database.Batchable<sObject>, Database.Stateful {

    private final static Id RT_Contact_MemberId         = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact_Member').getRecordTypeId();       // 고객 : iqos.com 회원 멤버

    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = '';
        query += ' SELECT Id, CCR_AgeVerificationStatus__c, KDCE_fm_AgeVerificationExpiryDate__c, CCR_AVStatusDateChange__c       ';
        query += ' FROM Contact                                 ';
        if (!Test.isRunningTest()) query += ' WHERE KDCE_fm_IsAgeReVerification__c = TRUE       ';
        if (!Test.isRunningTest()) query += ' AND CCR_AgeVerificationStatus__c = \'Verified\'   ';
        if (!Test.isRunningTest()) query += ' AND RecordTypeId = :RT_Contact_MemberId           ';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {

        for (Contact con : (List<Contact>) scope) {
            con.CCR_AgeVerificationStatus__c = 'Expired';
            con.CCR_AVStatusDateChange__c = System.now();
        }

        update scope;
    }

    @SuppressWarnings('PMD')
    public void finish(Database.BatchableContext BC) {

    }
}