force-app/main/default/objects/Contact/fields/CCR_DatabaseOptin__c.field-meta.xml
<CustomField>
    <fullName>CCR_DatabaseOptin__c</fullName>
    <defaultValue>true</defaultValue>
    <description>I want to be part of the DB / I want to be deleted</description>
    <label>Database Opt-in</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ConvertDormantDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ConvertDormantDate__c</fullName>
    <description>[KDCE] 휴면고객으로 전환된 일</description>
    <label>Dormant Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ConvertedConsumer__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ConvertedConsumer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>새로운 Iqos.com 가입 고객</description>
    <inlineHelpText>새로운 Iqos.com 가입 고객</inlineHelpText>
    <label>Converted Consumer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_DropoutDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DropoutDate__c</fullName>
    <description>[KDCE] 탈퇴고객으로 전환된 일자</description>
    <label>DropOut Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_DropoutRequestDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DropoutRequestDate__c</fullName>
    <description>[KDCE] 탈퇴 요청을 한 일자</description>
    <label>DropOut Request Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>[KDCE] Contact Key SpiceID 대체</description>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_fm_LastActivityDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_fm_LastActivityDate__c</fullName>
    <description>[KDCE] Last Login Date, Last Coupon Burnt Date, Last Case Date, Last Case Close Date, Last CRM Response Date, Last NPS Response Date 중 가장 마지막 날짜 저장</description>
    <formula>IF(
    AND(
        ISBLANK(KDCE_LastLoginDate__c),
        ISBLANK(KDCE_LastCouponUsedDate__c),
        ISBLANK(KDCE_LastCaseDate__c), 
		ISBLANK(KDCE_LastCloseDate__c), 
        ISBLANK(KDCE_LastCRMResponseDate__c),
		ISBLANK(KDCE_LastNPSResponseDate__c),
		ISBLANK(KDCE_LastOfflineProgramDate__c),
		ISBLANK(KDCE_ReactivateDormantDate__c),
		ISBLANK(KDCE_LastDeviceLinkDate__c),
		ISBLANK(KDCE_ECJoinDate__c)
    ),
    NULL,
    NOW() - MIN(
        NOW() - BLANKVALUE(KDCE_LastLoginDate__c, DATETIMEVALUE(&quot;1900-01-01 12:00:00&quot;)),
	    NOW() - BLANKVALUE(KDCE_LastCouponUsedDate__c, DATETIMEVALUE(&quot;1900-01-01 12:00:00&quot;)), 
        NOW() - BLANKVALUE(KDCE_LastCaseDate__c, DATETIMEVALUE(&quot;1900-01-01 12:00:00&quot;)),
        NOW() - BLANKVALUE(KDCE_LastCloseDate__c, DATETIMEVALUE(&quot;1900-01-01 12:00:00&quot;)),
		NOW() - BLANKVALUE(KDCE_LastCRMResponseDate__c, DATETIMEVALUE(&quot;1900-01-01 12:00:00&quot;)),
		NOW() - BLANKVALUE(KDCE_LastNPSResponseDate__c, DATETIMEVALUE(&quot;1900-01-01 12:00:00&quot;)),
		NOW() - BLANKVALUE(KDCE_LastOfflineProgramDate__c, DATETIMEVALUE(&quot;1900-01-01 12:00:00&quot;)),
		NOW() - BLANKVALUE(KDCE_ReactivateDormantDate__c, DATETIMEVALUE(&quot;1900-01-01 12:00:00&quot;)),
		NOW() - BLANKVALUE(KDCE_LastDeviceLinkDate__c, DATETIMEVALUE(&quot;1900-01-01 12:00:00&quot;)),
		NOW() - BLANKVALUE(KDCE_ECJoinDate__c, DATETIMEVALUE(&quot;1900-01-01 12:00:00&quot;))
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Activity Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsDormant__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDormant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 배치로 인해 휴면 처리가 된 고객</description>
    <label>Dormant Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsDropout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDropout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 탈퇴고객으로 전환된 고객</description>
    <label>DropOut Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsRequestDropout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsRequestDropout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 탈퇴 요청을 한 고객</description>
    <label>DropOut Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_KakaoId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_KakaoId__c</fullName>
    <description>[KDCE] KAKAO Account ID</description>
    <inlineHelpText>KAKAO Account ID</inlineHelpText>
    <label>KAKAO Account ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_Mig_Delete__c.field-meta.xml
<CustomField>
    <fullName>KDCE_Mig_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mig Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ReactivateDormantDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ReactivateDormantDate__c</fullName>
    <description>[KDCE] Reactivate Dormant Date</description>
    <label>Reactivate Dormant Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_RegistrationChannel__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationChannel__c</fullName>
    <description>[KDCE] Registration Channel</description>
    <inlineHelpText>Registration Channel</inlineHelpText>
    <label>Registration Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>EasyIqos</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
                <default>true</default>
                <label>SC</label>
            </value>
            <value>
                <fullName>iqos.com</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_RegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationDate__c</fullName>
    <description>[KDCE] 고객 등록 시간</description>
    <label>Registration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_RegistrationObject__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationObject__c</fullName>
    <description>Contact 별 중복규칙을 다르게 하기 위해 사용되는 필드 (Apex)</description>
    <label>Registration Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact_Prospect.recordType-meta.xml
<RecordType>
    <fullName>Contact_Prospect</fullName>
    <active>true</active>
    <description>[KDCE]</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Kakao_User_Mapping__c/Kakao_User_Mapping__c.object-meta.xml
<CustomObject>
    <label>Kakao User Mapping</label>
    <nameField>
        <displayFormat>KUM-{00000000}</displayFormat>
        <label>Kakao User Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao User Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_User_Mapping__c/fields/App_User_Id__c.field-meta.xml
<CustomField>
    <fullName>App_User_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>App User Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_DropOutContact__c/KDCE_DropOutContact__c.object-meta.xml
<CustomObject>
    <description>탈퇴 고객 정보를 저장하기 위한 오브젝트</description>
    <label>DropOut Contact</label>
    <nameField>
        <label>DropOut Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DropOut Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DropOutContact__c/fields/CCR_DatabaseOptin__c.field-meta.xml
<CustomField>
    <fullName>CCR_DatabaseOptin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Database Opt-in</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutContact__c/fields/KDCE_ConvertedConsumer__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ConvertedConsumer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted Consumer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutContact__c/fields/KDCE_DropoutRequestDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DropoutRequestDate__c</fullName>
    <label>DropOut Request Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutContact__c/fields/KDCE_fm_LastActivityDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_fm_LastActivityDate__c</fullName>
    <description>마지막 활동일</description>
    <label>Last Activity Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutContact__c/fields/KDCE_KakaoId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_KakaoId__c</fullName>
    <label>KAKAO Account ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_DropOutContactSoftDeletion_ba.cls
/****************************************************************************************
  * @filename      : KDCE_DropOutContactSoftDeletion_ba
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-11 오전 10:14
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : KDCE_DropOutContactSoftDeletion_ba_ts
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-11 오전 10:14     i2max_Jihyun.Lee        Create
****************************************************************************************/

public with sharing class KDCE_DropOutContactSoftDeletion_ba implements Database.Batchable<sObject>, Database.Stateful {
    private final static Id RT_Contact_ProspectId  = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact_Prospect').getRecordTypeId();     // 고객 : Prospect
    String objectName = 'CONTACT';
    String query = 'SELECT ';
    Map<String, Schema.SObjectField> conFieldMap = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap();
    //Set<Id> batchContactIds = new Set<Id>();

    public Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('===== START :: Dropout CONTACT SoftDel ===== ');

        Datetime d = System.today().addYears(-1);
        Datetime dt = (Datetime)Date.newInstance(d.year(), d.month(), d.day());
        String deleteTargetDt = dt.formatGmt('yyyy-MM-dd\'T\'HH:mm:ssZ');

        // 오브젝트에 해당하는 전체 필드 가져오기
        for (String fieldName : conFieldMap.keySet()) {
            if (query != 'SELECT ') query += ' , ';     // 첫번째 필드가 아닐 경우 , 붙이기
            query += fieldName;
        }
        query += ' FROM ';
        query += objectName;
        //if (!Test.isRunningTest()) query += ' WHERE (KDCE_IsRequestDropout__c = TRUE AND KDCE_IsDropout__c = FALSE AND KDCE_DropoutRequestDate__c = TODAY) '; //
        //if (!Test.isRunningTest()) query += ' OR (KDCE_fm_LastActivityDate__c < ' + deleteTargetDt + ' AND RecordTypeId =\''+ RT_Contact_ProspectId+'\' ) ';
        if (!Test.isRunningTest()) query += ' WHERE (KDCE_IsRequestDropout__c = TRUE AND KDCE_IsDropout__c = FALSE AND KDCE_DropoutRequestDate__c < LAST_N_DAYS:30 ) '; // Member Contact이 탈퇴요청을 한 경우 todo :: 날짜조건 나중에 확인필요(현0629. lastNDays:30이면,0529날짜가 분리저장 타겟 )
        if (!Test.isRunningTest()) query += ' OR (KDCE_fm_LastActivityDate__c < ' + deleteTargetDt + ' AND RecordTypeId = \'' + RT_Contact_ProspectId + '\' ) ';        // Prospect Contact의 마지막 활동이 1년이 경과한 경우

        //if (!Test.isRunningTest()) query += ' WHERE KDCE_Mig_Delete__c = True AND CCR_DatabaseOptin__c = False AND KDCE_IsDropout__c = FALSE AND KDCE_ConvertedConsumer__c = false ';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<SObject> scope) {
        System.debug('===== EXECUTE :: Dropout CONTACT SoftDel ===== ');

        Map<String, Schema.SObjectField> objectSchema = Schema.SObjectType.Contact.fields.getMap();

        // Null처리하면 안되는 필드 저장
        Set<String> notNullField = new Set<String>{
                'id', 'ownerid', 'accountid', 'kdce_externalid__c', 'kdce_registrationchannel__c', 'kdce_registrationdate__c', 'kdce_registrationobject__c',
                'kdce_isdropout__c', 'kdce_dropoutdate__c', 'kdce_isrequestdropout__c', 'kdce_dropoutrequestdate__c',
                'kdce_isdormant__c', 'kdce_convertdormantdate__c', 'kdce_reactivatedormantdate__c'
        };

        Set<String> kakaoIds = new Set<String>();

        for (Contact con : (List<Contact>) scope) {
            if(con.KDCE_KakaoId__c != null) kakaoIds.add(con.KDCE_KakaoId__c);
        }

        List<Kakao_User_Mapping__c> kumList = [SELECT Id FROM Kakao_User_Mapping__c WHERE App_User_Id__c IN :kakaoIds];
        /*
        for (Contact con : (List<Contact>) scope) {
            batchContactIds.add(con.Id);    // 다음 배치에서 Order, Case NULL처리할 배치
        }
        */

        // Member인 경우만 분리보관
        // Contact 휴면처리인 경우 null처리
        KDCE_ContactSeparateService.separateObject('DropOut', 'Contact', 'KDCE_DropOutContact__c', scope);
        KDCE_ContactSeparateService.setNullField('DropOut','Contact', scope, objectSchema, notNullField, null);

        if(kumList.size() > 0) Database.delete(kumList, false);
    }

    public void finish(Database.BatchableContext BC) {

        KDCE_DropOutCaseSoftDeletion_ba nextBatch = new KDCE_DropOutCaseSoftDeletion_ba();
        Database.executeBatch(nextBatch, 200);

        /*
        if(!batchContactIds.isEmpty()) {
            KDCE_DropOutCaseSoftDeletion_ba nextBatch = new KDCE_DropOutCaseSoftDeletion_ba();
            nextBatch.batchContactIds = batchContactIds;
            Database.executeBatch(nextBatch, 500);
        }
        */
    }
}