force-app/main/default/objects/Contact/fields/KDCE_Name__c.field-meta.xml
<CustomField>
    <fullName>KDCE_Name__c</fullName>
    <description>마스킹 처리가 안된 이름 저장</description>
    <externalId>true</externalId>
    <label>Name (No Mask)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/Kakao_Consult_Chat__c.object-meta.xml
<CustomObject>
    <label>Kakao Consult Chat</label>
    <nameField>
        <displayFormat>KCC-{0000000000}</displayFormat>
        <label>Kakao Consult Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Consult Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Kakao Consult Chat</relationshipLabel>
    <relationshipName>Kakao_Consult_Chat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <externalId>true</externalId>
    <label>User Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kakao_User_Mapping__c/Kakao_User_Mapping__c.object-meta.xml
<CustomObject>
    <label>Kakao User Mapping</label>
    <nameField>
        <displayFormat>KUM-{00000000}</displayFormat>
        <label>Kakao User Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao User Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_User_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Kakao User Mapping</relationshipLabel>
    <relationshipName>Kakao_User_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kakao_User_Mapping__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>User Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/KakaoConsultCustomerIdentify.cls
/**
 * @description       : Customer Identity link response rest service
 * @author            : Obidjon
 * @group             : Kakao Consult Chat
 * @last modified on  : 07-23-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   04-12-2021   Obidjon   Initial Version
 **/

@RestResource(urlMapping='/kakaoConsultCustomerIdentify')
global without sharing class KakaoConsultCustomerIdentify {
    @SuppressWarnings('PMD.ApexCRUDViolation')
    @HttpPost
    global static void doPostCustomerInformation() {
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response;
        String requestBody = request.requestBody.toString();
        KakaoConsultCustomerInformation customerInformation = KakaoConsultCustomerInformation.parse(requestBody);

        Case kakaoCase = [SELECT Id FROM Case WHERE Id = :customerInformation.cid];
        Contact contact;
        try {
            contact = [
                SELECT Id
                FROM Contact
                WHERE KDCE_Name__c = :customerInformation.lastName.trim() AND Phone = :customerInformation.phone
                LIMIT 1
            ];
            kakaoCase.ContactId = contact.Id;
        } catch (QueryException e) {
            contact = new Contact();
            contact.LastName = customerInformation.lastName;
            contact.Phone = customerInformation.phone;
            contact.Email = customerInformation.email;
            // if (String.isNotBlank(customerInformation.birthdate)) {
            //     List<String> birthdates = customerInformation.birthdate.split('-');
            //     contact.Birthdate = Date.newInstance(
            //         Integer.valueOf(birthdates[0]),
            //         Integer.valueOf(birthdates[1]),
            //         Integer.valueOf(birthdates[2])
            //     );
            // }
            insert contact;
            kakaoCase.ContactId = contact.id;
        }

        update kakaoCase;
        Kakao_Consult_Chat__c kakaoChat = [
            SELECT Id, User_Key__c
            FROM Kakao_Consult_Chat__c
            WHERE Case__c = :kakaoCase.Id
            LIMIT 1
        ];
        Kakao_User_Mapping__c kakaoUserMapping = new Kakao_User_Mapping__c();
        kakaoUserMapping.User_Key__c = kakaoChat.User_Key__c;
        kakaoUserMapping.Contact__c = contact.Id;
        Database.upsert(kakaoUserMapping, Kakao_User_Mapping__c.User_Key__c);

        response.statusCode = 200;
    }
}