force-app/main/default/objects/Contact/fields/KDCE_IsMGMIssue__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsMGMIssue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 개발용</description>
    <label>MGM Coupon Issue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LASLAU__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LASLAU__c</fullName>
    <description>[KDCE] LAS / LAU</description>
    <label>LAS/LAU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LAS</fullName>
                <default>true</default>
                <label>LAS</label>
            </value>
            <value>
                <fullName>LAU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact_Member.recordType-meta.xml
<RecordType>
    <fullName>Contact_Member</fullName>
    <active>true</active>
    <description>[KDCE]</description>
    <label>Member</label>
</RecordType>

force-app/main/default/objects/IF_XP_SFDC_001__c/IF_XP_SFDC_001__c.object-meta.xml
<CustomObject>
    <description>CVS 쿠폰 사용에 관한 더미 레코드</description>
    <label>IF XP SFDC 001</label>
    <nameField>
        <displayFormat>CouponIF-{YYYY}{MM}{DD}{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IF XP SFDC 001</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/BurnoutChannel__c.field-meta.xml
<CustomField>
    <fullName>BurnoutChannel__c</fullName>
    <label>BurnoutChannel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponAmount__c.field-meta.xml
<CustomField>
    <fullName>CouponAmount__c</fullName>
    <label>CouponAmount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>CouponExpiryDate__c</fullName>
    <label>CouponExpiryDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponId__c.field-meta.xml
<CustomField>
    <fullName>CouponId__c</fullName>
    <label>CouponId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/Couponissuedate__c.field-meta.xml
<CustomField>
    <fullName>Couponissuedate__c</fullName>
    <label>Couponissuedate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/Couponmoddate__c.field-meta.xml
<CustomField>
    <fullName>Couponmoddate__c</fullName>
    <label>Couponmoddate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponName__c.field-meta.xml
<CustomField>
    <fullName>CouponName__c</fullName>
    <label>CouponName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponOltCode__c.field-meta.xml
<CustomField>
    <fullName>CouponOltCode__c</fullName>
    <label>CouponOltCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponOltName__c.field-meta.xml
<CustomField>
    <fullName>CouponOltName__c</fullName>
    <label>CouponOltName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponStatus__c.field-meta.xml
<CustomField>
    <fullName>CouponStatus__c</fullName>
    <label>CouponStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponStatusDate__c.field-meta.xml
<CustomField>
    <fullName>CouponStatusDate__c</fullName>
    <label>CouponStatusDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CVSChainCode__c.field-meta.xml
<CustomField>
    <fullName>CVSChainCode__c</fullName>
    <label>CVSChainCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CVSChainName__c.field-meta.xml
<CustomField>
    <fullName>CVSChainName__c</fullName>
    <label>CVSChainName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/CouponCode__c.field-meta.xml
<CustomField>
    <fullName>CouponCode__c</fullName>
    <description>[KDCE] Coupon Code</description>
    <externalId>true</externalId>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>[KDCE] Coupon Type</description>
    <label>Coupon Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MGM</fullName>
            </value>
            <value>
                <fullName>CVS</fullName>
                <label>Special Purchase Code</label>
            </value>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Tradein</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_CVS.recordType-meta.xml
<RecordType>
    <fullName>Coupon_CVS</fullName>
    <active>true</active>
    <description>[KDCE] KA, GT</description>
    <label>Special Purchase Code</label>
</RecordType>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_MGM.recordType-meta.xml
<RecordType>
    <fullName>Coupon_MGM</fullName>
    <active>true</active>
    <description>[KDCE] MGM</description>
    <label>MGM</label>
</RecordType>

force-app/main/default/objects/KDCE_Order__c/KDCE_Order__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Order</description>
    <label>Order</label>
    <nameField>
        <displayFormat>KO{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applied Coupon</description>
    <inlineHelpText>Applied Coupon</inlineHelpText>
    <label>Coupon</label>
    <referenceTo>KDCE_Coupon__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/CouponCode__c.field-meta.xml
<CustomField>
    <fullName>CouponCode__c</fullName>
    <description>[KDCE] 쿠폰 코드
Mapping Column : coupon_code</description>
    <inlineHelpText>쿠폰 코드</inlineHelpText>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <description>[KDCE] 고객번호
Mapping Column : customer_id</description>
    <inlineHelpText>고객번호</inlineHelpText>
    <label>Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_OrderLineItem__c/KDCE_OrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_OrderLineItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>KDCE_Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CouponTestDataUtil.cls
/****************************************************************************************
  * @filename      : CouponTestDataUtil
  * @projectname   : PMK LocalDCE QA
  * @author        : i2max_JE Yoon
  * @date          : 2021-03-26
  * @group         :
  * @description   :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                author              description
  * ===============================================================
    0.1  2021-03-26          i2max_JE Yoon             Create
****************************************************************************************/
@IsTest
public without sharing class CouponTestDataUtil {

    public static Map<String, Id> recordTypeMap;
    public static Datetime now = System.now();
    public static List<Contact> contacts;
    public static Account account;
    public static KDCE_Order__c order;
    public static KDCE_OrderLineItem__c orderLineItem;
    public static KDCE_Coupon__c coupon;
    public static IF_XP_SFDC_001__c ifXpSfdc001;
    public static Task task;
    public static Integer recordCount;
    public static String developerName_Coupon_MGM = 'Coupon_MGM';
    public static String developerName_Coupon_CVS = 'Coupon_CVS';
    public static String couponStatus_Produce = 'Produce';


    public static void getRecordTypes () {
        recordTypeMap = new Map<String, Id>();
        List<RecordType> recordTypes = [SELECT Id, SobjectType, DeveloperName FROM RecordType];
        for (RecordType recordType : recordTypes) {
            recordTypeMap.put(recordType.SobjectType + '|' + recordType.DeveloperName, recordType.Id);
        }
    }

    public static Id getRecordTypeId (String sObjectName, String DeveloperName) {
        if (recordTypeMap == null) {
            getRecordTypes();
        }
        return recordTypeMap.get(sObjectName + '|' + DeveloperName);
    }

    public static Account getAccount() {
        if (account == null) {
            account = new Account(
                    Name = 'test ' + now
            );
        }

        return account;
    }

    public static List<Contact> getContacts(String couponDeveloperName) {
        if (contacts == null) {
            contacts = new List<Contact>();
            recordCount = couponDeveloperName == developerName_Coupon_MGM ? 2 : 1;

            for (Integer i = 0; i < recordCount; i++) {
                contacts.add(new Contact(
                        LastName = couponDeveloperName + i,
                        RecordTypeId = getRecordTypeId('Contact', 'Contact_Member'),
                        KDCE_LASLAU__c = 'LAS',
                        KDCE_IsMGMIssue__c = false,
                        Email = 'test' + i + '@test.com'
                ));
            }

            insert contacts;
        }

        return contacts;
    }

    public static KDCE_Coupon__c getCoupon(String developerName, String status) {
        //String type = developerName.contains('cvs') ? 'CVS' : 'GetInfo';
        if (coupon == null) {
            if (contacts == null) getContacts(developerName);
            coupon = new KDCE_Coupon__c(
                    RecordTypeId = getRecordTypeId('KDCE_Coupon__c', developerName),
                    Contact__c = status != couponStatus_Produce ? contacts[0].Id : null,
                    CouponCode__c = 'Test ' + developerName,
                    Status__c = status,
                    Type__c = 'MGM'
          //          Type__c = type
            );
            insert coupon;
        }

        return coupon;
    }

    public static KDCE_Order__c getOrder(String coupon_developerName, Boolean couponExists) {
        if (order == null) {
            if (coupon == null) getCoupon(coupon_developerName, 'Issue');
            order = new KDCE_Order__c(
                    CustomerId__c = coupon_developerName == developerName_Coupon_MGM ? contacts[1].Id : contacts[0].Id,
                    Contact__c = coupon_developerName == developerName_Coupon_MGM ? contacts[1].Id : contacts[0].Id,
                    Coupon__c = couponExists ? coupon.Id : null
            );
            insert order;
        }

        return order;
    }

    public static KDCE_OrderLineItem__c getOrderLineItem(String coupon_developerName, Boolean couponExists) {

        if (orderLineItem == null) {
            if (order == null) getOrder(coupon_developerName, couponExists);
            orderLineItem = new KDCE_OrderLineItem__c(
                    //Name = 'test ' + now,
                    Order__c = order.Id
            );
            insert orderLineItem;
        }

        return orderLineItem;
    }

    public static IF_XP_SFDC_001__c getIfXpSfdc001() {
        if (ifXpSfdc001 == null) {
            if (coupon == null) getCoupon(developerName_Coupon_CVS, 'Produce');
            ifXpSfdc001 = new IF_XP_SFDC_001__c(
                    BurnoutChannel__c = 'CVS',
                    CVSChainCode__c = '24',
                    CVSChainName__c = 'GS',
                    CouponId__c = 'Test ' + developerName_Coupon_CVS,
                    CouponIssueDate__c = '2019-11-21',
                    CouponExpiryDate__c = '2021-06-30',
                    CouponStatus__c = '1',
                    CouponStatusDate__c = '20190329155801',
                    CouponAmount__c = '31000',
                    CouponName__c = '[GS25] 할인권)아이코스',
                    CouponOltCode__c = '1234',
                    CouponOltName__c = '공덕점',
                    CouponModDate__c = '20190329155801'
            );

        }

        return ifXpSfdc001;
    }

}