force-app/main/default/objects/Contact/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>[KDCE] Contact Key SpiceID 대체</description>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LASLAU__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LASLAU__c</fullName>
    <description>[KDCE] LAS / LAU</description>
    <label>LAS/LAU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LAS</fullName>
                <default>true</default>
                <label>LAS</label>
            </value>
            <value>
                <fullName>LAU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>[KDCE] Coupon Price</description>
    <label>Coupon Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/CouponCode__c.field-meta.xml
<CustomField>
    <fullName>CouponCode__c</fullName>
    <description>[KDCE] Coupon Code</description>
    <externalId>true</externalId>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <description>[KDCE] Coupon Expiry Date</description>
    <label>Coupon Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/fm_ContactExtId__c.field-meta.xml
<CustomField>
    <fullName>fm_ContactExtId__c</fullName>
    <formula>Contact__r.KDCE_ExternalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consumer ID (FM)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/IsAvailable__c.field-meta.xml
<CustomField>
    <fullName>IsAvailable__c</fullName>
    <formula>OR(
	AND(RecordType.DeveloperName = &apos;Coupon_Paper&apos;, 
		NOT(ISPICKVAL(Status__c, &apos;Use&apos;))
	),
	AND(RecordType.DeveloperName = &apos;Coupon_Tradein&apos;, 
		NOT(ISPICKVAL(Status__c, &apos;Use&apos;))
	),
	AND(RecordType.DeveloperName = &apos;Coupon_MGM&apos;, 
		NOT(ISPICKVAL(Status__c, &apos;Produce&apos;)), 
		ru_UseCount__c &lt; 10
	),
	AND(ISPICKVAL(Status__c, &apos;Issue&apos;),
		fm_UseCount__c = 0
	), 
	AND(RecordType.DeveloperName = &apos;Coupon_Accessory&apos;, 
		fm_UseCount__c = 0
	),
	AND(RecordType.DeveloperName = &apos;Coupon_Hotel&apos;, 
		fm_UseCount__c &lt; 2
	)
)</formula>
    <label>Available YN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/IsSend__c.field-meta.xml
<CustomField>
    <fullName>IsSend__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] Coupon 발송 여부</description>
    <label>SMS Send YN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/ru_UseCount__c.field-meta.xml
<CustomField>
    <fullName>ru_UseCount__c</fullName>
    <description>[KDCE] Coupon 사용횟수</description>
    <label>Coupon Use Count (RU)</label>
    <summaryFilterItems>
        <field>KDCE_CouponHistory__c.ActionType__c</field>
        <operation>equals</operation>
        <value>Use</value>
    </summaryFilterItems>
    <summaryForeignKey>KDCE_CouponHistory__c.Coupon__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>[KDCE] Coupon Type</description>
    <label>Coupon Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MGM</fullName>
            </value>
            <value>
                <fullName>CVS</fullName>
                <label>Special Purchase Code</label>
            </value>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Tradein</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IF_MG_DCE_0078_BIZ.cls
/****************************************************************************************
  * @filename      : IF_MG_DCE_0078_BIZ
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-07 오후 2:34
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-07 오후 2:34     i2max_Jihyun.Lee        Create
****************************************************************************************/

public with sharing class IF_MG_DCE_0078_BIZ {
    private static IF_MG_DCE_0078_BIZ sInstance = null;
    public static IF_MG_DCE_0078_BIZ getInstance() {
        if(sInstance == null){
            sInstance = new IF_MG_DCE_0078_BIZ();
        }
        return sInstance;
    }

    public IF_MG_DCE_0078.InputBody pre(IF_MG_DCE_0078.InputBody inputBody, IF_MG_DCE_0078.OutputBody outputBody) {
        /* 업무 개발자에 의해 변경되어야 하는 부분 시작*/

        /* 업무 개발자에 의해 변경되어야 하는 부분 끝 */
        return inputBody;
    }

    public IF_MG_DCE_0078.OutputBody post(IF_MG_DCE_0078.InputBody inputBody, IF_MG_DCE_0078.OutputBody outputBody) {

        System.debug('=== inputBody : ' + inputBody);
        System.debug('=== inputBody.t_data : ' + inputBody.t_data);
        List<KDCE_Coupon__c> couponList = new List<KDCE_Coupon__c>();
        Boolean couponAvailable;
        String JobResult;

        // Input Data
        String couponCode = inputBody.t_data != null ? inputBody.t_data[0].couponCode : null;
        String contactExtId = inputBody.t_data != null ? inputBody.t_data[0].contactExtId : null;
        System.debug('=== couponCode : ' + couponCode);
        System.debug('=== contactExtId : ' + contactExtId);
        IF_KDCE_API_BizBase.validate(false, couponCode == null, 'Coupon Code 값이 무조건 있어야 합니다.');
        IF_KDCE_API_BizBase.validate(false, contactExtId == null, 'Contact External Id 값이 무조건 있어야 합니다.');

        // 해당 쿠폰 검색
        List<KDCE_Coupon__c> coupons = [
                SELECT  Id, Name, Amount__c, CouponCode__c, IsAvailable__c, IsSend__c, ExpiryDate__c,
                        Contact__c, fm_ContactExtId__c, ru_UseCount__c, Status__c, Type__c
                FROM    KDCE_Coupon__c
                WHERE   CouponCode__c = :couponCode
        ];
        // 해당 Contact 검색
        List<Contact> contacts = [SELECT Id, KDCE_LASLAU__c FROM Contact WHERE KDCE_ExternalId__c = :contactExtId];
        System.debug('=== coupons : ' + coupons);
        System.debug('=== contacts : ' + contacts);

        /** validation **/
        IF_KDCE_API_BizBase.validate(false, contacts.isEmpty(), '일치하는 Contact이 존재하지 않습니다.');
        if (coupons.isEmpty()) JobResult = '0401';                                                      // 없는 번호의 쿠폰일 경우
        else {
            if (coupons[0].IsAvailable__c == false) JobResult = '0402';                                     // 이미 사용된 쿠폰일 경우
            if (coupons[0].ExpiryDate__c < System.today()) JobResult = '0403';                              // 만료된 쿠폰일 경우
            if (coupons[0].Type__c == 'MGM' && contacts[0].KDCE_LASLAU__c == 'LAU') JobResult = '0404';     // LAU가 MGM 입력했을 경우
            IF (coupons[0].Type__c == 'MGM' && coupons[0].Contact__c == contacts[0].Id) JobResult = '0405'; // (MGM) 자신의 쿠폰번호를 입력했을 때
        }


        // Output 선언
        IF_MG_DCE_0078.OutputData outputData = new IF_MG_DCE_0078.OutputData();
        System.debug('=== outputData : ' + outputData);
        outputData.JobResult        = JobResult == null ? '0000' : JobResult;
        outputData.couponAvailable  = JobResult == null ? true : false;
        outputData.coupons          = coupons.isEmpty() ? null : coupons;
        outputBody.t_data.add(outputData);
        outputBody.ifAggregation    = IF_Comm.convertEmpty(inputBody.ifAggregation);
        outputBody.ifSplitCnt       = IF_Comm.convertEmpty(inputBody.ifSplitCnt);
        outputBody.ifRcvCnt         = IF_Comm.convertEmpty(outputBody.t_data.size());   // 수신수량 return 필드
//
        return outputBody;
    }
}