force-app/main/default/objects/Contact/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>[KDCE] Contact Key SpiceID 대체</description>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_QualtricsResponse__c/KDCE_QualtricsResponse__c.object-meta.xml
<CustomObject>
    <label>Qualtrics Response</label>
    <nameField>
        <displayFormat>QR-{0000000}</displayFormat>
        <label>Qualtrics Response 이름</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualtrics Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_QualtricsResponse__c/fields/Consumer_ID__c.field-meta.xml
<CustomField>
    <fullName>Consumer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_QualtricsResponse__c/fields/recordeddate__c.field-meta.xml
<CustomField>
    <fullName>recordeddate__c</fullName>
    <label>Recorded Date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_QualtricsResponse__c/fields/response_id__c.field-meta.xml
<CustomField>
    <fullName>response_id__c</fullName>
    <label>Response ID</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_QualtricsResponse_tr_ts.cls
/****************************************************************************************
  * @filename      : KDCE_QualtricsResponse_tr_ts
  * @projectname   : PMK qa - KR
  * @author        : Park HE
  * @date          : 2021-07-28
  * @group         :
  * @group-content :
  * @description   :
  * @tester        :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                    author          description
  * ===============================================================
    0.1     2021-07-28             Park HE         Create
****************************************************************************************/

@IsTest
private class KDCE_QualtricsResponse_tr_ts {
    @IsTest
    static void testBehavior() {
        Contact con = KDCE_TestUtil.contactMember;
        con.KDCE_ExternalId__c = 'testexternal';
        update con;
        KDCE_QualtricsResponse__c q1 = new KDCE_QualtricsResponse__c(Consumer_ID__c = con.KDCE_ExternalId__c,
                response_id__c = 'test', recordeddate__c = '2021-08-11T16:35:17.379Z');
        KDCE_QualtricsResponse__c q2 = new KDCE_QualtricsResponse__c(Consumer_ID__c = con.KDCE_ExternalId__c,
                response_id__c = 'test', recordeddate__c = '2021-08-10T16:35:17.379Z');
        List<KDCE_QualtricsResponse__c> qlist = new List<KDCE_QualtricsResponse__c>{q1, q2};
        insert qlist;
        update qlist;
    }
}