force-app/main/default/objects/Contact/fields/KDCE_IsDormant__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDormant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 배치로 인해 휴면 처리가 된 고객</description>
    <label>Dormant Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/KDCE_DormantContact__c.object-meta.xml
<CustomObject>
    <description>고객 중 휴면으로 전환된 고객 정보를 저장하기 위한 오브젝트</description>
    <label>Dormant Contact</label>
    <nameField>
        <label>Dormant Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dormant Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DormantContact__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dormant Contact</relationshipLabel>
    <relationshipName>Dormant_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_IsDormant__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDormant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dormant Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/KDCE_RestoreContactController.cls
/****************************************************************************************
  * @filename      : KDCE_RestoreContactController
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-04-29 오후 3:26
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-04-29 오후 3:26     i2max_Jihyun.Lee        Create
****************************************************************************************/

public with sharing class KDCE_RestoreContactController {

    // Contact 휴면 계정 복원 (IsDormant true -> false)
    @AuraEnabled
    public static void convertDormant(Id recordId) {
        System.debug('=== convertDormant : ');
        KDCE_DormantContact__c dormantContact = [SELECT Id, ContactId__c FROM KDCE_DormantContact__c WHERE Id = :recordId];
        String contactId = dormantContact.ContactId__c;

        List<Contact> contactList = [SELECT Id, KDCE_IsDormant__c FROM Contact WHERE Id = :dormantContact.ContactId__c];
        for (Contact con : contactList) {
            con.KDCE_IsDormant__c = false;
        }
        System.debug('=== contactList : ' + contactList);
        update contactList;

        String url = '/lightning/r/Contact/' + contactId + '/view';
        ApexPages.PageReference redirectPage = new PageReference(url);
        aura.redirect(redirectPage);
    }


}