force-app/main/default/objects/Contact/fields/KDCE_DCIssueCount__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DCIssueCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>[KDCE] Device Coupon 발급 횟수</description>
    <label>Device Coupon Issue Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_Name__c.field-meta.xml
<CustomField>
    <fullName>KDCE_Name__c</fullName>
    <description>마스킹 처리가 안된 이름 저장</description>
    <externalId>true</externalId>
    <label>Name (No Mask)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_CVS.recordType-meta.xml
<RecordType>
    <fullName>Coupon_CVS</fullName>
    <active>true</active>
    <description>[KDCE] KA, GT</description>
    <label>Special Purchase Code</label>
</RecordType>

force-app/main/default/classes/KDCE_ResetDCIssueCount_ba_Test.cls
/****************************************************************************************
  * @filename      : KDCE_ResetDCIssueCount_ba_Test
  * @projectname   : PMK LocalDCE QA
  * @author        : i2max_JE Yoon
  * @date          : 2021-03-31
  * @group         :
  * @description   :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                author              description
  * ===============================================================
    0.1  2021-03-31          i2max_JE Yoon             Create
****************************************************************************************/
@IsTest
private class KDCE_ResetDCIssueCount_ba_Test {
    static String developerName_Coupon_CVS = 'Coupon_CVS';

    @TestSetup
    static void setData() {
        CouponTestDataUtil.getCoupon(developerName_Coupon_CVS, 'Produce');
    }

    @IsTest
    static void testCase01() {

        Test.startTest();

        String lastName = developerName_Coupon_CVS+0;
        List<KDCE_Coupon__c> coupons = [SELECT Id, Status__c, Contact__c FROM KDCE_Coupon__c LIMIT 1];
        //List<Contact> contacts = [SELECT Id, LastName FROM Contact WHERE KDCE_Name__c = :lastName LIMIT 1];
        Contact con = [SELECT Id, LastName FROM Contact LIMIT 1];
        con.KDCE_DCIssueCount__c = 3;
        coupons[0].Status__c = 'Issue';
        coupons[0].Contact__c = con.Id;

        update con;
        update coupons;

        String CRON_EXP = '0 0 0 3 9 ? 2022';

        String jobId = System.schedule('ResetDCIssueCount_sc', CRON_EXP, new KDCE_ResetDCIssueCount_sc());
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE  Id = :jobId];
        System.assertEquals(CRON_EXP, ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
        System.assertEquals('2022-09-03 00:00:00', String.valueOf(ct.NextFireTime));
        //System.assertNotEquals(0, [SELECT Id, KDCE_DCIssueCount__c FROM Contact WHERE Id = :con.Id].KDCE_DCIssueCount__c);

        Test.stopTest();

    }
}