force-app/main/default/objects/Contact/fields/KDCE_MGMUseCount__c.field-meta.xml
<CustomField>
    <fullName>KDCE_MGMUseCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MGM Coupon Use Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_Name__c.field-meta.xml
<CustomField>
    <fullName>KDCE_Name__c</fullName>
    <description>마스킹 처리가 안된 이름 저장</description>
    <externalId>true</externalId>
    <label>Name (No Mask)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_MGM.recordType-meta.xml
<RecordType>
    <fullName>Coupon_MGM</fullName>
    <active>true</active>
    <description>[KDCE] MGM</description>
    <label>MGM</label>
</RecordType>

force-app/main/default/objects/KDCE_CouponHistory__c/KDCE_CouponHistory__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Coupon Journey</description>
    <label>Coupon Journey</label>
    <nameField>
        <displayFormat>CH-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Journeys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <description>[KDCE] Coupon Action Type</description>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <label>Coupon</label>
    <referenceTo>KDCE_Coupon__c</referenceTo>
    <relationshipLabel>Coupon Journeys</relationshipLabel>
    <relationshipName>CouponHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/KDCE_Order__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Order</description>
    <label>Order</label>
    <nameField>
        <displayFormat>KO{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <description>Order Action Type</description>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applied Coupon</description>
    <inlineHelpText>Applied Coupon</inlineHelpText>
    <label>Coupon</label>
    <referenceTo>KDCE_Coupon__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>[KDCE] 주문 상태
Mapping Column : order_status</description>
    <inlineHelpText>주문 상태</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>processing</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>ready_for_delivery</fullName>
            </value>
            <value>
                <fullName>picking</fullName>
            </value>
            <value>
                <fullName>delivery_collection</fullName>
            </value>
            <value>
                <fullName>complete_delivery</fullName>
            </value>
            <value>
                <fullName>closed</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>cancel</fullName>
            </value>
            <value>
                <fullName>cancel_order</fullName>
            </value>
            <value>
                <fullName>return_received</fullName>
            </value>
            <value>
                <fullName>reject</fullName>
            </value>
            <value>
                <fullName>authorized</fullName>
            </value>
            <value>
                <fullName>approved</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>renting</fullName>
            </value>
            <value>
                <fullName>complete</fullName>
                <label>Complete</label>
            </value>
            <value>
                <fullName>paid</fullName>
            </value>
            <value>
                <fullName>received</fullName>
            </value>
            <value>
                <fullName>processed_closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_CouponHistory_tr_Test.cls
/****************************************************************************************
  * @filename      : KDCE_CouponHistory_tr_Test
  * @projectname   : PMK LocalDCE QA
  * @author        : i2max_JE Yoon
  * @date          : 2021-04-01
  * @group         :
  * @description   :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                author              description
  * ===============================================================
    0.1  2021-04-01          i2max_JE Yoon             Create
****************************************************************************************/
@IsTest
private class KDCE_CouponHistory_tr_Test {

    final static String CANCEL_STATUS = '주문취소'; //todo 주문 취소 값 확정 되면 변경 필요
    static Contact contact;
    static KDCE_Coupon__c coupon;
    static KDCE_Order__c order;
    static KDCE_CouponHistory__c couponHistory;
    static String developerName_Coupon_MGM = 'Coupon_MGM';
    static String couponStatus_Use = 'Use';
    static String couponStatus_Cancel = 'Cancel';
    static Id RT_Coupon_MGM = Schema.SObjectType.KDCE_Coupon__c.getRecordTypeInfosByDeveloperName().get('Coupon_MGM').getRecordTypeId();

    static {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();
    }

    static void getData(String developerName_Coupon, String couponStatus) {

        //todo 쿠폰 사용 취소 시나리오도 추가되면 아래 주석 풀어 사용
        if (developerName_Coupon == developerName_Coupon_MGM && couponStatus == couponStatus_Cancel) {
            CouponTestDataUtil.getOrder(developerName_Coupon, true);
            coupon = [SELECT Status__c FROM KDCE_Coupon__c LIMIT 1];
            order = [SELECT OrderStatus__c FROM KDCE_Order__c LIMIT 1];
            order.OrderStatus__c = CANCEL_STATUS;
            update order;
        } else {
            CouponTestDataUtil.getCoupon(developerName_Coupon, couponStatus);
        }

        System.debug(developerName_Coupon);
        System.debug(couponStatus);
        System.debug(CouponTestDataUtil.coupon);
//        couponHistory = [SELECT ActionType__c FROM KDCE_CouponHistory__c WHERE ActionType__c = :couponStatus LIMIT 1];
//        contact = [SELECT KDCE_MGMUseCount__c FROM Contact WHERE KDCE_Name__c = :developerName_Coupon+0 LIMIT 1];
    }

    /**
     * @description MGM 쿠폰 사용 시나리오
     *              (히스토리 생성 및 MGM 쿠폰이 발급된 Contact.KDCE_MGMUseCount__c = 1)
     * @author JE Yoon
     **/
    @IsTest
    static void testCase01() {

        Test.startTest();
        if (contact == null) getData(developerName_Coupon_MGM, couponStatus_Use);

//        System.assertEquals(couponStatus_Use, couponHistory.ActionType__c);
//        System.assertEquals(1, contact.KDCE_MGMUseCount__c);
        Test.stopTest();
    }

    /**
     * @description MGM 쿠폰 사용 취소 시나리오 //todo 쿠폰 사용 취소 시나리오도 추가되면 아래 주석 풀어 사용
      *             (히스토리 생성 및 MGM 쿠폰이 발급된 Contact.KDCE_MGMUseCount__c = 0)
     * @author JE Yoon
     **/
    @IsTest
    static void testCase02() {

        Test.startTest();
        if (contact == null) getData(developerName_Coupon_MGM, couponStatus_Cancel);

        //System.assertEquals(couponStatus_Cancel, couponHistory.ActionType__c);
        //System.assertEquals(0, contact.KDCE_MGMUseCount__c);
        Test.stopTest();
    }

    @IsTest
    static void testBehavior01() {
        KDCE_Coupon__c coupon = KDCE_TestBizUtil.coupon;
        coupon.RecordTypeId = RT_Coupon_MGM;
        update coupon;

        KDCE_CouponHistory__c couponHistory = new KDCE_CouponHistory__c();
        couponHistory.Coupon__c = coupon.Id;
        couponHistory.ActionType__c = 'Use';
        insert couponHistory;
        System.debug('=== couponHistory : ' + couponHistory);
    }
}