force-app/main/default/objects/Contact/fields/KDCE_InformationOptIn__c.field-meta.xml
<CustomField>
    <fullName>KDCE_InformationOptIn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] information opt-in</description>
    <label>Information Opt-in</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_MarketingOptIn__c.field-meta.xml
<CustomField>
    <fullName>KDCE_MarketingOptIn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 마케팅 수신 동의여부 체크</description>
    <label>Marketing Opt-In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCAccepted__c/KDCE_TnCAccepted__c.object-meta.xml
<CustomObject>
    <description>[KDCE]Terms and Conditions Accepted</description>
    <label>Terms and Conditions Accepted</label>
    <nameField>
        <displayFormat>TCA-{YY}{MM}{DD}{00000}</displayFormat>
        <label>RecordNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions Accepted</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_TnCAccepted__c/fields/Accepted__c.field-meta.xml
<CustomField>
    <fullName>Accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] Accepted</description>
    <label>Accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCAccepted__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Terms and Conditions Accepted</relationshipLabel>
    <relationshipName>TnCAccepted</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCAccepted__c/fields/fm_Channel__c.field-meta.xml
<CustomField>
    <fullName>fm_Channel__c</fullName>
    <description>Terms and Condition Version Set Channel Name</description>
    <formula>TEXT(TnCVersionSet__r.Channel__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Terms and Condition Version Set Channel Name</inlineHelpText>
    <label>Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCAccepted__c/fields/fm_InformationOptIn__c.field-meta.xml
<CustomField>
    <fullName>fm_InformationOptIn__c</fullName>
    <description>Information Opt-In of relevant Terms and Conditions Version Set</description>
    <formula>TnCVersionSet__r.InfomationOptin__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Information Opt-In of relevant Terms and Conditions Version Set</inlineHelpText>
    <label>Information Opt-In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCAccepted__c/fields/fm_MarketingOptIn__c.field-meta.xml
<CustomField>
    <fullName>fm_MarketingOptIn__c</fullName>
    <description>Marketing Opt-In of relevant Terms and Conditions Version Set</description>
    <formula>TnCVersionSet__r.MarketingOptin__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Marketing Opt-In of relevant Terms and Conditions Version Set</inlineHelpText>
    <label>Marketing Opt-In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCAccepted__c/fields/TnC__c.field-meta.xml
<CustomField>
    <fullName>TnC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[KDCE] Terms and Conditions Lookup Id</description>
    <label>Terms and Conditions</label>
    <referenceTo>TermsandConditions__c</referenceTo>
    <relationshipName>TaCAcceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCAccepted__c/fields/TnCVersionSet__c.field-meta.xml
<CustomField>
    <fullName>TnCVersionSet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[KDCE] TnCVersionSet</description>
    <label>Terms and Conditions Version Set</label>
    <referenceTo>KDCE_TnCVersionSet__c</referenceTo>
    <relationshipLabel>Terms and Conditions Accepted</relationshipLabel>
    <relationshipName>Terms_and_Conditions_Accepted</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCHistory__c/KDCE_TnCHistory__c.object-meta.xml
<CustomObject>
    <description>[Korea DCE]Junction Object, that stores the information which User Registration / Contact has accepted which Terms and Conditions.</description>
    <label>Terms and Conditions History</label>
    <nameField>
        <displayFormat>ATaC-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_TnCHistory__c/fields/CCR_Acceptance_Date__c.field-meta.xml
<CustomField>
    <fullName>CCR_Acceptance_Date__c</fullName>
    <description>Date of acceptance for the specified terms and conditions</description>
    <inlineHelpText>Date of acceptance for the specified terms and conditions</inlineHelpText>
    <label>Acceptance Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCHistory__c/fields/DTE_Contact__c.field-meta.xml
<CustomField>
    <fullName>DTE_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores ID of the related Contact record</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Terms and Conditions History</relationshipLabel>
    <relationshipName>TnCHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCHistory__c/fields/KDCE_Accepted__c.field-meta.xml
<CustomField>
    <fullName>KDCE_Accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE]Accepted</description>
    <label>Accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCHistory__c/fields/KDCE_Description__c.field-meta.xml
<CustomField>
    <fullName>KDCE_Description__c</fullName>
    <description>[KDCE] Description</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCHistory__c/fields/KDCE_TnC__c.field-meta.xml
<CustomField>
    <fullName>KDCE_TnC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[KDCE]Stores ID of the related Terms and Conditions record</description>
    <label>Terms and Conditions</label>
    <referenceTo>TermsandConditions__c</referenceTo>
    <relationshipLabel>Terms and Conditions History</relationshipLabel>
    <relationshipName>Accepted_Terms_and_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCHistory__c/fields/KDCE_TnCVersionSet__c.field-meta.xml
<CustomField>
    <fullName>KDCE_TnCVersionSet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[KDCE] Terms and Conditions Version Set</description>
    <label>Terms and Conditions VersionSet</label>
    <referenceTo>KDCE_TnCVersionSet__c</referenceTo>
    <relationshipLabel>Terms and Conditions History</relationshipLabel>
    <relationshipName>TnCHistory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCVersion__c/KDCE_TnCVersion__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Terms and Conditions Version</description>
    <label>Terms and Conditions Version</label>
    <nameField>
        <label>Terms and Conditions Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms and Conditions Version</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_TnCVersion__c/fields/VersionNumber__c.field-meta.xml
<CustomField>
    <fullName>VersionNumber__c</fullName>
    <description>Version Number</description>
    <inlineHelpText>Version Number</inlineHelpText>
    <label>Version Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCVersionSet__c/KDCE_TnCVersionSet__c.object-meta.xml
<CustomObject>
    <description>[KDCE]Terms and Conditions Version Set</description>
    <label>Terms and Conditions Version Set</label>
    <nameField>
        <displayFormat>VS-{YY}{MM}{DD}{00000}</displayFormat>
        <label>T&amp;C VersionSet</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions Version Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_TnCVersionSet__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>[KDCE] Channel</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>KDCE_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_TnCVersionSet__c/fields/ChannelNo__c.field-meta.xml
<CustomField>
    <fullName>ChannelNo__c</fullName>
    <description>[KDCE]ChannelOrder 채널별 표시순서.</description>
    <label>Channel No</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCVersionSet__c/fields/TaC__c.field-meta.xml
<CustomField>
    <fullName>TaC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Terms and Conditions Lookup Id</description>
    <label>Terms and Conditions</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TermsandConditions__c.KDCE_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TermsandConditions__c</referenceTo>
    <relationshipLabel>Terms and Conditions Version Sets</relationshipLabel>
    <relationshipName>TaCVersionSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_TnCVersionSet__c/fields/TnCVersion__c.field-meta.xml
<CustomField>
    <fullName>TnCVersion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[KDCE]T&amp;C Version</description>
    <label>T&amp;C Version</label>
    <referenceTo>KDCE_TnCVersion__c</referenceTo>
    <relationshipLabel>T&amp;C Version Sets</relationshipLabel>
    <relationshipName>TnCVersionSet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TermsandConditions__c/TermsandConditions__c.object-meta.xml
<CustomObject>
    <description>[Korea DCE] As-Is reuse 
Terms and Conditions, that are related to the different markets. Actual Terms and Conditions need to be accepted during Self Registration or at login.</description>
    <label>Terms and Conditions</label>
    <nameField>
        <displayFormat>TaC-{YY}{MM}{DD}{00000}</displayFormat>
        <label>Terms and Conditions Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TermsandConditions__c/fields/KDCE_MarketingOptin__c.field-meta.xml
<CustomField>
    <fullName>KDCE_MarketingOptin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] Marketing Opt in 제어 T&amp;C 여부
고객의 Marketing Opt-in 필드와 연동됩니다.</description>
    <inlineHelpText>고객이 해당 T&amp;C 동의시, 고객의 Marketing Opt-in 필드와 연동되어 체크됩니다.</inlineHelpText>
    <label>(X)Marketing Opt-in</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TermsandConditions__c/fields/KDCE_SubGroup__c.field-meta.xml
<CustomField>
    <fullName>KDCE_SubGroup__c</fullName>
    <description>[KDCE] Version 관리하기 위한 값</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>KDCE_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PMTC</fullName>
                <label>[PMTC]이용약관  (필수)</label>
            </value>
            <value>
                <fullName>PMPM</fullName>
                <label>[PMPM]개인정보 수집 및 이용 (필수)</label>
            </value>
            <value>
                <fullName>PMPO</fullName>
                <label>[PMPO]개인정보 수집 및 이용 (선택)</label>
            </value>
            <value>
                <fullName>PMPP</fullName>
                <label>[PMPP]개인정보 처리업무 위탁 동의 (2020년 9월 16일 18시25분 가입자까지 유효)</label>
            </value>
            <value>
                <fullName>PMPT</fullName>
                <label>[PMPT]개인정보 제3자 제공 (선택)</label>
            </value>
            <value>
                <fullName>PMTP</fullName>
                <label>[PMTP]개인정보 국외이전 (선택)</label>
            </value>
            <value>
                <fullName>PMCPE</fullName>
                <label>[PMCPE]휴면회원 전환기간 특례</label>
            </value>
            <value>
                <fullName>globaloptin</fullName>
                <label>[Common]광고성 정보 수신 (통합)</label>
            </value>
            <value>
                <fullName>PMPMG</fullName>
                <label>[Getinfo]개인정보 수집 및 이용 (필수)</label>
            </value>
            <value>
                <fullName>PMPOG</fullName>
                <label>[Getinfo]개인정보 수집 및 이용</label>
            </value>
            <value>
                <fullName>PMPPG</fullName>
                <label>[Getinfo]개인정보 처리 업무 위탁에 대한 동의</label>
            </value>
            <value>
                <fullName>PMPTG</fullName>
                <label>[Getinfo]개인정보 제3자 제공 (선택)</label>
            </value>
            <value>
                <fullName>PMDP</fullName>
                <label>[PMDP]개인정보 수집 및 이용 동의 (필수)</label>
            </value>
            <value>
                <fullName>PMNL</fullName>
                <label>[PMNL]개인정보 수집 및 이용 동의 (선택)</label>
            </value>
            <value>
                <fullName>PMDT</fullName>
                <label>[PMDT]개인정보 국외이전 동의</label>
            </value>
            <value>
                <fullName>PMTR</fullName>
                <label>[PMTR]Rental 이용약관 (필수)</label>
            </value>
            <value>
                <fullName>PMTI</fullName>
                <label>[PMTI]보상판매 이용 약관 (필수)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TermsandConditions__c/fields/KDCE_TnCVersionSet__c.field-meta.xml
<CustomField>
    <fullName>KDCE_TnCVersionSet__c</fullName>
    <description>[KDCE]Terms and Conditions Versions</description>
    <label>(X)Terms and Conditions Version Sets</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1.0</fullName>
            </value>
            <value>
                <fullName>2.0</fullName>
            </value>
            <value>
                <fullName>3.0</fullName>
            </value>
            <value>
                <fullName>4.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_TnCAccepted_tr.cls
/****************************************************************************************
 * @filename      : KDCE_TnCAccepted_tr
 * @projectname   : PMK Local DCE QA
 * @author        : i2max_Sukun
 * @date          : 5/11/21 9:58 AM
 * @group         : Service
 * @group-content :
 * @description   : TnC Accepted Trigger Business Logic Class
 * @tester        :
 * @reference     :
 * @copyright     : Copyright © I2max. All Rights Reserved.
 * @modification Log
 * ===============================================================
 * ver     date                     author              description
 * ===============================================================
 0.1     5/11/21 9:58 AM            i2max_Sukun           Create
 0.2     5/21/21                    i2max_Sukun           Update
 ****************************************************************************************/
public with sharing class KDCE_TnCAccepted_tr extends TriggerHandler {
    // Call Center Profile Name
    private static final String CALL_CENTER_PROFILE = System.Label.KDCE_COM_PROFILE_NAME_CALL_CENTER;
    // TnC Accept Behavior에 따른 History Description
    private static final String LAB_TNC_HISTORY_DESC_ACCEPT = System.Label.LAB_TNC_HISTORY_DESC_ACCEPT;
    private static final String LAB_TNC_HISTORY_DESC_DECLINE = System.Label.LAB_TNC_HISTORY_DESC_DECLINE;
    private static final String LAB_TNC_HISTORY_DESC_DECLINE_MARKETING = System.Label.LAB_TNC_HISTORY_DESC_DECLINE_MARKETING;
    private static final String LAB_TNC_HISTORY_DESC_DECLINE_INFORMATION = System.Label.LAB_TNC_HISTORY_DESC_DECLINE_INFORMATION;
    private static final String LAB_TNC_HISTORY_DESC_DECLINE_MARKETINGANDINFORMATION = System.Label.LAB_TNC_HISTORY_DESC_DECLINE_MARKETINGANDINFORMATION;

    public override void afterUpdate() {
        updateDefaultBehavior();
    }

    /**
     * @description Accepted 내역 변경 시 Contact Accepted 내역에 따라 Marketing Opt-In, Information Opt-In 내역 반영
     * @description Accepted 내역 변경 시 TnCHistory 생성
     * @param
     * @return
     */
    private void updateDefaultBehavior() {
        ParamWrapper param = setRelevantContactAcceptanceInfo();
        createTnCHistory(param);
    }

    /**
     * @description Accepted 내역 변경 시 Contact Accepted 내역에 따라 Marketing Opt-In, Information Opt-In 내역 반영
     * @param
     * @return ParamWrapper (History 생성 시 필요한 추가 정보들을 Wrapper Class로 전달)
     */
    private ParamWrapper setRelevantContactAcceptanceInfo() {

        Map<Id, KDCE_TnCAccepted__c> tnCAcceptedOldMap = (Map<Id, KDCE_TnCAccepted__c>) Trigger.oldMap;
        Map<Id, KDCE_TnCAccepted__c> tnCAcceptedNewMap = (Map<Id, KDCE_TnCAccepted__c>) Trigger.newMap;
        Map<Id, Contact> contactsToBeUpdatedMap = new Map<Id, Contact>();
        List<Contact> contactsRetrieved;
        Set<String> channelSet = new Set<String>();

        ParamWrapper paramWrapper = new ParamWrapper();
        Map<Id, User> modifiedUserMap = new Map<Id, User>();
        Map<Id, Integer> finalOptOutIndicatorMap = new Map<Id, Integer>();

        for (KDCE_TnCAccepted__c tnCAccepted : (List<KDCE_TnCAccepted__c>) Trigger.new) {
            if (tnCAcceptedOldMap.get(tnCAccepted.Id).Accepted__c != tnCAccepted.Accepted__c) {
                if (tnCAccepted.Contact__c != null) contactsToBeUpdatedMap.put(tnCAccepted.Contact__c, null);
                if (tnCAccepted.fm_Channel__c != null) channelSet.add(tnCAccepted.fm_Channel__c);
            }
        }

        if (contactsToBeUpdatedMap.keySet().size() > 0) {
            contactsRetrieved = [
                    SELECT Id,
                            KDCE_MarketingOptIn__c,
                            KDCE_InformationOptIn__c,
                            RecordType.DeveloperName,
                            // Contact의 TnC Accepted 내역 중 같은 버전에 대한 내역만 retrieve
                    (
                            SELECT TnCVersionSet__r.TaC__r.KDCE_SubGroup__c,
                                    fm_MarketingOptIn__c,
                                    fm_InformationOptIn__c,
                                    TnCVersionSet__r.TnCVersion__r.VersionNumber__c,
                                    TnCVersionSet__r.Channel__c,
                                    Accepted__c,
                                    LastModifiedBy.Profile.Name,
                                    LastModifiedBy.LastName,
                                    fm_Channel__c
                            FROM TnCAccepted__r
                            WHERE
                                fm_Channel__c IN :channelSet
                            ORDER BY TnCVersionSet__r.TnCVersion__r.VersionNumber__c, TnCVersionSet__r.Channel__c, TnCVersionSet__r.ChannelNo__c
                    )

                    FROM Contact
                    WHERE Id IN :contactsToBeUpdatedMap.keySet()
            ];


            if (contactsRetrieved.size() > 0) {
                //flag
                Boolean marketingFlag = TRUE;
                Boolean informationFlag = TRUE;
                Set<String> channelComparingSet = new Set<String>();

                for (Contact con : contactsRetrieved) {
                    for (KDCE_TnCAccepted__c affectingTnCAccepted : con.TnCAccepted__r) {
                        if(tnCAcceptedNewMap.containsKey(affectingTnCAccepted.Id)) {
                            channelComparingSet.add(affectingTnCAccepted.fm_Channel__c);
                            finalOptOutIndicatorMap.put(affectingTnCAccepted.Id, null);
                        }
                    }

                    for (KDCE_TnCAccepted__c tnCAccepted : con.TnCAccepted__r) {
                        if(channelComparingSet.contains(tnCAccepted.fm_Channel__c)) {
                            //비동의 레코드 있을 시
                            if (!tnCAccepted.Accepted__c) {

                                // Accepted의 T&C Version Set이 Marketing 동의와 관련된 Version Set일 경우
                                if (tnCAccepted.fm_MarketingOptIn__c) {
                                    marketingFlag = FALSE;
                                }
                                // Accepted의 T&C Version Set이 Information 동의와 관련된 Version Set일 경우
                                if (tnCAccepted.fm_InformationOptIn__c) {
                                    informationFlag = FALSE;
                                }
                            }
                        }
                        if (tnCAcceptedNewMap.containsKey(tnCAccepted.Id)) modifiedUserMap.put(tnCAccepted.LastModifiedById, tnCAccepted.LastModifiedBy);
                    }

                    // 1은 marketingFlag FALSE 변경, 2는 InformationFlag FALSE 변경, 3은 둘다 FALSE 변경
                    Integer changeIndicator = marketingFlag == FALSE ?
                            (informationFlag == FALSE ? 3 : 1) :
                            (informationFlag == FALSE ? 2 : 0);

                    // [1] Map 내의 tnCAccepted에 대하여 해당 Contact의 Optout 최종 flag 정보 저장
                    for (Id id : finalOptOutIndicatorMap.keySet()) {
                        finalOptOutIndicatorMap.put(id, changeIndicator);
                    }

                    con.KDCE_MarketingOptIn__c = marketingFlag;
                    con.KDCE_InformationOptIn__c = informationFlag;

                    contactsToBeUpdatedMap.put(con.Id, con);
                }
            }
        }

        if (contactsToBeUpdatedMap.values().size() > 0) update contactsToBeUpdatedMap.values();

        paramWrapper.userMap = modifiedUserMap;
        paramWrapper.finalIndicatorMap = finalOptOutIndicatorMap;
        return paramWrapper;
    }

    /**
     * @description Accepted 내역 변경 시 TnCHistory 생성
     * @param ParamWrapper
     * @return
     */
    private void createTnCHistory(ParamWrapper additionalInformation) {
        List<KDCE_TnCHistory__c> tnCHistoryList = new List<KDCE_TnCHistory__c>();
        KDCE_TnCHistory__c tnCHistory;
        Map<Id, KDCE_TnCAccepted__c> tnCAcceptedOldMap = (Map<Id, KDCE_TnCAccepted__c>) Trigger.oldMap;

        for (KDCE_TnCAccepted__c tnCAccepted : (List<KDCE_TnCAccepted__c>) Trigger.new) {

            if (tnCAcceptedOldMap?.get(tnCAccepted.Id)?.Accepted__c != tnCAccepted?.Accepted__c) {
                tnCHistory = new KDCE_TnCHistory__c(
                        DTE_Contact__c = tnCAccepted?.Contact__c,
                        KDCE_TnCVersionSet__c = tnCAccepted?.TnCVersionSet__c,
                        KDCE_TnC__c = tnCAccepted?.TnC__c,
                        KDCE_Accepted__c = tnCAccepted?.Accepted__c,
                        CCR_Acceptance_Date__c = Datetime.now());

                tnCHistory.KDCE_Description__c = additionalInformation.userMap.get(tnCAccepted.LastModifiedById).LastName + '(이)가 고객의 해당 약관을 ';

                if (!tnCAccepted.Accepted__c) {
                    switch on additionalInformation.finalIndicatorMap.get(tnCAccepted.Id) {
                        when 1 {
                            tnCHistory.KDCE_Description__c += LAB_TNC_HISTORY_DESC_DECLINE_MARKETING;
                        }
                        when 2 {
                            tnCHistory.KDCE_Description__c += LAB_TNC_HISTORY_DESC_DECLINE_INFORMATION;
                        }
                        when 3 {
                            tnCHistory.KDCE_Description__c += LAB_TNC_HISTORY_DESC_DECLINE_MARKETINGANDINFORMATION;
                        }
                        when else {
                            tnCHistory.KDCE_Description__c += LAB_TNC_HISTORY_DESC_DECLINE;
                        }
                    }
                } else {
                    tnCHistory.KDCE_Description__c += LAB_TNC_HISTORY_DESC_ACCEPT;
                }

                // Call Center Profile일 경우
//                if (additionalInformation.userMap.get(tnCAccepted.LastModifiedById).Profile.Name.equals(CALL_CENTER_PROFILE)) {
//                    tnCHistory.KDCE_Description__c += ' (Modified by Call Center Agent)';
//                    tnCHistory.KDCE_Channel__c = 'call center';
//                }

                tnCHistoryList.add(tnCHistory);
            }

        }
        if(tnCHistoryList.size() > 0) insert tnCHistoryList;
    }

    private class ParamWrapper {
        private Map<Id, User> userMap { get; set; }
        private Map<Id, Integer> finalIndicatorMap { get; set; }

        ParamWrapper() {
            userMap = new Map<Id, User>();
            finalIndicatorMap = new Map<Id, Integer>();
        }
    }
}