force-app/main/default/objects/Contact/fields/KDCE_fm_IsTargetDormant__c.field-meta.xml
<CustomField>
    <fullName>KDCE_fm_IsTargetDormant__c</fullName>
    <description>[KDCE] 일정 기간 동안 활동내역이 없어서 휴면으로 전환될 고객</description>
    <formula>if (AND(ADDMONTHS(KDCE_fm_LastActivityDate__c,12)&lt;=now(),  ISPICKVAL(KDCE_PersonalInfoValidityPeriod__c, &apos;1y&apos;)),true, 
				if (AND(ADDMONTHS(KDCE_fm_LastActivityDate__c,36)&lt;=now(),  ISPICKVAL(KDCE_PersonalInfoValidityPeriod__c, &apos;3y&apos;) ), true, false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dormant Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LastCaseDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LastCaseDate__c</fullName>
    <description>[KDCE] Contact이 마지막 Case 생성한 날짜</description>
    <label>Last Case Date (Online)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LastCloseDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LastCloseDate__c</fullName>
    <description>[KDCE] 케이스가 종료되는 시점에 업데이트</description>
    <label>Last Case Close Date (Online)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LastCouponUsedDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LastCouponUsedDate__c</fullName>
    <description>[KDCE] CVS Coupon 마지막 사용 날짜</description>
    <label>Last CVS Coupon Burnt Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LastCRMResponseDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LastCRMResponseDate__c</fullName>
    <description>CRM 서베이 답변이 입력되면 업데이트</description>
    <label>Last CRM Survey Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LastNPSResponseDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LastNPSResponseDate__c</fullName>
    <label>Last NPS Survey Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_PersonalInfoValidityPeriod__c.field-meta.xml
<CustomField>
    <fullName>KDCE_PersonalInfoValidityPeriod__c</fullName>
    <description>[KDCE] Personal Information Validity Period</description>
    <label>Personal Information Validity Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1y</fullName>
                <label>1년</label>
            </value>
            <value>
                <fullName>3y</fullName>
                <label>3년</label>
            </value>
            <value>
                <fullName>dropout</fullName>
                <label>탈퇴시까지</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_DormantContact_ba_ts.cls
/****************************************************************************************
  * @filename      : KDCE_DormantContact_ba_ts
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-14 오후 2:12
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-14 오후 2:12     i2max_Jihyun.Lee        Create
****************************************************************************************/

@IsTest
public class KDCE_DormantContact_ba_ts {

    @IsTest
    static void testBehavior() {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();

        Datetime dt = System.now().addYears(-2);

        Contact con = KDCE_TestUtil.contactMember.clone(true);
        con.KDCE_PersonalInfoValidityPeriod__c = '1y';
        con.KDCE_LastCouponUsedDate__c = dt;
        con.KDCE_LastCaseDate__c = dt;
        con.KDCE_LastCloseDate__c = dt;
        con.KDCE_LastCRMResponseDate__c = dt;
        con.KDCE_LastNPSResponseDate__c = dt ;
        update con;

        System.debug(con.KDCE_fm_IsTargetDormant__c);

        Test.startTest();
        KDCE_DormantContact_ba batch = new KDCE_DormantContact_ba();
        Database.executeBatch(batch, 2000);
        Test.stopTest();

    }
}