force-app/main/default/objects/Contact/fields/KDCE_ConvertDormantDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ConvertDormantDate__c</fullName>
    <description>[KDCE] 휴면고객으로 전환된 일</description>
    <label>Dormant Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsDormant__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDormant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 배치로 인해 휴면 처리가 된 고객</description>
    <label>Dormant Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/KDCE_DormantOrder__c.object-meta.xml
<CustomObject>
    <description>휴면 전환된 고객의 Order 정보 분리 보관</description>
    <label>Dormant Order</label>
    <nameField>
        <displayFormat>DormantOrder{YY}{MM}{DD}{000000}</displayFormat>
        <label>Dormant Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dormant Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <externalId>true</externalId>
    <label>Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/CustomerEmail__c.field-meta.xml
<CustomField>
    <fullName>CustomerEmail__c</fullName>
    <description>[KDCE] 고객 이메일
            Mapping Column : customer_email</description>
    <inlineHelpText>고객 이메일</inlineHelpText>
    <label>Customer Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <description>[KDCE] 고객번호
            Mapping Column : customer_id</description>
    <inlineHelpText>고객번호</inlineHelpText>
    <label>Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <description>[KDCE] 고객 이름
            Mapping Column : customer_name</description>
    <inlineHelpText>고객 이름</inlineHelpText>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/ShippingAddress1__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress1__c</fullName>
    <description>[KDCE] 배송지 주소1
Mapping Column : shipping_address1</description>
    <inlineHelpText>배송지 주소1</inlineHelpText>
    <label>Shipping Address1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/ShippingAddress2__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress2__c</fullName>
    <description>[KDCE] 배송지 주소2
Mapping Column : shipping_address2</description>
    <inlineHelpText>배송지 주소2</inlineHelpText>
    <label>Shipping Address2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/ShippingAddressName__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddressName__c</fullName>
    <description>[KDCE] 수령고객 명
            Mapping Column : shipping_address_name</description>
    <inlineHelpText>수령고객 명</inlineHelpText>
    <label>Shipping Address Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/ShippingCity__c.field-meta.xml
<CustomField>
    <fullName>ShippingCity__c</fullName>
    <description>[KDCE] 배송지 도시
            Mapping Column : shipping_city</description>
    <inlineHelpText>배송지 도시</inlineHelpText>
    <label>Shipping City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/ShippingPhone__c.field-meta.xml
<CustomField>
    <fullName>ShippingPhone__c</fullName>
    <description>[KDCE] 배송지 전화번호
            Mapping Column : shipping_phone</description>
    <inlineHelpText>배송지 전화번호</inlineHelpText>
    <label>Shipping Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/ShippingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>ShippingPostalCode__c</fullName>
    <description>[KDCE] 배송지 우편번호
            Mapping Column : shipping_postal_code</description>
    <inlineHelpText>배송지 우편번호</inlineHelpText>
    <label>Shipping Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/ShippingState__c.field-meta.xml
<CustomField>
    <fullName>ShippingState__c</fullName>
    <description>Order Shipping State</description>
    <label>ShippingState</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantOrder__c/fields/ShippingStreet__c.field-meta.xml
<CustomField>
    <fullName>ShippingStreet__c</fullName>
    <description>Order Shipping Street</description>
    <label>ShippingStreet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/KDCE_Order__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Order</description>
    <label>Order</label>
    <nameField>
        <displayFormat>KO{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/CustomerEmail__c.field-meta.xml
<CustomField>
    <fullName>CustomerEmail__c</fullName>
    <description>[KDCE] 고객 이메일
Mapping Column : customer_email</description>
    <inlineHelpText>고객 이메일</inlineHelpText>
    <label>Customer Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <description>[KDCE] 고객번호
Mapping Column : customer_id</description>
    <inlineHelpText>고객번호</inlineHelpText>
    <label>Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <description>[KDCE] 고객 이름
Mapping Column : customer_name</description>
    <inlineHelpText>고객 이름</inlineHelpText>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingAddressName__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddressName__c</fullName>
    <description>[KDCE] 수령고객 명
Mapping Column : shipping_address_name</description>
    <inlineHelpText>수령고객 명</inlineHelpText>
    <label>Shipping Address Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingCity__c.field-meta.xml
<CustomField>
    <fullName>ShippingCity__c</fullName>
    <description>[KDCE] 배송지 도시
Mapping Column : shipping_city</description>
    <inlineHelpText>배송지 도시</inlineHelpText>
    <label>Shipping City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingPhone__c.field-meta.xml
<CustomField>
    <fullName>ShippingPhone__c</fullName>
    <description>[KDCE] 배송지 전화번호
Mapping Column : shipping_phone</description>
    <inlineHelpText>배송지 전화번호</inlineHelpText>
    <label>Shipping Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>ShippingPostalCode__c</fullName>
    <description>[KDCE] 배송지 우편번호
Mapping Column : shipping_postal_code</description>
    <inlineHelpText>배송지 우편번호</inlineHelpText>
    <label>Shipping Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingState__c.field-meta.xml
<CustomField>
    <fullName>ShippingState__c</fullName>
    <description>Order Shipping State</description>
    <label>ShippingState</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingStreet__c.field-meta.xml
<CustomField>
    <fullName>ShippingStreet__c</fullName>
    <description>Order Shipping Street</description>
    <label>ShippingStreet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_DormantOrder_ba.cls
/****************************************************************************************
  * @filename      : KDCE_DormantOrder_ba
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-10 오후 5:25
  * @group         : 
  * @group-content : 
  * @description   : Contact 휴면 전환시, Contact과 관련된 Order 분리보관 및 개인정보 Null처리
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-10 오후 5:25     i2max_Jihyun.Lee        Create
****************************************************************************************/
/*******************************************************************************************
 * Serial Batch Order
 * 1. KDCE_DormantContact_ba:        Contact 휴면 처리 (Contact 정보 Null처리). Member일 경우는 분리보관 및 개인정보 Null처리
 * 2. KDCE_DormantCase_ba:           Contact 휴면 전환시, Contact과 관련된 Case 분리보관 및 개인정보 Null처리
 * 3. KDCE_DormantOrderLineItem_ba:  Contact 휴면 전환시, Contact과 관련된 Order Line Item 분리보관 및 개인정보 Null처리
 * 4. KDCE_DormantOrder_ba:          Contact 휴면 전환시, Contact과 관련된 Order 분리보관 및 개인정보 Null처리
 * 5. KDCE_DormantOfflineProgram_ba: Contact 휴면 전환시, Contact과 관련된 Offline Program 분리보관 및 개인정보 Null처리
 *******************************************************************************************/

public with sharing class KDCE_DormantOrder_ba implements Database.Batchable<sObject>, Database.Stateful  {

    //public Set<Id> batchContactIds;

    String objectName = 'KDCE_Order__c';
    String query = 'SELECT ';
    Map<String, Schema.SObjectField> orderFieldMap = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap();


    public Database.QueryLocator start(Database.BatchableContext BC) {
        //System.debug('=== batchContactIds : ' + batchContactIds);

        for (String fieldName : orderFieldMap.keySet()) {
            if (query != 'SELECT ') query += ' ,';      // 첫번째 필드가 아닐 경우 , 붙이기
            query += fieldName;
        }
        query += ' FROM ';
        query += objectName;
        query += ' WHERE Contact__r.KDCE_IsDormant__c = TRUE AND Contact__r.KDCE_ConvertDormantDate__c = TODAY ';
        //query += ' WHERE Contact__c IN :batchContactIds';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {

        Map<String, Schema.SObjectField> objectSchema = Schema.SObjectType.KDCE_Order__c.fields.getMap();
        Set<String> notNullField = new Set<String>{
                'id', 'ownerid'
        };
        Set<String> nullField = new Set<String>{
                'contact__c', 'customerid__c', 'customername__c', 'customeremail__c',
                'shippingaddressname__c', 'shippingaddress1__c', 'shippingaddress2__c',
                'shippingphone__c', 'shippingstreet__c', 'shippingpostalcode__c',
                'shippingstate__c', 'shippingcity__c'
        };
        
        KDCE_ContactSeparateService.separateObject('Dormant', 'KDCE_Order__c', 'KDCE_DormantOrder__c', scope);
        KDCE_ContactSeparateService.setNullField('Dormant', 'KDCE_Order__c', scope, objectSchema, notNullField, nullField);

    }

    public void finish(Database.BatchableContext BC) {
        KDCE_DormantOfflineProgram_ba nextBatch = new KDCE_DormantOfflineProgram_ba();
        //nextBatch.batchContactIds = batchContactIds;
        Database.executeBatch(nextBatch, 200);
    }
}