force-app/main/default/objects/Contact/fields/KDCE_IsDormant__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDormant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 배치로 인해 휴면 처리가 된 고객</description>
    <label>Dormant Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsDropout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDropout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 탈퇴고객으로 전환된 고객</description>
    <label>DropOut Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>[KDCE] Coupon Price</description>
    <label>Coupon Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/ChannelDetails__c.field-meta.xml
<CustomField>
    <fullName>ChannelDetails__c</fullName>
    <description>[KDCE] CVS Channel</description>
    <label>CVS Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CU</fullName>
                <label>CU 편의점</label>
            </value>
            <value>
                <fullName>GS</fullName>
                <label>GS25 편의점</label>
            </value>
            <value>
                <fullName>MS</fullName>
                <label>미니스톱 편의점</label>
            </value>
            <value>
                <fullName>K7</fullName>
                <label>세븐일레븐 편의점</label>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>씨스페이스 편의점</label>
            </value>
            <value>
                <fullName>EM</fullName>
                <label>이마트24(위드미) 편의점</label>
            </value>
            <value>
                <fullName>SS</fullName>
                <label>일반 소매점</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/CouponCode__c.field-meta.xml
<CustomField>
    <fullName>CouponCode__c</fullName>
    <description>[KDCE] Coupon Code</description>
    <externalId>true</externalId>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <description>[KDCE] Coupon Expiry Date</description>
    <label>Coupon Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/ExternalType__c.field-meta.xml
<CustomField>
    <fullName>ExternalType__c</fullName>
    <description>데이터가 너무 많아 쿼리를 하기 위한 External Field (MGM 발급에서 사용)</description>
    <externalId>true</externalId>
    <label>ExternalType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/IssuableDate__c.field-meta.xml
<CustomField>
    <fullName>IssuableDate__c</fullName>
    <label>Coupon Issuable Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/IssueChannel__c.field-meta.xml
<CustomField>
    <fullName>IssueChannel__c</fullName>
    <label>Issue Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/IssueDate__c.field-meta.xml
<CustomField>
    <fullName>IssueDate__c</fullName>
    <description>[KDCE] Coupon Issue Date</description>
    <label>Issue Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>[KDCE] Coupon Type</description>
    <label>Coupon Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MGM</fullName>
            </value>
            <value>
                <fullName>CVS</fullName>
                <label>Special Purchase Code</label>
            </value>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Tradein</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_CVS.recordType-meta.xml
<RecordType>
    <fullName>Coupon_CVS</fullName>
    <active>true</active>
    <description>[KDCE] KA, GT</description>
    <label>Special Purchase Code</label>
</RecordType>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_CVS_Trade_In.recordType-meta.xml
<RecordType>
    <fullName>Coupon_CVS_Trade_In</fullName>
    <active>false</active>
    <label>CVS trade in Purchase coupon</label>
</RecordType>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_GetInfo.recordType-meta.xml
<RecordType>
    <fullName>Coupon_GetInfo</fullName>
    <active>true</active>
    <description>[KDCE] GetInfo</description>
    <label>GetInfo</label>
</RecordType>

force-app/main/default/objects/KDCE_Coupon__c/recordTypes/Coupon_MGM.recordType-meta.xml
<RecordType>
    <fullName>Coupon_MGM</fullName>
    <active>true</active>
    <description>[KDCE] MGM</description>
    <label>MGM</label>
</RecordType>

force-app/main/default/classes/KDCE_CouponIssueQuickController.cls
/****************************************************************************************
  * @filename      : KDCE_CouponIssueQuickController
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-03-16 오전 10:56
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-03-16 오전 10:56     i2max_Jihyun.Lee        Create
****************************************************************************************/

public with sharing class KDCE_CouponIssueQuickController {

    private final static Id RT_Coupon_CVSId             = Schema.SObjectType.KDCE_Coupon__c.getRecordTypeInfosByDeveloperName().get('Coupon_CVS').getRecordTypeId();
    private final static Id RT_Coupon_CVSTr             = Schema.SObjectType.KDCE_Coupon__c.getRecordTypeInfosByDeveloperName().get('Coupon_CVS_Trade_In').getRecordTypeId(); // 21.08.31 'CVS trade in Purchase coupon' 레코드 유형 추가
    private final static Id RT_Coupon_GetInfo           = Schema.SObjectType.KDCE_Coupon__c.getRecordTypeInfosByDeveloperName().get('Coupon_GetInfo').getRecordTypeId();
    private final static Id RT_Coupon_MGM               = Schema.SObjectType.KDCE_Coupon__c.getRecordTypeInfosByDeveloperName().get('Coupon_MGM').getRecordTypeId();

    // Coupon Record Type Name 별 Id
    private final static Map<String, Id> couponRtNameId = KDCE_Util.getRecordTypeNameBySObject('KDCE_Coupon__c');
    private final static Map<String, Id> couponRtDevNameId = KDCE_Util.getRecordTypeBySObject('KDCE_Coupon__c');

    @AuraEnabled
    public static Boolean getInvalidContact(Id recordId) {
        Boolean invalidContact = false;
        Contact con = [SELECT Id, KDCE_IsDropout__c, KDCE_IsDormant__c FROM Contact WHERE Id = :recordId];
        if (con.KDCE_IsDropout__c == true || con.KDCE_IsDormant__c) invalidContact = true;

        System.debug('=== invalidContact : ' + invalidContact);
        return invalidContact;
    }

    // Picklist Value 값 가져옴
    @AuraEnabled
    public static Map<String, List<String>> getPickListValuesList() {

        System.debug('=== getPickListValuesList : ');
        Map<String, List<String>> returnValueMap    = new Map<String, List<String>>(); // Return Value Map
        List<String> couponRecordTypeList           = new List<String>();   // Coupon Record Type
        List<String> couponCVSList                  = new List<String>();   // Coupon CVS

        // Channel Record Type
        for (String rtName : couponRtNameId.keySet()) {
            if(rtName.contains('Purchase')) couponRecordTypeList.add(rtName); // Record Type Name
        }
        returnValueMap.put('couponType', couponRecordTypeList);

        // Channel Detail (CVS) -> CVS 일 경우에만
        SObjectField picklistUsingGlobal    = SObjectType.KDCE_Coupon__c.fields.ChannelDetails__c.getSObjectField();
        List<PicklistEntry> entries         = picklistUsingGlobal.getDescribe().getPicklistValues();
        for (PicklistEntry entry : entries) {
            couponCVSList.add(String.valueOf(entry.label));
        }
        returnValueMap.put('channelCVS', couponCVSList);
        System.debug('=== returnValueMap : ' + returnValueMap);

        return returnValueMap;
    }

    // Coupon Record Type이 'CVS'인 경우에만 Channel CVS 선택가능

    @AuraEnabled
    public static Map<String, Object> checkValidChannelCVS(String selectedCouponType) {
        Map<String, Object> returnValueMap = new Map<String, Object>(); 
        Boolean checkValid = false;
        List<String> couponCVSList = new List<String>();
        Id couponTypeId = couponRtNameId.get(selectedCouponType);
        SObjectField picklistUsingGlobal    = SObjectType.KDCE_Coupon__c.fields.ChannelDetails__c.getSObjectField();
        List<PicklistEntry> entries         = picklistUsingGlobal.getDescribe().getPicklistValues();

        if (selectedCouponType == 'CVS trade in Purchase coupon') {
            for (PicklistEntry entry : entries) {
                if(String.valueOf(entry.label).contains('GS25')) couponCVSList.add(String.valueOf(entry.label));
            }
        }else{
            for (PicklistEntry entry : entries) {
               couponCVSList.add(String.valueOf(entry.label));
            }
        }
        returnValueMap.put('channelCVS', couponCVSList);
        System.debug('=== returnValueMap : ' + returnValueMap);

        if (couponTypeId == RT_Coupon_CVSId || couponTypeId == RT_Coupon_CVSTr) checkValid = true; // 21.08.31 couponTypeId == RT_Coupon_CVSTr 추가 ('CVS trade in Purchase coupon')
        returnValueMap.put('checkValid', checkValid);
        return returnValueMap;
    }
/*
    @AuraEnabled
    public static Boolean checkValidChannelCVS(String selectedCouponType) {
        Boolean checkValid = false;
        Id couponTypeId = couponRtNameId.get(selectedCouponType);

        if (couponTypeId == RT_Coupon_CVSId) checkValid = true;
        return checkValid;
    }

    @AuraEnabled
    public static Map<String, List<String>> checkCouponType(String selectedCouponType) {
        Map<String, List<String>> returnValueMap = new Map<String, List<String>>(); 
        Boolean checkValid = false;
        List<String> couponCVSList = new List<String>();
        Id couponTypeId = couponRtNameId.get(selectedCouponType);
        if (couponTypeId == RT_Coupon_CVSTr) {
            SObjectField picklistUsingGlobal    = SObjectType.KDCE_Coupon__c.fields.ChannelDetails__c.getSObjectField();
            List<PicklistEntry> entries         = picklistUsingGlobal.getDescribe().getPicklistValues();

            for (PicklistEntry entry : entries) {
                if(String.valueOf(entry.label).contains('GS25')) couponCVSList.add(String.valueOf(entry.label));
            }
            returnValueMap.put('channelCVS', couponCVSList);
            System.debug('=== returnValueMap : ' + returnValueMap);
            return returnValueMap;
        }
*/
    // 쿠폰 리스트 반환
    @AuraEnabled
    public static List<KDCE_Coupon__c> getCouponList(Id recordId, String selectedCouponType, String selectedChannelCVS) {

        System.debug('=== selectedCouponType : ' + selectedCouponType);
        System.debug('=== selectedChannelCVS : ' + selectedChannelCVS);
        Id couponTypeId;
        String channelCVS;
        String channelTypeAPIName;

        // 쿠폰 유형 Id
        couponTypeId = couponRtNameId.get(selectedCouponType);

        // 쿠폰 Channel CVS Id
        SObjectField picklistUsingGlobal    = SObjectType.KDCE_Coupon__c.fields.ChannelDetails__c.getSObjectField();
        List<PicklistEntry> entries         = picklistUsingGlobal.getDescribe().getPicklistValues();
        for (PicklistEntry entry : entries) {
            if (String.valueOf(entry.label) == selectedChannelCVS) channelCVS = String.valueOf(entry.value);
        }

        // 쿠폰 Type Development Name
        SObjectField picklistTypeObjectField = SObjectType.KDCE_Coupon__c.fields.Type__c.getSObjectField();
        List<PicklistEntry> entriesTypeEntries = picklistTypeObjectField.getDescribe().getPicklistValues();
        for (PicklistEntry entry : entriesTypeEntries) {
            if (String.valueOf(entry.label) == selectedCouponType) channelTypeAPIName = String.valueOf(entry.value);
        }

        // 발급가능한 쿠폰 검색  // TODO 가장 먼저 발급할 쿠폰을 어떤 기준으로 뽑을지 정의 필요
        String query = '';
        query += ' SELECT   CouponCode__c, Status__c, ExpiryDate__c, Contact__c, Amount__c  ';
        query += ' FROM     KDCE_Coupon__c                                                  ';
        query += ' WHERE    Contact__c = NULL                                               ';
        query += ' AND      ExternalType__c = :channelTypeAPIName                           ';
        query += ' AND      RecordTypeId = :couponTypeId                                    ';
        query += ' AND      Status__c = \'Produce\'                                         ';
        if (couponTypeId == RT_Coupon_CVSId){
            query += ' AND ChannelDetails__c = :channelCVS ';
            query += ' AND IssuableDate__c >= TODAY ';
        }
        query += ' LIMIT    1                                                               ';
        List<KDCE_Coupon__c> couponList = Database.query(query);
        System.debug('=== query : ' + query);
        System.debug('=== couponList : ' + couponList);

        return couponList;
    }

    @AuraEnabled
    public static Boolean saveCouponList(Id recordId, List<KDCE_Coupon__c> couponList) {
        System.debug('=== couponList : ' + couponList);

        Boolean contactLink = false;

        // Contact 연결 재확인
        Set<Id> couponIds = new Set<Id>();
        for (KDCE_Coupon__c coupon : couponList) couponIds.add(coupon.Id);
        List<KDCE_Coupon__c> saveCouponList = [
                SELECT Id, Contact__c, Status__c, IssueChannel__c, IssueDate__c
                FROM KDCE_Coupon__c WHERE Id IN :couponIds];

        for (KDCE_Coupon__c coupon : saveCouponList) {
            System.debug('=== coupon.Contact__c : ' + coupon.Contact__c);
            if (coupon.Contact__c != null) {
                contactLink = true;
                return contactLink;
            }
            coupon.Status__c        = KDCE_GlobalValue.COUPON_STATUS_ISSUE;
            coupon.Contact__c       = recordId;
            coupon.IssueChannel__c  = 'Call Center';
            coupon.IssueDate__c     = System.now();
        }

        update saveCouponList;
        return contactLink;
    }

}