force-app/main/default/objects/Contact/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>[KDCE] Contact Key SpiceID 대체</description>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>[i2sema] Notification Sending Infomations
알림 메세지 발송정보</description>
    <label>Notifications</label>
    <nameField>
        <displayFormat>N{yyMMdd}{0000000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Channel</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL1__c.field-meta.xml
<CustomField>
    <fullName>LABEL1__c</fullName>
    <label>LABEL1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL2__c.field-meta.xml
<CustomField>
    <fullName>LABEL2__c</fullName>
    <label>LABEL2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL3__c.field-meta.xml
<CustomField>
    <fullName>LABEL3__c</fullName>
    <label>LABEL3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL4__c.field-meta.xml
<CustomField>
    <fullName>LABEL4__c</fullName>
    <label>LABEL4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL5__c.field-meta.xml
<CustomField>
    <fullName>LABEL5__c</fullName>
    <label>LABEL5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/NotificationGroup__c.field-meta.xml
<CustomField>
    <fullName>NotificationGroup__c</fullName>
    <label>Notification Group</label>
    <referenceTo>NotificationGroup__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/NotificationTemplate__c.field-meta.xml
<CustomField>
    <fullName>NotificationTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Notification Template</description>
    <label>Notification Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>NotificationTemplate__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NotificationTemplate__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NotificationGroup__c/NotificationGroup__c.object-meta.xml
<CustomObject>
    <description>[2020.02.10] Notification 발송요청 묶음</description>
    <label>Notification Group</label>
    <nameField>
        <displayFormat>NG{yyMMdd}{0000000000}</displayFormat>
        <label>Notification Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/NotificationTemplate__c.object-meta.xml
<CustomObject>
    <description>[i2sema] Notification Message Templates
Channel 별 알림 메세지 템플릿 제공</description>
    <label>Notification Template</label>
    <nameField>
        <label>Notification Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Notification 발송 채널</description>
    <label>Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>[20.01.06] 템플릿 내용</description>
    <label>Content</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/fm_LABELCount__c.field-meta.xml
<CustomField>
    <fullName>fm_LABELCount__c</fullName>
    <description>LABEL 유무 카운트</description>
    <formula>IF(LABEL1__c== false, 0, 1)+
IF(LABEL2__c== false, 0, 1)+
IF(LABEL3__c== false, 0, 1)+
IF(LABEL4__c== false, 0, 1)+
IF(LABEL5__c== false, 0, 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LABEL Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <description>KDCE Notiforce Template External Id for Sending API From 3rd Party System.</description>
    <displayFormat>NT-{YY}{MM}{DD}-{00000}</displayFormat>
    <externalId>true</externalId>
    <label>External Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL1__c.field-meta.xml
<CustomField>
    <fullName>LABEL1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL2__c.field-meta.xml
<CustomField>
    <fullName>LABEL2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL3__c.field-meta.xml
<CustomField>
    <fullName>LABEL3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL4__c.field-meta.xml
<CustomField>
    <fullName>LABEL4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL5__c.field-meta.xml
<CustomField>
    <fullName>LABEL5__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL5</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/i2SEMA_Util_ts.cls
/****************************************************************************************
  * @filename      : i2SEMA_Util_ts
  * @projectname   : i2SEMA Core
  * @author        : i2max_shlee 
  * @date          : 2020/04/22 7:59 PM
  * @group         : e.g)tab name
  * @group-content : e.g)view file  
  * @description   : 
  * @tester        : i2SEMA_Util_ts_ts.cls
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                author              description
  * ===============================================================
    0.1     2020/04/22 7:59 PM     i2max_shlee       Create
****************************************************************************************/
@IsTest
public with sharing class i2SEMA_Util_ts {

    /**
     * @description Test Data 생성
     */
    @TestSetup static void setup(){

        i2SEMA_TestDataUtil.getSMSNotification();
    }

    /**
     * @description notification 재시도 initialize 실행
     */
    static testmethod void testCase01(){
        Notification__c notification = null;
        System.assertEquals(i2SEMA_Util.isEmpty(notification), true);
        System.assertEquals(i2SEMA_Util.isNotEmpty(notification), false);

        String test01 = '';
        System.assertEquals(i2SEMA_Util.isEmpty(test01), true);
        System.assertEquals(i2SEMA_Util.isNotEmpty(test01), false);

//        System.assertEquals(i2SEMA_Util.isEmpty(i2SEMA_TestDataUtil.smsTemplate), false);
//        System.assertEquals(i2SEMA_Util.isNotEmpty(i2SEMA_TestDataUtil.smsTemplate), true);

        String test02 = 'null';
        System.assertEquals(i2SEMA_Util.convertIFString(test02), '');
        System.assertNotEquals(i2SEMA_Util.convertEmpty(test02), '');

        String test03 = '010-2288-4132';
        System.assertEquals(i2SEMA_Util.convertPhoneNumberFormat(test03), '01022884132');

        Map<String,String> picklistVal = i2SEMA_Util.getPicklistValue('NotificationTemplate__c','Channel__c');
        System.debug('picklistVal : '+picklistVal);
        System.assertEquals(picklistVal.get('0'), 'SMS');
        System.assertEquals(picklistVal.get('2'), 'MMS');
        System.assertEquals(picklistVal.get('3'), 'LMS');

        List<String> sObjectTypes = new List<String>{'NotificationTemplate__c','Notification__c','NotificationGroup__c'};
        Map<String,Object> sObjectTypeMap = i2SEMA_Util.getSObjectDescribe(sObjectTypes);
        System.debug(sObjectTypeMap.get('NotificationTemplate__c'));
//        System.assertEquals(sObjectTypeMap.get('NotificationTemplate__c'));

        System.assertEquals(i2SEMA_Util.isValidMessageLength('0', '안녕하세요.'), true);
        System.assertEquals(i2SEMA_Util.isValidMessageLength('0', '안녕하세요.안녕하세요.안녕하세요.안녕하세요.안녕하세요.안녕하세요.안녕하세요.안녕하세요.안녕하세요.안녕하세요.안녕하세요.안녕하세요.'), false);
        System.assertEquals(i2SEMA_Util.isValidMessageLength('2', '안녕하세요.'), true);
        System.assertEquals(i2SEMA_Util.isValidMessageLength('3', '안녕하세요.'), true);
        System.assertEquals(i2SEMA_Util.isValidMessageLength('1009', '안녕하세요.'), true);
        System.assertEquals(i2SEMA_Util.isValidMessageLength('1008', '안녕하세요.'), true);
        System.assertEquals(i2SEMA_Util.isValidMessageLength('10', '안녕하세요.'), true);


        Datetime myDateTime = Datetime.newInstance(1997, 1, 31, 7, 8, 16);
        System.assertEquals(i2SEMA_Util.convertSchedule(myDateTime), '0 8 7 31 1 ? 1997');

        System.assertEquals(i2SEMA_Util.getFindURLs('String test : www.google.com'), null);

        NotificationTemplate__c nt = new NotificationTemplate__c(Content__c = 'test %%LABEL1%% %%LABEL2%% %%LABEL3%% %%LABEL4%% %%LABEL5%%',
                LABEL1__c = true,
                LABEL2__c = true,
                LABEL3__c = true,
                LABEL4__c = true,
                LABEL5__c = true,
                Channel__c = '0' );
        insert nt;
        System.debug('nt  ' + nt.fm_LABELCount__c);

        Contact con = i2SEMA_TestDataUtil.getContact();
        con.KDCE_ExternalId__c = 'testExternalId';
        update con;

        List<i2SEMA_Util.Receiver> receivers = new List<i2SEMA_Util.Receiver>();
        List<String> labels     = new List<String>{'공덕 아이코스점','서울 마포구 마포대로 137','09:00~18:00','test1', 'test2'};
        i2SEMA_Util.Receiver receiver = new i2SEMA_Util.Receiver();
        receiver.receiverExtId  = 'testExternalId';
        receiver.labels         = labels;
        receivers.add(receiver);

        i2SEMA_Util.I2Notification msg = new i2SEMA_Util.I2Notification();
        System.debug('nt.KDCE_ExternalId__c ' + nt.KDCE_ExternalId__c);
        msg.templateExtId   = 'nt.KDCE_ExternalId__c';
        msg.receiverType    = 'Contact';
        msg.receivers       = receivers;

        i2SEMA_Util.sendNotification(msg);
        List<String> btnURLs     = new List<String>{'test'};

        receivers = new List<i2SEMA_Util.Receiver>();
        receiver.btnURLs = btnURLs;
        receivers.add(receiver);

        msg = new i2SEMA_Util.I2Notification();
        System.debug('nt.KDCE_ExternalId__c ' + nt.KDCE_ExternalId__c);
        msg.templateExtId   = 'nt.KDCE_ExternalId__c';
        msg.receiverType    = 'Contact';
        msg.receivers       = receivers;
        i2SEMA_Util.sendNotification(msg);

        i2SEMA_Util.runtest();






    }
}