force-app/main/default/objects/Contact/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>[KDCE] Contact Key SpiceID 대체</description>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_MarketingOptInDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_MarketingOptInDate__c</fullName>
    <label>Marketing Opt-In Change Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_Name__c.field-meta.xml
<CustomField>
    <fullName>KDCE_Name__c</fullName>
    <description>마스킹 처리가 안된 이름 저장</description>
    <externalId>true</externalId>
    <label>Name (No Mask)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_PNKey__c.field-meta.xml
<CustomField>
    <fullName>KDCE_PNKey__c</fullName>
    <description>[KDCE] Record Key 전화번호</description>
    <externalId>true</externalId>
    <label>Contact Key (Phone Number)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/ChannelDetails__c.field-meta.xml
<CustomField>
    <fullName>ChannelDetails__c</fullName>
    <description>[KDCE] CVS Channel</description>
    <label>CVS Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CU</fullName>
                <label>CU 편의점</label>
            </value>
            <value>
                <fullName>GS</fullName>
                <label>GS25 편의점</label>
            </value>
            <value>
                <fullName>MS</fullName>
                <label>미니스톱 편의점</label>
            </value>
            <value>
                <fullName>K7</fullName>
                <label>세븐일레븐 편의점</label>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>씨스페이스 편의점</label>
            </value>
            <value>
                <fullName>EM</fullName>
                <label>이마트24(위드미) 편의점</label>
            </value>
            <value>
                <fullName>SS</fullName>
                <label>일반 소매점</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/CouponCode__c.field-meta.xml
<CustomField>
    <fullName>CouponCode__c</fullName>
    <description>[KDCE] Coupon Code</description>
    <externalId>true</externalId>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <description>[KDCE] Coupon Expiry Date</description>
    <label>Coupon Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/IsAvailable__c.field-meta.xml
<CustomField>
    <fullName>IsAvailable__c</fullName>
    <formula>OR(
	AND(RecordType.DeveloperName = &apos;Coupon_Paper&apos;, 
		NOT(ISPICKVAL(Status__c, &apos;Use&apos;))
	),
	AND(RecordType.DeveloperName = &apos;Coupon_Tradein&apos;, 
		NOT(ISPICKVAL(Status__c, &apos;Use&apos;))
	),
	AND(RecordType.DeveloperName = &apos;Coupon_MGM&apos;, 
		NOT(ISPICKVAL(Status__c, &apos;Produce&apos;)), 
		ru_UseCount__c &lt; 10
	),
	AND(ISPICKVAL(Status__c, &apos;Issue&apos;),
		fm_UseCount__c = 0
	), 
	AND(RecordType.DeveloperName = &apos;Coupon_Accessory&apos;, 
		fm_UseCount__c = 0
	),
	AND(RecordType.DeveloperName = &apos;Coupon_Hotel&apos;, 
		fm_UseCount__c &lt; 2
	)
)</formula>
    <label>Available YN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>[KDCE] Coupon Type</description>
    <label>Coupon Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MGM</fullName>
            </value>
            <value>
                <fullName>CVS</fullName>
                <label>Special Purchase Code</label>
            </value>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Tradein</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>[i2sema] Notification Sending Infomations
알림 메세지 발송정보</description>
    <label>Notifications</label>
    <nameField>
        <displayFormat>N{yyMMdd}{0000000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Channel</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL1__c.field-meta.xml
<CustomField>
    <fullName>LABEL1__c</fullName>
    <label>LABEL1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL2__c.field-meta.xml
<CustomField>
    <fullName>LABEL2__c</fullName>
    <label>LABEL2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL3__c.field-meta.xml
<CustomField>
    <fullName>LABEL3__c</fullName>
    <label>LABEL3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LABEL4__c.field-meta.xml
<CustomField>
    <fullName>LABEL4__c</fullName>
    <label>LABEL4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/NotificationGroup__c.field-meta.xml
<CustomField>
    <fullName>NotificationGroup__c</fullName>
    <label>Notification Group</label>
    <referenceTo>NotificationGroup__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/NotificationTemplate__c.field-meta.xml
<CustomField>
    <fullName>NotificationTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Notification Template</description>
    <label>Notification Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>NotificationTemplate__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NotificationTemplate__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/RawContents__c.field-meta.xml
<CustomField>
    <fullName>RawContents__c</fullName>
    <label>Raw Contents</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>메세지CL? 타입  1:광고성, 2:정보성.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cl_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NotificationGroup__c/NotificationGroup__c.object-meta.xml
<CustomObject>
    <description>[2020.02.10] Notification 발송요청 묶음</description>
    <label>Notification Group</label>
    <nameField>
        <displayFormat>NG{yyMMdd}{0000000000}</displayFormat>
        <label>Notification Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/NotificationTemplate__c.object-meta.xml
<CustomObject>
    <description>[i2sema] Notification Message Templates
Channel 별 알림 메세지 템플릿 제공</description>
    <label>Notification Template</label>
    <nameField>
        <label>Notification Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Notification 발송 채널</description>
    <label>Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>[20.01.06] 템플릿 내용</description>
    <label>Content</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <description>KDCE Notiforce Template External Id for Sending API From 3rd Party System.</description>
    <displayFormat>NT-{YY}{MM}{DD}-{00000}</displayFormat>
    <externalId>true</externalId>
    <label>External Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL1__c.field-meta.xml
<CustomField>
    <fullName>LABEL1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL2__c.field-meta.xml
<CustomField>
    <fullName>LABEL2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL3__c.field-meta.xml
<CustomField>
    <fullName>LABEL3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/LABEL4__c.field-meta.xml
<CustomField>
    <fullName>LABEL4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LABEL4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>메세지 CL 타입  1:광고성, 2:정보성</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cl_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_CouponResendQa.cls
/****************************************************************************************
 * @filename      : KDCE_CouponResendQa
 * @projectname   : PMK Local DCE QA
 * @author        : i2max_Sukun
 * @date          : 4/9/21 1:45 PM
 * @group         : Service
 * @group-content :
 * @description   : Server-Side Controller for KDCE_CouponResendQa Component.
 * @tester        :
 * @reference     :
 * @copyright     : Copyright © I2max. All Rights Reserved.
 * @modification Log
 * ===============================================================
 * ver     date                     author              description
 * ===============================================================
 0.1     4/9/21 1:45 PM            i2max_Sukun           Create
 ****************************************************************************************/
public with sharing class KDCE_CouponResendQa {

    //     재전송 쿠폰 Template External Id
    private static final String TEMPLATE_EXTERNAL_ID = System.Label.KDCE_CPN_TEMPLT_RESEND;
    private static final String CVS_TEMPL       = System.Label.KDCE_NotificationTemplate_Coupon_CVS;
    private static final String GETINFO_TEMPL   = System.Label.KDCE_NotificationTemplate_Coupon_GetInfo;
    private static final String MGM_TEMPL       = System.Label.KDCE_NotificationTemplate_Coupon_MGM;
    //public static String testNotificationTemplateId;

    private static Map<String, String> pvMap_Coupon_channel = KDCE_Util.getPicklistValue('KDCE_Coupon__c', 'ChannelDetails__c');


    /**
    * init
    * @param recordId
    * @return KDCE_ComponentResponse 
    */
    @AuraEnabled
    public static KDCE_ComponentResponse init(String recordId) {
        system.debug('[KDCE_CouponResendQa] - initialize');
        KDCE_ComponentResponse response = new KDCE_ComponentResponse();

        System.debug('initialize recordId : ' + recordId); // template notification이 아닌, Coupon 의 record Id

        // Ref, Req Data
        ReferenceData refData = new ReferenceData(recordId);
        RequestData reqData = new RequestData(recordId);

        // Notification Template External Id 하드코딩
        //NotificationTemplate__c notificationTemplate = !Test.isRunningTest() ? [SELECT Id, Content__c FROM NotificationTemplate__c WHERE KDCE_ExternalId__c = :TEMPLATE_EXTERNAL_ID LIMIT 1] :
         //       [SELECT Id, Content__c FROM NotificationTemplate__c WHERE Id =:testNotificationTemplateId];

        KDCE_Coupon__c currentCouponInfo = [
                SELECT Id, CouponCode__c, ExpiryDate__c, Contact__c, Contact__r.KDCE_Name__c, Contact__r.KDCE_PNKey__c, Type__c, ChannelDetails__c,
                        Contact__r.KDCE_MarketingOptInDate__c, IsAvailable__c
                FROM KDCE_Coupon__c
                WHERE Id = :recordId LIMIT 1];

        String templateExtId = currentCouponInfo.Type__c == KDCE_GlobalValue.COUPON_TYPE_CVS ? CVS_TEMPL : currentCouponInfo.Type__c == KDCE_GlobalValue.COUPON_TYPE_GETINFO ? GETINFO_TEMPL :
                currentCouponInfo.Type__c == KDCE_GlobalValue.COUPON_TYPE_MGM ? MGM_TEMPL :null;
        NotificationTemplate__c notificationTemplate;
        System.debug('templateExtId' + templateExtId);
        if(templateExtId <> null && !Test.isRunningTest())
        notificationTemplate = [
                SELECT Id, Content__c, KDCE_ExternalId__c FROM NotificationTemplate__c WHERE KDCE_ExternalId__c = :templateExtId LIMIT 1
        ];
        if(Test.isRunningTest())  notificationTemplate = [SELECT Id, Content__c, KDCE_ExternalId__c FROM NotificationTemplate__c Limit 1];

        System.debug('notificationTemplate ' + notificationTemplate);

        try {

            if(currentCouponInfo.Type__c == KDCE_GlobalValue.COUPON_TYPE_CVS) {
                String displayText = notificationTemplate.Content__c;
                displayText = displayText.replace('%%LABEL1%%', currentCouponInfo.Contact__r ?.KDCE_Name__c);
                displayText = displayText.replace('%%LABEL2%%', pvMap_Coupon_channel?.get(currentCouponInfo ?.ChannelDetails__c)); // 구입처 참조 가능시 변경
                displayText = displayText.replace('%%LABEL3%%', currentCouponInfo ?.CouponCode__c);
                if (currentCouponInfo.ExpiryDate__c != null) {
                    displayText = displayText.replace('%%LABEL4%%', '~' + currentCouponInfo.ExpiryDate__c);
                    reqData.notification.LABEL4__c = String.valueOf(currentCouponInfo ?.ExpiryDate__c);
                } else {
                    displayText = displayText.replace('%%LABEL4%%', '');
                    reqData.notification.LABEL4__c = '';

                }
                System.debug(displayText);
                // set ReferenceData
                refData.content = displayText;
                // set default RequestData
                reqData.rawContent = displayText;
                reqData.templateId = notificationTemplate.Id;
                reqData.contactId = currentCouponInfo.Contact__c;
                reqData.notification.LABEL1__c = currentCouponInfo.Contact__r ?.KDCE_Name__c;
                reqData.notification.LABEL2__c =  pvMap_Coupon_channel?.get(currentCouponInfo ?.ChannelDetails__c); //currentCouponInfo ?.ChannelDetails__c; //'unknown'; // 구입처 참조 가능시 변경
                reqData.notification.LABEL3__c = currentCouponInfo ?.CouponCode__c;
            }

            else if(currentCouponInfo.Type__c == KDCE_GlobalValue.COUPON_TYPE_GETINFO) {
                String displayText = notificationTemplate.Content__c;
                displayText = displayText.replace('%%LABEL1%%', currentCouponInfo ?.CouponCode__c);
                String expiexpiryD = currentCouponInfo.ExpiryDate__c == null ? '' : String.valueOf(currentCouponInfo.ExpiryDate__c);
                String optInD = currentCouponInfo.Contact__r.KDCE_MarketingOptInDate__c == null ? '' : String.valueOf(currentCouponInfo.Contact__r.KDCE_MarketingOptInDate__c);
                displayText = displayText.replace('%%LABEL2%%', expiexpiryD);
                displayText = displayText.replace('%%LABEL3%%', optInD);

                System.debug('displayText :: ' + displayText);
                // set ReferenceData
                refData.content = displayText;
                // set default RequestData
                reqData.rawContent = displayText;
                reqData.templateId = notificationTemplate.Id;
                reqData.contactId = currentCouponInfo.Contact__c;
                reqData.notification.LABEL1__c = currentCouponInfo ?.CouponCode__c;
                reqData.notification.LABEL2__c =  expiexpiryD;
                reqData.notification.LABEL3__c =  optInD;
            }

            else if(currentCouponInfo.Type__c == KDCE_GlobalValue.COUPON_TYPE_MGM) {
                String displayText = notificationTemplate.Content__c;
                displayText = displayText.replace('%%LABEL1%%', currentCouponInfo ?.CouponCode__c);

                System.debug(displayText);
                // set ReferenceData
                refData.content = displayText;
                // set default RequestData
                reqData.rawContent = displayText;
                reqData.templateId = notificationTemplate.Id;
                reqData.contactId = currentCouponInfo.Contact__c;
                reqData.notification.LABEL1__c = currentCouponInfo ?.CouponCode__c;
            }

        } catch (Exception e) {
            System.debug('Retrieval Failure >> ' + e.getMessage());
        } finally {
            response.setData('refData', refData);
            response.setData('reqData', reqData);
            response.setData('available', currentCouponInfo.IsAvailable__c);
        }

        return response;
    }

    /**
     * save
     * @param recordId
     * @param reqData
     * @return Boolean
     */
    @AuraEnabled
    public static Boolean save(String recordId, Object reqData) {
        System.debug('coupon resend start');
        Boolean allDmlResult = false;

        RequestData requestData = (RequestData)JSON.deserialize(JSON.serialize(reqData), RequestData.class);
        System.debug(requestData);

//        try {
        NotificationGroup__c notificationGroup = new NotificationGroup__c();
        insert notificationGroup;

        NotificationTemplate__c template = [
          SELECT Id, Channel__c, Content__c, Type__c, KDCE_ExternalId__c FROM NotificationTemplate__c WHERE Id = :requestData.templateId LIMIT 1
        ];

        if(Util.isEmpty(template)) throw new AuraHandledException('Template is empty.');

        Notification__c notification = new Notification__c();
        notification.NotificationGroup__c = notificationGroup.Id;
        notification.NotificationTemplate__c = template.Id;
        notification.RawContents__c = template.Content__c;
        notification.Contact__c = requestData.contactId;
        notification.Channel__c = template.Channel__c;
        notification.Type__c = template.Type__c; // 정보성 Noti 타입의 경우

        if (template.KDCE_ExternalId__c == CVS_TEMPL) {
            notification.LABEL1__c = requestData.notification.LABEL1__c;
            notification.LABEL2__c = requestData.notification.LABEL2__c;
            notification.LABEL3__c = requestData.notification.LABEL3__c;
            notification.LABEL4__c = requestData.notification.LABEL4__c;
        }
        else if (template.KDCE_ExternalId__c == GETINFO_TEMPL) {
            notification.LABEL1__c = requestData.notification.LABEL1__c;
            notification.LABEL2__c = requestData.notification.LABEL2__c;
            notification.LABEL3__c = requestData.notification.LABEL3__c;
        }
        else if (template.KDCE_ExternalId__c == MGM_TEMPL) {
            notification.LABEL1__c = requestData.notification.LABEL1__c;
        }

        if (notification <> null) {
            insert notification;
            allDmlResult = TRUE;
        }

        if(!Test.isRunningTest()) {
            i2SEMA_IFNotificationSend_qu messageSendQu = new i2SEMA_IFNotificationSend_qu(notification);
            Id messageSendJobId = System.enqueueJob(messageSendQu);
        }
//        } catch (Exception e) {
//            System.debug('Resend Coupone Notification error >> ' + e.getMessage());
//        }
        System.debug('allDmlResult : '+allDmlResult);
        System.debug('notification : ' + notification);

        return allDmlResult;
    }

    public class ReferenceData {
        @AuraEnabled public String recordId                 { get; set; }
        @AuraEnabled public String content                  { get; set; }

        public ReferenceData() { }
        public ReferenceData(String recordId) {
            this.recordId = recordId;
        }
    }

    public class RequestData {
        @AuraEnabled public String recordId                 { get; set; }
        @AuraEnabled public String templateId               { get; set; }
        @AuraEnabled public String contactId                { get; set; }
        @AuraEnabled public String rawContent               { get; set; }
        @AuraEnabled public Notification__c notification    { get; set; }

        public RequestData() {
            notification = new Notification__c();
        }
        public RequestData(String recordId) {
            this.recordId = recordId;
            notification = new Notification__c();
        }
    }
}