force-app/main/default/objects/Contact/fields/KDCE_LastCaseDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LastCaseDate__c</fullName>
    <description>[KDCE] Contact이 마지막 Case 생성한 날짜</description>
    <label>Last Case Date (Online)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LastCloseDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LastCloseDate__c</fullName>
    <description>[KDCE] 케이스가 종료되는 시점에 업데이트</description>
    <label>Last Case Close Date (Online)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LastCouponUsedDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LastCouponUsedDate__c</fullName>
    <description>[KDCE] CVS Coupon 마지막 사용 날짜</description>
    <label>Last CVS Coupon Burnt Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LastCRMResponseDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LastCRMResponseDate__c</fullName>
    <description>CRM 서베이 답변이 입력되면 업데이트</description>
    <label>Last CRM Survey Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LastLoginDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LastLoginDate__c</fullName>
    <description>[KDCE] 마지막 로그인 날짜</description>
    <label>Last Login Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_LastNPSResponseDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_LastNPSResponseDate__c</fullName>
    <label>Last NPS Survey Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ReactivateDormantDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ReactivateDormantDate__c</fullName>
    <description>[KDCE] Reactivate Dormant Date</description>
    <label>Reactivate Dormant Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/KDCE_OfflineProgram__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Offline Progrma (Trade-in, Upgrade, Rental, Replacement..)</description>
    <label>Offline Program</label>
    <nameField>
        <displayFormat>OP{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offline Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Offline Program</relationshipLabel>
    <relationshipName>OfflineProgram</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_OfflineProgram__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Rental Process</fullName>
            </value>
            <value>
                <fullName>Rental Cancel</fullName>
            </value>
            <value>
                <fullName>Rental Closed</fullName>
            </value>
            <value>
                <fullName>Rental Purchase</fullName>
                <isActive>false</isActive>
                <label>Rental Purchase</label>
            </value>
            <value>
                <fullName>Rental Refund</fullName>
                <isActive>false</isActive>
                <label>Rental Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/KDCE_Order__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Order</description>
    <label>Order</label>
    <nameField>
        <displayFormat>KO{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>[KDCE] 주문 상태
Mapping Column : order_status</description>
    <inlineHelpText>주문 상태</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>processing</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>ready_for_delivery</fullName>
            </value>
            <value>
                <fullName>picking</fullName>
            </value>
            <value>
                <fullName>delivery_collection</fullName>
            </value>
            <value>
                <fullName>complete_delivery</fullName>
            </value>
            <value>
                <fullName>closed</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>cancel</fullName>
            </value>
            <value>
                <fullName>cancel_order</fullName>
            </value>
            <value>
                <fullName>return_received</fullName>
            </value>
            <value>
                <fullName>reject</fullName>
            </value>
            <value>
                <fullName>authorized</fullName>
            </value>
            <value>
                <fullName>approved</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>renting</fullName>
            </value>
            <value>
                <fullName>complete</fullName>
                <label>Complete</label>
            </value>
            <value>
                <fullName>paid</fullName>
            </value>
            <value>
                <fullName>received</fullName>
            </value>
            <value>
                <fullName>processed_closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KDCE_DropOutContactSoftDeletion_ba_ts.cls
/****************************************************************************************
  * @filename      : KDCE_DropOutContactSoftDeletion_ba_ts
  * @projectname   : PMK qa - KR
  * @author        : Park HE
  * @date          : 2021-06-18
  * @group         :
  * @group-content :
  * @description   :
  * @tester        :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                    author          description
  * ===============================================================
    0.1     2021-06-18             Park HE         Create
****************************************************************************************/

@IsTest
private class KDCE_DropOutContactSoftDeletion_ba_ts {

    //static Contact cont;

    @TestSetup
    static void testBehavior() {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();

        List<SObject> sObjects = new List<SObject>();
        Contact cont = KDCE_TestUtil.contactProspect.clone(false);
        cont.KDCE_LastLoginDate__c = System.today().addMonths(-13);
        cont.Email = 'test@test.net';
        cont.Phone = '01098765432';
        cont.LastName = 'contTest';
        insert cont;

        Case ca = KDCE_TestUtil.caseItem.clone(true);
        ca.ContactId = cont.Id;
        ca.Status = KDCE_GlobalValue.CASE_STATUS_CLOSED;
        Test.setCreatedDate(ca.Id, System.today().addMonths(-15));
        sObjects.add(ca);


        KDCE_Order__c order = KDCE_TestBizUtil.order.clone(true);
        order.Contact__c = cont.Id;
        order.OrderStatus__c = KDCE_GlobalValue.ORDER_STATUS_CLOSE;
        sObjects.add(order);

        KDCE_OfflineProgram__c offline = KDCE_TestBizUtil.offlineProgram.clone(true);
        offline.Contact__c = cont.Id;
        offline.Status__c = KDCE_GlobalValue.OFF_PG_STATUS_COMPLETE;
        sObjects.add(offline);

        update sObjects;

    }

    @IsTest
    static void testBehavior2() {
        Test.startTest();

        Contact cont = [SELECT Id FROM Contact LIMIT 1];

        cont.KDCE_LastLoginDate__c = System.today().addMonths(-13);
        cont.KDCE_LastCouponUsedDate__c = System.today().addMonths(-13);
        cont.KDCE_LastCaseDate__c = System.today().addMonths(-13);
        cont.KDCE_LastCloseDate__c = System.today().addMonths(-13);
        cont.KDCE_LastCRMResponseDate__c = System.today().addMonths(-13);
        cont.KDCE_LastNPSResponseDate__c = System.today().addMonths(-13);
        cont.KDCE_ReactivateDormantDate__c = System.today().addMonths(-13);
        //sObjects.add(cont);
        update cont;

        Database.executeBatch(new KDCE_DropOutContactSoftDeletion_ba(), 200);
        Test.stopTest();
    }
}