force-app/main/default/objects/Contact/fields/KDCE_DropoutDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DropoutDate__c</fullName>
    <description>[KDCE] 탈퇴고객으로 전환된 일자</description>
    <label>DropOut Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsDropout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDropout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 탈퇴고객으로 전환된 고객</description>
    <label>DropOut Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrder__c/KDCE_DropOutOrder__c.object-meta.xml
<CustomObject>
    <description>탈퇴 고객 중 Order에 대한 정보 분리 보관</description>
    <label>DropOut Order</label>
    <nameField>
        <displayFormat>DropOutOrder{YY}{MM}{DD}{000000}</displayFormat>
        <label>DropOutOrder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DropOutOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <externalId>true</externalId>
    <label>Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/CustomerEmail__c.field-meta.xml
<CustomField>
    <fullName>CustomerEmail__c</fullName>
    <description>[KDCE] 고객 이메일
            Mapping Column : customer_email</description>
    <inlineHelpText>고객 이메일</inlineHelpText>
    <label>Customer Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <description>[KDCE] 고객번호
            Mapping Column : customer_id</description>
    <inlineHelpText>고객번호</inlineHelpText>
    <label>Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <description>[KDCE] 고객 이름
            Mapping Column : customer_name</description>
    <inlineHelpText>고객 이름</inlineHelpText>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/ShippingAddress1__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress1__c</fullName>
    <description>[KDCE] 배송지 주소1
Mapping Column : shipping_address1</description>
    <inlineHelpText>배송지 주소1</inlineHelpText>
    <label>Shipping Address1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/ShippingAddress2__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress2__c</fullName>
    <description>[KDCE] 배송지 주소2
Mapping Column : shipping_address2</description>
    <inlineHelpText>배송지 주소2</inlineHelpText>
    <label>Shipping Address2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/ShippingAddressName__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddressName__c</fullName>
    <description>[KDCE] 수령고객 명
            Mapping Column : shipping_address_name</description>
    <inlineHelpText>수령고객 명</inlineHelpText>
    <label>Shipping Address Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/ShippingCity__c.field-meta.xml
<CustomField>
    <fullName>ShippingCity__c</fullName>
    <description>[KDCE] 배송지 도시
            Mapping Column : shipping_city</description>
    <inlineHelpText>배송지 도시</inlineHelpText>
    <label>Shipping City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/ShippingPhone__c.field-meta.xml
<CustomField>
    <fullName>ShippingPhone__c</fullName>
    <description>[KDCE] 배송지 전화번호
            Mapping Column : shipping_phone</description>
    <inlineHelpText>배송지 전화번호</inlineHelpText>
    <label>Shipping Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DropOutOrder__c/fields/ShippingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>ShippingPostalCode__c</fullName>
    <description>[KDCE] 배송지 우편번호
            Mapping Column : shipping_postal_code</description>
    <inlineHelpText>배송지 우편번호</inlineHelpText>
    <label>Shipping Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/KDCE_Order__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Order</description>
    <label>Order</label>
    <nameField>
        <displayFormat>KO{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/CustomerEmail__c.field-meta.xml
<CustomField>
    <fullName>CustomerEmail__c</fullName>
    <description>[KDCE] 고객 이메일
Mapping Column : customer_email</description>
    <inlineHelpText>고객 이메일</inlineHelpText>
    <label>Customer Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <description>[KDCE] 고객번호
Mapping Column : customer_id</description>
    <inlineHelpText>고객번호</inlineHelpText>
    <label>Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <description>[KDCE] 고객 이름
Mapping Column : customer_name</description>
    <inlineHelpText>고객 이름</inlineHelpText>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingAddressName__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddressName__c</fullName>
    <description>[KDCE] 수령고객 명
Mapping Column : shipping_address_name</description>
    <inlineHelpText>수령고객 명</inlineHelpText>
    <label>Shipping Address Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingCity__c.field-meta.xml
<CustomField>
    <fullName>ShippingCity__c</fullName>
    <description>[KDCE] 배송지 도시
Mapping Column : shipping_city</description>
    <inlineHelpText>배송지 도시</inlineHelpText>
    <label>Shipping City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingPhone__c.field-meta.xml
<CustomField>
    <fullName>ShippingPhone__c</fullName>
    <description>[KDCE] 배송지 전화번호
Mapping Column : shipping_phone</description>
    <inlineHelpText>배송지 전화번호</inlineHelpText>
    <label>Shipping Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>ShippingPostalCode__c</fullName>
    <description>[KDCE] 배송지 우편번호
Mapping Column : shipping_postal_code</description>
    <inlineHelpText>배송지 우편번호</inlineHelpText>
    <label>Shipping Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingState__c.field-meta.xml
<CustomField>
    <fullName>ShippingState__c</fullName>
    <description>Order Shipping State</description>
    <label>ShippingState</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingStreet__c.field-meta.xml
<CustomField>
    <fullName>ShippingStreet__c</fullName>
    <description>Order Shipping Street</description>
    <label>ShippingStreet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_DropOutOrderSoftDeletion_ba.cls
/****************************************************************************************
  * @filename      : KDCE_DropOutOrderSoftDeletion_ba
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-11 오전 10:31
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : KDCE_DropOutContactSoftDeletion_ba_ts
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-11 오전 10:31     i2max_Jihyun.Lee        Create
****************************************************************************************/

public with sharing class KDCE_DropOutOrderSoftDeletion_ba implements Database.Batchable<sObject>, Database.Stateful {

    //public Set<Id> batchContactIds;

    String objectName = 'KDCE_Order__c';
    String query = 'SELECT ';
    Map<String, Schema.SObjectField> orderFieldMap = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap();


    public Database.QueryLocator start(Database.BatchableContext BC) {

        for (String fieldName : orderFieldMap.keySet()) {
            if (query != 'SELECT ') query += ' ,';      // 첫번째 필드가 아닐 경우 , 붙이기
            query += fieldName;
        }
        query += ' FROM ';
        query += objectName;
        if (!Test.isRunningTest()) query += ' WHERE Contact__r.KDCE_IsDropOut__c = true AND Contact__r.KDCE_DropOutDate__c = TODAY ';
        //query += ' WHERE Contact__c IN :batchContactIds';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {

        Map<String, Schema.SObjectField> objectSchema = Schema.SObjectType.KDCE_Order__c.fields.getMap();
        Set<String> notNullField = new Set<String>{
                'id', 'ownerid'
        };

        Set<String> orderPersonalField = new Set<String>{
                'contact__c', 'customerid__c', 'customername__c', 'customeremail__c',
                'shippingaddressname__c', 'shippingaddress1__c', 'shippingaddress2__c',
                'shippingphone__c', 'shippingstreet__c', 'shippingpostalcode__c',
                'shippingstate__c', 'shippingcity__c'
        };

        /*
        List<KDCE_Order__c> within5YearsList = new List<KDCE_Order__c>();
        Datetime createdDt;
        for(KDCE_Order__c item : (List<KDCE_Order__c>) scope){
            createdDt = Date.newInstance(item.CreatedDate.year(), item.CreatedDate.month(), item.CreatedDate.day());
            System.debug(createdDt);
            if(item.CreatedDate  >  createdDt){
                within5YearsList.add(item);
            }
        }
        */

        //KDCE_ContactSeparateService.separateObject('DropOut', 'KDCE_Order__c', 'KDCE_DropOutOrder__c', within5YearsList);
        KDCE_ContactSeparateService.separateObject('DropOut', 'KDCE_Order__c', 'KDCE_DropOutOrder__c', scope);
        KDCE_ContactSeparateService.setNullField('DropOut', 'KDCE_Order__c', scope, objectSchema, notNullField, orderPersonalField);



    }

    public void finish(Database.BatchableContext BC) {

        KDCE_DropOutOfflineSoftDeletion_ba nextBatch = new KDCE_DropOutOfflineSoftDeletion_ba();
        Database.executeBatch(nextBatch, 200);

        /*
        if(!batchContactIds.isEmpty()) {
            KDCE_DropOutOfflineSoftDeletion_ba nextBatch = new KDCE_DropOutOfflineSoftDeletion_ba();
            nextBatch.batchContactIds = batchContactIds;
            Database.executeBatch(nextBatch, 2000);
        }
        */
    }
}