force-app/main/default/objects/Contact/fields/KDCE_ConvertDormantDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ConvertDormantDate__c</fullName>
    <description>[KDCE] 휴면고객으로 전환된 일</description>
    <label>Dormant Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_DropoutDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DropoutDate__c</fullName>
    <description>[KDCE] 탈퇴고객으로 전환된 일자</description>
    <label>DropOut Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_DropoutRequestDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DropoutRequestDate__c</fullName>
    <description>[KDCE] 탈퇴 요청을 한 일자</description>
    <label>DropOut Request Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>[KDCE] Contact Key SpiceID 대체</description>
    <externalId>true</externalId>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsDormant__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDormant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 배치로 인해 휴면 처리가 된 고객</description>
    <label>Dormant Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsDropout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDropout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 탈퇴고객으로 전환된 고객</description>
    <label>DropOut Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_IsRequestDropout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsRequestDropout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 탈퇴 요청을 한 고객</description>
    <label>DropOut Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_ReactivateDormantDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ReactivateDormantDate__c</fullName>
    <description>[KDCE] Reactivate Dormant Date</description>
    <label>Reactivate Dormant Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_RegistrationChannel__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationChannel__c</fullName>
    <description>[KDCE] Registration Channel</description>
    <inlineHelpText>Registration Channel</inlineHelpText>
    <label>Registration Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>EasyIqos</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
                <default>true</default>
                <label>SC</label>
            </value>
            <value>
                <fullName>iqos.com</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_RegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationDate__c</fullName>
    <description>[KDCE] 고객 등록 시간</description>
    <label>Registration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/KDCE_RegistrationObject__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationObject__c</fullName>
    <description>Contact 별 중복규칙을 다르게 하기 위해 사용되는 필드 (Apex)</description>
    <label>Registration Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantCase__c/KDCE_DormantCase__c.object-meta.xml
<CustomObject>
    <description>휴면 전환된 고객의 Case 정보 분리 보관</description>
    <label>Dormant Case</label>
    <nameField>
        <displayFormat>DormantCase{YY}{MM}{DD}{000000}</displayFormat>
        <label>Dormant Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dormant Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DormantCase__c/fields/KDCE_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ExternalId__c</fullName>
    <label>Consumer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/KDCE_DormantContact__c.object-meta.xml
<CustomObject>
    <description>고객 중 휴면으로 전환된 고객 정보를 저장하기 위한 오브젝트</description>
    <label>Dormant Contact</label>
    <nameField>
        <label>Dormant Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dormant Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_ConvertDormantDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ConvertDormantDate__c</fullName>
    <label>Dormant Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_DropoutDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_DropoutDate__c</fullName>
    <label>DropOut Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_IsDormant__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDormant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dormant Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_IsDropout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsDropout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DropOut Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_IsRequestDropout__c.field-meta.xml
<CustomField>
    <fullName>KDCE_IsRequestDropout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DropOut Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_ReactivateDormantDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_ReactivateDormantDate__c</fullName>
    <label>Reactivate Dormant Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_RegistrationChannel__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationChannel__c</fullName>
    <label>Registration Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IQOS</fullName>
            </value>
            <value>
                <fullName>GetInfo</fullName>
            </value>
            <value>
                <fullName>EasyIqos</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_RegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationDate__c</fullName>
    <label>Registration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_DormantContact__c/fields/KDCE_RegistrationObject__c.field-meta.xml
<CustomField>
    <fullName>KDCE_RegistrationObject__c</fullName>
    <description>Contact 별 중복규칙을 다르게 하기 위해 사용되는 필드 (Apex)</description>
    <label>Registration Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_ContactSeparateService_ts.cls
/****************************************************************************************
  * @filename      : KDCE_ContactSeparateService_ts
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-15 오후 2:31
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-15 오후 2:31     i2max_Jihyun.Lee        Create
****************************************************************************************/

@IsTest
private class KDCE_ContactSeparateService_ts {

    static {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();
    }

    @IsTest
    private static void testBehavior01() {
        List<SObject> contactList = new List<SObject>();
        List<SObject> caseList = new List<SObject>();
        Set<Id> contactIds = new Set<Id>();
        Contact contact = KDCE_TestUtil.contactMember;
        contactList.add(contact);
        contactIds.add(contact.Id);

        Map<String, Schema.SObjectField> contactSchema = Schema.SObjectType.Contact.fields.getMap();
        Map<String, Schema.SObjectField> caseSchema = Schema.SObjectType.Case.fields.getMap();

        // Null처리하면 안되는 필드 저장
        Set<String> notNullField = new Set<String>{
                'id', 'ownerid', 'accountid', 'kdce_externalid__c', 'kdce_registrationchannel__c', 'kdce_registrationdate__c', 'kdce_registrationobject__c',
                'kdce_isdropout__c', 'kdce_dropoutdate__c', 'kdce_isrequestdropout__c', 'kdce_dropoutrequestdate__c',
                'kdce_isdormant__c', 'kdce_convertdormantdate__c', 'kdce_reactivatedormantdate__c'
        };

        // Contact
        KDCE_ContactSeparateService.separateObject('Dormant', 'Contact', 'KDCE_DormantContact__c', contactList);
        KDCE_ContactSeparateService.setNullField('Dormant', 'Contact', contactList, contactSchema, notNullField, null);
        KDCE_ContactSeparateService.setNullField('DropOut', 'Contact', contactList, contactSchema, notNullField, null);
        KDCE_ContactSeparateService.restoreObject('Contact', 'KDCE_DormantContact__c', contactIds, contactList);

        // Case
        Case case2 = KDCE_TestUtil.caseItem;
        caseList.add(case2);
        KDCE_ContactSeparateService.separateObject('Dormant', 'Case', 'KDCE_DormantCase__c', caseList);
        KDCE_ContactSeparateService.setNullField('Dormant', 'Case', caseList, caseSchema, null, null);
        KDCE_ContactSeparateService.restoreObject('Case', 'KDCE_DormantCase__c', contactIds, contactList);

    }
}