force-app/main/default/objects/KakaoConsultDealerCredentials__c/KakaoConsultDealerCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Kakao Consult Dealer Credentials</label>
</CustomObject>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Channel_Secret__c.field-meta.xml
<CustomField>
    <fullName>Channel_Secret__c</fullName>
    <label>Channel Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Customer_Identify_Url__c.field-meta.xml
<CustomField>
    <fullName>Customer_Identify_Url__c</fullName>
    <label>Customer Identify Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/JWT_Token__c.field-meta.xml
<CustomField>
    <fullName>JWT_Token__c</fullName>
    <label>JWT Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Sender_Key__c.field-meta.xml
<CustomField>
    <fullName>Sender_Key__c</fullName>
    <label>Sender Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/KakaoConsult_JWT_Test.cls
/**
 * @description       :
 * @author            : Obidjon
 * @group             :
 * @last modified on  : 04-25-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   04-25-2021   Obidjon   Initial Version
 **/
@isTest
private class KakaoConsult_JWT_Test {
    @testSetup
    private static void testSetup() {
        KakaoConsultDealerCredentials__c dealerCredentials = new KakaoConsultDealerCredentials__c();
        dealerCredentials.Channel_Secret__c = 'channelsecret';
        dealerCredentials.Sender_Key__c = 'senderkey';
        dealerCredentials.JWT_Token__c = 'jwtToken';
        dealerCredentials.Customer_Identify_Url__c = 'https://test.ap24.force.com';
        insert dealerCredentials;
    }

    @isTest
    private static void testVerify() {
        KakaoConsultDealerCredentials__c dealerCredentials = KakaoConsultDealerCredentials__c.getOrgDefaults();
        String jwtToken = dealerCredentials.JWT_Token__c;
        String secret = dealerCredentials.Channel_Secret__c;
        String headerSignature = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqd3RUb2tlbiI6Imp3dFRva2VuIn0.i-dbIe0W3r6s84IysAxlWa_fL4yrmutImUlay7Z9AIU';

        KakaoConsult_JWT jwt = new KakaoConsult_JWT('HS256', 'JWT', jwtToken, secret);
        System.assert(jwt.verify(headerSignature), 'JWT verification failed');
    }
}