force-app/main/default/objects/KakaoConsultDealerCredentials__c/KakaoConsultDealerCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Kakao Consult Dealer Credentials</label>
</CustomObject>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Channel_Secret__c.field-meta.xml
<CustomField>
    <fullName>Channel_Secret__c</fullName>
    <label>Channel Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Customer_Identify_Url__c.field-meta.xml
<CustomField>
    <fullName>Customer_Identify_Url__c</fullName>
    <label>Customer Identify Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/JWT_Token__c.field-meta.xml
<CustomField>
    <fullName>JWT_Token__c</fullName>
    <label>JWT Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Sender_Key__c.field-meta.xml
<CustomField>
    <fullName>Sender_Key__c</fullName>
    <label>Sender Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/InboundReferenceRestService_Test.cls
/**
 * @description       :
 * @author            : Obidjon
 * @group             :
 * @last modified on  : 06-13-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   06-13-2021   Obidjon   Initial Version
 **/
@isTest
private class InboundReferenceRestService_Test {
    @testSetup
    private static void testSetup() {
        KakaoConsultDealerCredentials__c dealerCredentials = new KakaoConsultDealerCredentials__c();
        dealerCredentials.Channel_Secret__c = 'channelsecret';
        dealerCredentials.Sender_Key__c = 'senderkey';
        dealerCredentials.JWT_Token__c = 'jwtToken';
        dealerCredentials.Customer_Identify_Url__c = 'https://test.ap24.force.com';
        insert dealerCredentials;
    }

    @isTest
    private static void doPostReference() {
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestURI = '/services/apexrest/reference';
        request.httpMethod = 'POST';
        String body = '{';
        body += '"user_key": "aEmSUzBR1OsV",';
        body += '"sender_key": "6f77c070905056b409a5125ef96c99ab659c2b34",';
        body += '"app_user_id": "123456",';
        body += '"time": 1.623491429556e12,';
        body += '"reference": { "extra": "", "text": "", "lastText": "", "lastTextDate": "", "appUserId": null },';
        body += '"last_reference": { "extra": "", "bot": "", "bot_event": "", "created_at": "" }';
        body += '}';

        request.requestBody = Blob.valueOf(body);
        Test.startTest();
        RestContext.request = request;
        RestContext.response = response;
        InboundReferenceRestService.doPostReference();
        System.assertEquals(200, response.statusCode, 'Failed status of doPostExpireSession');
        Test.stopTest();
    }
}