force-app/main/default/objects/Kakao_Chat_Feed__c/Kakao_Chat_Feed__c.object-meta.xml
<CustomObject>
    <label>Kakao Chat Feed</label>
    <nameField>
        <displayFormat>KCF-{000000000}</displayFormat>
        <label>Kakao Chat Feed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Chat Feeds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>Image Url</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Kakao_Consult_Chat__c.field-meta.xml
<CustomField>
    <fullName>Kakao_Consult_Chat__c</fullName>
    <label>Kakao Consult Chat</label>
    <referenceTo>Kakao_Consult_Chat__c</referenceTo>
    <relationshipLabel>Kakao Chat Feed</relationshipLabel>
    <relationshipName>Kakao_Chat_Feed</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Audio</fullName>
            </value>
            <value>
                <fullName>File</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/Kakao_Consult_Chat__c.object-meta.xml
<CustomObject>
    <label>Kakao Consult Chat</label>
    <nameField>
        <displayFormat>KCC-{0000000000}</displayFormat>
        <label>Kakao Consult Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Consult Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Kakao Consult Chat</relationshipLabel>
    <relationshipName>Kakao_Consult_Chat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <externalId>true</externalId>
    <label>User Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/KakaoConsultDealerCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Kakao Consult Dealer Credentials</label>
</CustomObject>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Channel_Secret__c.field-meta.xml
<CustomField>
    <fullName>Channel_Secret__c</fullName>
    <label>Channel Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Customer_Identify_Url__c.field-meta.xml
<CustomField>
    <fullName>Customer_Identify_Url__c</fullName>
    <label>Customer Identify Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/JWT_Token__c.field-meta.xml
<CustomField>
    <fullName>JWT_Token__c</fullName>
    <label>JWT Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Sender_Key__c.field-meta.xml
<CustomField>
    <fullName>Sender_Key__c</fullName>
    <label>Sender Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OutboundMessageController_Test.cls
/**
 * @description       : Test class of outbound messaging logic
 * @author            : Obidjon
 * @group             : Kakao Consult Chat
 * @last modified on  : 05-23-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   04-23-2021   Obidjon   Initial Version
 **/
@isTest
private class OutboundMessageController_Test {
    @testSetup
    private static void testSetup() {
        User standardUser = KakaoTestUtils.createUser('Standard User');
        KakaoTestUtils.assignPermissionSet('KakaoConsult_User', standardUser.Id);

        System.runAs(standardUser) {
            KakaoConsultDealerCredentials__c dealerCredentials = new KakaoConsultDealerCredentials__c();
            dealerCredentials.Channel_Secret__c = 'channelsecret';
            dealerCredentials.Sender_Key__c = 'senderkey';
            dealerCredentials.JWT_Token__c = 'jwtToken';
            dealerCredentials.Customer_Identify_Url__c = 'https://test.ap24.force.com';
            insert dealerCredentials;

            Case kakaoCase = new Case();
            kakaoCase.Subject = 'Test Case';
            insert kakaoCase;

            Kakao_Consult_Chat__c consultChat = new Kakao_Consult_Chat__c();
            consultChat.Case__c = kakaoCase.Id;
            consultChat.User_Key__c = 'testuserkey';
            insert consultChat;

            Kakao_Chat_Feed__c chatFeed1 = new Kakao_Chat_Feed__c();
            chatFeed1.Kakao_Consult_Chat__c = consultChat.Id;
            chatFeed1.Message__c = 'Test Content';
            chatFeed1.Type__c = 'Text';
            insert chatFeed1;

            Kakao_Chat_Feed__c chatFeed2 = new Kakao_Chat_Feed__c();
            chatFeed2.Kakao_Consult_Chat__c = consultChat.Id;
            chatFeed2.Message__c = 'Test Content';
            chatFeed2.Type__c = 'Image';
            chatFeed2.Image_Url__c = 'https://image.force.com/image.jpg';
            insert chatFeed2;
        }
    }

    @isTest
    private static void testSendTextMessage() {
        User standardUser = [SELECT Id FROM User WHERE Alias = 'standt' LIMIT 1];

        System.runAs(standardUser) {
            Kakao_Chat_Feed__c chatFeed = [SELECT Id FROM Kakao_Chat_Feed__c WHERE Type__c = 'Text' LIMIT 1];
            Test.startTest();
            Map<String, String> headers = new Map<String, String>();
            headers.put('Content-Type', 'application/json');
            CalloutUtilsMock calloutMock = new CalloutUtilsMock(headers, '{"status":"success"}', 200);
            Test.setMock(HttpCalloutMock.class, calloutMock);
            OutboundMessageController.sendTextMessage(chatFeed.Id);
            Test.stopTest();
        }
    }

    @isTest
    private static void testSendImageMessage() {
        User standardUser = [SELECT Id FROM User WHERE Alias = 'standt' LIMIT 1];

        System.runAs(standardUser) {
            Kakao_Chat_Feed__c chatFeed = [SELECT Id FROM Kakao_Chat_Feed__c WHERE Type__c = 'Image' LIMIT 1];
            Test.startTest();
            Map<String, String> headers = new Map<String, String>();
            headers.put('Content-Type', 'application/json');
            CalloutUtilsMock calloutMock = new CalloutUtilsMock(headers, '{"status":"success"}', 200);
            Test.setMock(HttpCalloutMock.class, calloutMock);
            OutboundMessageController.sendImageMessage(chatFeed.Id);
            Test.stopTest();
        }
    }

    @isTest
    private static void testSendTextMessageException() {
        User standardUser = [SELECT Id FROM User WHERE Alias = 'standt' LIMIT 1];

        System.runAs(standardUser) {
            Test.startTest();
            Map<String, String> headers = new Map<String, String>();
            headers.put('Content-Type', 'application/json');
            CalloutUtilsMock calloutMock = new CalloutUtilsMock(headers, '{"status":"success"}', 200);
            Test.setMock(HttpCalloutMock.class, calloutMock);
            try {
                OutboundMessageController.sendImageMessage('falseid');
            } catch (Exception e) {
                System.assert(true);
            }
            Test.stopTest();
        }
    }
}