force-app/main/default/objects/Kakao_Chat_Feed__c/Kakao_Chat_Feed__c.object-meta.xml
<CustomObject>
    <label>Kakao Chat Feed</label>
    <nameField>
        <displayFormat>KCF-{000000000}</displayFormat>
        <label>Kakao Chat Feed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Chat Feeds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/File_Url__c.field-meta.xml
<CustomField>
    <fullName>File_Url__c</fullName>
    <label>File Url</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>Image Url</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Kakao_Consult_Chat__c.field-meta.xml
<CustomField>
    <fullName>Kakao_Consult_Chat__c</fullName>
    <label>Kakao Consult Chat</label>
    <referenceTo>Kakao_Consult_Chat__c</referenceTo>
    <relationshipLabel>Kakao Chat Feed</relationshipLabel>
    <relationshipName>Kakao_Chat_Feed</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <defaultValue>&apos;Agent&apos;</defaultValue>
    <label>Sender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Processing&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Audio</fullName>
            </value>
            <value>
                <fullName>File</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/Kakao_Consult_Chat__c.object-meta.xml
<CustomObject>
    <label>Kakao Consult Chat</label>
    <nameField>
        <displayFormat>KCC-{0000000000}</displayFormat>
        <label>Kakao Consult Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Consult Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Kakao Consult Chat</relationshipLabel>
    <relationshipName>Kakao_Consult_Chat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Session_Live__c.field-meta.xml
<CustomField>
    <fullName>Session_Live__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Session Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <externalId>true</externalId>
    <label>User Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kakao_User_Mapping__c/Kakao_User_Mapping__c.object-meta.xml
<CustomObject>
    <label>Kakao User Mapping</label>
    <nameField>
        <displayFormat>KUM-{00000000}</displayFormat>
        <label>Kakao User Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao User Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_User_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Kakao User Mapping</relationshipLabel>
    <relationshipName>Kakao_User_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kakao_User_Mapping__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>User Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/KakaoConsultDealerCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Kakao Consult Dealer Credentials</label>
</CustomObject>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Channel_Secret__c.field-meta.xml
<CustomField>
    <fullName>Channel_Secret__c</fullName>
    <label>Channel Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/JWT_Token__c.field-meta.xml
<CustomField>
    <fullName>JWT_Token__c</fullName>
    <label>JWT Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Welcome_Message__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Message__c</fullName>
    <label>Welcome Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/InboundMessageRestService.cls
/**
 * @description       : Inbound message service rest service
 * @author            : Obidjon
 * @group             : Kakao Consult Chat
 * @last modified on  : 07-15-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   04-05-2021   Obidjon   Initial Version
 **/
@RestResource(urlMapping='/message')
global without sharing class InboundMessageRestService {
    private static Map<String, String> typeMap = new Map<String, String>{
        'text' => 'Text',
        'photo' => 'Image',
        'video' => 'Video',
        'audio' => 'Audio',
        'file' => 'File'
    };

    @SuppressWarnings('PMD.ApexCRUDViolation')
    @HttpPost
    global static void doPostMessages() {
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response;
        String requestBody = request.requestBody.toString();
        InboundMessage message = InboundMessage.parse(requestBody);

        KakaoConsultDealerCredentials__c dealerCredentials = KakaoConsultDealerCredentials__c.getOrgDefaults();
        String jwtToken = dealerCredentials.JWT_Token__c;
        String secret = dealerCredentials.Channel_Secret__c;
        String headerSignature = request.headers.get('X-Signature');

        KakaoConsult_JWT jwt = new KakaoConsult_JWT('HS256', 'JWT', jwtToken, secret);
        if (!Test.isRunningTest() && !jwt.verify(headerSignature)) {
            response.statusCode = 401;
            return;
        }

        Kakao_Consult_Chat__c consultChat;
        Kakao_Chat_Feed__c welcomeMessageFeed;
        try {
            consultChat = [
                SELECT Id
                FROM Kakao_Consult_Chat__c
                WHERE Session_Live__c = TRUE AND User_Key__c = :message.user_key
                LIMIT 1
            ];
        } catch (QueryException e) {
            List<Kakao_User_Mapping__c> kakaoUserMapping = [
                SELECT Id, Contact__c
                FROM Kakao_User_Mapping__c
                WHERE User_Key__c = :message.user_key AND Contact__c != NULL
            ];

            Case kakaoCase = new Case();
            if (!Test.isRunningTest()) {
                kakaoCase.OwnerId = [SELECT Id FROM Group WHERE DeveloperName = 'Kakao_Chat_Queue'].Id;
            } else {
                kakaoCase.OwnerId = UserInfo.getUserId();
            }
            kakaoCase.Subject = '카카오상담';
            kakaoCase.Origin = 'Kakao Chat';
            if (kakaoUserMapping.size() > 0) {
                kakaoCase.ContactId = kakaoUserMapping.get(0).Contact__c;
            }
            insert kakaoCase;

            consultChat = new Kakao_Consult_Chat__c();
            consultChat.Session_Live__c = true;
            consultChat.User_Key__c = message.user_key;
            consultChat.Case__c = kakaoCase.Id;
            // In case of first message conflict
            List<Kakao_Consult_Chat__c> existingChatList = [
                SELECT Id
                FROM Kakao_Consult_Chat__c
                WHERE Session_Live__c = TRUE AND User_Key__c = :message.user_key
                LIMIT 1
            ];
            if (existingChatList.size() > 0) {
                delete kakaoCase;
                consultChat = existingChatList.get(0);
            } else {
                insert consultChat;
            }

            if (String.isNotBlank(dealerCredentials.Welcome_Message__c)) {
                welcomeMessageFeed = new Kakao_Chat_Feed__c();
                welcomeMessageFeed.Kakao_Consult_Chat__c = consultChat.Id;
                welcomeMessageFeed.Sender__c = 'Agent';
                welcomeMessageFeed.Status__c = 'Success';
                welcomeMessageFeed.Type__c = typeMap.get('text');
                welcomeMessageFeed.Message__c = dealerCredentials.Welcome_Message__c;
            }
        }
        consultChat = [SELECT Id, Case__c FROM Kakao_Consult_Chat__c WHERE Id = :consultChat.Id];

        Kakao_Chat_Feed__c chatFeed = new Kakao_Chat_Feed__c();
        chatFeed.Kakao_Consult_Chat__c = consultChat.Id;
        chatFeed.Sender__c = 'Customer';
        chatFeed.Status__c = 'Success';
        chatFeed.Type__c = typeMap.get(message.type);
        if (message.type == 'text') {
            chatFeed.Message__c = message.content;
        } else if (message.type == 'photo') {
            chatFeed.Image_Url__c = message.urlContent.url;
        } else {
            chatFeed.File_Url__c = message.urlContent.url;
        }
        insert chatFeed;

        if (message.type == 'photo') {
            FileSaveService.saveFile(chatFeed.Image_Url__c, consultChat.Case__c, chatFeed.Id);
        }

        if (welcomeMessageFeed != null && !Test.isRunningTest()) {
            insert welcomeMessageFeed;
            OutboundMessageController.sendTextMessage(welcomeMessageFeed.Id);
        }

        response.statusCode = 200;
    }
}