force-app/main/default/objects/Kakao_Chat_Feed__c/Kakao_Chat_Feed__c.object-meta.xml
<CustomObject>
    <label>Kakao Chat Feed</label>
    <nameField>
        <displayFormat>KCF-{000000000}</displayFormat>
        <label>Kakao Chat Feed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Chat Feeds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/File_Url__c.field-meta.xml
<CustomField>
    <fullName>File_Url__c</fullName>
    <label>File Url</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>Image Url</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/isAgent__c.field-meta.xml
<CustomField>
    <fullName>isAgent__c</fullName>
    <formula>ISPICKVAL(Sender__c, &apos;Agent&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isAgent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Kakao_Consult_Chat__c.field-meta.xml
<CustomField>
    <fullName>Kakao_Consult_Chat__c</fullName>
    <label>Kakao Consult Chat</label>
    <referenceTo>Kakao_Consult_Chat__c</referenceTo>
    <relationshipLabel>Kakao Chat Feed</relationshipLabel>
    <relationshipName>Kakao_Chat_Feed</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <defaultValue>&apos;Agent&apos;</defaultValue>
    <label>Sender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Sent_Time__c.field-meta.xml
<CustomField>
    <fullName>Sent_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Sent Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Sent_Time_formatted__c.field-meta.xml
<CustomField>
    <fullName>Sent_Time_formatted__c</fullName>
    <description>This field is only used as wrapper field for front end</description>
    <label>Sent Time formatted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Session_Live_fm__c.field-meta.xml
<CustomField>
    <fullName>Session_Live_fm__c</fullName>
    <formula>Kakao_Consult_Chat__r.Session_Live__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Processing&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Audio</fullName>
            </value>
            <value>
                <fullName>File</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/Kakao_Consult_Chat__c.object-meta.xml
<CustomObject>
    <label>Kakao Consult Chat</label>
    <nameField>
        <displayFormat>KCC-{0000000000}</displayFormat>
        <label>Kakao Consult Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Consult Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Kakao Consult Chat</relationshipLabel>
    <relationshipName>Kakao_Consult_Chat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/KakaoChatFeedController.cls
/**
 * @description       : Kakao Chat feed controller
 * @author            : Obidjon
 * @group             : Kakao Consult Chat
 * @last modified on  : 04-25-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   03-09-2021   Obidjon   Initial Version
 **/
public with sharing class KakaoChatFeedController {
    @AuraEnabled(cacheable=true)
    public static List<Kakao_Chat_Feed__c> getKakaoChatFeeds(Id caseId) {
        try {
            Kakao_Consult_Chat__c kakaoConsultChat = [
                SELECT Id, Case__c
                FROM Kakao_Consult_Chat__c
                WHERE Case__r.Id = :caseId
                WITH SECURITY_ENFORCED
            ];

            List<Kakao_Chat_Feed__c> chatFeeds = [
                SELECT
                    Id,
                    Message__c,
                    Image_Url__c,
                    File_Url__c,
                    Sender__c,
                    Sent_Time__c,
                    Status__c,
                    Type__c,
                    IsAgent__c,
                    Kakao_Consult_Chat__c,
                    Session_Live_fm__c
                FROM Kakao_Chat_Feed__c
                WHERE Kakao_Consult_Chat__c = :kakaoConsultChat.Id
                WITH SECURITY_ENFORCED
                ORDER BY Sent_Time__c
            ];

            for (Kakao_Chat_Feed__c chatFeed : chatFeeds) {
                chatFeed.Sent_Time_formatted__c = chatFeed.Sent_Time__c.format(
                    'HH:mm',
                    UserInfo.getTimeZone().toString()
                );
            }

            return chatFeeds;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}