force-app/main/default/objects/Kakao_Chat_Feed__c/Kakao_Chat_Feed__c.object-meta.xml
<CustomObject>
    <label>Kakao Chat Feed</label>
    <nameField>
        <displayFormat>KCF-{000000000}</displayFormat>
        <label>Kakao Chat Feed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Chat Feeds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Kakao_Consult_Chat__c.field-meta.xml
<CustomField>
    <fullName>Kakao_Consult_Chat__c</fullName>
    <label>Kakao Consult Chat</label>
    <referenceTo>Kakao_Consult_Chat__c</referenceTo>
    <relationshipLabel>Kakao Chat Feed</relationshipLabel>
    <relationshipName>Kakao_Chat_Feed</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/Kakao_Consult_Chat__c.object-meta.xml
<CustomObject>
    <label>Kakao Consult Chat</label>
    <nameField>
        <displayFormat>KCC-{0000000000}</displayFormat>
        <label>Kakao Consult Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Consult Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Session_Live__c.field-meta.xml
<CustomField>
    <fullName>Session_Live__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Session Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PostInstallClass.cls
/**
 * @description       :
 * @author            : Obidjon
 * @group             :
 * @last modified on  : 06-14-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   04-25-2021   Obidjon   Initial Version
 **/
global class PostInstallClass implements InstallHandler {
    global void onInstall(InstallContext context) {
        if (context.previousVersion() == null) {
            List<PushTopic> customerChat = [SELECT Id FROM PushTopic WHERE Name = 'KakaoConsultChatCustomer'];
            if (customerChat == null || customerChat.size() == 0) {
                PushTopic pushTopic = new PushTopic();
                pushTopic.Name = 'KakaoConsultChatCustomer';
                pushTopic.Query = 'Select Id, Kakao_Consult_Chat__c from Kakao_Chat_Feed__c';
                pushTopic.ApiVersion = 51.0;
                pushTopic.NotifyForOperationCreate = true;
                pushTopic.NotifyForOperationUpdate = true;
                pushTopic.NotifyForOperationUndelete = true;
                pushTopic.NotifyForOperationDelete = true;
                pushTopic.NotifyForFields = 'All';
                if (!Test.isRunningTest()) {
                    insert pushTopic;
                }
            }

            List<PushTopic> expiredChatTopic = [SELECT Id FROM PushTopic WHERE Name = 'KakaoConsultChatExpired'];
            if (expiredChatTopic == null || expiredChatTopic.size() == 0) {
                PushTopic topic = new PushTopic();
                topic.Name = 'KakaoConsultChatExpired';
                topic.Query = 'Select Id, Session_Live__c from Kakao_Consult_Chat__c';
                topic.ApiVersion = 51.0;
                topic.NotifyForOperationCreate = false;
                topic.NotifyForOperationUpdate = true;
                topic.NotifyForOperationUndelete = false;
                topic.NotifyForOperationDelete = false;
                topic.NotifyForFields = 'All';
                if (!Test.isRunningTest()) {
                    insert topic;
                }
            }

            List<Group> kakaoConsultGroupList = [SELECT Id FROM Group WHERE DeveloperName = 'Kakao_Chat_Queue'];
            if (Test.isRunningTest() || kakaoConsultGroupList == null || kakaoConsultGroupList.size() == 0) {
                Group kakaoConsultGroup = new Group();
                kakaoConsultGroup.Name = 'Kakao Chat Queue';
                kakaoConsultGroup.DeveloperName = 'Kakao_Chat_Queue';
                kakaoConsultGroup.Type = 'Queue';
                if (!Test.isRunningTest()) {
                    insert kakaoConsultGroup;
                }

                QueuesObject kakaoConsultQueue = new QueueSObject();
                kakaoConsultQueue.QueueId = kakaoConsultGroup.Id;
                kakaoConsultQueue.SobjectType = 'Case';
                if (!Test.isRunningTest()) {
                    insert kakaoConsultQueue;
                }
            }
        }
    }
}