force-app/main/default/objects/Kakao_Chat_Feed__c/Kakao_Chat_Feed__c.object-meta.xml
<CustomObject>
    <label>Kakao Chat Feed</label>
    <nameField>
        <displayFormat>KCF-{000000000}</displayFormat>
        <label>Kakao Chat Feed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Chat Feeds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Kakao_Consult_Chat__c.field-meta.xml
<CustomField>
    <fullName>Kakao_Consult_Chat__c</fullName>
    <label>Kakao Consult Chat</label>
    <referenceTo>Kakao_Consult_Chat__c</referenceTo>
    <relationshipLabel>Kakao Chat Feed</relationshipLabel>
    <relationshipName>Kakao_Chat_Feed</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Processing&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kakao_Chat_Feed__c/fields/User_Key_fm__c.field-meta.xml
<CustomField>
    <fullName>User_Key_fm__c</fullName>
    <formula>Kakao_Consult_Chat__r.User_Key__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kakao_Consult_Chat__c/Kakao_Consult_Chat__c.object-meta.xml
<CustomObject>
    <label>Kakao Consult Chat</label>
    <nameField>
        <displayFormat>KCC-{0000000000}</displayFormat>
        <label>Kakao Consult Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Consult Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Consult_Chat__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Kakao Consult Chat</relationshipLabel>
    <relationshipName>Kakao_Consult_Chat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/KakaoConsultDealerCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Kakao Consult Dealer Credentials</label>
</CustomObject>

force-app/main/default/objects/KakaoConsultDealerCredentials__c/fields/Customer_Identify_Url__c.field-meta.xml
<CustomField>
    <fullName>Customer_Identify_Url__c</fullName>
    <label>Customer Identify Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/CustomerIdentifyCallout.cls
/**
 * @description       : Customer identity link sending callout service
 * @author            : Obidjon
 * @group             : Kakao Consult Chat
 * @last modified on  : 04-23-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   04-14-2021   Obidjon   Initial Version
 **/
public with sharing class CustomerIdentifyCallout {
    public static void process(Id kakaoChatFeedId) {
        Kakao_Chat_Feed__c chatFeed = [
            SELECT Id, Message__c, User_Key_fm__c, Kakao_Consult_Chat__r.Case__c
            FROM Kakao_Chat_Feed__c
            WHERE Id = :kakaoChatFeedId
            WITH SECURITY_ENFORCED
        ];

        KakaoConsultDealerCredentials__c dealerCredentials = KakaoConsultDealerCredentials__c.getOrgDefaults();
        chatFeed.Message__c = 'Identifier link';

        String identifierLink =
            dealerCredentials.Customer_Identify_Url__c +
            'cid=' +
            chatFeed.Kakao_Consult_Chat__r.Case__c;

        List<Map<String, Object>> linkJsonObject = new List<Map<String, Object>>();
        linkJsonObject.add(new Map<String, Object>());
        linkJsonObject.get(0).put('name', '고객 정보 입력');
        linkJsonObject.get(0).put('type', 'WL');
        linkJsonObject.get(0).put('url_mobile', identifierLink);
        linkJsonObject.get(0).put('url_pc', identifierLink);

        Map<String, Object> bodyMap = new Map<String, Object>();
        bodyMap.put('serial_number', chatFeed.Id);
        bodyMap.put('message_type', 'LI');
        bodyMap.put('message', '보다 빠르고 정확한 서비스 제공 위해서 개인 정보 입력해주세요!');
        bodyMap.put('links', linkJsonObject);

        HttpResponse response = RestApiHelper.makeApiCall(
            'Kakao_Consult_Chat',
            RestApiHelper.RestMethod.POST,
            'https://kakao-apis.enomix.co.kr/v1/chat/write',
            bodyMap,
            chatFeed.User_Key_fm__c
        );
        try {
            if (Schema.SObjectType.Kakao_Chat_Feed__c.fields.Status__c.isUpdateable()) {
                chatFeed.Status__c = response.getStatusCode() == 200 ? 'Success' : 'Error';
                update chatFeed;
            } else {
                throw new CRUDPermissionException('No update permission on Status of Kakao_Chat_Feed object');
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}