force-app/main/default/objects/IF_XP_SFDC_001__c/IF_XP_SFDC_001__c.object-meta.xml
<CustomObject>
    <description>CVS 쿠폰 사용에 관한 더미 레코드</description>
    <label>IF XP SFDC 001</label>
    <nameField>
        <displayFormat>CouponIF-{YYYY}{MM}{DD}{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IF XP SFDC 001</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/BurnoutChannel__c.field-meta.xml
<CustomField>
    <fullName>BurnoutChannel__c</fullName>
    <label>BurnoutChannel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponAmount__c.field-meta.xml
<CustomField>
    <fullName>CouponAmount__c</fullName>
    <label>CouponAmount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>CouponExpiryDate__c</fullName>
    <label>CouponExpiryDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponId__c.field-meta.xml
<CustomField>
    <fullName>CouponId__c</fullName>
    <label>CouponId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/Couponissuedate__c.field-meta.xml
<CustomField>
    <fullName>Couponissuedate__c</fullName>
    <label>Couponissuedate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponName__c.field-meta.xml
<CustomField>
    <fullName>CouponName__c</fullName>
    <label>CouponName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponOltCode__c.field-meta.xml
<CustomField>
    <fullName>CouponOltCode__c</fullName>
    <label>CouponOltCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponOltName__c.field-meta.xml
<CustomField>
    <fullName>CouponOltName__c</fullName>
    <label>CouponOltName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponStatus__c.field-meta.xml
<CustomField>
    <fullName>CouponStatus__c</fullName>
    <label>CouponStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponStatusDate__c.field-meta.xml
<CustomField>
    <fullName>CouponStatusDate__c</fullName>
    <label>CouponStatusDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CVSChainCode__c.field-meta.xml
<CustomField>
    <fullName>CVSChainCode__c</fullName>
    <label>CVSChainCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CVSChainName__c.field-meta.xml
<CustomField>
    <fullName>CVSChainName__c</fullName>
    <label>CVSChainName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/CouponCode__c.field-meta.xml
<CustomField>
    <fullName>CouponCode__c</fullName>
    <description>[KDCE] Coupon Code</description>
    <externalId>true</externalId>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IF_XP_SFDC_001_ba_Test.cls
/****************************************************************************************
  * @filename      : IF_XP_SFDC_001_ba_Test
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-15 오후 2:15
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-15 오후 2:15     i2max_Jihyun.Lee        Create
****************************************************************************************/

@IsTest
private class IF_XP_SFDC_001_ba_Test {

    @IsTest
    static void testBehavior() {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();

        KDCE_Coupon__c coupon = KDCE_TestBizUtil.coupon;


        IF_XP_SFDC_001__c xp01 = new IF_XP_SFDC_001__c(
                BurnoutChannel__c = 'CVS',
                CouponAmount__c = '10000',
                CouponExpiryDate__c = '20190630',
                CouponId__c = coupon.CouponCode__c,
                Couponissuedate__c = '20190329',
                CouponName__c = '아이코스상품권 1만원권',
                CouponOltName__c = '1111',
                CouponOltCode__c = '1111',
                CouponStatus__c = '1',
                CouponStatusDate__c = '20190300000000',
                CVSChainCode__c = '2',
                CVSChainName__c = 'k7'
        );
        insert xp01;

        Test.startTest();
        IF_XP_SFDC_001_ba batch = new IF_XP_SFDC_001_ba();
        Database.executeBatch(batch, 2000);
        Test.stopTest();

    }
}