force-app/main/default/objects/IF_XP_SFDC_001__c/IF_XP_SFDC_001__c.object-meta.xml
<CustomObject>
    <description>CVS 쿠폰 사용에 관한 더미 레코드</description>
    <label>IF XP SFDC 001</label>
    <nameField>
        <displayFormat>CouponIF-{YYYY}{MM}{DD}{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IF XP SFDC 001</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/BurnoutChannel__c.field-meta.xml
<CustomField>
    <fullName>BurnoutChannel__c</fullName>
    <label>BurnoutChannel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponAmount__c.field-meta.xml
<CustomField>
    <fullName>CouponAmount__c</fullName>
    <label>CouponAmount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>CouponExpiryDate__c</fullName>
    <label>CouponExpiryDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponId__c.field-meta.xml
<CustomField>
    <fullName>CouponId__c</fullName>
    <label>CouponId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/Couponissuedate__c.field-meta.xml
<CustomField>
    <fullName>Couponissuedate__c</fullName>
    <label>Couponissuedate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/Couponmoddate__c.field-meta.xml
<CustomField>
    <fullName>Couponmoddate__c</fullName>
    <label>Couponmoddate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponName__c.field-meta.xml
<CustomField>
    <fullName>CouponName__c</fullName>
    <label>CouponName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponOltCode__c.field-meta.xml
<CustomField>
    <fullName>CouponOltCode__c</fullName>
    <label>CouponOltCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponOltName__c.field-meta.xml
<CustomField>
    <fullName>CouponOltName__c</fullName>
    <label>CouponOltName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponProductCode__c.field-meta.xml
<CustomField>
    <fullName>CouponProductCode__c</fullName>
    <label>CouponProductCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponProductName__c.field-meta.xml
<CustomField>
    <fullName>CouponProductName__c</fullName>
    <label>CouponProductName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponStatus__c.field-meta.xml
<CustomField>
    <fullName>CouponStatus__c</fullName>
    <label>CouponStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponStatusDate__c.field-meta.xml
<CustomField>
    <fullName>CouponStatusDate__c</fullName>
    <label>CouponStatusDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponStatusDatetime__c.field-meta.xml
<CustomField>
    <fullName>CouponStatusDatetime__c</fullName>
    <description>Text인 CouponStatusDate__c 값을 트리거롤 통해 Datetime으로 변환</description>
    <label>CouponStatusDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CVSChainCode__c.field-meta.xml
<CustomField>
    <fullName>CVSChainCode__c</fullName>
    <label>CVSChainCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CVSChainName__c.field-meta.xml
<CustomField>
    <fullName>CVSChainName__c</fullName>
    <label>CVSChainName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/ErrorContent__c.field-meta.xml
<CustomField>
    <fullName>ErrorContent__c</fullName>
    <description>[KDCE] 에러가 발생한 경우 원인을 기록함</description>
    <label>Error Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/IsError__c.field-meta.xml
<CustomField>
    <fullName>IsError__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 처리중 Error가 발생하면 True로 업데이트</description>
    <label>IsError</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/IsProcess__c.field-meta.xml
<CustomField>
    <fullName>IsProcess__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 레코드의 처리가 진행되었는지 확인하는 필드</description>
    <label>IsProcess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/CouponCode__c.field-meta.xml
<CustomField>
    <fullName>CouponCode__c</fullName>
    <description>[KDCE] Coupon Code</description>
    <externalId>true</externalId>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/UsedDate__c.field-meta.xml
<CustomField>
    <fullName>UsedDate__c</fullName>
    <label>CVS Used Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/KDCE_CouponHistory__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Coupon Journey</description>
    <label>Coupon Journey</label>
    <nameField>
        <displayFormat>CH-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Journeys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/ActionChannel__c.field-meta.xml
<CustomField>
    <fullName>ActionChannel__c</fullName>
    <description>[KDCE] History Action Channel : Online / Offline / Call Center</description>
    <label>Action Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/ActionDate__c.field-meta.xml
<CustomField>
    <fullName>ActionDate__c</fullName>
    <description>[KDCE] Coupon이 변경된 Date/Time</description>
    <label>Action Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupon Journeys</relationshipLabel>
    <relationshipName>CouponHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Store Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>Store Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IF_XP_SFDC_001_ba.cls
/****************************************************************************************
  * @filename      : IF_XP_SFDC_001_ba
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-02 오후 1:38
  * @group         : 
  * @group-content : 
  * @description   : IF_XP_SFDC_001: CVS 쿠폰 사용에 관한 더미 레코드 레코드 등록 후, Coupon으로 변경시키는 배치
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-02 오후 1:38     i2max_Jihyun.Lee        Create
****************************************************************************************/

public with sharing class IF_XP_SFDC_001_ba implements Database.Batchable<SObject>, Database.Stateful {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = '';
        query += ' SELECT   Id                      ';
        query += '  ,       BurnoutChannel__c       ';
        query += '  ,       CouponAmount__c         ';
        query += '  ,       CouponExpiryDate__c     ';
        query += '  ,       CouponId__c             ';
        query += '  ,       Couponissuedate__c      ';
        query += '  ,       Couponmoddate__c        ';
        query += '  ,       CouponName__c           ';
        query += '  ,       CouponOltName__c        ';
        query += '  ,       CouponOltCode__c        ';
        query += '  ,       CouponProductCode__c    ';
        query += '  ,       CouponProductName__c    ';
        query += '  ,       CouponStatus__c         ';
        query += '  ,       CouponStatusDate__c     ';
        query += '  ,       CouponStatusDatetime__c ';
        query += '  ,       CVSChainCode__c         ';
        query += '  ,       CVSChainName__c         ';
        query += '  ,       ErrorContent__c         ';
        query += '  ,       IsError__c              ';
        query += '  ,       IsProcess__c            ';
        query += ' FROM     IF_XP_SFDC_001__c       ';
        query += ' WHERE    IsProcess__c = false    ';
        query += ' ORDER BY CouponId__c, CouponStatusDatetime__c ';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {

        // Coupon별 Status값 저장 // TODO 기존에 있던 데이터가 사용인데, 취소 사용 데이터가 들어온 경우는 어떻게?..
        List<KDCE_CouponHistory__c> couponHistoryList = new List<KDCE_CouponHistory__c>();
        Set<String> couponCodeSet = new Set<String>();
        for (IF_XP_SFDC_001__c xp : (List<IF_XP_SFDC_001__c>) scope) {
            couponCodeSet.add(xp.CouponId__c);
        }
        Map<String, KDCE_Coupon__c> couponMap = new Map<String, KDCE_Coupon__c>();
        for (KDCE_Coupon__c coupon : [SELECT Id, CouponCode__c, Contact__c FROM KDCE_Coupon__c WHERE CouponCode__c IN :couponCodeSet]) {
            couponMap.put(coupon.CouponCode__c, coupon);
        }
        System.debug('=== couponMap : ' + couponMap);

        Map<Id, KDCE_Coupon__c> updateCouponMap = new Map<Id, KDCE_Coupon__c>();
        KDCE_Coupon__c coupon;
        KDCE_CouponHistory__c history;
        String couponHistoryStatus;

        for (IF_XP_SFDC_001__c xp : (List<IF_XP_SFDC_001__c>) scope) {
            System.debug('=== xp : ' + xp);
            xp.IsProcess__c = true;

            // Coupon 생성
            if (couponMap.containsKey(xp.CouponId__c)) {
                coupon = new KDCE_Coupon__c();
                coupon.Id = couponMap.get(xp.CouponId__c).Id;

                if (xp.CouponStatus__c == '1') {
                    coupon.Status__c    = KDCE_GlobalValue.COUPON_STATUS_USE;
                    coupon.UsedDate__c  = xp.CouponStatusDatetime__c;
                    couponHistoryStatus = KDCE_GlobalValue.COUPON_HISTORY_TYPE_USE;
                }
                else if (xp.CouponStatus__c == '-1') {
                    coupon.Status__c    = KDCE_GlobalValue.COUPON_STATUS_ISSUE;
                    coupon.UsedDate__c  = null;
                    couponHistoryStatus = KDCE_GlobalValue.COUPON_HISTORY_TYPE_CANCEL;
                }
//                couponList.add(coupon);
                updateCouponMap.put(coupon.Id, coupon);

                // History 생성
                history                     = KDCE_CouponService.createCouponHistory(coupon.Id, couponHistoryStatus);
                history.Contact__c          = couponMap.get(xp.CouponId__c).Contact__c;
                history.ActionDate__c       = xp.CouponStatusDatetime__c;
                history.ActionChannel__c    = KDCE_GlobalValue.COUPON_HISTORY_CHANNEL_OFFLINE;
                history.StoreCode__c        = xp.CouponOltCode__c;
                history.StoreName__c        = xp.CouponOltName__c;
                couponHistoryList.add(history);
            }

            // 일치하는 쿠폰이 없으면 에러처리
            else {
                xp.IsError__c = true;
                xp.ErrorContent__c = 'Coupon Id does not exist.';
            }

        }

        update scope;
        List<Database.SaveResult> updateCoupon = Database.update(updateCouponMap.values(), true);
        List<Database.SaveResult> insertCouponHistory = Database.insert(couponHistoryList);
    }

    @SuppressWarnings('PMD')
    public void finish(Database.BatchableContext BC) {

    }
}