force-app/main/default/objects/IF_XP_SFDC_001__c/IF_XP_SFDC_001__c.object-meta.xml
<CustomObject>
    <description>CVS 쿠폰 사용에 관한 더미 레코드</description>
    <label>IF XP SFDC 001</label>
    <nameField>
        <displayFormat>CouponIF-{YYYY}{MM}{DD}{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IF XP SFDC 001</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponId__c.field-meta.xml
<CustomField>
    <fullName>CouponId__c</fullName>
    <label>CouponId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponOltCode__c.field-meta.xml
<CustomField>
    <fullName>CouponOltCode__c</fullName>
    <label>CouponOltCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponOltName__c.field-meta.xml
<CustomField>
    <fullName>CouponOltName__c</fullName>
    <label>CouponOltName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponStatus__c.field-meta.xml
<CustomField>
    <fullName>CouponStatus__c</fullName>
    <label>CouponStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponStatusDate__c.field-meta.xml
<CustomField>
    <fullName>CouponStatusDate__c</fullName>
    <label>CouponStatusDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponStatusDatetime__c.field-meta.xml
<CustomField>
    <fullName>CouponStatusDatetime__c</fullName>
    <description>Text인 CouponStatusDate__c 값을 트리거롤 통해 Datetime으로 변환</description>
    <label>CouponStatusDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/ErrorContent__c.field-meta.xml
<CustomField>
    <fullName>ErrorContent__c</fullName>
    <description>[KDCE] 에러가 발생한 경우 원인을 기록함</description>
    <label>Error Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/IsError__c.field-meta.xml
<CustomField>
    <fullName>IsError__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 처리중 Error가 발생하면 True로 업데이트</description>
    <label>IsError</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/IsProcess__c.field-meta.xml
<CustomField>
    <fullName>IsProcess__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 레코드의 처리가 진행되었는지 확인하는 필드</description>
    <label>IsProcess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/CouponCode__c.field-meta.xml
<CustomField>
    <fullName>CouponCode__c</fullName>
    <description>[KDCE] Coupon Code</description>
    <externalId>true</externalId>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/UsedDate__c.field-meta.xml
<CustomField>
    <fullName>UsedDate__c</fullName>
    <label>CVS Used Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/KDCE_CouponHistory__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Coupon Journey</description>
    <label>Coupon Journey</label>
    <nameField>
        <displayFormat>CH-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Journeys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/ActionChannel__c.field-meta.xml
<CustomField>
    <fullName>ActionChannel__c</fullName>
    <description>[KDCE] History Action Channel : Online / Offline / Call Center</description>
    <label>Action Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/ActionDate__c.field-meta.xml
<CustomField>
    <fullName>ActionDate__c</fullName>
    <description>[KDCE] Coupon이 변경된 Date/Time</description>
    <label>Action Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <description>[KDCE] Coupon Action Type</description>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupon Journeys</relationshipLabel>
    <relationshipName>CouponHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Store Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>Store Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IF_XP_SFDC_001_tr.cls
/****************************************************************************************
  * @filename      : IF_XP_SFDC_001_tr
  * @projectname   : PMK LocalDCE QA
  * @author        : i2max_JE Yoon
  * @date          : 2021-03-22
  * @group         :
  * @description   :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                author              description
  * ===============================================================
    0.1  2021-03-22          i2max_JE Yoon             Create
****************************************************************************************/
public without sharing class IF_XP_SFDC_001_tr extends TriggerHandler {

    private static Map<String, String> pvMap_CouponHistory_ActionType = KDCE_Util.getPicklistValue('KDCE_CouponHistory__c', 'ActionType__c');
    private static Map<String, String> pvMap_CouponHistory_ActionChannel = KDCE_Util.getPicklistValue('KDCE_CouponHistory__c', 'ActionChannel__c');
    private static Map<String, String> pvMap_Coupon_Status = KDCE_Util.getPicklistValue('KDCE_Coupon__c', 'Status__c');

    public override void beforeInsert() {
//        this.createCouponHistory(); // 인터페이스가 제대로 처리 되었는지 여부 및 쿠폰 Status__c 업데이트, 쿠폰 히스토리 레코드 생성
        convertStatusDate();    // Coupon Status Date를 Datetime으로 변환
    }

    /**
     * @description IF_XP_SFDC_001__c에 레코드가 생성되면 쿠폰코드(CouponId__c) 값으로 쿠폰을 조회해
     *              1. 쿠폰의 Status__c = Use로 업데이트
     *              2. 쿠폰 히스토리 레코드 생성
     *              3. IF_XP_SFDC_001__c.IsProcess__c = true 처리
     *              (해당하는 쿠폰이 없을 시에는 IsError__c = false 및 ErrorContent__c = 'Coupon Id does not exist.' 처리)
     * @author JE Yoon (2021.03.22)
     **/
//    private void createCouponHistory() {
//        Map<String, KDCE_Coupon__c> couponCodeMap   = new Map<String, KDCE_Coupon__c>();
//        Map<String, Datetime> couponCode_Date_Map   = new Map<String, Datetime>();
//        List<KDCE_Coupon__c> coupons                = new List<KDCE_Coupon__c>();
//
//        List<KDCE_CouponHistory__c> histories       = new List<KDCE_CouponHistory__c>();
//        Map<Id, KDCE_CouponHistory__c> insertUseHistoryMap = new Map<Id, KDCE_CouponHistory__c>();
//        Map<Id, KDCE_CouponHistory__c> insertIssueHistoryMap = new Map<Id, KDCE_CouponHistory__c>();
//        KDCE_Coupon__c coupon;
//        KDCE_CouponHistory__c history;
//
//        Datetime dt;
//        String actionChannel_Offline                 = pvMap_CouponHistory_ActionChannel.get('Offline');
//        String couponStatus_Use                      = pvMap_Coupon_Status.get('Use');
//        String couponStatus_Issue                    = pvMap_Coupon_Status.get('Issue');
//        String actionType_Use                        = pvMap_CouponHistory_ActionType.get('Use');
//        String actionType_Cancel                     = pvMap_CouponHistory_ActionType.get('Cancel');
//        String couponHistoryStatus;
//        String ifxp_date;
//        String date_converted;
//
//        // 텍스트 타입의 쿠폰 사용일을 Datetime 형태로 변환 처리
//        for (IF_XP_SFDC_001__c ifxp : (List<IF_XP_SFDC_001__c>) Trigger.new) {
//            ifxp_date = ifxp.CouponStatusDate__c; // 인터페이스로 들어오는 날짜/시간 형식: 20190329155801
//            if (ifxp_date.length() == 14) {
//                date_converted = ifxp_date.substring(0,4) + '-' + ifxp_date.substring(4,6) + '-' + ifxp_date.substring(6,8) + ' ';
//                date_converted += ifxp_date.substring(8,10) + ':' + ifxp_date.substring(10,12) + ':' + ifxp_date.substring(12,14);
//                dt = Datetime.valueOf(date_converted);
//            }
//            couponCode_Date_Map.put(ifxp.CouponId__c, dt);
//        }
//
//        coupons = [SELECT Contact__c, Status__c, CouponCode__c FROM KDCE_Coupon__c WHERE CouponCode__c = :couponCode_Date_Map.keySet()];
//
//        if (!coupons.isEmpty()) {
//            for (KDCE_Coupon__c kdceCoupon : coupons) {
//                couponCodeMap.put(kdceCoupon.CouponCode__c, kdceCoupon);
//            }
//        }
//
//        // 각 더미 데이터에 대해 쿠폰 상태를 사용으로 업데이트하고 쿠폰 히스토리 데이터 생성
//        for (IF_XP_SFDC_001__c ifxp : (List<IF_XP_SFDC_001__c>) Trigger.new) {
//            coupon = couponCodeMap.get(ifxp.CouponId__c);
//            if (coupon == null) {
//                ifxp.IsProcess__c = true;
//                ifxp.IsError__c = true;
//                ifxp.ErrorContent__c = 'Coupon Id does not exist.';
//            }
//            else {
//                ifxp.IsProcess__c = true;
//                if (ifxp.CouponStatus__c == '1') {
//                    coupon.Status__c    = KDCE_GlobalValue.COUPON_STATUS_USE;
//                    coupon.UsedDate__c  = couponCode_Date_Map.get(coupon.CouponCode__c);
//                    couponHistoryStatus = actionType_Use;
//                }
//                else if (ifxp.CouponStatus__c == '-1') {
//                    coupon.Status__c    = KDCE_GlobalValue.COUPON_STATUS_ISSUE;
//                    coupon.UsedDate__c  = null;
//                    couponHistoryStatus = actionType_Cancel;
//                }
//
//                // Coupon Action 별
//                history                     = KDCE_CouponService.createCouponHistory(coupon.Id, couponHistoryStatus);
//                history.Contact__c          = coupon.Contact__c;
//                history.ActionDate__c       = couponCode_Date_Map.get(coupon.CouponCode__c);
//                history.ActionChannel__c    = actionChannel_Offline;
//                history.StoreCode__c        = ifxp.CouponOltCode__c;
//                history.StoreName__c        = ifxp.CouponOltName__c;
//
//                // Use, Cancel 동시에 들어올 경우 Use 먼저 처리하고 Cancel 처리하도록
//                if (ifxp.CouponStatus__c == '1') insertUseHistoryMap.put(history.Id, history);
//                else if (ifxp.CouponStatus__c == '-1') insertIssueHistoryMap.put(history.Id, history);
//
//                System.debug('=== insertUseHistoryMap : ' + insertUseHistoryMap);
//                System.debug('=== insertIssueHistoryMap : ' + insertIssueHistoryMap);
//            }
//        }
//
//        if (!insertUseHistoryMap.isEmpty()) insert insertUseHistoryMap.values();
//        if (!insertIssueHistoryMap.isEmpty()) insert insertIssueHistoryMap.values();
//        if (!couponCodeMap.isEmpty()) update couponCodeMap.values();
//    }

    /**
     * Text인 CouponStatusDate__c 값을 Datetime 필드로 변환
     */
    private void convertStatusDate() {
        System.debug('@@@@@@ convertStatusDate @@@@@@');
        Datetime dt;
        String ifxp_date;
        String date_converted;

        for (IF_XP_SFDC_001__c ifxp : (List<IF_XP_SFDC_001__c>) Trigger.new) {
            if (ifxp.CouponStatusDate__c != null) {
                ifxp_date = ifxp.CouponStatusDate__c; // 인터페이스로 들어오는 날짜/시간 형식: 20190329155801
                if (ifxp_date.length() == 14) {
                    date_converted = ifxp_date.substring(0,4) + '-' + ifxp_date.substring(4,6) + '-' + ifxp_date.substring(6,8) + ' ';
                    date_converted += ifxp_date.substring(8,10) + ':' + ifxp_date.substring(10,12) + ':' + ifxp_date.substring(12,14);
                    dt = Datetime.valueOf(date_converted);
                }
                ifxp.CouponStatusDatetime__c = dt;
            }
        }
    }

}