force-app/main/default/objects/IF_XP_SFDC_001__c/IF_XP_SFDC_001__c.object-meta.xml
<CustomObject>
    <description>CVS 쿠폰 사용에 관한 더미 레코드</description>
    <label>IF XP SFDC 001</label>
    <nameField>
        <displayFormat>CouponIF-{YYYY}{MM}{DD}{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IF XP SFDC 001</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponId__c.field-meta.xml
<CustomField>
    <fullName>CouponId__c</fullName>
    <label>CouponId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponStatus__c.field-meta.xml
<CustomField>
    <fullName>CouponStatus__c</fullName>
    <label>CouponStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/CouponStatusDate__c.field-meta.xml
<CustomField>
    <fullName>CouponStatusDate__c</fullName>
    <label>CouponStatusDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/ErrorContent__c.field-meta.xml
<CustomField>
    <fullName>ErrorContent__c</fullName>
    <description>[KDCE] 에러가 발생한 경우 원인을 기록함</description>
    <label>Error Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/IsError__c.field-meta.xml
<CustomField>
    <fullName>IsError__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 처리중 Error가 발생하면 True로 업데이트</description>
    <label>IsError</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IF_XP_SFDC_001__c/fields/IsProcess__c.field-meta.xml
<CustomField>
    <fullName>IsProcess__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[KDCE] 레코드의 처리가 진행되었는지 확인하는 필드</description>
    <label>IsProcess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/KDCE_Coupon__c.object-meta.xml
<CustomObject>
    <description>[Local KDCE]</description>
    <label>Coupon</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Coupon__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/CouponCode__c.field-meta.xml
<CustomField>
    <fullName>CouponCode__c</fullName>
    <description>[KDCE] Coupon Code</description>
    <externalId>true</externalId>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KDCE_Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Produce&apos;</defaultValue>
    <description>[KDCE] Coupon Status</description>
    <label>Coupon Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
                <default>true</default>
                <label>Produce</label>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/KDCE_CouponHistory__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Coupon Journey</description>
    <label>Coupon Journey</label>
    <nameField>
        <displayFormat>CH-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Journeys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/ActionChannel__c.field-meta.xml
<CustomField>
    <fullName>ActionChannel__c</fullName>
    <description>[KDCE] History Action Channel : Online / Offline / Call Center</description>
    <label>Action Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/ActionDate__c.field-meta.xml
<CustomField>
    <fullName>ActionDate__c</fullName>
    <description>[KDCE] Coupon이 변경된 Date/Time</description>
    <label>Action Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <description>[KDCE] Coupon Action Type</description>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Produce</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Use</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupon Journeys</relationshipLabel>
    <relationshipName>CouponHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <label>Coupon</label>
    <referenceTo>KDCE_Coupon__c</referenceTo>
    <relationshipLabel>Coupon Journeys</relationshipLabel>
    <relationshipName>CouponHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Store Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_CouponHistory__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>Store Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IF_XP_SFDC_001_tr_Test.cls
/****************************************************************************************
  * @filename      : IF_XP_SFDC_001_tr_Test
  * @projectname   : PMK LocalDCE QA
  * @author        : i2max_JE Yoon
  * @date          : 2021-03-31
  * @group         :
  * @description   :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                author              description
  * ===============================================================
    0.1  2021-03-31          i2max_JE Yoon             Create
****************************************************************************************/
@IsTest
private class IF_XP_SFDC_001_tr_Test {

    static String couponStatus_Use = 'Use';
    static String couponStatus_Cancel = 'Cancel';
    static String couponStatus_Issue = 'Issue';
    static String actionChannel_Offline = 'Offline';
    static String date_converted;
    static String ifxp_date;
    static Datetime dt;
    static IF_XP_SFDC_001__c ifxp;
    static List<IF_XP_SFDC_001__c> ifXpSfdc001s;
    static List<KDCE_Coupon__c> coupons;
    static List<KDCE_CouponHistory__c> couponHistories;
    static String errorContent = 'Coupon Id does not exist.';


    static void getData(Integer IFXP_CouponStatus, Boolean couponExists) {
        ifxp = CouponTestDataUtil.getIfXpSfdc001();
        if (IFXP_CouponStatus == -1 && couponExists == true) {
            ifxp.CouponStatus__c = '-1';
        } else if (couponExists == false) {
            ifxp.CouponId__c = 'Fake Coupon';
        }

        insert ifxp;

        ifXpSfdc001s = [SELECT CouponId__c, IsProcess__c, IsError__c, ErrorContent__c, CouponStatusDate__c FROM IF_XP_SFDC_001__c LIMIT 1];
        coupons = [SELECT Status__c, Contact__c FROM KDCE_Coupon__c WHERE CouponCode__c = :ifxp.CouponId__c LIMIT 1];
        couponHistories = [SELECT Coupon__c, Contact__c, ActionDate__c, ActionChannel__c, ActionType__c, StoreCode__c, StoreName__c FROM KDCE_CouponHistory__c WHERE Coupon__r.CouponCode__c = :ifxp.CouponId__c AND ActionChannel__c = :actionChannel_Offline LIMIT 1];

        ifxp_date = ifXpSfdc001s[0].CouponStatusDate__c;
        if (ifxp_date.length() == 14) {
            date_converted = ifxp_date.substring(0,4) + '-' + ifxp_date.substring(4,6) + '-' + ifxp_date.substring(6,8) + ' ';
            date_converted += ifxp_date.substring(8,10) + ':' + ifxp_date.substring(10,12) + ':' + ifxp_date.substring(12,14);
            dt = Datetime.valueOf(date_converted);
        }
    }

    /**
     * @description IF_XP_SFDC_001에 CouponStatus__c = 1이고 쿠폰이 시스템에 존재할 때 시나리오
     * @author JE Yoon
     **/
    @IsTest
    static void testCase01() {

        Test.startTest();
        if (ifxp == null) getData(1, true);

//        System.assertNotEquals(true, ifXpSfdc001s[0].IsProcess__c);
//        System.assertEquals(false, ifXpSfdc001s[0].IsError__c);
//        System.assertEquals(couponStatus_Use, coupons[0].Status__c);
//        System.assertEquals(coupons[0].Id, couponHistories[0].Coupon__c);
//        System.assertEquals(coupons[0].Contact__c, couponHistories[0].Contact__c);
//        System.assertEquals(dt, couponHistories[0].ActionDate__c);
//        System.assertEquals(actionChannel_Offline, couponHistories[0].ActionChannel__c);
//        System.assertEquals(couponStatus_Use, couponHistories[0].ActionType__c);
//        System.assertEquals('1234', couponHistories[0].StoreCode__c);
//        System.assertEquals('공덕점', couponHistories[0].StoreName__c);
        Test.stopTest();

    }

    /**
     * @description IF_XP_SFDC_001에 CouponStatus__c = -1이고 쿠폰 Id가 시스템에 존재할 때 시나리오
     * @author JE Yoon
     **/
    @IsTest
    static void testCase02() {

        Test.startTest();
        if (ifxp == null) getData(-1, true);

//        System.assertEquals(true, ifXpSfdc001s[0].IsProcess__c);
//        System.assertEquals(false, ifXpSfdc001s[0].IsError__c);
//        System.assertEquals(couponStatus_Issue, coupons[0].Status__c);
//        System.assertEquals(coupons[0].Id, couponHistories[0].Coupon__c);
//        System.assertEquals(coupons[0].Contact__c, couponHistories[0].Contact__c);
//        System.assertEquals(dt, couponHistories[0].ActionDate__c);
//        System.assertEquals(actionChannel_Offline, couponHistories[0].ActionChannel__c);
//        System.assertEquals(couponStatus_Cancel, couponHistories[0].ActionType__c);
//        System.assertEquals('1234', couponHistories[0].StoreCode__c);
//        System.assertEquals('공덕점', couponHistories[0].StoreName__c);
        Test.stopTest();

    }

    /**
 * @description IF_XP_SFDC_001에 CouponStatus__c = 1이고 쿠폰 Id가 시스템에 존재하지 않을 때 시나리오
 * @author JE Yoon
 **/
    @IsTest
    static void testCase03() {

        Test.startTest();
        if (ifxp == null) getData(1, false);

//        System.assertEquals('Fake Coupon', ifXpSfdc001s[0].CouponId__c);
//        System.assertEquals(false, ifXpSfdc001s[0].IsProcess__c);
//        System.assertEquals(0, coupons.size());
//        System.assertEquals(0, couponHistories.size());
//        System.assertEquals(errorContent, ifXpSfdc001s[0].ErrorContent__c);
//        System.assertEquals(true, ifXpSfdc001s[0].IsError__c);
        Test.stopTest();

    }
}