force-app/main/default/objects/Contact/recordTypes/Contact_Prospect.recordType-meta.xml
<RecordType>
    <fullName>Contact_Prospect</fullName>
    <active>true</active>
    <description>[KDCE]</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/KDCE_Order__c/KDCE_Order__c.object-meta.xml
<CustomObject>
    <description>[KDCE] Order</description>
    <label>Order</label>
    <nameField>
        <displayFormat>KO{YY}{MM}{DD}{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/CustomerEmail__c.field-meta.xml
<CustomField>
    <fullName>CustomerEmail__c</fullName>
    <description>[KDCE] 고객 이메일
Mapping Column : customer_email</description>
    <inlineHelpText>고객 이메일</inlineHelpText>
    <label>Customer Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <description>[KDCE] 고객번호
Mapping Column : customer_id</description>
    <inlineHelpText>고객번호</inlineHelpText>
    <label>Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <description>[KDCE] 고객 이름
Mapping Column : customer_name</description>
    <inlineHelpText>고객 이름</inlineHelpText>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingAddressName__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddressName__c</fullName>
    <description>[KDCE] 수령고객 명
Mapping Column : shipping_address_name</description>
    <inlineHelpText>수령고객 명</inlineHelpText>
    <label>Shipping Address Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingCity__c.field-meta.xml
<CustomField>
    <fullName>ShippingCity__c</fullName>
    <description>[KDCE] 배송지 도시
Mapping Column : shipping_city</description>
    <inlineHelpText>배송지 도시</inlineHelpText>
    <label>Shipping City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingPhone__c.field-meta.xml
<CustomField>
    <fullName>ShippingPhone__c</fullName>
    <description>[KDCE] 배송지 전화번호
Mapping Column : shipping_phone</description>
    <inlineHelpText>배송지 전화번호</inlineHelpText>
    <label>Shipping Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>ShippingPostalCode__c</fullName>
    <description>[KDCE] 배송지 우편번호
Mapping Column : shipping_postal_code</description>
    <inlineHelpText>배송지 우편번호</inlineHelpText>
    <label>Shipping Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingState__c.field-meta.xml
<CustomField>
    <fullName>ShippingState__c</fullName>
    <description>Order Shipping State</description>
    <label>ShippingState</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KDCE_Order__c/fields/ShippingStreet__c.field-meta.xml
<CustomField>
    <fullName>ShippingStreet__c</fullName>
    <description>Order Shipping Street</description>
    <label>ShippingStreet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KDCE_LiveOrderNull_ba.cls
/****************************************************************************************
  * @filename      : KDCE_LiveOrderNull_ba
  * @projectname   : PMK qa - KR
  * @author        : Park HE
  * @date          : 2021-06-13
  * @group         :
  * @group-content :
  * @description   : 5년 이상 된 Prospect 고객의 Order 레코드 중 개인정보 관련 데이터 Null 처리
  * @tester        :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                    author          description
  * ===============================================================
    0.1     2021-06-13             Park HE         Create
****************************************************************************************/
public with sharing class KDCE_LiveOrderNull_ba implements Database.Batchable<SObject>{

    public Set<Id> batchContactIds;

    String objectName = 'KDCE_Order__c';
    String query = 'SELECT ';
    Map<String, Schema.SObjectField> orderFieldMap = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap();


    public Database.QueryLocator start(Database.BatchableContext BC) {

        Integer lastYear = -5;
        Datetime deleteTargetDt = (Datetime.now().addYears(lastYear)).dateGMT();
        //Date targetDate = Date.today().addYears(-5);

        for (String fieldName : orderFieldMap.keySet()) {
            if (query != 'SELECT ') query += ' ,';      // 첫번째 필드가 아닐 경우 , 붙이기
            query += fieldName;
        }
        query += ' FROM ';
        query += objectName;
        if (!Test.isRunningTest()) query += ' WHERE Contact__r.RecordType.DeveloperName = \'Contact_Prospect\' ';// AND Id =\'a1R1m000000hNgOEAU\'';
        if (!Test.isRunningTest()) query += ' AND CreatedDate < :deleteTargetDt AND Contact__c != null ';

        System.debug('query : ' + query);
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<SObject> scope) {
        System.debug('KDCE_LiveOrderNull_ba : ' + scope);

        Map<String, Schema.SObjectField> objectSchema = Schema.SObjectType.KDCE_Order__c.fields.getMap();
        Set<String> notNullField = new Set<String>{
                'id', 'ownerid'
        };

        Set<String> orderPersonalField = new Set<String>{
                'contact__c', 'customerid__c', 'customername__c', 'customeremail__c',
                'shippingaddressname__c', 'shippingaddress1__c', 'shippingaddress2__c',
                'shippingphone__c', 'shippingstreet__c', 'shippingpostalcode__c',
                'shippingstate__c', 'shippingcity__c'
        };

        KDCE_ContactSeparateService.setNullField('RoekDropOut', 'KDCE_Order__c', scope, objectSchema, notNullField, orderPersonalField);

    }

    @SuppressWarnings('PMD')
    public void finish(Database.BatchableContext BC) {

    }
}