force-app/main/default/objects/Kakao_Quick_Text__c/Kakao_Quick_Text__c.object-meta.xml
<CustomObject>
    <label>Kakao Quick Text</label>
    <nameField>
        <displayFormat>KQT-{000000}</displayFormat>
        <label>Kakao Quick Text Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Quick Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Quick_Text__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kakao_Quick_Text__c/fields/Global__c.field-meta.xml
<CustomField>
    <fullName>Global__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Global</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Kakao_Quick_Text__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/KakaoQuickTextController.cls
/**
 * @description       :
 * @author            : Obidjon
 * @group             :
 * @last modified on  : 05-23-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   05-14-2021   Obidjon   Initial Version
 **/
public with sharing class KakaoQuickTextController {
    @testVisible
    private static String testExceptionMessage;

    @AuraEnabled(cacheable=true)
    public static List<Kakao_Quick_Text__c> getKakaoQuickTexts() {
        try {
            testException(KakaoQuickTextController.testExceptionMessage);
            List<Kakao_Quick_Text__c> kakaoQuickTextList = [
                SELECT Id, Content__c, Label__c
                FROM Kakao_Quick_Text__c
                WHERE Active__c = TRUE OR (Active__c = TRUE AND Global__c = TRUE)
                WITH SECURITY_ENFORCED
            ];

            return kakaoQuickTextList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static void testException(String exceptionMessage) {
        if (String.isNotBlank(exceptionMessage)) {
            throw new AuraHandledException(exceptionMessage);
        }
    }
}