force-app/main/default/objects/Kakao_Quick_Text__c/Kakao_Quick_Text__c.object-meta.xml
<CustomObject>
    <label>Kakao Quick Text</label>
    <nameField>
        <displayFormat>KQT-{000000}</displayFormat>
        <label>Kakao Quick Text Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kakao Quick Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kakao_Quick_Text__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Kakao_Quick_Text__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/KakaoQuickTextController_Test.cls
/**
 * @description       :
 * @author            : Obidjon
 * @group             :
 * @last modified on  : 05-23-2021
 * @last modified by  : Obidjon
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   05-23-2021   Obidjon   Initial Version
 **/
@isTest
private class KakaoQuickTextController_Test {
    @testSetup
    private static void testSetup() {
        User standardUser = KakaoTestUtils.createUser('Standard User');
        KakaoTestUtils.assignPermissionSet('KakaoConsult_User', standardUser.Id);

        System.runAs(standardUser) {
            List<Kakao_Quick_Text__c> kakaoQuickTextList = new List<Kakao_Quick_Text__c>();
            for (Integer i = 0; i < 10; i++) {
                Kakao_Quick_Text__c quickText = new Kakao_Quick_Text__c();
                quickText.Active__c = true;
                quickText.Label__c = 'Quick Text Test ' + String.valueOf(i);
                quickText.Content__c = 'Content of test quick text ' + String.valueOf(i);
                kakaoQuickTextList.add(quickText);
            }

            insert kakaoQuickTextList;
        }
    }

    @isTest
    private static void testGetKakaoQuickTexts() {
        User standardUser = [SELECT Id FROM User WHERE Alias = 'standt' LIMIT 1];

        System.runAs(standardUser) {
            List<Kakao_Quick_Text__c> quickTextList = KakaoQuickTextController.getKakaoQuickTexts();
            System.assertEquals(10, quickTextList.size(), 'Error with quick text insert and retrieve logic');

            KakaoQuickTextController.testExceptionMessage = 'TestException';
            try {
                KakaoQuickTextController.getKakaoQuickTexts();
            } catch (Exception e) {
            }
        }
    }
}