force-app/main/default/objects/KDCE_DormantContact__c/KDCE_DormantContact__c.object-meta.xml
<CustomObject>
    <description>고객 중 휴면으로 전환된 고객 정보를 저장하기 위한 오브젝트</description>
    <label>Dormant Contact</label>
    <nameField>
        <label>Dormant Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dormant Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KDCE_DormantContact__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dormant Contact</relationshipLabel>
    <relationshipName>Dormant_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/KDCE_RestoreContactController_ts.cls
/****************************************************************************************
  * @filename      : KDCE_RestoreContactController_ts
  * @projectname   : [PMI] QA 20210204
  * @author        : i2max_Jihyun.Lee
  * @date          : 2021-06-18 오후 5:21
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : 
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * =========================================================================
  * ver     date                    author                    description
  * =========================================================================
    0.1     2021-06-18 오후 5:21     i2max_Jihyun.Lee        Create
****************************************************************************************/

@IsTest
private class KDCE_RestoreContactController_ts {

    static {
        KDCE_TestUtil.init();
        KDCE_TestBizUtil.init();
    }

    @IsTest
    static void testBehavior(){
        KDCE_DormantContact__c dormantContact = new KDCE_DormantContact__c();
        dormantContact.ContactId__c = KDCE_TestUtil.contactMember.Id;
        insert dormantContact;

        KDCE_RestoreContactController.convertDormant(dormantContact.Id);
    }
}